### ISSUE TITLE
wkey parameter is invalid from ip: xxx.xxx.xxx.xxx

### ISSUE THREAD

**Issue by ghost** [mailchimp/mc-magento2#101]
Hi when we try to update the webhook in mailchimp (which got automatically generated) I get a 403 response code.
In my logs I found a lot of these:
[2017-10-17 10:07:48] MailChimpLogger.INFO: wkey parameter is invalid from ip: XXX.XXX.XXX....

Any suggestions?

**Comment by gonzaloebiz** [comment]
Hi @marcmayo 

please read the issue reporting guidelines in the home page of the extension and re format your issue.

Best
