### ISSUE TITLE
E commerce Order data not sent when "Magento always manage emails" is Yes

### ISSUE THREAD

**Issue by JelleGroenendal** [mailchimp/mc-magento2#1013]
We have several store views connected to Mailchimp. With that connection we also configured the E commerce settings to get the automation and products on Mailchimp its side to work. What we notice is that when we set "Magento manage emails" on "Yes" the magento order data is not sent to Mailchimp.
When we set the same setting on "No" then the order data is sent to Mailchimp but not the new newsletter subscribers.

### Steps to reproduce

    1. Magento EE 2.3.5
    2. mailchimp/mc-magento2 102.3.38
    3. Connected to Mailchimp
    4. Setup E-commerce configuration / instance
    5. Set Magento manage emails on yes
             Results in: Newsletter subscribers are shared with Mailchimp but not the order data if E-commerce settings are configured
    6. Set Magento manage emails on no
             Results in: The order data is shared but not the Newsletter subscribers

### Actual and Expected result

    1. When setting Magento manage emails on yes:
              Results in: Newsletter subscribers and the order data are shared with Mailchimp if E-commerce settings are configured
    2. When setting Magento manage emails on no
             Results in: The order data is shared but not the Newsletter subscribers if E-commerce settings are configured

**Comment by gonzaloebiz** [comment]
Hi @JelleGroenendal,

can you share the Account Details for both cases? This one
![image](https://user-images.githubusercontent.com/6222792/85878949-e8232a80-b7af-11ea-8689-7cb5f844bc65.png)

**Comment by gonzaloebiz** [comment]
We close the issue after 2 months without responses
