### ISSUE TITLE
Issue on Setup Upgrade

### ISSUE THREAD

**Issue by ninjacoder30** [mailchimp/mc-magento2#1014]
After Execution of Setup Upgrade getting below error
....
Module 'Ebizmarts_MailChimp':
Installing data... Class Mailchimp does not exist

Plugin Version:   "version": "102.3.37"

Magento :2.3.4 

Please note i have copied : https://github.com/ebizmarts/mailchimp-lib
inside vendor folder

**Comment by gonzaloebiz** [comment]
Hi @ninjacoder30 

try installing via composer
