### ISSUE TITLE
wkey parameter is invalid from ip: xxx.xxx.xxx.xxx

### ISSUE THREAD

**Issue by ghost** [mailchimp/mc-magento2#102]
1. Magento CE 2.1.6 is installed.
2. mc-magento2 1.0.24
3. I have set up multiple stores in Magento and have set up multiple stores in Mailchimp as well.
4. Mailchimp is currently syncing (finished but the status doesn't change -> see #66 )
5. It automatically created webhooks in my Mailchimp account for each list like Domain.com/index.php/mailchimp/webhook/index/wkey/905a61cdd18sia/  (changed the key in the end as I don't want to make it public) 
It created the same key for all lists. 

Now when I try to add the webhook manually to Mailchimp I get: We couldn't verify the URL is working. Please double check and try again. HTTP Code: 403

Also in the logs I see a lot of wkey parameter is invalid from ip: xxx.xxx.xxx.xxx

I assume that the wkey is wrong for some reason. I already tried to re-create the stores, re-save the configuration in Magento 2 etc. I also deleted the webhook from the list and re-saved and re-created everything but the webhook didn't get added again

**Comment by gonzaloebiz** [comment]
You changed the crypt key?

**Comment by ghost** [comment]
@gonzaloebiz I only changed it for the post to not make it public for all github users... Did not change anything in the system.

**Comment by gonzaloebiz** [comment]
@marcmayo check the webhook for the list in mailchimp, be sure that the url include the first crypt key of your magento

**Comment by ghost** [comment]
@gonzaloebiz where can I see the first crypt key of Magento? Is it the one I can generate in System -> Encryption Key? I re-generated it and it still doesn't work.
Can't seem to find another "crypt key"

**Comment by gonzaloebiz** [comment]
You can find the key in the file app/etc/env.php

**Comment by ghost** [comment]
@gonzaloebiz I tried this as well. Also re-created the key and tried again. Does not work.

**Comment by gonzaloebiz** [comment]
Put a log after this line https://github.com/mailchimp/mc-magento2/blob/develop/Controller/WebHook/Index.php#L67 to check both values.

**Comment by ghost** [comment]
@gonzaloebiz got it. The webhook key and the wkey were different. 
Thanks for the tip.

**Comment by gonzaloebiz** [comment]
you recognize the key in the webhook? in an old one?

**Comment by ghost** [comment]
What I did was 
`		$this->_helper->log(' Webhookskey is '.$this->_helper->getWebhooksKey());`

`		$this->_helper->log('get param wkey is '.$this->getRequest()->getParam('wkey'));`

both keys were different. I then changed the URL in Mailchimp to fit the key given by Magento and it worked. But they key I have now is not similiar to the key in app/etc/env.php in any way.
