### ISSUE TITLE
Create custom field mapping

### ISSUE THREAD

**Issue by dtamajon** [mailchimp/mc-magento2#1025]
Hi!

I have configured the MailChimp module on M2, and I have mapped custom fields created on MailChimp to existing fields in Magento2.

Now, I want to add some more specific fields, like Country or Zip code which are in the shipping address, but I don't want to sync full shipping address.

Is it some way to map only parts of the address? Otherwise, I will really appereciate any tip about how modify module to achieve that.

Thank you!

**Comment by gonzaloebiz** [comment]
Hi @dtamajon 

thanks for your feedback.
No, this is not possible

Best

**Comment by dtamajon** [comment]
Hi @gonzaloebiz 

I have created a fork and added address fields available for mapping. You can check here:
https://github.com/dtamajon/mc-magento2/commit/d1dbd1d87a78e81cd0d547a686edbc81987b0d98

If you think they are worth for the module, I will ask for a pull request.

Of course, let me know if I can afford any improvement on code to be valid on the main branch... I didn't use much time on it!

**Comment by gonzaloebiz** [comment]
Hi @dtamajon 

i will try it and back to you

**Comment by gonzaloebiz** [comment]
Hi @dtamajon 

we use your code as a base for fixing this issue.

thanks

**Comment by dtamajon** [comment]
Glad to help!
