### ISSUE TITLE
Send Coupon Codes (Promo Codes) to Mailchimp With Order Data

### ISSUE THREAD

**Issue by Swiftless** [mailchimp/mc-magento2#1029]
### Preconditions

    1. Magento OS 2.3.3 installed
    2. mc-magento2 v102.3.37.
    3. Store is connected to Mailchimp 
    4. Promo codes and orders syncing to Mailchimp
    5. Campaign draft ready in Mailchimp

### Steps to reproduce

    1. Send campaign email in Mailchimp
    2. Follow link in campaign email to Magento store
    3. Place an order using a coupon code
    4. Review Campaign Report in Mailchimp

### Actual and Expected result

    Expected result:
    Campaign Report shows promo code for an order

    Actual result:
    Campaign Report doesn't show promo code for an order

### Additional information

Mailchimp support after a chat today have informed me that the "Promo Code" column against an order in their Report screen should be coming across from the integration/site. This is supported by the API documentation:
https://developer.mailchimp.com/documentation/mailchimp/reference/ecommerce/orders/

Promo Rules and Promo Codes appear to be syncing correctly to Mailchimp on their own according to the table "mailchimp_sync_ecommerce". However when in Mailchimp and viewing a Report for a Campaign, the "Promo Code" column against an order is always empty.

**Comment by gonzaloebiz** [comment]
Please follow the [issue guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)

**Comment by Swiftless** [comment]
Hi @gonzaloebiz I'll reword the issue, bear with me.

**Comment by Swiftless** [comment]
@gonzaloebiz done, please let me know if you need me to do anything else to have this addressed.
