### ISSUE TITLE
Magento 2.4 support? 

### ISSUE THREAD

**Issue by duffner** [mailchimp/mc-magento2#1031]
As this is more of a question rather than an actual bug, I chose not to use the full bug format.  When will 2.4 support become available?

**Comment by Swiftless** [comment]
Hope it's ok for me to respond - the latest release states Magento 2.4 compatibility

**Comment by gonzaloebiz** [comment]
Hi,

take look at https://github.com/mailchimp/mc-magento2/releases/tag/102.3.40

Best
