### ISSUE TITLE
Fallback to JQueryUI Compat activated.

### ISSUE THREAD

**Issue by samy-m-dev** [mailchimp/mc-magento2#1034]
In  vendor/mailchimp/mc-magento2/view/frontend/web/js/campaigncatcher.js

There's dependency to **'jquery/ui'**

That will produce a warning/error on frontend as it's not recommended:

`Fallback to JQueryUI Compat activated. Your store is missing a dependency for a jQueryUI widget. Identifying and addressing the dependency will drastically improve the performance of your site.`

The dependency can be safely removed.

**Comment by Quazz** [comment]
Relevant PR https://github.com/mailchimp/mc-magento2/pull/997
