### ISSUE TITLE
API Key ignored if no new line

### ISSUE THREAD

**Issue by maderlock** [mailchimp/mc-magento2#104]
Pre-condition
* Extension v3.0.14
* Magento 2.1.9

Steps
* Enable in config
* Copy and paste API key into list
* submit

Expected result
* Dropdown of API keys will show single API key so that we can select it

Actual result
* Dropdown is empty

In order to make the API key appear I eventually entered a new line after the end of the API key. When I did that and submitted the key appears in the drop-down list. Obviously (at least to me), it should show without a new-line being entered.

**Comment by gonzaloebiz** [comment]
Extension v3.0.14 not exist, take a look at https://github.com/mailchimp/mc-magento2/releases

**Comment by maderlock** [comment]
Apologies. That must be the version of the MC library. It's version 1.0.24.

Please reopen.

**Comment by maderlock** [comment]
Please reopen
