### ISSUE TITLE
Multistore product sync wrong name 

### ISSUE THREAD

**Issue by JoostWan** [mailchimp/mc-magento2#1055]
### Preconditions

    1. Magento CE 2.3.5-p2
    2. mc-magento2  102.3.39

### Problem

The product sync to Mailchimp for Ecommerce data synces the wrong name. It should be sync to name of the product for that specific store ID but it uses the name from default store (ID 1). The url and the image are correct but only name not. 

```
protected function _buildProductData(
        \Magento\Catalog\Model\Product $product,
        $magentoStoreId,
        $isVarient = true,
        $variants = null
    ) {

        error_log("Store ID: " . $magentoStoreId);
        error_log("Product Name: " . $product->getName());

        $data = [];
        $parent = null;

        //data applied for both root and varient products
        $data["id"] = $product->getId();
        $data["title"] = $product->getName();
        $data["url"] = $product->getProductUrl();

....
```

```
[03-Sep-2020 08:20:50 UTC] Store ID: 5
[03-Sep-2020 08:20:50 UTC] Product Name: Product name default store
[03-Sep-2020 08:20:50 UTC] Array
(
    [id] => 139
    [title] => Product name default store
    [url] => xxxxxx
    [image_url] => xxxx
    [published_at_foreign] =>
    [sku] => productsku
    [price] => 5
    [inventory_quantity] => 746
    [backorders] => 0
    [visibility] => true
)

```

**Comment by JoostWan** [comment]
When i added `$storeId` to this request the values are correct;

https://github.com/mailchimp/mc-magento2/blob/develop-2.3/Model/Api/Product.php#L145
https://github.com/mailchimp/mc-magento2/blob/develop-2.3/Model/Api/Product.php#L559
https://github.com/mailchimp/mc-magento2/blob/develop-2.3/Model/Api/Product.php#L600

**Comment by gonzaloebiz** [comment]
Thanks @JoostWan for your contribution

Best
