### ISSUE TITLE
Class Mailchimp does not exist

### ISSUE THREAD

**Issue by Krupaly2k-zz** [mailchimp/mc-magento2#106]
Hi,

I have installed the extension and after click on Mailchimp menu in admin it shows error:

3 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid block type: Ebizmarts\MailChimp\Block\Adminhtml\System\Config\Fieldset\Hint
Exception #1 (ReflectionException): Class Mailchimp does not exist
Exception #2 (ReflectionException): Class Mailchimp does not exist

Please help me to resolve this issue

**Comment by gonzaloebiz** [comment]
composer require ebizmarts/mailchimp-lib

**Comment by shenmusam** [comment]
I use the command to install

![image](https://user-images.githubusercontent.com/37282394/37321501-8f64049e-26b3-11e8-92d6-6fd43a3ea7a4.png)

**Comment by lewis-dan** [comment]
Inside your composer.json file update the following lines - 
"require" : {
    "ebizmarts/mailchimp-lib": "3.0.*"
  }

**Comment by gonzaloebiz** [comment]
Hi @lewis-dan

i don't understand your comment.
If you see, this dependency is there https://github.com/mailchimp/mc-magento2/blob/develop-2.2/composer.json#L28 since the first version, you don't need to do this

Best
