### ISSUE TITLE
Unable to use Two Way Sync

### ISSUE THREAD

**Issue by kkazadi** [mailchimp/mc-magento2#1063]
### Preconditions

The Two Way Sync in Magento does not seem to be working, I have successfully setup a Magento 2 store to sync to Mailchimp and vice versa but it appears Customers and Subscribers are only syncing from Magento to Mailchimp and not the other way around even though I have enabled "Two Way Sync". Any changes made to Subscribers within Mailchimp does not reflect on Magento side

1. API Key set
2. Webhook created
3. Vanilla Magento 2.3.1
4. Mailchimp v102.3.39

![Screenshot_93](https://user-images.githubusercontent.com/23381441/94560479-0858fe80-0263-11eb-98fa-933febe17a17.png)

### Steps to reproduce

1. Navigate to storefront and subscriber via Magento default newsletter form
2. Subscriber can be found within Magento admin under Marketing -> Newsletter Subscribers
3. Cron job automatically run and sync subscriber to Mailchimp
4. Subscriber can be found within Mailchimp Audience list
5. Unsubscribe the customer within Mailchimp but customer remains subscribed within Magento

**Comment by gonzaloebiz** [comment]
Hi @kkazadi is your store a public store? If your store is a local or protected URL the 2way doesn't work (this is because Mailchimp can't access to your store).
Also, be sure that your magento crons are running (take a look at https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-cron.html)

Best

**Comment by kkazadi** [comment]
Hi @gonzaloebiz, Yes the store is public and I have checked Crons are running. Could there be any other reason why this wouldn't work?

**Comment by gonzaloebiz** [comment]
I see that you don't have customers, products, etc, so I think that you have another problem, please drop us an email to our support team to help you

Best
