### ISSUE TITLE
Address field not synced

### ISSUE THREAD

**Issue by dtamajon** [mailchimp/mc-magento2#1064]
I have created an Address field in Mailchimp account, on "Audience fields and *|MERGE|* tags". Then I have mapped it on Magento 2 with Default Shipping Address.

When I create or force a user sync, the user appears on Mailchimp, but addres information is never shown.

{"id":"0b27e1c696","email":"sample@gmail.com","email_type":"html","web_id":"196643476","merges":{"EMAIL":"sample@gmail.com","FNAME":"MyName","LNAME":"My Surname","MMERGE3":"My Shop","MMERGE4":"","MMERGE5":""},"list_id":"6f6d24b06f"}

On MMERG4 should be Shipping Addres and on MMERG5 should be Billing Addres, but theyare always empty.

Additionally, when the user enable/disable the newsletter subscription, it is not changed on Mailchimp and remains the first status.

**Comment by gonzaloebiz** [comment]
Hi @dtamajon 

please follow the [issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)

Best

**Comment by dtamajon** [comment]
Sorry, I forgot to update to latest version where issue is solved
