### ISSUE TITLE
di compile produces Class Mailchimp does not exist 

### ISSUE THREAD

**Issue by jpratt** [mailchimp/mc-magento2#107]
Magento CE 2.1.9
MailChimp 1.0.24

When doing a di:compile I am getting an error:

"Class Mailchimp does not exist "

Looking for a reference for this class I am seeing in Cron\Webhook.php on lines 217 and 219 calls to const \Mailchimp::SUBSCRIBED and \Mailchimp::UNSUBSCRIBED, where are these class constants defined?

Also a possible unrelated issue on line 213 of the same file:

$subscriber->setStreId($stores[0]);

Is this supposed to be setStoreId? Typo?

**Comment by gonzaloebiz** [comment]
duplicate

**Comment by jpratt** [comment]
Should have created a separate issue. And the store ID line. Is that a typo/bug?

**Comment by gonzaloebiz** [comment]
Yes is a typo, i just fixing it
