### ISSUE TITLE
Composer problem with mc-magento2:102.3.41

### ISSUE THREAD

**Issue by kf202020** [mailchimp/mc-magento2#1075]
Hello,
I'm experiencing some trouble trying to install mailchimp via composer.

Using magento 2.4 and when I go with

`composer require mailchimp/mc-magento2:102.3.41`

This is what I Got

```
  Problem 1
    - Installation request for mailchimp/mc-magento2 102.3.41 -> satisfiable by mailchimp/mc-magento2[102.3.41].
    - mailchimp/mc-magento2 102.3.41 requires magento/framework 102.0.*||103.0.* -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

```

Any idea?

**Comment by gonzaloebiz** [comment]
Hi @kf202020 

can you please run this command and let me know the result?

composer show | grep framework

Best

**Comment by gonzaloebiz** [comment]
no news in one week, i close the issue waiting for more info

**Comment by kf202020** [comment]
Sorry for late response.
@gonzaloebiz it was a corrupted magento!!!
Thanks for your support!

**Comment by gonzaloebiz** [comment]
OK thanks for back to us.

Best
