### ISSUE TITLE
Unsubscribing users in Mailchimp will not sync with Magento2

### ISSUE THREAD

**Issue by mdlonline** [mailchimp/mc-magento2#1076]
Using Mailchimp mc-magento2 version 102.3.40 and Magento 2.4.0 i am getting the following issue:
I have enabled the e-commerce setting.

Subscribing a customer in Magento to the newsletter -> Email is added to Mailchimp
Unsubscribing a customer in Mailchimp -> no change in Magento 

I am receiving a webhook call from mailchimp however it seems that Magento is not doing anything with it. 
I expect it to uncheck the "Subscribed to newsletter"checkbox.

**Comment by gonzaloebiz** [comment]
Hi @mdlonline 

thanks for your feedback.
You already have the magento cron configured and running? Please take a look at https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-cron.html

Best

**Comment by mdlonline** [comment]
Hi @gonzaloebiz ,

yes, this is a live site with the cron running.

Thanks

**Comment by mdlonline** [comment]
Here is my cron history:
![chrome_2020-10-28_16-18-08](https://user-images.githubusercontent.com/5389528/97456598-4ff1a980-1939-11eb-80c0-622a80d15038.png)

**Comment by gonzaloebiz** [comment]
What about the mailchimp_webhook_request table?

**Comment by mdlonline** [comment]
There is info in this, however it does not seem te reflect in my account (screenshot is only showing my email but there are more) 
![chrome_2020-11-03_11-51-16](https://user-images.githubusercontent.com/5389528/97976429-fa028300-1dca-11eb-91dc-f4f8d1437756.png)

**Comment by gonzaloebiz** [comment]
Hi @mdlonline 

i just check your issue using magento 2.4 and mc-magento2 102.3.41 version of the extension and works like a charm
Can you please give us more info to try to replicate?

**Comment by mdlonline** [comment]
Is there a way to debug the webhook function that changes the customer data in Magento?

**Comment by gonzaloebiz** [comment]
You can use the log function of the helper, like this https://github.com/mailchimp/mc-magento2/blob/develop-2.3/Cron/Webhook.php#L190
This function logs in the var/log/MailChimp.log file

Best

**Comment by gonzaloebiz** [comment]
Close the issue until having any new
