### ISSUE TITLE
Change Mailchimp Store on Website Scope

### ISSUE THREAD

**Issue by r4pt0s** [mailchimp/mc-magento2#1077]
## Change Mailchimp Store on Website Scope

> Unable to change Mailchimp store on website scope

### Preconditions

    1. Magento CE 2.3.5-p2 without sample data is installed.
    2. mc-magento2 v102.3.41
    3. Multistore, Multishop Magento Shop
    4. API key is set up and working

### Steps to reproduce

    1. Change scope in configuration from Default to other Website.
    2. Go to Mailchimp configuration.
    3. remove Use Website checkbox at Mailchimpo Store
    4. Change Mailchimp store to a different one than in default configuration
    5. Change Mailchimp list to a different one than in default configuration
    6. Save

#### Expected result:
   Successfully connected to Mailchimp store and right list

   #### Actual result:
    Error message: **The store that was requested wasn't found. Verify the store and try again.**

### Additional information

Setting another Mailchimp Store does work on store view scope but not on website scope. I think the reason is because the extension is of course not able to find the right store because on website scope there is no store view id.

Cheers :)

**Comment by gonzaloebiz** [comment]
Hi @r4pt0s 

thanks for your feedback.
I test your issue and works OK for me.
Do you have any other settings in your configuration page? p.e. customer fields maps or available groups
Or any other information that you can give us to try to replicate your issue

Best

**Comment by gonzaloebiz** [comment]
No news in 11 days, close the issue until we have more info
