### ISSUE TITLE
Subscribing for a second time does not work.

### ISSUE THREAD

**Issue by LucasMDL** [mailchimp/mc-magento2#1078]
Using Mailchimp mc-magento2 version 102.3.40 and Magento 2.4.0. 

I am getting the following issue:

When a customer has subscribed and unsubscribed once before, the 'subscribe' webhook is not fired. Just the 'profile' webhook'. After this, Mailchimp states that the customer is only eligible for transactional emails.

Steps to reproduce: 
1. Create new customer
2. Subscribe to newsletter from account page.
3. Unsubscribe via Mailchimp
4. Subscribe to newsletter from account page again.

I expect the customer to be registered in Mailchimp, but Mailchimp states that the customer is only eligible for transactional emails.

**Comment by gonzaloebiz** [comment]
Please follow the[issue format guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)

**Comment by LucasMDL** [comment]
I have updated the description.

**Comment by LucasMDL** [comment]
This solution is not working. The subscriber always has the 'unsubscribed' status.
