### ISSUE TITLE
Ecommerce Cron error "Requested country is not available."

### ISSUE THREAD

**Issue by stennkool** [mailchimp/mc-magento2#1084]
Cron ebizmarts_ecommerce outputs error:
Requested country is not available.

Version: 102.3.41
Magento: 2.3.4
Multiple storefronts (languages) and multiple Mailchimp Stores (1 list for each language).

In issue #58 this has already been fixed for other e-commerce jobs but the issue still persists when the country is attached to the address.

In the _getAddressValues method in the Ebizmarts\MailChimp\Helper\Data class a disabled country can still cause exceptions and thus prevent the cron from completing.

**Comment by JoostWan** [comment]
We have (i think) the same issue; https://github.com/mailchimp/mc-magento2/issues/1113
