### ISSUE TITLE
Subscribing for a second time does not work #2

### ISSUE THREAD

**Issue by LucasMDL** [mailchimp/mc-magento2#1086]
Same issue as #1078. The provided fix doesn't solve the problem. The added function always has the unsubscribed status.

Using Mailchimp mc-magento2 version 102.3.40 and Magento 2.4.0.

I am getting the following issue:

When a customer has subscribed and unsubscribed once before, the 'subscribe' webhook is not fired. Just the 'profile' webhook'. After this, Mailchimp states that the customer is only eligible for transactional emails.

Steps to reproduce:

Create new customer
Subscribe to newsletter from account page.
Unsubscribe via Mailchimp
Subscribe to newsletter from account page again.
I expect the customer to be registered in Mailchimp, but Mailchimp states that the customer is only eligible for transactional emails.

**Comment by jonathanribas** [comment]
We are actually having 502 errors due to https://github.com/mailchimp/mc-magento2/pull/1080/files, we have disabled  `newsletter_subscriber_save_before` event.

**Comment by lamasfoker** [comment]
I am digging in this but I think it is related with the way the unsubscription is handled. If the customer is deleted then it is not possible to re-add he/she with the API. See the [docu](https://mailchimp.com/help/delete-contacts/#Archive_vs._Remove) or [this](https://stackoverflow.com/questions/52198510/mailchimp-resubscribe-a-deleted-member-causes-the-api-to-return-a-400-bad-reques) answer.

**Comment by gonzaloebiz** [comment]
Look at #1078
