### ISSUE TITLE
Installing data... Class Mailchimp does not exist

### ISSUE THREAD

**Issue by lightbyte** [mailchimp/mc-magento2#1087]
### Preconditions

    1. Magento CE 2.4
    2. mc-magento2 102.3.41

### Steps to reproduce

    1. Download the zip file from git
    2. Unzip it and copy it to app/code/Ebizmarts
    3. Rename copied folder to MailChimp
    4. In command line exec composer dump-autoload 
    5. Run bin/magento setup:upgrade
    6. And it ends with:

```
Module 'Ebizmarts_MailChimp':
Installing data... Class Mailchimp does not exist
```

### Actual and Expected result

Get the module installed correctly.

**Comment by gonzaloebiz** [comment]
Hi @lightbyte 

the extension needs this https://github.com/ebizmarts/mailchimp-lib if you install the extension via composer like is recommended this lib will be installed automatically.

Best
