### ISSUE TITLE
Magento2.4.x support

### ISSUE THREAD

**Issue by ufairiya** [mailchimp/mc-magento2#1088]
Tried to install the extension for Magento 2.4.1
But could not find a compatible version and the versions available are for M2.3.x
Will there be any issue when I install this for Magento 2.4.1 ?

**Comment by gonzaloebiz** [comment]
Take a look at https://github.com/mailchimp/mc-magento2/releases

Best

**Comment by ufairiya** [comment]
Thanks for the info. will check on this and get back to you.
