### ISSUE TITLE
The confirmation email is sent twice because the getImportMode () method cannot be honored

### ISSUE THREAD

**Issue by sedax90** [mailchimp/mc-magento2#1089]
### Preconditions

    1. Magento CE 2.4.1 without sample data is installed.
    2. mc-magento2 102.3.41
    3. Mailchimp double Opt In is activated
    4. Magento Config --> Mailchimp --> Magento always manage emails --> NO
    5. Magento Config --> Customer --> Newsletter --> Confirmation required --> YES

### Steps to reproduce
Subscribe to newsletter.

### Actual and Expected result
You will get two emails instead of once. One from Magento and one from Mailchimp.

### Additional information
I think the problem could be in Plugin beforeSubscribe(). This method add import_mode to true, but when magento subscribe a user it creates a new Subscriber object:

\Magento\Newsletter\Model\SubscriptionManager.php
```
$subscriber = $this->subscriberFactory->create()->loadBySubscriberEmail($email, $websiteId);
```

The correct way could be to add this data in the afterLoadBySubscriberEmail method.
I've create a new Plugin with this code, and now it works correctly:

```
class Subscriber
{
    protected Data $_helper;

    protected LoggerInterface $logger;

    /**
     * Subscriber constructor.
     * @param Data $_helper
     * @param LoggerInterface $logger
     */
    public function __construct(Data $_helper, LoggerInterface $logger)
    {
        $this->_helper = $_helper;
        $this->logger = $logger;
    }

    /**
     * @param \Magento\Newsletter\Model\Subscriber $subscriber
     * @param $result
     * @return mixed
     */
    public function afterLoadBySubscriberEmail(\Magento\Newsletter\Model\Subscriber $subscriber, $result)
    {
        try {
            if (!$this->_helper->getConfigValue(
                Data::XML_MAGENTO_MAIL,
                $result->getStoreId()
            )) {
                $result->setImportMode(true);
            }
        } catch (\Exception $exception) {
            $this->logger->critical($exception->getMessage());
        }

        return $result;
    }
}
```

**Comment by denis-zyk** [comment]
Hi @sedax90,

I was wondering what is the plan on adding the changes mentioned here to a new module release?

**Comment by artttj** [comment]
Hi @gonzaloebiz,

I assume the issue with double opt-in (#1108) is resolved now, isn't it?  
When to expect a new release?

**Comment by gonzaloebiz** [comment]
Hi @artttj 

yes, the issue is solved.
We don't have an ETA for a new release, sorry

Best

**Comment by artttj** [comment]
Hi @gonzaloebiz,

We pulled the code straight from [develop-2.4](https://github.com/mailchimp/mc-magento2/tree/develop-2.4) branch (Magento 2.4.1 Commerce).

Now we receive a double opt-in email from Mailchimp, both during registration and via subscription form. 
Which is great!

BUT then, once customer confirms their email (`Require Emails Confirmation` -> `Yes` in `Customer Configuration`, double opt-in is enabled on both MC and M2 sides), Magento sends transaction email with Newsletter subscription confirmation, even if `Magento always manage emails` option is set to `No`.

This is related to the current issue I guess.

[This part of the code](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Newsletter/Model/SubscriptionManager.php#L155) is being triggered. This can be overridden, but I'm wondering if you have a better solution.

Besides that we still have an issue in the customer account section, the Newsletter subscription status checkbox is not being set.

I can create another issue ticket if that makes sense, or please let us know if we are doing anything wrong. I wanted to inform you of what we've found.
My colleague is also in contact with Ebizmarts support, but I suppose we are in the right place to discuss the thing.
