### ISSUE TITLE
After adding MailChimp store, warning on grid.

### ISSUE THREAD

**Issue by jpratt** [mailchimp/mc-magento2#109]
Magento 2.1.9
1. Under "MailChimp Stores", I click to add a store. 
2. I fill out information to add a store.

Result: The store appears to save but when it is redirected to the stores I get: Warning: Invalid argument supplied for foreach() in /var/www/vhosts/xxxxxxx/releases/20171027235957/vendor/magento/framework/View/Element/UiComponent/DataProvider/DataProvider.php on line 252

This is problematic as I need to see a list of the stores. But this warning is shown instead.

**Comment by gonzaloebiz** [comment]
What version of m4m you have?

**Comment by jpratt** [comment]
I assume you are referring to the setup version. It is 1.0.24.

**Comment by gonzaloebiz** [comment]
check if you have an invalid api key in the apikey list

**Comment by jpratt** [comment]
My api key seems to work and get a list of valid lists from mailchimp.

**Comment by gonzaloebiz** [comment]
OK
The issue in only when you add a new store? If you go from the magento menus to mailchimp stores this not happens?

**Comment by jpratt** [comment]
Yes it does happen once one store is added and I go back to the stores list.

**Comment by gonzaloebiz** [comment]
Weird, i just test it and work OK for me.
Do you have any other additional information to reproduce the issue?

**Comment by jpratt** [comment]
No, just seeing this warning on the main stores grid. Does not show anything in the content except this warning.

**Comment by gonzaloebiz** [comment]
We need a way to reproduce.
You try in a vanilla installation?

**Comment by gonzaloebiz** [comment]
No news on 1 week, close the issue

**Comment by BaberAhmed** [comment]
Good Afternoon, I am having the same issue. I get same issue, please see below steps to recreate issue:

1) Install Module
2) configure with valid account and API key
3) Go to MailChimp > MailChimp Stores (grid + filters will load normally) click Add new MailChimp Store
4) Fill in details and click Save
5) Will attempt/Save the store and reload the grid, will fail and display the following error from then on it will always do this: You can attempt to add more stores but grid will fail to load.

Warning: Invalid argument supplied for foreach() in /var/www/magento/staging/vendor/magento/framework/View/Element/UiComponent/DataProvider/DataProvider.php on line 252

Module version 1.0.24
Magento version 2.1.4

Your help would be appreciated.

Kind Regards
Baber
