### ISSUE TITLE
Magento 2.3.6 - Locale AU - This MailChimp account is not connected to Magento.

### ISSUE THREAD

**Issue by gilbertsohal** [mailchimp/mc-magento2#1096]
# Issue reporting guidelines

To maintain an effective bugfix workflow and make sure issues will be solved in a timely manner we kindly ask reporters to follow some simple guidelines.

Before creating an issue, please do the following:

* Make sure the behavior you are reporting is really a bug, not a feature.
* Check the existing [issues](https://github.com/mailchimp/mc-magento2/issues) to make sure you are not duplicating somebody’s work.
* Make sure, that information you are about to report is a technical issue, please refer to the [Community Forums](http://ebizmarts.com/mailchimp-for-magento-support)  for technical questions.

If you are sure that the problem you are experiencing is caused by a bug, file a new issue in a Github issue tracker following the recommendations below.

## Title

Magento 2.3.6 - Locale AU - This MailChimp account is not connected to Magento.

Good example would be:

> Unable to Connect MailChimp account with Magento.

Unclear example:

> This MailChimp account is not connected to Magento.

### Preconditions

After successfully Allow the access for mailchimp list still getting (This MailChimp account is not connected to Magento.) and there is nothing showing in Mailchimp Store and Mailchimp List.

Example:

    1. Magento CE 2.3.6 without sample data is installed.
    2. mc-magento2 102.3.41.
    3. Test category is set up.
    4. Virtual Product is created and assigned to the Test Category.
    ...

### Steps to reproduce

After successfully Allow the access for mailchimp still getting (This MailChimp account is not connected to Magento.) and there is nothing showing in Mailchimp Store and Mailchimp List. 

When I check the console I m getting script error. I’m using AU locale without any other issue. Could you please help me to sort out the issue.

Screenshot 2
https://nimb.ws/6KbPe2

Unable to resolve the source file for 'adminhtml/Magento/backend/en_US/configmonkeyapikey.js'
<pre>#1 Magento\Framework\App\StaticResource->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#2 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\StaticResource#00000000754ee28e0000000038430270#) called at [pub/static.php:13]
</pre>

Unable to resolve the source file for 'adminhtml/Magento/backend/en_US/mailchimpconfirmation.js'
<pre>#1 Magento\Framework\App\StaticResource->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#2 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\StaticResource#000000006989bad6000000001c74c86f#) called at [pub/static.php:13]
</pre>

Example:

    1. Navigate to Mailchimp > Mailchimp General Configuration.
    2. Open Get API credentials.
    3. Click "Login" on the Popup.
    4. Allow Access.
    5. Copy the above API Key and paste it on MailChimp > Configuration > MailChimp General Configuration > API Key list
    ...

### Actual and Expected result

This MailChimp account is connected to Magento.

Example:

    Expected result:
    Order is placed successfully, customer is redirected to the success page.
    Actual result:
    "Place order" button is not visible, order cannot be placed.

### Additional information

Additional information is often requested when the bug report is processed, you can save time by providing Magento and browser logs, screenshots, any other artifacts related to the issue at your own judgement.

**Comment by gonzaloebiz** [comment]
Hi @gilbertsohal 

looks like you update the extension from an old version and you don't generate the static files ok.
Delete the pub/static directory (run rm -rf pub/static/*) and regenerate the static files
run
bin/magento -f setup:static-content:deploy
bin/magento cache:clean

best
