### ISSUE TITLE
Problem with suscription

### ISSUE THREAD

**Issue by jcarlosebizmarts** [mailchimp/mc-magento2#1106]
Issue Description:

A Customer created and subscribed directly from Magento's Frontend appears as Blank under the Email Marketing Tab in the Mailchimp All Contacts.

Preconditions:

    1. Magento 2.4.2 with Sample Data Installed.
    2. mc-magento2 v102.3.42.
    3. M4M is Configured, Mailchimp and eCommerce are Enabled.

Steps to reproduce:

    1. Create an account on Frontend.
    2. Wait and Check Mailchimp to see if the Customer was received.
    3. Subscribe to Newsletter from either the Footer Form, Account Settings or Checkout.
    4. Wait and Check Mailchimp to see if the Subscriber was received.

Actual and Expected result:

    Expected result: 
    Subscriber information is received and Email Marketing says Subscribed.
    Actual result:
    Subscriber information is received but Email Marketing tab appears blank.

**Comment by gonzaloebiz** [comment]
Please take a look at https://github.com/mailchimp/mc-magento2/pull/1120

Best
