### ISSUE TITLE
Error with option "Magento always manage emails" in Mailchimp configuration

### ISSUE THREAD

**Issue by jcarlosebizmarts** [mailchimp/mc-magento2#1108]
Issue Description:

Magento seems to always send the emails of confirmation and welcome ignoring if the "Magento always manage emails" setting is either on yes or no.

Preconditions:

    1. Magento 2.4.2 with sample data installed.
    2. mc-magento2 v102.3.42.
    3. Mailchimp and Magento are configured with Double-opt in.
    4. Mailchimp has the option "Send a final welcome email" checked in. 
    5. Magento's Newsletter has the option "Need to confirm" on.
    6. Mailchimp for Magento has "Magento always manage emails." off.

Steps to reproduce:

    1. Enter the Main Site either as a Guest or a Customer.
    2. Subscribe to Newsletter from Footer Form or Account Settings.
    3. Receive the confirmation email.
    

Actual and Expected result:

    Expected result:
    Suscription and welcoming email are received directly from Mailchimp.
    Actual result:
    Both emails are received from Magento regardless of configuration.    

Additional information

We had Mandrill installed to make these tests, we tested both with "Magento always manage emails" on and off, and enable double-opt in, on and off in both Magento and Mailchimp.

**Comment by sedax90** [comment]
I think this problem could be related (and solved) with this: https://github.com/mailchimp/mc-magento2/issues/1089

**Comment by gonzaloebiz** [comment]
Please take a look at https://github.com/mailchimp/mc-magento2/issues/1089
