### ISSUE TITLE
Filled in Interest groups not visible in admin area

### ISSUE THREAD

**Issue by Jeroenll** [mailchimp/mc-magento2#1109]
### Preconditions
1. Magento CE 2.3.4.
2. mc-magento2 102.3.42.

### Steps to reproduce
1. Setup audience with interest group.
2. Create customer account, subscribe to newsletter and fill in interest group in my account section.
3. Open customer in admin area and open mailchimp tab.

#### Expected result:
Interest groups are shown with values selected.

#### Actual result:
Interest groups are shown without selected values.

**Comment by gonzaloebiz** [comment]
Hi @JeroenVanLeusden 

Have you already try with version 102.3.44? With this version works Ok for me

Best
