### ISSUE TITLE
Installation error 102.3.41

### ISSUE THREAD

**Issue by tschirmer** [mailchimp/mc-magento2#1114]
## Title

Installation error on Magento 2.3.6 @ Mailchimp module 102.3.41

> Can't install

### Preconditions
1.  Magento CE 2.3.6 without sample data installed.
2. Composer install with 102.3.41
2. run install script:
```
Module 'Ebizmarts_MailChimp':
Installing data... Upgrading data...
In Mysql.php line 110:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mailchimp_abandonedcart_flag' in 'field list', query was: UPDATE `sales_order_grid` AS `G`
   INNER JOIN `sales_order` AS `O` ON O.entity_id = G.entity_id
  SET `G`.`mailchimp_flag` = IF(mailchimp_abandonedcart_flag OR mailchimp_campaign_id OR mailchimp_landing_page, 1, 0)


In Mysql.php line 91:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mailchimp_abandonedcart_flag' in 'field list'

```

### Steps to reproduce
This is quite buggy in reproduction. Something this works, and sometimes it doesn't, it appears like a race condition on the database. 

our requires within our composer.json are:
```
    "magento/data-migration-tool": "2.3.5",
    "magento/product-community-edition": "2.3.6",
    "magento2translations/language_en_au": "2.3.x-dev",
    "mailchimp/mc-magento2": "102.3.41",
```
Example:

1.  composer install
2. bin/magento setup:install

### Actual and Expected result

    Expected result:
    Should install with no errors:

    Actual result:
    Every few installs this error occurs. It's not consistent, but on our infrastructure it's maybe 1/2 the time.

**Comment by gonzaloebiz** [comment]
Hi @tschirmer 

this is only possible if you a prior installation, thus is if you have an entry in the setup_module for the extension.
This way magento thinks you are updating the extension and not installing it.
So, be sure that you don't have an entry in setup_module

Best

**Comment by tschirmer** [comment]
Hey @gonzaloebiz 

This was after a fresh database installation (drop database, create database).

Thanks,
Tony
