### ISSUE TITLE
Error due to customer data race condition

### ISSUE THREAD

**Issue by maderlock** [mailchimp/mc-magento2#112]
Magento 2.1.9
Mailchimp module 1.0.25
Varnish 3

Checkout works fine.
When I turn on the MailChimp extension and fill in details:

Visiting the checkout I get stuck on a wait spinner. The following error is shown in the console:

    section-config.js:33 Uncaught TypeError: Cannot read property '*' of undefined
        at Object.getAffectedSections (section-config.js:33)
        at HTMLDocument.<anonymous> (customer-data.js:344)
       at HTMLDocument.dispatch (jquery.js:5226)
        at HTMLDocument.elemData.handle (jquery.js:4878)
        at Object.trigger (jquery.js:5130)
        at Object.jQuery.event.trigger (jquery-migrate.js:493)
        at done (jquery.js:9858)
        at XMLHttpRequest.callback (jquery.js:10311)

This is due to a post-ajax event listener looking for affected sections, which is expecting customer data to be loaded. As this is a race condition, depending on your setup you may not have an issue.

The solution to this particular error could be to change the call in mailchimp.js to be a GET (as it should be as it does not affect internal state). The listener only fires getAffectedSections on a POST or PUT as these are the only calls that should change Magento's internal state.

Sadly, although this gets rid of the javascript error, the only way I can get the checkout working again is to disable MailChimp completely. I suspect there are other race conditions as on one server this is working for me, but the same installation code and data does not work on another similar server.

**Comment by gonzaloebiz** [comment]
Can you share your varnish configuration?

**Comment by maderlock** [comment]
Sure:

	import std;
	# The minimal Varnish version is 3.0.5
	# For SSL offloading, pass the following header in your proxy server or load balancer: 'X-Forwarded-Proto: https'

	backend default {
	    .host = "127.0.0.1";
	    .port = "8080";
	}
	acl purge {
	    "127.0.0.1";
	}
	sub vcl_recv {
	    # Uncomment to disable hits - always pass!!
	    return (pass);

	    if (req.restarts == 0) {
	        if (req.http.x-forwarded-for) {
	            set req.http.X-Forwarded-For =
	            req.http.X-Forwarded-For + ", " + client.ip;
	        } else {
	            set req.http.X-Forwarded-For = client.ip;
	        }
	    }
	    if (req.request == "PURGE") {
	        if (client.ip !~ purge) {
	            error 405 "Method not allowed";
	        }
	        if (!req.http.X-Magento-Tags-Pattern) {
	            error 400 "X-Magento-Tags-Pattern header required";
	        }
	        ban("obj.http.X-Magento-Tags ~ " + req.http.X-Magento-Tags-Pattern);
	        error 200 "Purged";
	    }
	    if (req.request != "GET" &&
	        req.request != "HEAD" &&
	        req.request != "PUT" &&
	        req.request != "POST" &&
	        req.request != "TRACE" &&
	        req.request != "OPTIONS" &&
	        req.request != "DELETE") {
	          /* Non-RFC2616 or CONNECT which is weird. */
	          return (pipe);
	    }
	    # We only deal with GET and HEAD by default
	    if (req.request != "GET" && req.request != "HEAD") {
	        return (pass);
	    }
	    # Exclude the admin panel and SOAP API
	    if (req.url ~ "/admin" || req.url ~ "/soap") {
	        return (pass);
	    }

	    if (req.url ~ "/wp/") {
	        return (pass);
	    }

	    if (req.url ~ "/c3_tiling/tilingblock/layout") {
	        return (pass);
	    }
	    # We only deal with GET and HEAD by default
	    if (req.request != "GET" && req.request != "HEAD") {
	        return (pass);
	    }
	    # Bypass shopping cart, checkout and search requests
	    if (req.url ~ "/checkout" || req.url ~ "/catalogsearch") {
	        return (pass);
	    }
	    # normalize url in case of leading HTTP scheme and domain
	    set req.url = regsub(req.url, "^http[s]?://", "");
	    # collect all cookies
	    std.collect(req.http.Cookie);
	    # static files are always cacheable. remove SSL flag and cookie
	    if (req.url ~ "^/(pub/)?(media|static)/.*\.(ico|css|js|jpg|jpeg|png|gif|tiff|bmp|gz|tgz|bz2|tbz|mp3|ogg|svg|swf|woff|woff2|eot|ttf|otf)$") {
	        unset req.http.Https;
	        unset req.http.X-Forwarded-Proto;
	        unset req.http.Cookie;
	    }
	    set req.grace = 1m;
	    return (lookup);
	}
	sub vcl_hash {
	    if (req.http.cookie ~ "X-Magento-Vary=") {
	        hash_data(regsub(req.http.cookie, "^.*?X-Magento-Vary=([^;]+);*.*$", "\1"));
	    }
	    if (req.http.X-Forwarded-Proto) {
	        hash_data(req.http.X-Forwarded-Proto);
	    }
	}
	sub vcl_fetch {
	    if (beresp.http.content-type ~ "text") {
	        set beresp.do_esi = true;
	    }
	    if (req.url ~ "\.js$" || beresp.http.content-type ~ "text") {
	        set beresp.do_gzip = true;
	    }
	    # cache only successfully responses and 404s
	    if (beresp.status != 200 && beresp.status != 404) {
	        set beresp.ttl = 0s;
	        return (hit_for_pass);
	    } elsif (beresp.http.Cache-Control ~ "private") {
	        return (hit_for_pass);
	    } elsif (beresp.http.varnish-control ~ "no-cache") {
	        set beresp.ttl = 0s;
	        return (hit_for_pass);
	    }
	    # Cache 404s but only for 30 seconds
	    if (beresp.status == 404) {
	        set beresp.ttl = 30s;
	    }
	    if (beresp.http.X-Magento-Debug) {
	        set beresp.http.X-Magento-Cache-Control = beresp.http.Cache-Control;
	    }
	    # validate if we need to cache it and prevent from setting cookie
	    # images, css and js are cacheable by default so we have to remove cookie also
	    if (beresp.ttl > 0s && (req.request == "GET" || req.request == "HEAD")) {
	        unset beresp.http.set-cookie;
	        if (req.url !~ "\.(ico|css|js|jpg|jpeg|png|gif|tiff|bmp|mp3|ogg|svg|swf|woff|woff2|eot|ttf|otf)(\?|$)") {
	            set beresp.http.Pragma = "no-cache";
	            set beresp.http.Expires = "-1";
	            set beresp.http.Cache-Control = "no-store, no-cache, must-revalidate, max-age=0";
	            set beresp.grace = 1m;
	        }
	    }
	}
	sub vcl_deliver {
	    if (resp.http.X-Magento-Debug) {
	        if (obj.hits > 0) {
	            set resp.http.X-Magento-Cache-Debug = "HIT";
	        } else {
	            set resp.http.X-Magento-Cache-Debug = "MISS";
	        }
	    } else {
	        unset resp.http.Age;
	    }
	    unset resp.http.X-Magento-Debug;
	    unset resp.http.X-Magento-Tags;
	    unset resp.http.X-Powered-By;
	    unset resp.http.Server;
	    unset resp.http.X-Varnish;
	    unset resp.http.Via;
	    unset resp.http.Link;
	}

**Comment by maderlock** [comment]
I will try completely bypassing varnish in case it's the use of varnish that is what is causing the issue.

**Comment by gonzaloebiz** [comment]
Hi @maderlock 

i try with both, with POST and GET in https://github.com/mailchimp/mc-magento2/blob/develop/view/frontend/web/js/mailchimpjs.js#L4 and both works for me.
Can you identify the differences of your servers? Perhaps the version of varnish or php or both, perhaps some configuration in magento
I know , is hard to reproduce in fact i can't.
Anyway, i think you are wright, the ajax call must be a GET

Best

**Comment by maderlock** [comment]
It's difficult, as I have virtually identical setups and on one this causes a problem and another it does not. I will delve deeper into this as soon as I can.

Thanks for making the POST->GET change. It may be that the listener causing the error only fires when varnish is in use, but this will remove one javascript error from the console so at least I can discount that.

**Comment by dan-ding** [comment]
Seeing this too. No varnish.

**Comment by maderlock** [comment]
Still seeing this issue with Magento 2.2. Not just in the checkout now either. I'm using the latest numbered version of the extension: 1.0.27

**Comment by maderlock** [comment]
I see that the change in commit 403af40 does not seem to have made it into releases. Any reason why?

**Comment by gonzaloebiz** [comment]
@maderlock 

no, i don't know why, surely for an error in our end.
With this modification your issue has gone?
