### ISSUE TITLE
Subscibers List Import from CSV do not sync to Magento 2

### ISSUE THREAD

**Issue by kkazadi** [mailchimp/mc-magento2#1129]
### Preconditions
1. Magento CE 2.3.4
2. Mailchimp v102.3.42

### Steps to reproduce
1. Setup Mailchimp module in Magento backend with Stores and API keys
2. Setup Audience with tags.
3. Import subscriber list from CSV
4. Imported subscribers appear in Mailchimp audience list

### Expected result
Audience List to sync to Magento Newsletter list including imported subscribers from CSV as shown in Mailchimp.
![Screenshot_395](https://user-images.githubusercontent.com/23381441/110781740-f1392680-826e-11eb-8a71-a0b98df492ef.png)

### Actual
All subscribers synced to Magento Newsletter list except imported subscribers from CSV

### Additional information

Noticed when creating webhook, it shows supported source as per below
By a subscriber
By an account admin
By the API

Could this be the reason, imported subscribers not syncing to Magento 2, see attached
![Screenshot_396](https://user-images.githubusercontent.com/23381441/110781594-c64ed280-826e-11eb-9f0a-d06671b85607.png)

**Comment by gonzaloebiz** [comment]
Hi @kkazadi 

thanks for your feedback.
Is your site public?  Keep in mind that the webhooks works only for public and not protected sites.
The best option is to delete the existing webhook in Mailchimp and create a new one from the extension configuration page, you have a button for this.
![image](https://user-images.githubusercontent.com/6222792/110788400-52e89900-824d-11eb-9ed3-0160ceac171e.png)

**Comment by kkazadi** [comment]
Hi @gonzaloebiz 

Thank you for your prompt feedback.
The website is public and not protected,
I have deleted the existing webhook from MC and re-created it from Magento backend Mailchimp configuration as suggested but still not syncing imported subscribers from Mailchimp to Magento. Not sure what else to do here or if the imported subscribers are supported or expected to be synced back to Magneto?

**Comment by gonzaloebiz** [comment]
Please contact our support by email at mailchimp@ebizmarts-desk.zendesk.com to help you
