### ISSUE TITLE
How does migration from M1 to M2 work? is there a guide? tips tricks?

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento2#1130]
## Title

How does migration from M1 to M2 work? is there a guide? tips tricks?

Can you add this to the readme file?

## Issue Description

We dont know how to migrate from M1 to M2

### Preconditions

Magento 1.9.4.x

### Steps to reproduce

No steps yet, because this is the question?

**Comment by gonzaloebiz** [comment]
the extension doesn't support migration, you must re-sync all the data

Best

**Comment by seansan** [comment]
There are no fields to migrate? UUID or?

And if we connect m2 to the same list will this work?

Sorry the answer is a little too short.

**Comment by gonzaloebiz** [comment]
We don't recommend using the same audience
You must create a new Mailchimp store, because in Mailchimp the store contains the version of magento.
If you use the same audience for the Mailchimp store, all the subscribers will be rejected as already subscribed.

Best

**Comment by seansan** [comment]
Wow! this sounds rather dangerous

- MC may contain emails that M1 does not?
- and many flows have been set up in MC ... "just" making a new audience
for every store ... sounds like dangerous and a lot of work!



thanks, Sean

**Comment by gonzaloebiz** [comment]
why dangerous?

**Comment by seansan** [comment]
What about recording the steps somewhere to avoid problems? I can only
assume that many have already migrated etc. and that knowledge on this
subject is available. Especially by Ebizmarts! ;)
