### ISSUE TITLE
Mailchimp not sync after upgrade magento version

### ISSUE THREAD

**Issue by neulhoangtran** [mailchimp/mc-magento2#1131]
Hi Team.
I got an issue after completed upgrading magento version from magento 2.3.3 to magento 2.4.2
it thrown errow in mailchimp log : https://prnt.sc/10tx8rl
and it can't sync: https://prnt.sc/10tx9mp
Can everybody tell me why it occur and how to fix it? Thanks alot!

**Comment by gonzaloebiz** [comment]
Hi @HoangTN96 

thanks for choosing our extensions.
Please contact our support team.

Best

**Comment by neulhoangtran** [comment]
Hi @gonzaloebiz 
How i can contact with them ?
Awaiting your reply!

**Comment by gonzaloebiz** [comment]
Look at the home page of the extension

![image](https://user-images.githubusercontent.com/6222792/112517757-73e5d980-8d77-11eb-8d1a-951be2554b44.png)
