### ISSUE TITLE
Exception when running cron

### ISSUE THREAD

**Issue by maderlock** [mailchimp/mc-magento2#114]
Pre-condition

**Extension v1.0.25**
Magento 2.1.9
Steps

Enable in config and turn on ecommerce syncing
Start cron job syncing
Expected result

Sync will run multiple times, updating customers, products etc.
Actual result

Sync runs multiple times, updating customers, products etc.

Then at some point it starts crashing out and then crashes every time with this message:

[RuntimeException]
Cron-job "ebizmarts_ecommerce" threw exception
Magento\Framework\Exception\NoSuchEntityException

[Magento\Framework\Exception\NoSuchEntityException]
Requested product doesn't exist

I'm not sure at what point this occurs as the runtime exception does not seem to be logged.

However, here is what is being stored in the cron schedule table:
![screenshot 2017-11-08 10 54 17](https://user-images.githubusercontent.com/630320/32545360-63c59886-c473-11e7-8985-3a72cdc0e236.png)

I would not be surprised if orders exist for products that have since been deleted. That's pretty normal on a Magento site, which is why so many product details are stored against order items.

**Comment by maderlock** [comment]
Tested with develop branch. Still having the same error. Is there any logging I could add that might help you resolve this for me?

**Comment by maderlock** [comment]
I've put a try catch block around the whole cron job. Here is what I get:

	Requested product doesn't exist#0 .../web-root/vendor/mailchimp/mc-magento2/Model/Api/Product.php(128): Magento\Catalog\Model\ProductRepository->get(NULL)
	#1 .../web-root/vendor/mailchimp/mc-magento2/Cron/Ecommerce.php(169): Ebizmarts\MailChimp\Model\Api\Product->_sendProducts(1)
	#2 .../web-root/vendor/mailchimp/mc-magento2/Cron/Ecommerce.php(123): Ebizmarts\MailChimp\Cron\Ecommerce->_processStore(1, '<hidden>...', '<hidden>')
	#3 [internal function]: Ebizmarts\MailChimp\Cron\Ecommerce->execute(Object(Magento\Cron\Model\Schedule))

It looks like you've added product existence checks around pushing orders and the cart, but this seems to be trying to sync products. I can see that the line in question is attempting to load a product by SKU, but the product does not exist. I'm not sure how this list gets populated, but by wrapping this line in a try catch block and continuing (possibly removing the item?) this might resolve the error.

Certainly in my case just continuing at this point has allowed me to sync up more data, though I don't know if I'll have issues with holes. Probably not a great problem as it would surely be the oldest orders that match non-existant items.

**Comment by maderlock** [comment]
I wonder if this has been caused by the batch nature of product upload? If this takes a while and products are deleted during the process, could this cause the issue? Sounds plausible...

**Comment by gonzaloebiz** [comment]
When an order/cart was synced, first of all, the products in the order/cart are synced. In the case of an order/cart that contains a product that was deleted no product are synced and the order/cart neither (that is because the total of the order/cart not match the lines). And the order/cart is marked as with errors to allow continues with the others orders/carts

Best

**Comment by maderlock** [comment]
Do you know why I'm getting this error unless I put the try/catch in Model/Api/Product.php? Currently I'm having to leave a modified file on the live server and exclude it from deployment. It would be good to get this fix into a release. And I'd like to know if just skipping products on line 128 is safe!

**Comment by khnaim** [comment]
Issues in version 1.0.28 and 1.0.29 , did you find a solution for this fix ?
