### ISSUE TITLE
Enhancement request: coupon generation

### ISSUE THREAD

**Issue by maderlock** [mailchimp/mc-magento2#115]
I have a couple of clients asking if there is any way to generate coupons for abandoned carts. Having a global one is insecure and cannot be time limited.

Uncertain how this would work given that it is Mailchimp that creates these messages. Perhaps a coupon could be created by Magento on spec and then pushed to MailChimp? Or a webhook used to tell Magento to create it?

Really interested to hear if this is possible or any ideas you have for getting something like this working.

**Comment by gonzaloebiz** [comment]
That's is not possible for now, sorry
