### ISSUE TITLE
Typo in events.xml

### ISSUE THREAD

**Issue by blaurienti** [mailchimp/mc-magento2#1161]
I found an issue in app/etc/events.xml on line 27

<observer name="'mailchimp_newsletter_subscriber_save_before" instance="\Ebizmarts\MailChimp\Observer\Subscriber\SaveBefore" />

There's a single quote in the name attribute.

**Comment by gonzaloebiz** [comment]
Take a look at https://github.com/mailchimp/mc-magento2/issues/1102
