### ISSUE TITLE
Unsubscribed Customers Sent To Mailchimp

### ISSUE THREAD

**Issue by kestraly** [mailchimp/mc-magento2#1172]
Magento 2.3.6-p1
MC version - 102.3.42

**Expected Behaviour**
Customer places an order as a guest without subscribing to the newsletter. _no sync with MailChimp is performed._
Customer creates an account, but does not subscribe to newsletter. _no sync with MailChimp is performed._

**Current Behaviour**
Customer places an order as a guest without subscribing to the newsletter, _customer is syncronized with MailChimp as Unsubscribed_
Customer creates an account, but does not subscribe to newsletter. _customer is syncronized with MailChimp as Unsubscribed_

MailChimp becomes flooded with unsubscribed customers.

An initial check for none subscribers?

The guest order is more of a concern

**Comment by gonzaloebiz** [comment]
The customer is created in mailchimp as a customer (not as a subscriber)
All orders must be linked to a customer in Mailchimp, no matter if the customer is subscribed or not

Best
