### ISSUE TITLE
Mailchimp not working

### ISSUE THREAD

**Issue by stjohnkrog11** [mailchimp/mc-magento2#1177]
I have downloaded the latest version from adobe and done a manual install, run setup:upgrade and i am getting the following: 

                                                                                                                                       
Warning: DOMXPath::query(): Invalid predicate in /Users/stjohn/Projects/client/vendor/magento/framework/Config/Dom.php on line 336

I have tried multiply ways of fixing this and getting no where with it.

Any help or guidance would be amazing!

**Comment by gonzaloebiz** [comment]
Please use the issue format

**Comment by stjohnkrog11** [comment]
Thank you for the help. I will do it again.
