### ISSUE TITLE
Magento DOI confirmation mail sent although "Magento always manage emails" set to "no"

### ISSUE THREAD

**Issue by Wutzl** [mailchimp/mc-magento2#1189]
### Preconditions

    1. Magento CE 2.3.6-p1
    2. Mailchimp v102.3.41
    3. New Customers have to confirm their registration (Magento's "Require Emails Confirmation" at config section "Create New Account Options" is set to yes.)

### Steps to reproduce

"Magento always manage emails" is set to no in the magento backend configuration of the module, so that the email to confirm your newsletter subscription comes from MailChimp instead of Magento. Works fine except for users who subscribe to newsletter while creating a new account in the shop. In that case, after registration I receive an email to confirm my account from Magento, aswell as the email to confirm my newsletter registration from MailChimp (as expected).
But once I confirm my shop account, I afterwards get the email to confirm my newsletter subscription from Magento aswell.

### Actual and Expected result

    Expected result:
    Magento's newsletter confirmation email isn't sent after confirming the shop account.
    Actual result:
    Magento's newsletter confirmation email is sent after confirming the shop account.

**Comment by gonzaloebiz** [comment]
Hi @Wutzl 

take a look at https://github.com/mailchimp/mc-magento2/issues/1106
For magento  2.3.6-p1 you must use the branch corresponding to 2.4

Best
