### ISSUE TITLE
No check for store id != -1 in Ecommerce.php 150th line

### ISSUE THREAD

**Issue by archonkulis** [mailchimp/mc-magento2#119]
Running newest version of extension ( 1.0.25 ) cron "ebizmarts_ecommerce" and receiving:

"Resource Not Found : The requested resource could not be found"

Found out that it's because there is no check on 150th line:

```
        foreach($syncs as $mailchimpStoreId => $val) {
            if($val&&!$this->_helper->getConfigValue(\Ebizmarts\MailChimp\Helper\Data::XML_PATH_IS_SYNC."/$mailchimpStoreId", 0, 'default')) {
                $api = $this->_helper->getApi($val['storeid']);
                $api->ecommerce->stores->edit($mailchimpStoreId, null, null, null, null, null, null, null, null, null, null, false);
                $this->_helper->saveConfigValue(\Ebizmarts\MailChimp\Helper\Data::XML_PATH_IS_SYNC."/$mailchimpStoreId", date('Y-m-d'), 0, 'default');
            }
        }
```

after foreach, there should be check:

```
                $mailchimpStoreId  = $this->_helper->getConfigValue(\Ebizmarts\MailChimp\Helper\Data::XML_MAILCHIMP_STORE, $storeId);
                if ($mailchimpStoreId != -1) {
.....
}
```

Or something like that.

Let me know what you think.

Thanks.

**Comment by gonzaloebiz** [comment]
Hi @archonkulis,

please follow the [guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines) for issue reporting.

**Comment by archonkulis** [comment]
@gonzaloebiz This is not the usual case, where I can show how to reproduce the error - this is something I noticed when manually running the cron. Please read what I wrote in the description and you will most likely understand everything - if you need something specific, please let me know and don't close the ticket just like that without at least reading what I wrote - it shows that you don't value other peoples time. Thank you.
