### ISSUE TITLE
Not seeing guest abandoned cart emails

### ISSUE THREAD

**Issue by maderlock** [mailchimp/mc-magento2#120]
Setup
* 1.0.25 plus a couple of commits (35a4245f1ae63d0ecf574716c5865e13f3597a77)
* magento 2.1.9
* Varnish 3
* Default abandoned cart automation (series of 3 emails) in MailChimp
* Sync with MailChimp listed as complete - I can see recent customers listed on MailChimp and ecommerce data for recent orders

Steps
* As a guest, add items to cart and get to payment step of checkout so that email address is captured in quote
* Ensure that ecommerce cron job is running
* Wait 1 hour and maybe a little longer

Expected
* An abandoned cart email and listing at least 1 email sent in MailChimp

Actual
* No email sent
* MailChimp lists 0 emails sent out

I don't know how to check whether a cart has been pushed to MailChimp from either side, but the steps to recreate seem sufficient.

I'll now test with a signed in customer and see if that makes a difference.

**Comment by gonzaloebiz** [comment]
Hi @maderlock 

check the table cron_schedule for the job_code ebizmarts_ecommerce.
If the table don't show errors, check the table quote and confirm that the quote you want have a customer_email and is_active and not converted.
If the quote looks OK, check the table mailchimp_sync_ecommerce with type = QUO and related_id = your quote id, if no mailchimp_sync_error on this table for this quote, then the quote must be synced.
You can check if the quote was synced OK via the mailchimp API with postman (https://www.getpostman.com/), keep in mind the the cart id in mailchimp is the quote id in magento.

Best

**Comment by aasim110** [comment]
Hi @gonzaloebiz I can't receive any abandoned cart for both logged in user and guest users as well.

Setup

    Magento 2.1.9
    Default abandoned cart automation (series of 3 emails) in MailChimp
    Sync with MailChimp listed as complete - I can see recent customers listed on MailChimp and ecommerce data for recent orders, Total Products, Total Carts.
    Checked the table cron_schedule for the job_code ebizmarts_ecommerce and not found any error message
    Checked the table quote and confirmed that the quote was not converted.
    Checked the tablemailchimp_sync_ecommerce with type = QUO and related_id, and not found anything on mailchimp_sync_error table for this quote

Steps

    As a logged in user or guest, add items to cart and get to payment step of checkout so that email address is captured in quote
    Ensure that ecommerce cron job is running
    Wait for whole day and maybe longer

Expected

    An abandoned cart email and listing at least 1 email sent in MailChimp

Actual

    No email sent
    MailChimp lists 0 emails sent out

**Comment by gonzaloebiz** [comment]
No news in one week
