### ISSUE TITLE
Confused about which version to install on Magento 2.3.7

### ISSUE THREAD

**Issue by hostep** [mailchimp/mc-magento2#1205]
## Issue Description

Release https://github.com/mailchimp/mc-magento2/releases/tag/102.3.43 says:

> Use this version ONLY for Magento 2.3
> ...
> ATTENTION
> If you use Magento 2.3.6-p1 or up, install the version for Magento 2.4

However https://github.com/mailchimp/mc-magento2/releases/tag/103.4.43 says:

> Use this version ONLY for Magento 2.4

That's part one of the confusion.

Part two is that [103.4.x](https://github.com/mailchimp/mc-magento2/blob/103.4.43/composer.json#L27) has this constraint:

```
"magento/framework": "103.0.*",
```

Which means it can't be installed on Magento 2.3.x

So there is some confusion into what version we should install on Magento 2.3.7.
Does 102.3.43 have known issues on 2.3.7? If yes: how can we install 103.4.43 on 2.3.7 if the composer constraints don't allow us to?

Thanks!

**Comment by gonzaloebiz** [comment]
Hi @hostep 

thanks for your feedback.
Take a look at the new release https://github.com/mailchimp/mc-magento2/releases/tag/103.4.43

Best

**Comment by hostep** [comment]
Thanks @gonzaloebiz! I can install 103.4.43 on Magento 2.3.7 now!

But did you now just re-release 103.4.43 with different code then before? You can never do that!
People who already had installed the previous 103.4.43 version will get very confused why a "newer" version is suddenly released with different code but the same version. This new version should have been published as 103.4.44 I think!

Also, the constraint `"magento/framework": "103.0.*||>=102.0.6-p1",` will allow this module to get installed on Magento 2.5 or 2.6 which aren't released or verified with your module yet.
See https://jubianchi.github.io/semver-check/#/103.0.*||%3E%3D102.0.6-p1/199.99.99

A better constraint would have been: `102.0.6-p1||^102.0.7||^103.0`, see https://jubianchi.github.io/semver-check/#/102.0.6-p1||^102.0.7||^103.0/199.99.99 (I'm not sure how composer deals with `-p1` in their constraints, and the tool linked here doesn't seem to take that into account, so please double check yourself first)

**Comment by hostep** [comment]
And another big problem!

Running `bin/magento setup:di:compile` on Magento 2.3.7 with 103.4.43 of this module gives this error:

```
  Class Magento\Framework\View\Helper\SecureHtmlRenderer does not exist
```

This class was introduced in Magento 2.4.0: https://github.com/magento/magento2/blob/2.4.0/lib/internal/Magento/Framework/View/Helper/SecureHtmlRenderer.php
And doesn't exist yet in Magento 2.3.7: https://github.com/magento/magento2/blob/2.3.7/lib/internal/Magento/Framework/View/Helper/SecureHtmlRenderer.php

So version 103.4.x is definitely not compatible with Magento 2.3.x and you really shouldn't recommend this!

Please always test before making claims about Magento compatibility, this doesn't appear to have been done here!

**Comment by gonzaloebiz** [comment]
Hi @hostep 

take a look at this version https://github.com/mailchimp/mc-magento2/releases/tag/103.2.43-p1

Best

**Comment by hostep** [comment]
Thanks @gonzaloebiz, I'll try it out later this week.

But your constraints are still very wrong because `102.0.6-p1||>=102.0.7` will allow version 999.999.999 as well, which is probably not desired?

**Comment by hostep** [comment]
@gonzaloebiz: any thoughts on this constraint? Do you agree it's not correct and should be reworked in the next version?

**Comment by gonzaloebiz** [comment]
Hi @hostep 

yes, we will fix it in the next version

Best
