### ISSUE TITLE
Magento 2.3 - Mailchimp is not savind Interest Group on Success Checkout Page

### ISSUE THREAD

**Issue by FBXWEB** [mailchimp/mc-magento2#1207]
### Preconditions

    1. Magento CE 2.3.2 without sample data is installed.
    2. mc-magento v102.3.43
    3. PHP 7.2
    4. Interest Group created on Mailchimp Dashboard, and is showed in Magento Admin (maichimp configurations)
    ...

### Steps to reproduce
1 - Install Mailchimp following the instructions on Mailchimp Releases Page to find the right version to Magento 2.3.2:
https://github.com/mailchimp/mc-magento2/releases

Version 102.3.43
@gonzaloebiz gonzaloebiz released this 4 days ago
Use this version ONLY for Magento 2.3
For install it, run
Composer Command to Install:  composer require mailchimp/mc-magento2:102.3.43

2 - After Installation using composer run the command:
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy -f

3 - Setup mailchimp following this documentation: https://mailchimp.com/pt-br/help/connect-or-disconnect-mailchimp-for-magento-2/

4 - After setup everything following the user guide, I've created the Interest Group in Mailchimp Dashboard, and then I've setup this Interest Group to be showed in Magento Checkout Success Page.  I've choose the CHECKBOX TYPE and Created 3 interest for this group;

### Actual Result:

I've selected one or all interest checkbox options and hit the button to assign the newsletter, when I will check on Mailchimp Dashboard, the customer name, address, phone are been displayed as "Subscribed", but in the GROUP COLUMN there isnt any information that I've selected on checkout. The same happen if I try to assign trough customer dashboard. Don't matter where I never get the group interest options saved in Mailchimp Dashboard. 
    

### Expected Result:

I believe that after the customer choose some options in Interest Group this should be saved in Group Column as well can be saved in Magento Admin and Customer Panel 

### Additional information

I'm using an custom theme, and after the instalation I couldn't see the Interest Group Options on checkout, then I've realized that I needed change the LAYOUT.XML from my theme, so I've changed this file:

(I'm using a child theme)
app/design/frontend/[MY_THEME]/[MY_THEME]_child/Magento_Checkout/layout/checkout_onepage_success.xml

And inserted these lines:
`<referenceContainer name="order.success.additional.info">
            <block class="Ebizmarts\MailChimp\Block\Checkout\Success" ifconfig="mailchimp/general/interest_in_success" name="mailchimp.order.success" template="Magento_Checkout::checkout/order/success.phtml"/>
        </referenceContainer>`

And after that I've copied the file: [MAGENTO_DIR]/vendor/mailchimp/mc-magento2/view/frontend/templates/checkout/order/success.phtml

And pasted in: app/design/frontend/[MY_THEME]/[MY_THEME]_child/Magento_Checkout/templates/checkout/order/success.phtml

After this changes in my theme I could see the interest group in my success page on checkout process.
But the only issue here is about the Interest Group Options that are not been saved in Mailchimp Dashboard;

**Comment by gonzaloebiz** [comment]
Hi @FBXWEB 

i just re-tested and works like a charm
You need to have the magento cron configured and running because the groups are synced by the cron.

Best
