### ISSUE TITLE
Compatibility  mc-magento2 103.4.43 with Slider Revolution Responsive Magento Extension 6.2.15 

### ISSUE THREAD

**Issue by sorwarh** [mailchimp/mc-magento2#1209]
## Compatibility  mc-magento2 103.4.43 with Slider Revolution Responsive Magento Extension 6.2.15 
Hello

Slider Revolution Responsive Magento Extension is a magento 2 module that renders custom sliders.

Slider Revolution 6.2.15  works correctly  with mc-mailchimp 102.3.41

Updating the mc-mailchimp to 103.4.43 .
I get a JavaScript error that makes the Slider Revolution module not work correctly (Sliders are not displayed due to javascript error)

**I would like to know if the mc-magento2 103.4.43 is compatible with the module [Slider Revolution Responsive Magento Extension 6.2.15.5](https://nwdthemes.com/category/extensions/slider-revolution-2/) .** 
 

> Environment information
    1. Magento CE 2.4.2
    2. mc-magento2 103.4.43
    3. Slider Revolution Responsive Magento Extension 6.2.15.5
    
### Steps to reproduce

First  put a slider in cms page with the mc-magento2 103.4.43 module disabled. We can see in the cms page  it works correctly and the slider is shown

If we activate the mc-magento2  103.4.43 module ,we will see that the slide is no longer displayed. Javascript error in console

### Actual and Expected result

    Expected result:
    Keep showing the slides of the Slider Revolution  module
    Actual result:
    The slides of the Revslider module are not displayed .
    Javascript error caused by mc-magento2  103.4.43 module
     

### Additional information

![Screenshot](https://user-images.githubusercontent.com/62402381/121409584-f7b86680-c961-11eb-8f18-e09f4fe2ae7d.png)

<script type="text/javascript">
require(
[
'rs6',
'revolutionTools'

],
function(jQuery, punchgs) {
setREVStartSize({c: 'rev_slider_1_1',rl:[1240,1024,778,480],el:[709,709,709,400],gw:[1920,1024,778,480],gh:[709,709,709,400],type:'standard',justify:'',layout:'fullwidth',mh:"0"});
var revapi1,
tpj;
jQuery(function() {
tpj = jQuery;
revapi1 = tpj("#rev_slider_1_1")
if(revapi1==undefined || revapi1.revolution == undefined){
revslider_showDoubleJqueryError("rev_slider_1_1");
}else{
revapi1.revolution({
sliderLayout:"fullwidth",
visibilityLevels:"1240,1024,778,480",
gridwidth:"1920,1024,778,480",
gridheight:"709,709,709,400",
spinner:"spinner0",
perspective:600,
perspectiveType:"global",
editorheight:"709,709,709,400",
responsiveLevels:"1240,1024,778,480",
progressBar:{disableProgressBar:true},
navigation: {
onHoverStop:false
},
fallbacks: {
allowHTML5AutoPlayOnAndroid:true
},
});
}

});
});
</script>

**Comment by gonzaloebiz** [comment]
Hi @sorwarh 

thanks for choosing our extensions.
I don't see any error with our extension in your description, I see errors with setREVStartSize that I suppose is a variable from the other extension. I think you must contact the developers of the other extension.
Anyway, the extension is a paid one and I can't test it.
Really sorry. Let me know if you need some help at our end.

Best

**Comment by sorwarh** [comment]
Hi @gonzaloebiz  how are you. 

It could be an internal error of your plugin.

I have the Slider Revolution module in other Magento 2.4.2 with mc-mailchimp 102.3.41 and it works correctly but with mc-mailchimp 103.4.43 it doesn't work.

If I deactivate the mailchimp module, that JavaScript error no longer appears.

I can prepare an environment for you to review.
Waiting for your answer.

Kind regards

**Comment by gonzaloebiz** [comment]
Hi @sorwarh 

we have only 1 js in the frontend, this js is this https://github.com/mailchimp/mc-magento2/blob/develop-2.4/view/frontend/web/js/campaigncatcher.js, and as you can see the last modification is from the 27 Aug 2020 related to this issue https://github.com/mailchimp/mc-magento2/issues/1034, this issue as you can see is included in version 10x.x.41 (the same version that you have and works ok).
And as you can see in the console of the developers tool the error comes from a function that not exists, this function is not called from our extension, so why you think that the issue is related to us?

Best

**Comment by sorwarh** [comment]
Because before updating the module, that JavaScript error does not appear. 

I have checked the module, I have seen that you have changed **/view/frontend/templates/mailchimpjs.phtml** You instantiate the SecureHtmlRenderer in the Mailchimpjs block and make a call to a function that doesn't quite render correctly.

`echo $render->renderTag('script',['type'=>'text/javascript','src'=>$url],'',false);
`



This is why the javascript error is generated. There may be other errors that are not showing in the console.

Regards

**Comment by gonzaloebiz** [comment]
Hi @sorwarh 

can you send me an email to our support  mailchimp@ebizmarts-desk.zendesk.com mentioning the issue with your store URL to take a look?

Best
