### ISSUE TITLE
After install setup_version="103.4.43" show Impossible to process constructor argument Parameter #7 [ <required> Mailchimp $api ] of Ebizmarts\MailChimp\Helper\Data class

### ISSUE THREAD

**Issue by webkeonsanjeev** [mailchimp/mc-magento2#1215]
Hi Team,

I am using magento version 2.4.2 and installed all files in app/code/Ebizmarts/MailChimp/ location when when I run php bin/magento setup:upgrade command it show below error.
Impossible to process constructor argument Parameter #7 [ <required> Mailchimp $api ] of Ebizmarts\MailChimp\Helper\Data class
![image](https://user-images.githubusercontent.com/6489135/122169991-afd29b80-ce9b-11eb-9c5c-4bffe2812bfa.png)

Thanks

**Comment by gonzaloebiz** [comment]
Hi @webkeonsanjeev 

take a look at https://github.com/mailchimp/mc-magento2/blob/develop-2.4/composer.json#L28
You need to install the ebizmarts/mailchimp-lib

Best
