### ISSUE TITLE
Could not find package mailchimp/mc-magento2 in a version matching 102.3.43-p1

### ISSUE THREAD

**Issue by kerlama** [mailchimp/mc-magento2#1216]
I think the title is self explanatory.

**Comment by gonzaloebiz** [comment]
Sorry but i don't understand, magento doesn't have a version 102.3.43

**Comment by kerlama** [comment]
Not sure why you closed this ticket. I am talking about:
composer require mailchimp/mc-magento2:102.3.43-p1

when I do that, I am getting the message from the ticket title
http://prntscr.com/15oqd24

**Comment by gonzaloebiz** [comment]
can you try now?
