### ISSUE TITLE
ImportAfter observer is throwing exceptions if the _store column is not present in the import data

### ISSUE THREAD

**Issue by koenner01** [mailchimp/mc-magento2#1224]
## Issue Description

When running a product import the \Ebizmarts\MailChimp\Observer\Adminhtml\Product\ImportAfter observer is assuming the "_store" column is always present in the data. This results in crashing the import due to the exception being thrown. 

### Preconditions

1. CE 2.3.7
2. mc-magento2 102.3.43 (or up)

### Steps to reproduce

Run an import without the "_store" column in the product data (this is not required if you import the websites)

### Actual result

Exception is thrown and import is blocked.

### Expected result

Import should run and the ImportAfter observer should fallback to store id 0

**Comment by gonzaloebiz** [comment]
Hi @koenner01 

can you give us an example?

Best

**Comment by hostep** [comment]
@gonzaloebiz, some csv file like this probably:

```csv
sku,attribute_set_code,product_type,product_websites,status,name,price
some-sku,Default,simple,base,1,SomeName,100.00
```

**Comment by gonzaloebiz** [comment]
I'm just install a new magento 2.3.7 with sample data.
![image](https://user-images.githubusercontent.com/6222792/124001730-5003e680-d9ab-11eb-9367-25d69afd0493.png)

Install the version v102.3.43-p1 of the extension
![image](https://user-images.githubusercontent.com/6222792/124001890-7e81c180-d9ab-11eb-8d65-6993f9a42e1b.png)

The use this csv to import a product

sku,attribute_set_code,product_type,product_websites,name,price,status
example1,Bag,simple,base,Example 1,100,1

![image](https://user-images.githubusercontent.com/6222792/124002263-e801d000-d9ab-11eb-8574-3d3b22b22b9d.png)

When i click on ckeck data all is ok

![image](https://user-images.githubusercontent.com/6222792/124002494-3020f280-d9ac-11eb-8ceb-37b641523417.png)

Then when i click on the import button all is ok

![image](https://user-images.githubusercontent.com/6222792/124002599-547ccf00-d9ac-11eb-9815-2a4539875cf4.png)

As you can see, the product was imported without problems

![image](https://user-images.githubusercontent.com/6222792/124002731-7a09d880-d9ac-11eb-875c-ff84faf99bd8.png)

Perhaps some extra extension?

**Comment by hostep** [comment]
Strange, we saw your extension failing on [this line](https://github.com/mailchimp/mc-magento2/blob/102.3.43-p1/Observer/Adminhtml/Product/ImportAfter.php#L33). So in your case, the `_store` key exists in the array at the time you are trying to replicate the problem even if it doesn't exists in the csv file?

If you can't reproduce, I'll ask my colleague @koenner01 to double check again when he finds some time

**Comment by gonzaloebiz** [comment]
Hi @hostep 

i see the issue that you say, but the issue doesn't stop the import, the product is imported OK.
We will upload a fix soon
Thanks for pointing that

Best

**Comment by hostep** [comment]
Excellent, thanks @gonzaloebiz!
