### ISSUE TITLE
Self closing script tag breaks all pages rendering

### ISSUE THREAD

**Issue by fabianaromagnoli** [mailchimp/mc-magento2#1225]
### Preconditions
1. Magento EE 2.4.2
2. mailchimp/mc-magento2 103.4.43
2. PHP 7.4
3. Chrome Version 91.0.4472.114

### Description
In `view/frontend/templates/mailchimpjs.phtml` you use the core method`\Magento\Framework\View\Helper\SecureHtmlRender\HtmlRenderer::renderTag`, but this method seems to always use self-closing if tag if there's no content, so that the script tag is rendered like this:

`<script type="text&#x2F;javascript" src="https&#x3A;&#x2F;&#x2F;chimpstatic.com&#x2F;mcjs-connected&[...].js"/>`

According to [html specifications](https://html.spec.whatwg.org/multipage/syntax.html#syntax-tags) not all tags can be self-closing, and script tag is one of them. Self-closing the script tag is not supported by most browsers and it causes a broken rendering of the whole html page.

**Comment by minimit** [comment]
There's a PR in magento https://github.com/magento/magento2/pull/33199

**Comment by gonzaloebiz** [comment]
Hi @fabianaromagnoli 

take a look at this PR https://github.com/mailchimp/mc-magento2/commit/a80240f9a6abdf6a4c9979070a2965c27eeba774

Best
