### ISSUE TITLE
<script> tag in Block/Mailchimpjs rendered incorrectly since version 103.4 because of Magento bug

### ISSUE THREAD

**Issue by leeroybrun** [mailchimp/mc-magento2#1226]
## Issue description

Since installing the latest version of mc-magento2 for Magento 2.4 our website broke.

I've tracked the bug, and it seems to be linked to this Magento issue : https://github.com/magento/magento2/issues/32822

The change in mc-magento2 was introduced in this commit :

https://github.com/mailchimp/mc-magento2/commit/e19fa3f17dd9d14e1cc41f1b7afd8d4d10495fbc#diff-4e3812f9c7c55a0bd4952b3458ee6ac496e1a3519febdb0506a0012097368a6b

Here is the code generated by Magento for the `<script>` tag.

![Capture d’écran 2021-06-24 à 13 02 55](https://user-images.githubusercontent.com/1729528/123252547-b0e37880-d4ec-11eb-933d-644691513163.png)

The browser is not handling it well because it should be closed by `</script>` instead of a self-closing tag.

The result is that every tag on our website between the start of the mailchimpjs `<script` tag and the next `</script>` tag on the page is ignored by the browser.

**Comment by gonzaloebiz** [comment]
Hi @leeroybrun 

take a look at https://github.com/mailchimp/mc-magento2/commit/a80240f9a6abdf6a4c9979070a2965c27eeba774

Best

**Comment by leeroybrun** [comment]
Hi @gonzaloebiz,

Great thank you !

In which composer version is it included?
I cannot seem to get this fix from composer.

**Comment by gonzaloebiz** [comment]
This fix will be available in the next version of the extension, we don't have an ETA for this but you always can install the develop version with compomer, run this command

composer require mailchimp/mc-magento2:dev-develop-2.4

Best

**Comment by barryvdh** [comment]
You can install the patch with the composer-patches module; https://github.com/mailchimp/mc-magento2/commit/a80240f9a6abdf6a4c9979070a2965c27eeba774.diff
But a new release would be helpful. In this case it broke our autocomplete, but could be any script that comes after this.

**Comment by barryvdh** [comment]
Can you please release a new version. This issue is breaking websites in a weird way, which makes it hard to track down.

**Comment by leeroybrun** [comment]
I also think that this is quite important to publish a new version with the fix soon... there are probably a lot of developers scratching their heads right now trying to figure out why their website is completely broken. In our case all of our Javascript was broken because of this and as @barryvdh said, it is quite hard to track down.
