### ISSUE TITLE
mc-magento2-1.0.25 composer installation

### ISSUE THREAD

**Issue by Sharlyll** [mailchimp/mc-magento2#123]
Hi,

can someone please tell how  mc-magento2-1.0.25 is installed on a shared server? 

I am currently on magento 2.2.1
thanks!

**Comment by gonzaloebiz** [comment]
use composer

**Comment by Sharlyll** [comment]
Hi @gonzaloebiz, When I use composer, it install Ebizmart 1.0.24 which throws errors. 
Can you provide the exact composer command for 1.0.25?

Thanks

**Comment by Sharlyll** [comment]
@gonzaloebiz  when I run composer require mailchimp/mc-magento2, it gives memory limit errors:

Using version ^1.0 for mailchimp/mc-magento2
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory

Fatal error: Out of memory (allocated 847257600) (tried to allocate 20480 bytes) in phar:///usr/local/bin/composer.phar/src/Composer/DependencyResolver/RuleSetGenerator.php on line 126


so I run this instead:   composer require mailchimp/mc-magento2-1.0.25
and it gives this error:

[InvalidArgumentException]                                                                     
  Could not find package mailchimp/mc-magento2-1.0.25 at any version for your minimum-stability  
   (stable). Check the package spelling or your minimum-stability

**Comment by gonzaloebiz** [comment]
Is not an issue from our extension.
you can try [this](https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors)
