### ISSUE TITLE
*Feature* - Avoid loading JS on frontend - Send order data by API for processing status

### ISSUE THREAD

**Issue by onlyapproved** [mailchimp/mc-magento2#1234]
This is a feature request. 

for avoiding an overload of JS loaded on websites, it would be great to support a lighter implementation in M2. 

even though the external JS is not large, it still causes external requests. my suggestion is to add functionality to e-commerce data is not tracked in real-time on the frontend, but instead sent by Cron post-order authoriize.

**Comment by gonzaloebiz** [comment]
What do you mean with "to add functionality to e-commerce data is not tracked in real-time on the frontend"?
The js p.e. display the popup that you define for your audience, so, we can't remove the js
