### ISSUE TITLE
token parameter is incorrect in abandoned cart email in the cart url

### ISSUE THREAD

**Issue by akosglue** [mailchimp/mc-magento2#1241]
### Preconditions

You have received an abanoed cart emial from mailchimp.
In the email you can find a link to the magento shop, that is something like:
www. .../mailchimp/cart/loadquote/id/.../token/...

### Actual and Expected result

The token parameter is in some cases incorrect. The id parameter is correct. Some users receive the url with the correct token, some user get a url with non-existing/incorrect token. This results in that the cart can't be re-loaded.

magento 2.2.9
mailchimp 101.2.37

**Comment by gonzaloebiz** [comment]
Hi @akosglue 

i'm trying to replicate your issue with mailchimp 101.2.43 but works ok, can you please try with mailchimp 101.2.43 or be more specific on how to replicate it.

Best
