### ISSUE TITLE
Javascript escaping too aggressive; prevents body attributes

### ISSUE THREAD

**Issue by JesseMaxwell** [mailchimp/mc-magento2#1255]
The recent security update in version 103.4.43 escapes the script tag too much in: `view/frontend/templates/mailchimpjs.phtml`. It causes a somewhat subtle problem where `<body/>` attributes are not correctly rendered in the DOM.

This is what the script looks like (ID's replaced with `1111111111`):
```
<script type="text&#x2F;javascript" src="https&#x3A;&#x2F;&#x2F;chimpstatic.com&#x2F;mcjs-connected&#x2F;js&#x2F;users&#x2F;11111111111&#x2F;1111111111.js"/> 
```

### Context:

* Magento 2.4.2-p1
* Module version: 103.4.43
* Problem introduced in commit: https://github.com/mailchimp/mc-magento2/commit/e19fa3f17dd9d14e1cc41f1b7afd8d4d10495fbc
* Relates to: https://github.com/mailchimp/mc-magento2/issues/1097
* It seems this would be a fix: https://github.com/mailchimp/mc-magento2/pull/439/files#diff-4e3812f9c7c55a0bd4952b3458ee6ac496e1a3519febdb0506a0012097368a6b
* Correct Magento 2.4.x fix seems to be:

```
<?php
/** @var $block \Ebizmarts\Mailchimp\Block\Mailchimpjs */
$url = $block->getJsUrl();
?>
<script type="text/javascript" src="<?php echo $escaper->escapeUrl($url);?>" defer></script>
```

------------------------------

### Steps to Reproduce

1. Enable and setup Mailchimp on a store.
2. Make sure `mailchimp/general/mailchimpjsurl` has a valid value in the config table.
3. Visit frontend of site.

**Expected:** valid script tag like: 
```
<script type="text/javascript" src="[URL_FROM_MAILCHIMP_ADMIN_SECTION_HERE]"/> 
```

**Actual:** invalid script tag that breaks the `<body/>` `class` attribute: 
```
<script type=""text&#x2F;javascript" src="[OVERLY_ESCAPED_URL]"/> 
```

**Comment by JesseMaxwell** [comment]
Patch in case it's helpful to someone (can be installed with `cweagans/composer-patches`):

```
From 9832e8be55005ef214992f4bd1e93d1471713f04 Mon Sep 17 00:00:00 2001
From: ---
Date: Mon, 19 Jul 2021 15:07:21 -0500
Subject: [PATCH] Update the way the script tag is rendered

---
 view/frontend/templates/mailchimpjs.phtml | 3 +--
 1 file changed, 1 insertion(+), 2 deletions(-)

diff --git a/view/frontend/templates/mailchimpjs.phtml b/view/frontend/templates/mailchimpjs.phtml
index 5c5bf48..f02921e 100644
--- a/view/frontend/templates/mailchimpjs.phtml
+++ b/view/frontend/templates/mailchimpjs.phtml
@@ -3,6 +3,5 @@
  * @var $block \Ebizmarts\Mailchimp\Block\Mailchimpjs
  */
 $url = $block->getJsUrl();
-$render = $block->getRender();
-echo $render->renderTag('script',['type'=>'text/javascript','src'=>$url],'',false);
 ?>
+<script type="text/javascript" src="<?php echo $escaper->escapeUrl($url);?>" defer></script>
-- 
2.29.2

```

**Comment by matthewbrown62** [comment]
I am having this issue as well. Applied the patch and it solved the issue.

**Comment by gonzaloebiz** [comment]
Hi @JesseMaxwell 

please take a look at https://github.com/mailchimp/mc-magento2/issues/1209
This fix will be available in the next release.

Best

**Comment by andreasemer** [comment]
@gonzaloebiz Why are you not creating a release with this major and critical bug fix?
