### ISSUE TITLE
v103.4.43 Update Changes Photo Gallery and Category Page

### ISSUE THREAD

**Issue by pioneerathletics** [mailchimp/mc-magento2#1261]
# Issue reporting guidelines

### Preconditions

    1. Magento CE 2.4.2-p1
    2. PHP 7.4
    3. MySQL 5.7
    2. Updated to v103.4.43 from v102.3.42
    

### Steps to reproduce

    1. Updated to v103.4.43 from v102.3.42 

### Actual and Expected result

    Expected result:
  Product photo gallery and category page would remain the same.

    Actual result:
   Product photo gallery has inexplicably been decreased in size, plus appears to be floating left ![screenshot-1](https://user-images.githubusercontent.com/19981272/126535598-9d6fd6d2-f86b-474c-90b1-5f0c901eef96.png). Product Category has also changed with the "products per page" widget appearing at the top of the page, along with "add to cart" buttons reappearing ![screenshot-2](https://user-images.githubusercontent.com/19981272/126535600-a4bb54ec-6853-444d-be26-590d46f35c15.png). I disabled the Mailchimp extension and the pages went back to normal. 

### Additional information

Attached are screenshot 1 showing the product photo gallery. Screenshot 2 shows the category page. I disabled the Mailchimp extension and the pages went back to normal. I tested on both Chrome and Firefox.
![screenshot-1](https://user-images.githubusercontent.com/19981272/126535598-9d6fd6d2-f86b-474c-90b1-5f0c901eef96.png)
![screenshot-2](https://user-images.githubusercontent.com/19981272/126535600-a4bb54ec-6853-444d-be26-590d46f35c15.png)

**Comment by gonzaloebiz** [comment]
Hi @pioneerathletics 

please take a look at https://github.com/mailchimp/mc-magento2/issues/1209

Best

**Comment by riccardofinkers** [comment]
I can confirm the same issue. 

The issue is that after the update de body HTML tag doesn't have the right attributes and body classes anymore so therefor CSS elements break that where made on those body classes.

**Comment by riccardofinkers** [comment]
@pioneerathletics the awnser is in ticket #1255 I have resolved this issue by editing the mailchimpjs.phtml :)

**Comment by gonzaloebiz** [comment]
Apply this fix https://github.com/mailchimp/mc-magento2/commit/a80240f9a6abdf6a4c9979070a2965c27eeba774
The fix will be available un the next release

Best
