### ISSUE TITLE
Body classes not set when URL is provided in mailchimpjs.phtml

### ISSUE THREAD

**Issue by marceldekoning** [mailchimp/mc-magento2#1262]
**Preconditions:**
Magento 2.4.2

**Steps to reproduce**
1. Make sure you have your Mailchimp backend credentials filled in.
2. Make sure your mailchimp/general/mailchimpjsurl configuration is filled with an URL like: https://chimpstatic.com/mcjs-connected/js/users/...
3. Go to the frontend (for example category page). In my case all the body classes are gone and the head has an extra tag

`<script type="text/javascript" src="https://chimpstatic.com/mcjs-connected/js/...a6e.js">    </head><body data-container="body" data-mage-init='{"loaderAjax": {}, "loader": { "icon": "https://.../static/version1627285867/frontend/.../.../nl_NL/images/loader-2.gif"}}' id="html-body" class="search-open page-with-filter page-products categorypath-sierbestrating category-sierbestrating catalog-category-view page-layout-2columns-left">         <div id="cookie-status">The store will not work correctly in the case when cookies are disabled.</div> <script type="text&#x2F;javascript">document.querySelector("#cookie-status").style.display = "none";</script>`

**Expected Result**
Body has all its core classes like catalog-category-view and so on.

**Actual Result**
All the body classes are gone.

**Comment by gonzaloebiz** [comment]
Hi @marceldekoning 

please take a look at https://github.com/mailchimp/mc-magento2/issues/1209

Best
