### ISSUE TITLE
compile error 2.3.7:  "Class Magento\Framework\View\Helper\SecureHtmlRenderer does not exist"

### ISSUE THREAD

**Issue by AndyJAllen** [mailchimp/mc-magento2#1265]
![image](https://user-images.githubusercontent.com/19735797/127210665-b4e2c54e-fee2-40f5-9952-0677d7d6bdeb.png)

It spawns from file:
`/vendor/mailchimp/mc-magento2/Block/Mailchimpjs.php`

Installed with lines:
`"ebizmarts/mailchimp-lib": "*",
"mailchimp/mc-magento2": "*"`

Removing mailchimp lets Magento 2.3.7 compile.

**Comment by gonzaloebiz** [comment]
Please follow the issue guidelines

**Comment by AndyJAllen** [comment]
The issue being conveyed seems pertinent to me? The file, which is pointed out, is generating an error, which is pointed out, on the Magento version during compile, which is pointed out, using latest version of the mailchimp code, indicated by version *.

The file pointed out is using a class in the constructor that doesn't exist in 2.3.7.

I guess consider this ticket an FYI...do as you will.

**Comment by gonzaloebiz** [comment]
If you don't fill the issue guidelines we can't reproduce your issue and can't help you.
What is your magento version? What version of mc-magento2 are you trying? What version of php are you using? What're steps you follow to install the extension?

Best

**Comment by gonzaloebiz** [comment]
The documentation for each version is pretty clear

![image](https://user-images.githubusercontent.com/6222792/127217254-a6f5e0a9-79b9-4a93-af65-82ab2d83dc63.png)

**Comment by AndyJAllen** [comment]
Thank you. I was expecting composer to satisfy the requirements.

**Comment by gonzaloebiz** [comment]
You are welcome, the next time be less pushy, and keep in mind the rules are there to help you

**Comment by AndyJAllen** [comment]
I can confirm that version works from your screenshot.
