### ISSUE TITLE
Create New MailChimp Store - Warning: Invalid Argument supplied for foreach()

### ISSUE THREAD

**Issue by BaberAhmed** [mailchimp/mc-magento2#127]
Good Afternoon, I am an issue with adding new MailChimp Store, please see below steps to recreate issue:

1) Install Module
2) configure with valid account and API key
3) Go to MailChimp > MailChimp Stores (grid + filters will load normally) click Create new MailChimp Store
4) Fill in details and click Save
5) Will attempt/Save the store and reload the grid, will fail and display the following error from then on it will always do this: You can attempt to add more stores but grid + filters will fail to load.

Warning: Invalid argument supplied for foreach() in /var/www/magento/staging/vendor/magento/framework/View/Element/UiComponent/DataProvider/DataProvider.php on line 252

Module version 1.0.24
Magento version 2.1.4

Kind Regards
Baber

**Comment by gonzaloebiz** [comment]
Hi @BaberAhmed 

thanks for your feedback.
How you proceed to install the extension? If you don't use composer, please double check that the extension was installed correctly.
By the way, the current version is 1.0.25, so i recommend try with this version.

Best

**Comment by BaberAhmed** [comment]
Hi,

Thanks for the quick feedback, yes we used composer for install, I will take a look at upgrading the module and trying again.

I will update if it works or if the persists.

Kind Regards
Baber

**Comment by BaberAhmed** [comment]
HI,

I have updated to latest version of 1.0.25 and the error is still showing, please can you advise?

Kind Regards
Baber
