### ISSUE TITLE
Weltpixel font loader gets inserted into mailchimp javascript tag

### ISSUE THREAD

**Issue by jdereus87** [mailchimp/mc-magento2#1278]
**Conditions**
Magento 2.4.2-p1
Mailchimp: 103.4.43
Weltpixel/FrontendOptions: 1.10.11 (part of Weltpixel_Pearl theme).

**Visual**
![Selection_999(137)](https://user-images.githubusercontent.com/48788831/129045531-b92a4041-f82f-4836-9eb0-8cf12e006219.png)

**Problem**
The script that loads google fonts for the pearl theme gets inserted into the mailchimp js tag, causing it to not load the theme fonts properly. Disabling the mailchimp module makes the fonts load again. Not sure if this is an error due to weltpixel or due to the mailchimp module (or just an unlucky combination). 

**Code**
![Selection_999(138)](https://user-images.githubusercontent.com/48788831/129046624-93ecd588-8b05-47ad-9b7a-041e884cffe1.png)

**Comment by gonzaloebiz** [comment]
Hi @jdereus87 

try applying this pr https://github.com/mailchimp/mc-magento2/commit/9e89f0c6b5f42845941ac28984de22c2a601cff4

Best

**Comment by jdereus87** [comment]
@gonzaloebiz ill give it a try and will let you know the result. thanks for the quick response

**Comment by jdereus87** [comment]
@gonzaloebiz your fix worked. Fonts are loaded again. Thank you.
