### ISSUE TITLE
Magento 2.1.9 Mailchimp Abandoned cart not working

### ISSUE THREAD

**Issue by aasim110** [mailchimp/mc-magento2#128]
I have tried following steps to setup Abandoned cart using Mailchimp module.

Setup

        Magento 2.1.9
            Default abandoned cart automation (series of 3 emails) in MailChimp
            Sync with MailChimp listed as complete - I can see recent customers listed on MailChimp and ecommerce data for recent orders, Total Products, Total Carts.
            Checked the table cron_schedule for the job_code ebizmarts_ecommerce and not found any error message
            Checked the table quote and confirmed that the quote was not converted.
            Checked the tablemailchimp_sync_ecommerce with type = QUO and related_id, and not found anything on mailchimp_sync_error table for this quote

Steps

        As a logged in user or guest, add items to cart and get to payment step of checkout so that email address is captured in quote.
        Ensure that eCommerce CRON job is running
        Wait for whole day and maybe longer

Expected Result

        An abandoned cart email and listing at least 1 email sent in MailChimp

Actual Result

        No email sent MailChimp lists
        0 emails sent out

**Comment by gonzaloebiz** [comment]
Hi @aasim110 

what version of mailchimp4magento you have?
Can you confirm via api that the cart is in the mailchimp store?

By the way, you don't need to double post your issue.

Best

**Comment by aasim110** [comment]
Hi @gonzaloebiz  I'm using mc-magento2-1.0.25 version. 
How can I check cart is in the mailchimp store via API ?
I can see following in my Magento2 admin mailchimp setting.

Total Subscribers: 146492
Ecommerce Data uploaded to MailChimp
Total Customers: 2695
Total Products: 33637
Total Orders: 58
Total Carts: 50
This account is currently syncing

Best Regards,
Aasim Goriya

**Comment by gonzaloebiz** [comment]
Hi @aasim110 

the abandoned cart automation is not fired until the store is not completely synced.

Best

**Comment by aasim110** [comment]
Hi @gonzaloebiz  So How much time it will take to synchronize ? I have started this before 2 days and its still synchronizing.

Best Regards,
Aasim Goriya

**Comment by gonzaloebiz** [comment]
I don't know, this depends on the size of your magento store, quantity of products, orders etc.
