### ISSUE TITLE
Tag 102.3.43 is incorrect

### ISSUE THREAD

**Issue by PascalBrouwers** [mailchimp/mc-magento2#1285]
Looking at https://github.com/mailchimp/mc-magento2/blob/c123b4da339ae858c72985ef6c17f8fc80209716/Cron/BatchesClean.php

This is still containing the old code which should have been fixed in 102.3.43 (https://github.com/mailchimp/mc-magento2/issues/1107)

Can you create a 102.3.44 release which does include all code?

**Comment by allrude** [comment]
Same for the fix https://github.com/mailchimp/mc-magento2/pull/1214 from @gonzaloebiz

**Comment by PascalBrouwers** [comment]
Also missing: https://github.com/mailchimp/mc-magento2/issues/1224 
Is there anything correct with this tag?

**Comment by PascalBrouwers** [comment]
@gonzaloebiz please take a look and get a correct tag out.

**Comment by andreasemer** [comment]
Is this project still active?
