### ISSUE TITLE
Version 103.4.43 mailchimpjs.phtml JS script incomplete/invalid

### ISSUE THREAD

**Issue by stephan-cream** [mailchimp/mc-magento2#1286]
Dear Mailchimp,

The JS that is loaded from the mailchimpjs seems to be incomplete or invalid.
We are using the version 103.4.43 of you module on Magento 2.4.3.
The seeming lack of an end `</script>` tag causes several elements like `<link>`, `</head>` and `<body>` to be part of your chimpstatic JS script.

## Issue Description
The following occurs:
`<script type="text/javascript" src="https://chimpstatic.com/mcjs-connected/js/users/{omitted}"><link rel="prefetch" as="script" href="{omitted}"/><link rel="prefetch" as="script" {omitted}"/></head><body data-container="body" data-mage-init='' id="html-body" class="cms-home cms-index-index page-layout-homepage">`
This causes page elements to be loaded incorrectly and break the functionality of the shop.

### Preconditions
- Magento 2.4.3
- Mailchimp 103.4.43
- PHP 7.3

### Steps to reproduce
- Have the Mailchimp module enabled with above preconditions.

### Actual and Expected result
**Expected result:**
- Correct working script, properly loaded elements.

**Actual result:**
- Messed up page, elements not properly loaded.

### Additional information
Seems similar in nature to https://github.com/mailchimp/mc-magento2/issues/1209
However we do not have the Slider Revolution module on our store.

**Comment by gonzaloebiz** [comment]
Hi @stephan-cream 

you are right, apply this fix https://github.com/mailchimp/mc-magento2/issues/1266
I know that the description is not the same, but the origin of the issue is the same.

Best
