### ISSUE TITLE
Self closing script tag in 103.4.43 causes styling issue 

### ISSUE THREAD

**Issue by nataliefox-288** [mailchimp/mc-magento2#1287]
mc-magento2 103.4.43 
Code used in file /vendor/mailchimp/mc-magento2/view/frontend/templates/mailchimpjs.phtml utilises renderTag which means the tag calling chimpmatic.com js is rendered as follows:

<script type="text&#x2F;javascript" src="https&#x3A;&#x2F;&#x2F;chimpstatic.com&#x2F;mcjs-connected&#x2F;js&#x2F;users&#x2F;f2cbd97bb63e44179317e60b1&#x2F;481df3050bde990d2b57cbaf5.js"/>

which causes a styling issue because the script tag is self closing.

Dropping back to mc-magento2 v102.3.43 stops this issue because it includes a properly formed script tag, but this version is listed as being for Magento 2.3 only.

**Comment by gonzaloebiz** [comment]
Hi @nataliefox-288 

please apply this PR https://github.com/mailchimp/mc-magento2/commit/9e89f0c6b5f42845941ac28984de22c2a601cff4
