### ISSUE TITLE
Option for not loading external js script, when only two-way subscriber sync is needed *Feature*

### ISSUE THREAD

**Issue by onlyapproved** [mailchimp/mc-magento2#1298]
**Issue Description**

Magento 2 is in general a script nightmare, and some e-commerce businesses is trying to make the pageload much lighter and trying to obtain better ranking in Page-Speed parameters. 

As Mailchimp is not always used for handling abandoned cart and other automations, it would make sense to have the ability to disable all real-time observing, tracking etc. So that one can chose just to use the module for two-way subscriber sync by cron or Webhook. Monitoring of campaign efficiency could be obtained in other ways such as: 

Adding url parameters to the campaign's link and monitor it through GA
Adding feature for using google tag manager and parse the data back to Mailchimp
Using the order-sync feature, to push order information by CRON and thereby match the sale

There are currently no other options than the mc-magento2 module, and automations such as Zapier does not seem to have the feature to handle two-way subscriber sync properly.

**Comment by gonzaloebiz** [comment]
Hi @onlyapproved 

you can comment this lines https://github.com/mailchimp/mc-magento2/blob/develop-2.3/view/frontend/layout/default.xml#L15-L22 and no js will be loaded (or you can rename this file)

Best
