### ISSUE TITLE
Request: Multiple Magento Stores -> 1 MC Store

### ISSUE THREAD

**Issue by ghost** [mailchimp/mc-magento2#130]
Hi,
we are running multiple Magento Stores but they basically have all the same Products and everything is the same except the Currency and the URL's.. We use .com/ca/ for canada /au/ for australia etc. That's the only difference.
Is it possible to link all stores to one Mailchimp store and then set the URLS in the settings for each store?
This way automations and everything else would be much more easy to handle as only 1 instead of 9 campaigns would be required.
Not sure if it's currently possible

**Comment by gonzaloebiz** [comment]
If you have questions, please send an email to our support at mailchimp@ebizmarts-desk.zendesk.com

Best
