### ISSUE TITLE
Chimpstatic URLs throwing 403

### ISSUE THREAD

**Issue by pmonosolo** [mailchimp/mc-magento2#1308]
We have a website where we're loading 2 chimpstatic scripts. We have no idea where both of the scripts are being loaded (we checked our head and google tag manager) 

But, both of the scripts are throwing 403 response. Is this normal? 

![2021-10-05 15_06_59-Photopea _ Online Photo Editor](https://user-images.githubusercontent.com/66754347/136111492-b1ac0ecc-293d-48b2-b1a5-cda983bc0f80.jpg)

The delay on the page because of these 403 responses is about 400ms.

We are not actively using the Mailchimp plugin.

Mailchimp Plugin Version:
102.3.41

**Comment by gonzaloebiz** [comment]
Hi @pmonosolo 

remove the entry in the table core_config_data for path = 'mailchimp/general/mailchimpjsurl'

Best

**Comment by supersuryaansh** [comment]
I am facing the same issue but I am not using the plugin but a <script> tag
