### ISSUE TITLE
Performance Issue During Product Import

### ISSUE THREAD

**Issue by sprankhub** [mailchimp/mc-magento2#1309]
### Preconditions

1. Magento Open Source 2.4.3
2. mc-magento2 103.4.44

### Steps to reproduce

1. Import "many" products.

### Actual and Expected result

Expected result: Import with Mailchimp module enabled is as fast as import without Mailchimp module.
Actual result: Mailchimp module slows down the import as for each imported product, multiple database queries are executed, see `\Ebizmarts\MailChimp\Observer\Adminhtml\Product\ImportAfter`.

Such changes need to be executed asynchronously to not slow down the actual import.

**Comment by gonzaloebiz** [comment]
Hi @sprankhub 

we can't do this asynch, we need to mark the product as modified in the e-commerce table to re-sync the product to mailchimp.

Best

**Comment by sprankhub** [comment]
Then at least implement this in a performant way! Currently, for each imported product, you first load the FULL product just to get the ID from it. Then, you update your Mailchimp-specific table for this product. A performant way would be to load a product collection by all SKUs at once, then retrieve all IDs and update the Mailchimp-specific table with ONE database call.

**Comment by sprankhub** [comment]
Much better, thanks! Although I do not quite get why you do this in batches of 100? Why not all at once?

https://github.com/mailchimp/mc-magento2/blob/334cafc42ced4e6de7422e1d6221b21f93e5658a/Observer/Adminhtml/Product/ImportAfter.php#L38-L41

When you are at it, could you change the default branch to 2.4?

**Comment by gonzaloebiz** [comment]
because in some servers, depending on your server configuration and on the number of products to import, can fail, so i prefer to make it in batches of 100. If you consider that your server support more, you are free to increment this number

**Comment by sprankhub** [comment]
What would fail? The whole import or your updates? Because what you do now should be done in a matter of seconds (maximum) even with a huge amount of products. So I really do not understand the reasoning for the 100 batch.
