### ISSUE TITLE
Undefined Promocode on cron

### ISSUE THREAD

**Issue by ghost** [mailchimp/mc-magento2#131]
Magento CE 2.16
Mailchimp 1.0.25
Stores including Customers, Orders, Carts and Products are completely synced.

Hi in our cron schedule we get:
Notice: Undefined property: Mailchimp_Ecommerce::$promoCodes in /home/cloudpanel/htdocs/www.sterntaufe-deutschland.de/app/code/Ebizmarts/MailChimp/Model/Api/PromoRules.php on line 143

I fixed it by commenting out line 141 to 153. Not sure what it does but as we are not working with promo codes it did the job for us..

**Comment by gonzaloebiz** [comment]
You don't update the ebizmarts/mailchimp-lib run
composer require ebizmarts/mailchimp-lib

Best
