### ISSUE TITLE
Something's very wrong with Release 103.4.43!!

### ISSUE THREAD

**Issue by perfpcs** [mailchimp/mc-magento2#1310]
Major CSS and JS Errors/Conflicts basically kill our M2.4.3-p1site. 

Every page is broken when this release is enabled. Will go back to the previous version.

Anyone else having these issues and if so know why or solutions?
thanks
Hank

**Comment by perfpcs** [comment]
We reverted back to 102.3.42 and all is back to normal. What was added or changed in this last revision that could break all the CSS and JS on a site so badly??? Was it rested with the latest M 2.4.3-p1? 
There is some very major bug(s) with the latest release.

**Comment by gonzaloebiz** [comment]
This issue was fixed in https://github.com/mailchimp/mc-magento2/issues/1266 that is included in https://github.com/mailchimp/mc-magento2/releases/tag/103.4.44

**Comment by perfpcs** [comment]
Yeah I couldn't download that version because it was not in the Magento repo but only in the packagelist. When will you push this to Magento repo?

thanks
Hank

**Comment by gonzaloebiz** [comment]
If you mean magento marketplace, the version is already in the marketplace https://marketplace.magento.com/mailchimp-mc-magento2.html

**Comment by perfpcs** [comment]
No I mean the Magento Repo
            "type": "composer",
            "url": "https://repo.magento.com/"
I tried to update from there but it was not available there composer said.

**Comment by gonzaloebiz** [comment]
we can't upload to this repo, this repo only contains the core extensions.
For installing our extension you can do it via composer as the instructions

![image](https://user-images.githubusercontent.com/6222792/137763757-d94652d0-c6e1-4fca-aff5-ec463e2d3fd4.png)

**Comment by perfpcs** [comment]
![image](https://user-images.githubusercontent.com/22109696/137772110-c250ace6-4887-4c76-9903-e52450975477.png)

**Comment by gonzaloebiz** [comment]
![image](https://user-images.githubusercontent.com/6222792/137777495-4c031d1d-f621-45ee-a1d1-fed320bf9227.png)

**Comment by perfpcs** [comment]
You must be using packagelist.org. as your repository

I have to use this:

    "repositories": {
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },

and that repo does not have latest Mailchimp version. needs to be pushed there.

**Comment by gonzaloebiz** [comment]
of course, i use pakagist.org as any other free extension. As i already say, the magento repo is only for those core extensions.
my  composer.json looks like this:

   "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],

(the standard way) and works like a charm, this is the default magento installation

**Comment by perfpcs** [comment]
Mine is the same and I showed you above my screenshot of what happens when I try to update to that version.

**Comment by gonzaloebiz** [comment]
as i can see, you run this cmd
`composer require  mailchimp/mc-magento2: 103.4.44`
not this
`composer require  mailchimp/mc-magento2:103.4.44`

try with the right command

**Comment by perfpcs** [comment]
OK so that extra space was issue. Its working now. Thank you.

**Comment by gonzaloebiz** [comment]
copy/paste is always the best way
