### ISSUE TITLE
ChimpStatic.com JS missing closing </script> tag

### ISSUE THREAD

**Issue by itmsenior** [mailchimp/mc-magento2#1312]
Hello,

As per title really. We needed to override the mailchimpjs.phtml template and add a closing </script> tag to avoid issues with other JS on the page.

### Preconditions

    1. Magento 2.4.3-p1
    2. Mailchimp 103.4.43

### Steps to reproduce

1. Install and enable module
2. View page source of any Magento page
    ...

### Expected result
1. ChimpStatic JS includes opening and closing `<script></script>` tags.

### Actual result
1. ChimpStatic JS missing closing `</script>` tag.

We temporarily fixed it with the following but this is a very hacky method:
```
$url = $block->getJsUrl();
$render = $block->getRender();

$script = str_replace(">", "></script>", $render->renderTag('script',['type'=>'text/javascript','src'=>$url],'',false));
echo $script;

```

**Comment by gonzaloebiz** [comment]
Take a look at this https://github.com/mailchimp/mc-magento2/issues/1266
