### ISSUE TITLE
Do not sync disabled products or products that are of of stock

### ISSUE THREAD

**Issue by stephansteiner** [mailchimp/mc-magento2#1313]
Our shop unfortunately has many products that are still active, but out of stock (37000 products not in stock, 2000 products in stock). Out of stock products are not visible in the shop (cannot be seen using product url).
Unfortunately those products are still being synced to mailchimp.
Is there a way to exclude those products from being synced?

**Comment by gonzaloebiz** [comment]
Please follow the [issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)
