### ISSUE TITLE
How to change the audience after having set up a store?

### ISSUE THREAD

**Issue by mpchadwick** [mailchimp/mc-magento2#1328]
This is more of a documentation issue, but potentially also a functional issue. We set up a Mailchimp store but it's pointing to the wrong Mailchimp audience. I can't find any way in the admin panel to point to store to a different audience. Is it possible? If so can you provide documentation. If not it feels like a gap in functionality.

**Comment by gonzaloebiz** [comment]
Hi @mpchadwick 

no, you can't change the audience once the mailchimp store is created.

Best
