### ISSUE TITLE
Problem syncing country with customer address

### ISSUE THREAD

**Issue by ClickCons** [mailchimp/mc-magento2#1329]
Good afternoon,
I am writing to inform you of a problem with syncing customer addresses to Mailchimp.
The ecommerce360 transfers customer data great, but it has a problem in the synchronization of the address, exactly with the customer country, because mailchimp has the Country field preset and it only accepts the country values ​​in English.
Your plugin sends the name of the country in the language of that country (for example "España"), and for that reason it doesn't fit Mailchimp well (Mailchimp wants "Spain").
To solve it it is necessary to look for this function inside your plugin: $country->getName();
And replace it with the following: $country->getName('en_US');

I don't know if there is another better solution, but this way it works.
I would need to know if this patch can be included in its next release. This is important.

I await your comments.
Kind regards.

**Comment by gonzaloebiz** [comment]
Hi @ClickCons 

i will take a look on this and back to you

Best
