### ISSUE TITLE
Fatal error:  Uncaught Error: Class 'Ebizmarts\MailChimp\Controller\Adminhtml\Stores' not found

### ISSUE THREAD

**Issue by nickalmeida** [mailchimp/mc-magento2#1354]
Hello guys, I am getting the following error when running the compilation

Fatal error:  Uncaught Error: Class 'Ebizmarts\MailChimp\Controller\Adminhtml\Stores' not found in /home/xxxxx/xxxxx/public_html/app/code/Ebizmarts/Mailchimp/Controller/Adminhtml/Stores/Index.php:17
Stack trace:
#0 /home/xxxxx/xxxxx/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(136): require_once()
#1 /home/xxxxx/xxxxx/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass()
#2 /home/xxxxx/xxxxx/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract()
#3 /home/xxxxx/xxxxx/public_html/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php(61): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList()
#4 /home/xxxxx/xxxxx/public_html/setup/src/Magento in /home/xxxxx/xxxxx/public_html/app/code/Ebizmarts/Mailchimp/Controller/Adminhtml/Stores/Index.php on line 17

Magento version: 2.4.1
PHP: 7.4

**Comment by gonzaloebiz** [comment]
Please follow the [issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)
