### ISSUE TITLE
Subscribe save customer email to all store view for exist customer.

### ISSUE THREAD

**Issue by kaihati** [mailchimp/mc-magento2#1355]
When i enable module, my old customer appear on newsletter subscribers as new for all store view as attachment
![image_2022_01_19T03_26_39_246Z](https://user-images.githubusercontent.com/62735100/150109156-40a75fcf-6540-43d6-8b11-640233f50d58.png)

**Comment by gonzaloebiz** [comment]
Hi @kaihati 

please follow the [issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)
