### ISSUE TITLE
ECommerce Tracking sends customer and order data, regardless of newsletter subscriber status

### ISSUE THREAD

**Issue by ThomasNegeli** [mailchimp/mc-magento2#1356]
https://github.com/mailchimp/mc-magento2/blob/a451fc3c3fa853e8f5f7fbae7ad081752904233f/Cron/Ecommerce.php#L217

https://github.com/mailchimp/mc-magento2/blob/a451fc3c3fa853e8f5f7fbae7ad081752904233f/Cron/Ecommerce.php#L222

If a customer is not subscribed to any newsletter, why are you sending user data to the Mailchimp servers?

Currently you are sending ALL CUSOMERS and ALL ORDERS to the Mailchimp service, regardless of the newsletter subscriber status.

You should be aware that this is a data protection regulatory issue.

**Comment by gonzaloebiz** [comment]
Hi, this is because an order MUST have a customer in mailchimp
Keep in mind, if you enable the ecommerce feature, all products/orders/customers will be synced, no matter if belongs to a subscriber or not

Best

**Comment by norgeindian** [comment]
@gonzaloebiz , would it be an idea to add a setting, where one can decide, which data should be transferred?
In our case, we would like to only have the products in mailchimp, but no orders or customers. I think it would be awesome to have such a setting in the config.
