### ISSUE TITLE
Error running setup:di:compile on 2.3.7-p2 with mailchimp/mc-magento2 103.4.43

### ISSUE THREAD

**Issue by PaulWatt** [mailchimp/mc-magento2#1358]
Preconditions

1. upgrade to magento EE 2.3.7-p2
2. mailchimp/mc-magento2 103.4.43 

Steps to reproduce

1. install or upgrade to magento 2.3.7-p2
2. composer require mailchimp/mc-magento2:103.4.43 --no-update
3. composer update
4. bin/magento setup:upgrade
5. bin/magento setup:di:compile

Error:
Compilation was started.
Area configuration aggregation... 5/8 [=================>----------]  62% 40 secs 382.0 MiB
In ClassReader.php line 43:
                                                                         
  Class Magento\Framework\View\Helper\SecureHtmlRenderer does not exist  
                                                                         
If I remove mailchimp/mc-magento2 compilation works perfectly.
![Screenshot 2022-02-28 at 23 41 34](https://user-images.githubusercontent.com/7156317/156077521-8c0ebe25-0c88-4568-94b2-f0c7791d94b8.png)

**Comment by gonzaloebiz** [comment]
Hi @PaulWatt 

you are using a wrong version of the extension for your magento version, please take a look at https://github.com/mailchimp/mc-magento2/releases and select the right version for your magento version

Best
