### ISSUE TITLE
Not all MailChimp lists are showing in Magento admin configuration

### ISSUE THREAD

**Issue by lstellway** [mailchimp/mc-magento2#136]
## Preconditions

1. Using Magento `2.1.9`
2. mailchimp/mc-magento `1.0.25`
3. Configure plugin - add API key

## Steps to reproduce

1. Create multiple lists in MailChimp account
2. Navigate to MailChimp configuration 
  - Stores > Configuration > MailChimp > MailChimp
3. Try to choose different lists

## Actual and Expected result

I expect to be able to choose from different lists, however only one shows as an available option.

## Additional information

I have create a pull request that fixes this issue.

**Comment by gonzaloebiz** [comment]
Hi @loganstellway 

this is not the expected result.
The list depends on the mailchimp store, once you select the mailchimp store the list can be only one, one mailchimp store has only one list associated.

Best

**Comment by lstellway** [comment]
@gonzaloebiz 
Ah! Got it - thank you
