### ISSUE TITLE
Unable to install via Composer 2.0 In Magento 2.4.

### ISSUE THREAD

**Issue by rpate683** [mailchimp/mc-magento2#1365]
# Unable to install via Composer 2.0 In Magento 2.4.x

Steps to reproduce the issue

- install and use Magento 2.4.x  with composer 2.x 
- composer require mailchimp/mc-magento2
- error occured: 
 Problem 1
    - laminas/laminas-dependency-plugin 1.0.4 requires composer-plugin-api ^1.1 -> found composer-plugin-api[2.1.0] but it does not match the constraint.
    - magento/product-community-edition 2.4.1 requires laminas/laminas-dependency-plugin ^1.0 -> satisfiable by laminas/laminas-dependency-plugin[1.0.4].
    - magento/product-community-edition is locked to version 2.4.1 and an update of this package was not requested.

**Comment by gonzaloebiz** [comment]
Just try and work like a charm.
Try specifying the version in the require command of mc-magento2 like the doc says https://github.com/mailchimp/mc-magento2/releases/tag/103.4.44

Best
