### ISSUE TITLE
Mailchimp doesn't send emails

### ISSUE THREAD

**Issue by MajorKuprich** [mailchimp/mc-magento2#1367]
Hello,

We have properly set up Mailchimp <--> Magento sync but after subscribing newsletter Mailchimp doesn't send emails to customers.
There are no info in Mailchimp logs (debug config set to YES).

**Preconditions**
- Magento 2.4.3
- Mailchimp 103.4.44
- Config **Magento always manage emails** set to _No_

**Steps to reproduce**

- Subscribe Newsletter subscription with email address

**Expected result**

- Mailchimp sends Newsletter email to customer email address

**Actual result**

- Mailchimp doesn't send Newsletter email to customer email address

**Comment by gonzaloebiz** [comment]
You already setup the double opt in in magento?

**Comment by MajorKuprich** [comment]
Hi @gonzaloebiz,

I confirm that double opt in Newsletter config is set up.
Unfortunately the result is the same. :(

Have a look at Mailchimp & Newsletter config, please.

![](https://i.imgur.com/8pVfIB1.png)
![](https://i.imgur.com/u06yG9J.png)

**Comment by gonzaloebiz** [comment]
Hi @MajorKuprich 

please drop an email to our support staff

Best
