### ISSUE TITLE
Magento 2 won't send update to Mailchimp

### ISSUE THREAD

**Issue by Brouwerrr** [mailchimp/mc-magento2#1375]
Goodmorning,

Our MC-Magento2 to mailchimp update account won't work. Instead it's sends an update. What can we do?

To be more specific, a customer updates his e-mailadress in Magento2. There Magento and MC-Magento2 will send this information to Mailchimp. Instead of giving the profile in mailchimp an update, it creates a new profile in Mailchimp. What can we do? I know it's possible. 

It's for our website www.geneeskundeboek.nl. Thank you!

Michiel Brouwer

**Comment by gonzaloebiz** [comment]
Hi @Brouwerrr 

please contact our support team

Best

**Comment by Brouwerrr** [comment]
Hi,

Can you tell me where/how? I can't find any contact info besides this page. Thank you
