### ISSUE TITLE
Magento 2.4 Unsubscribed users are syncing to Mail chimp as Subscribed

### ISSUE THREAD

**Issue by sandeep570** [mailchimp/mc-magento2#1376]
Hi Team,

I am facing an issue is that when a customer creates an account but does not opt-in newsletter. After account creation in Magento, I can see the user is not Subscribed to Newsletter but whereas in Mailchimp it is showing Subscribed in "Email Marketing". Could you please help me out with this?

Thanks in advance

**Comment by sandeep570** [comment]
@gonzaloebiz  Could you please help me with this?

**Comment by gonzaloebiz** [comment]
Please, use the [Issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)
