### ISSUE TITLE
Compatibility with Magento 2.4.4 and PHP 8.1

### ISSUE THREAD

**Issue by asterion** [mailchimp/mc-magento2#1379]
## Issue Description

Magento 2.4.4 requiere PHP 8.1

### Preconditions

Magento 2.4.4
Mailchimp 103.4

### Steps to reproduce

Run bin/magento setup:di:compile

Deprecated Functionality: Optional parameter $isMailChimpStoreId declared before required parameter $mailchimpStoreId is implicitly treated as a required parameter in /app/vendor/mailchimp/mc-magento2/Model/Api/Result.php on line 69

**Comment by gonzaloebiz** [comment]
Hi @asterion 

take a look at https://github.com/mailchimp/mc-magento2/issues/1377

Best
