### ISSUE TITLE
 Customers, Products, Orders and Cart count zero.

### ISSUE THREAD

**Issue by NiteshKuyate** [mailchimp/mc-magento2#138]
We have installed Mailchimp for Magento 2 (1.0.25 version) and configured it by following http://wiki.ebizmarts.com/configuration-guide-m4m2 this.
Now, our store is connected with mailchimp but Customers, Products, Orders and Cart count showing is zero, which is wrong but subscribers count is right.
We are also getting **500 internal server error** you can find in below screenshot.
https://s.nimbus.everhelper.me/share/1258154/r4dowpgzckx4tn368onp

**Log details are :**

1 exception(s):
Exception #0 (Mailchimp_Error): Resource Not Found : The requested resource could not be found.

Exception #0 (Mailchimp_Error): Resource Not Found : The requested resource could not be found.
#0 /chroot/home/blaupart/blauparts.com/html/vendor/ebizmarts/mailchimp-lib/src/Mailchimp/EcommerceStores.php(66): Mailchimp->call('ecommerce/store...', Array, 'GET')
#1 /chroot/home/blaupart/blauparts.com/html/app/code/Ebizmarts/MailChimp/Helper/Data.php(766): Mailchimp_EcommerceStore->get('153362a1b5e0483...')
#2 /chroot/home/blaupart/blauparts.com/html/app/code/Ebizmarts/MailChimp/Controller/Script/Get.php(53): Ebizmarts\MailChimp\Helper\Data->getJsUrl('1')
#3 /chroot/home/blaupart/blauparts.com/html/var/generation/Ebizmarts/MailChimp/Controller/Script/Get/Interceptor.php(24): Ebizmarts\MailChimp\Controller\Script\Get->execute()
#4 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/App/Action/Action.php(102): Ebizmarts\MailChimp\Controller\Script\Get\Interceptor->execute()
#5 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#6 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Chain/Chain.php(70): Ebizmarts\MailChimp\Controller\Script\Get\Interceptor->___callParent('dispatch', Array)
#7 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Ebizmarts\\MailC...', 'dispatch', Object(Ebizmarts\MailChimp\Controller\Script\Get\Interceptor), Array, 'contextPlugin')
#8 /chroot/home/blaupart/blauparts.com/html/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#9 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Ebizmarts\MailChimp\Controller\Script\Get\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#10 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Ebizmarts\\MailC...', 'dispatch', Object(Ebizmarts\MailChimp\Controller\Script\Get\Interceptor), Array, 'customer-app-ac...')
#11 /chroot/home/blaupart/blauparts.com/html/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#12 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Ebizmarts\MailChimp\Controller\Script\Get\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#13 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Ebizmarts\\MailC...', 'dispatch', Object(Ebizmarts\MailChimp\Controller\Script\Get\Interceptor), Array, 'storeCheck')
#14 /chroot/home/blaupart/blauparts.com/html/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Ebizmarts\MailChimp\Controller\Script\Get\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#16 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Ebizmarts\\MailC...', 'dispatch', Object(Ebizmarts\MailChimp\Controller\Script\Get\Interceptor), Array, 'weee-app-action...')
#17 /chroot/home/blaupart/blauparts.com/html/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#18 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Ebizmarts\MailChimp\Controller\Script\Get\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#19 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Ebizmarts\\MailC...', 'dispatch', Object(Ebizmarts\MailChimp\Controller\Script\Get\Interceptor), Array, 'tax-app-action-...')
#20 /chroot/home/blaupart/blauparts.com/html/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Ebizmarts\MailChimp\Controller\Script\Get\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#21 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Ebizmarts\MailChimp\Controller\Script\Get\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 /chroot/home/blaupart/blauparts.com/html/var/generation/Ebizmarts/MailChimp/Controller/Script/Get/Interceptor.php(39): Ebizmarts\MailChimp\Controller\Script\Get\Interceptor->___callPlugins('dispatch', Array, Array)
#23 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/App/FrontController.php(55): Ebizmarts\MailChimp\Controller\Script\Get\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#25 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#26 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#27 /chroot/home/blaupart/blauparts.com/html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#28 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#30 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#31 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#32 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'searchautocompl...')
#33 /chroot/home/blaupart/blauparts.com/html/vendor/mirasvit/module-search-autocomplete/src/SearchAutocomplete/Plugin/ResponsePlugin.php(156): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#34 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Chain/Chain.php(67): Mirasvit\SearchAutocomplete\Plugin\ResponsePlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#36 /chroot/home/blaupart/blauparts.com/html/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#37 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#38 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#39 /chroot/home/blaupart/blauparts.com/html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(68): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#40 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#41 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'Amasty_Invisibl...')
#42 /chroot/home/blaupart/blauparts.com/html/app/code/Amasty/InvisibleCaptcha/Plugin/Predispatch.php(77): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#43 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/Interception/Interceptor.php(142): Amasty\InvisibleCaptcha\Plugin\Predispatch->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#44 /chroot/home/blaupart/blauparts.com/html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#45 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#46 /chroot/home/blaupart/blauparts.com/html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#47 /chroot/home/blaupart/blauparts.com/html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#48 {main}

Please tell us what to do because our site is Live.

Thanks.

**Comment by gonzaloebiz** [comment]
What version of ebizmarts/mailchimp-lib do you have?

**Comment by NiteshKuyate** [comment]
ebizmarts/mailchimp-lib version : 3.0.16

**Comment by gonzaloebiz** [comment]
Be sure to run from your store root directory

rm -rf pub/static;php7.0 bin/magento setup:static-content:deploy;php7.0 bin/magento cache:clean

**Comment by NiteshKuyate** [comment]
Right now I am unable to run this commands.
As we go in maintainance mode then I will run these commands and let you know status.

**Comment by NiteshKuyate** [comment]
I run these commands now but issue still occurs.
Let us know, What steps need to do?

**Comment by NiteshKuyate** [comment]
Default Store view 
**Use Website** checkbox of **Mailchimp Store** was unchecked and therefore in core_config_data there were 2 entries (1 for default and 2nd for store).
Now, after re-configuration our issue solved.
