### ISSUE TITLE
Archived contact gets unarchived when making an order

### ISSUE THREAD

**Issue by federicocanedo** [mailchimp/mc-magento2#1381]
Preconditions:
> 1. Any version of mc-magento2.

Steps to reproduce:

> 1.    Have an archived contact in MailChimp.
> 2.    Make an order with that email.

Actual result:

> 1. Contact is still archived.

Actual result:
 > 1. Contact gets unarchived.

**Comment by gonzaloebiz** [comment]
After some test, works OK
