### ISSUE TITLE
Incompatibility with Magento 2.4.4 x PHP 8.1

### ISSUE THREAD

**Issue by Axel29** [mailchimp/mc-magento2#1382]
### Preconditions

1. Magento CE 2.4.4
2. mc-magento2 103.4.44
3. PHP 8.1

### Steps to reproduce

1. Install the latest version of the module (`composer require mailchimp/mc-magento2:103.4.44`)
2. Run `php bin/magento setup:upgrade` command to enable it

### Actual and Expected result

The command goes through the whole process without any error.

### Additional information

Multiple Exception due to an incompatibility with PHP 8.1 are thrown:

**Error n°1:**
```bash
Deprecated Functionality: Optional parameter $listId declared before required parameter $storeId is implicitly treated as a required parameter in /app/vendor/mailchimp/mc-magento2/Helper/Data.php on line 648
```

The parameters of the `\Ebizmarts\MailChimp\Helper\Data::createStore` should be inversed or the `$storeId` parameter should be set to "null" as default.

**Error n°2:**
Once the first error is fixed, this one appears:

```bash
Deprecated Functionality: Optional parameter $recipients declared before required parameter $settings is implicitly treated as a required parameter in /app/vendor/ebizmarts/mailchimp-lib/src/Mailchimp/Campaigns.php on line 44
```

I guess the `$settings` parameter should be set as an empty array by default.
If not, it should be declared before the optional parameters.

**Error n°3:**

Once the error n°2 is fixed, this one appears:

```bash
Deprecated Functionality: Optional parameter $recipients declared before required parameter $settings is implicitly treated as a required parameter in /app/vendor/ebizmarts/mailchimp-lib/src/Mailchimp/Campaigns.php on line 130
```

Same thing as error n°2, I guess the `$settings` parameter should be set as an empty array by default.

**Error n°4:**

Once the error n°3 is fixed, this one appears:

```bash
Deprecated Functionality: Optional parameter $blockId declared before required parameter $message is implicitly treated as a required parameter in /app/vendor/ebizmarts/mailchimp-lib/src/Mailchimp/CampaignsFeedback.php on line 24
```

I guess the `$message` parameter should be set as an empty string by default.
If not, it should be declared before the optional parameters.

**Error n°5:**

Once the error n°3 is fixed, this one appears:

```bash
Deprecated Functionality: Optional parameter $blockId declared before required parameter $message is implicitly treated as a required parameter in /app/vendor/ebizmarts/mailchimp-lib/src/Mailchimp/CampaignsFeedback.php on line 75
```

I guess the `$message` parameter should be set as an `null` by default.
The `isComplete` parameter should be set as a default boolean value. From what I've seen, the `modify` method isn't called anywhere, so the boolean could be `true` by default I guess.
If not, these parameters should be declared before the optional parameters.

___

The errors keep poping up one after an other, I stopped patching them one by one.
The ebizmarts/mailchimp-lib must be upgraded I guess...

**Comment by Axel29** [comment]
EDIT: I had to manually update the `ebizmarts/mailchimp-lib` package from 3.0.34 to 3.0.35 and now the errors are gone.

I don't know why composer installed the version 3.0.34 though.

**Comment by gonzaloebiz** [comment]
Take a look at https://github.com/mailchimp/mc-magento2/issues/1377

**Comment by Axel29** [comment]
> Take a look at #1377

Please reopen the issue.
The usage of `ebizmarts/mailchimp-lib` v3.0.35 only fixes the issues related to this package.

But the first error reclared in my first message is still linked to THIS repository and needs to be fixed.

**Comment by gonzaloebiz** [comment]
The fixes are in the issue that I put in the previous comment and will be available in the next release

**Comment by Axel29** [comment]
Right, sorry I didn't even notice that the whole `createStore` method was removed, I was looking at the methods declaration and didn't see any parameters changed ^^" Anyway thanks for the update.
