### ISSUE TITLE
PHP 8.1 - Error on optional parameters

### ISSUE THREAD

**Issue by VincentMarmiesse** [mailchimp/mc-magento2#1384]
When using the module on PHP 8.1 (Magento 2.4.4), I have the following error when I try to compile the DI:

```
Deprecated Functionality: Optional parameter $isMailChimpStoreId declared before required parameter $mailchimpStoreId is implicitly treated as a required parameter in /var/www/html/vendor/mailchimp/mc-magento2/Model/Api/Result.php on line 69
```
This parameter does not seem to be used in this function.

There is also an error on `createStore` function from `Helper/Data.php`, but this function does not seem to be called anywere.

**Comment by gonzaloebiz** [comment]
Please take a look at https://github.com/mailchimp/mc-magento2/issues/1377

Best

**Comment by VincentMarmiesse** [comment]
Hi,

Thanks!

Is this fix released yet?
The last release seems to be from  Oct 4, 2021.

**Comment by gonzaloebiz** [comment]
In the next release, we don't have an ETA yet
