### ISSUE TITLE
Magento 2.4.4 not supported in any release version

### ISSUE THREAD

**Issue by jmspswny** [mailchimp/mc-magento2#1385]
Magento 2.4.4 requires PHP 8.1.  The current 2.4.x release fails to run on PHP8.x due to parameter order for functions requirements, as documented here:

https://www.php.net/manual/en/functions.arguments.php#functions.arguments.default

Specifically we get errors like:

Deprecated Functionality: Required parameter $mailchimpStoreId follows optional parameter $isMailChimpStoreId in ./vendor/mailchimp/mc-magento2/Model/Api/Result.php on line 69

In multiple places.  The develop-2.4 of mc-magento2 appears to have fixed this issue, but nothing has been released to make those changes generally available.

**Comment by jmspswny** [comment]
found existing issue.  the code has already been fixed but not released.

**Comment by gonzaloebiz** [comment]
Please, take a look at https://github.com/mailchimp/mc-magento2/issues/1377
This fix will be available in the next release.

Best
