### ISSUE TITLE
Country not send to Mailchimp

### ISSUE THREAD

**Issue by alep93** [mailchimp/mc-magento2#1386]
When new customer has been created, mailchimp not get the correct country_code, and set default value to USA.

**Comment by gonzaloebiz** [comment]
Hi @alep93 

please follow the [Issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)

Best

**Comment by NicoDG** [comment]
We're experiencing the same issue.
