### ISSUE TITLE
SSL certificate problem Can't add stores to configuration 

### ISSUE THREAD

**Issue by palo** [mailchimp/mc-magento2#139]
Having this issue "SSL certificate problem: unable to get local issuer certificate." preventing from successfully configuring the extension.

We are able to install and configura the extension in a development "clone" of our store in ubuntu 16 setup. We tried the fixes suggested in the link bellow but none works.  https://stackoverflow.com/questions/22973701/ssl-errors-using-mailchimps-api 

Also, this server had a magento 1.9  store connected to mailchimp and never had this issue.

Can someone help overcome this? 

1. Magento CE 2.2.1
2. mc-magento2 1.0.25
3. ubuntu 14.04.1
4. PHP 7.0.25

## Expected result

Adding a store fails after selecting an API key with the message:
"A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later."

```
[2017-11-21 17:00:24] MailChimpLogger.INFO: API call to ecommerce/stores?count=100 failed: SSL certificate problem: unable to get local issuer certificate
[2017-11-21 17:00:24] MailChimpLogger.INFO: API call to lists/ failed: SSL certificate problem: unable to get local issuer certificate

```

**Comment by gonzaloebiz** [comment]
This is not an issue with the extension, is a issue with your server.
You can get a lot of suggestions searching for "ubuntu SSL certificate problem: unable to get local issuer certificate"

Best
