### ISSUE TITLE
PHP8 Deprecation notices - M2.4.4 compatibility

### ISSUE THREAD

**Issue by jdereus87** [mailchimp/mc-magento2#1397]
Requirements:
M2.4.4.
PHP 8.1

Description:
After updating both magento & mailchimp to the newest versions we get deprecation notices in setup:upgrade & setup:di:compile

Setup:upgrade:
PHP Deprecated:  Optional parameter $listId declared before required parameter $storeId is implicitly treated as a required parameter in /vendor/mailchimp/mc-magento2/Helper/Data.php on line 648

Setup:di:compile: 
PHP Deprecated:  Optional parameter $listId declared before required parameter $storeId is implicitly treated as a required parameter in /vendor/mailchimp/mc-magento2/Helper/Data.php on line 648
PHP Deprecated:  Optional parameter $isMailChimpStoreId declared before required parameter $mailchimpStoreId is implicitly treated as a required parameter in /data/web/magento2/vendor/mailchimp/mc-magento2/Model/Api/Result.php on line 69

Result:
It just gives PHP deprecated notices. It does not break setup:upgrade or setup:di:compile. I have not tested it breaks the actual workings of the module.

Question:
Any estimated date yet on a 2.4.4. compatibility release?

**Comment by gonzaloebiz** [comment]
Hi @jdereus87 

take a look at https://github.com/mailchimp/mc-magento2/issues/1377
We will try to release next week

Best
