### ISSUE TITLE
Put a column in the order grid to show if the order was synced

### ISSUE THREAD

**Issue by gonzaloebiz** [mailchimp/mc-magento2#140]
Add a new column in the order grid with the status of the synchronization with mailchimp
They are 6 possibles statuses:
![image](https://user-images.githubusercontent.com/6222792/54032074-598c3380-418f-11e9-8c4c-99d615c66b54.png) 
means that this order is from a store that is not connected with mailchimp
![image](https://user-images.githubusercontent.com/6222792/54032144-8c362c00-418f-11e9-829b-f872ecb1bfeb.png)
means that the order was never synced, but need to be synced
![image](https://user-images.githubusercontent.com/6222792/54032191-b0920880-418f-11e9-8bf2-81866ead3af2.png)
means that the order was synced recently, and we are waiting for a mailchimp response
![image](https://user-images.githubusercontent.com/6222792/54032255-d8816c00-418f-11e9-9dc4-df9ec1514460.png)
means that the order was synced successfully
![image](https://user-images.githubusercontent.com/6222792/54032321-08307400-4190-11e9-8df4-079dab408b12.png)
means that the order was synced but with errors, look at the error grid for more info
![image](https://user-images.githubusercontent.com/6222792/54032463-6bbaa180-4190-11e9-8601-17901ae4b6d6.png)
means that the order was synced, but modified, so we need to resync it

The new grid look like

![image](https://user-images.githubusercontent.com/6222792/54033028-010a6580-4192-11e9-8cd9-e0cdf8cbcfc8.png)

**Comment by jhruehl** [comment]
Honestly. Why are you messing so much with the core Magento tables. Even if customers just want to use the Mailchimp sync functionality, your Magento Update script messes with other tables.

Just add another table, put your information there and reference the orders via entity_id.

**Comment by gonzaloebiz** [comment]
We are waiting for the icons from Mailchimp
