### ISSUE TITLE
Create New MailChimp Store - Warning: Invalid Argument supplied for foreach() - part 2

### ISSUE THREAD

**Issue by BaberAhmed** [mailchimp/mc-magento2#141]
Hi,

Please can you reference - https://github.com/mailchimp/mc-magento2/issues/127

I have updated to latest version of 1.0.25 and the error is still showing, please can you advise?

Regards,
Baber

**Comment by BaberAhmed** [comment]
Good Morning,

Just checking in to see if there was any feedback on the above issue please.

Kind Regards
Baber

**Comment by gonzaloebiz** [comment]
We could not replicate

**Comment by BaberAhmed** [comment]
Good Afternoon,

Ok thought it was a bit odd, I did some more testing and the issue arises only in Magento production mode, in Dev mode the behaviour is as expected.

The steps to replicate are the same but with the additional last step is to put your dev environment to product mode and reload the admin screen for mail-chimp stores and it will show the error.

Cheers
Baber

**Comment by jsdupuis** [comment]
Hi. I have the exact same problem. Magento 2.1.8 with MailChmip 1.0.25. Any solution found? Data is syncing, but I can only see this error message when going into MailChimp Stores. Error happened after saving a store.

**Comment by SantiParagarino** [comment]
Hello @jsdupuis 

We are not able to reproduce this locally.
I suggest you to make sure the installation was made correctly and verify the static files. Sometimes when the file permissions are not set properly the javascript files are not successfully loaded in the back end causing unexpected behavior.

**Comment by gonzaloebiz** [comment]
Hi @jsdupuis @BaberAhmed 

are you using capistrano to deploy?

Best

**Comment by jsdupuis** [comment]
Hi @gonzaloebiz. Not using capistrano. My first attempt was by using the "Web setup wizard" menu in the backend of Magento. Then I uninstalled everything and reinstalled using composer via SSH. I got the same problem. Uninstalled again, deleted the tables, and reinstalled by SSH. Same problem. All my e-commerce data is synching with Mailchimp. It's only that I cannot use the Mailchimp store menu.
