### ISSUE TITLE
Release 1.0.25

### ISSUE THREAD

**Issue by inelukipg** [mailchimp/mc-magento2#142]
Hi,
When will you push Release 1.0.25 to Marketplace?¨

**Comment by inelukipg** [comment]
Hi,
Any news about this?

**Comment by NiteshKuyate** [comment]
@inelukipg Mailchimp 1.0.25 released.

**Comment by inelukipg** [comment]
@NiteshKuyate On https://marketplace.magento.com/mailchimp-mc-magento2.html#product.info.details.release_notes I can only find 1.0.24.

**Comment by NiteshKuyate** [comment]
@inelukipg You can get this here [https://store.ebizmarts.com/mailchimp4magento2.html](https://store.ebizmarts.com/mailchimp4magento2.html)

**Comment by inelukipg** [comment]
@NiteshKuyate Ok, thanks. But I already installed previous version via composer (from marketplace). I think that's a better way of installing and updating extensions than copying files.
Could you update the version on Marketplace?

**Comment by NiteshKuyate** [comment]
@inelukipg I am not a developer at Mailchimp, I had already faced same issue then I download it from that shared link.

**Comment by inelukipg** [comment]
Ok @NiteshKuyate, did you uninstall the composer installed version first?

**Comment by NiteshKuyate** [comment]
@inelukipg For first and second time I used same link to download.
For second time configuration, Firstly disabled mailchimp extension then flush cache and then removed all files of Mailchimp (mailchimp-lib) of prev version then installed fresh 1.0.25 version and get mailchimp-lib using composer, then configured it, works fine for me.

**Comment by ebizmarts-keller** [comment]
@inelukipg You should be able to update via composer to version 1.0.25

Just run **composer require mailchimp/mc-magento2**

Or if that doesn't work, run **composer require mailchimp/mc-magento2 1.0.25**

**Comment by inelukipg** [comment]
Thank you @ebizmarts-keller 
This worked: `composer require mailchimp/mc-magento2 1.0.25`
