### ISSUE TITLE
product price in abandoned cart is 0

### ISSUE THREAD

**Issue by mohammedTBB** [mailchimp/mc-magento2#1421]
## Title

> product price in abandoned cart is 0

## Issue Description

the product is showing the correct price in product page and category page but showing 0 in abandoned cart.

### Preconditions
-Magento 2.4.3
-Php 7.4
-mailchimp/mc-magento2 103.4.44

### Steps to reproduce

    1. create a simple product with price 0
    2. add new customizable option with price
    
![image](https://user-images.githubusercontent.com/66772877/171667305-ad134cfb-47f2-4bff-896f-a25e923e981f.png)
   
    3. then en el front end, add the product to the cart
    4. abandon the cart
    5. an email recieved with price 0

### Actual and Expected result

the product should show the same price in product page.

**Comment by federicocanedo** [comment]
Hello, after some testing we identified the issue, MailChimp does not support products with customizable options, I commented the issue with the team to see if there is an alternative that can be done in our side.

**Comment by mohammedTBB** [comment]
Hi @federicocanedo thanks for the testings, 
is there any thing new about the issue? alternatives?

**Comment by mohammedTBB** [comment]
Hi @federicocanedo
Is there any updates?

**Comment by mohammedTBB** [comment]
Hi @federicocanedo
I can see The ticket is still open, is it WIP? any news?

**Comment by mohammedTBB** [comment]
Hi @federicocanedo
Is there any news about this issue?

**Comment by federicocanedo** [comment]
This is not fixable since Mailchimp does not support products with price of 0.

We haven't found an alternative without modifying the product's price.
