### ISSUE TITLE
Plugin class Ebizmarts\MailChimp\Model\Plugin\Subscriber doesn't exist

### ISSUE THREAD

**Issue by Quedendil** [mailchimp/mc-magento2#1422]
After setup:upgrade
I am getting the error: 
Plugin class Ebizmarts\MailChimp\Model\Plugin\Subscriber doesn't exist

**Comment by gonzaloebiz** [comment]
Hi @Quedendil 

please follow the [issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)

Best

**Comment by gonzaloebiz** [comment]
Closing the issue after more than 1 month without response
