### ISSUE TITLE
Error with webhooks when processed on a certain order

### ISSUE THREAD

**Issue by ebizmarts-keller** [mailchimp/mc-magento2#143]
When webhook requests on the database are on a certain order for a subscriber, the cronjob will throw an error.

**Case 1: upemail before an unsubscribe** 

![screenshot at 2017-11-29 16-14-55](https://user-images.githubusercontent.com/19838935/33394263-87bdf1bc-d520-11e7-90d2-b0509c74b793.png)

![screenshot at 2017-11-29 16-09-01](https://user-images.githubusercontent.com/19838935/33394043-d4294afc-d51f-11e7-979d-c83c13cb70b0.png)

**Case 2: profile before an unsubscribe** 

![screenshot at 2017-11-29 16-12-44](https://user-images.githubusercontent.com/19838935/33394169-46c4df54-d520-11e7-9b75-0616e28dbed2.png)

![screenshot at 2017-11-29 16-13-14](https://user-images.githubusercontent.com/19838935/33394178-4ae5597e-d520-11e7-8895-97bdd9ae7f04.png)

**Comment by MaxKonstructive** [comment]
Hey @ebizmarts-keller, I am seeing a similar issue with a profile/upemail change.

In Magento there is a profile webhook request that uses the new email address.

And then a upemail which is changing them.

Therefore Magento is trying to process a request on an email address which doesn't exist.

**Comment by ebizmarts-keller** [comment]
cannot replicate in latest version
