### ISSUE TITLE
Subscribers First and Last Name do not get synced into Mailchimp

### ISSUE THREAD

**Issue by WarrenTinSoldier** [mailchimp/mc-magento2#1430]
**Issue Description**
When you subscribe with your email, first and last name, only the email gets synced into Mailchimp.

**Preconditions**
-Magento 2.3.5-p2
-Php 7.3
-mailchimp/mc-magento2 102.3.44

**Steps to Reproduce**

Subscribe a user with email, first and last name using a newsletter form containing all 3 fields.
Check Mailchimp data on subscribed user.

**Expected Result**
The email, first and last name of subscriber appears in Mailchimp.

**Actual Result**
Only the email of subscriber appears in Mailchimp.

**Comment by agustinbv** [comment]
Hello Warren,

Could you indicate where exactly is this 3 field form located? Do you refer to the customer account creation form that has the check button to subscribe to the newsletter?
