### ISSUE TITLE
Abandoned cart email no recieved

### ISSUE THREAD

**Issue by mohammedTBB** [mailchimp/mc-magento2#1431]
Preconditions:
magento 2.4.4
php 8.1
mailchimp 103.4.45

After updating to the latest version of mailchimp (103.4.45), customers are not able to recieve abandoned cart emails.
plus the contacts in queue is empty:

![image](https://user-images.githubusercontent.com/66772877/174024884-d6c47b7d-92c8-47ba-b139-5c11bd8003ea.png)

take into account the email is registered in the quote table in magento.
 
no log error detected to be informed.

Can you please confirm that the abandoned cart is working?

**Comment by gonzaloebiz** [comment]
Please send a ticket to our support team at mailchimp@ebizmarts-desk.zendesk.com
