### ISSUE TITLE
Compatibility with Magento Enterprise Edition 2.1.x

### ISSUE THREAD

**Issue by avelikdusgg** [mailchimp/mc-magento2#144]
Mailchimp 1.0.25 is not compatible with Magento Enterprise Edition 2.1.x, because
mysql error appears during synchronization of promo rules .
Cron job ebizmarts_ecommerce stopped with error message :

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'websites.rule_id' in 'on clause', query was: SELECT `main_table`.*, `rule_coupons`.`code`, `websites`.*, `m4m`.* FROM `salesrule` AS `main_table`
 LEFT JOIN `salesrule_coupon` AS `rule_coupons` ON main_table.rule_id = rule_coupons.rule_id AND rule_coupons.is_primary = 1
 LEFT JOIN `salesrule_website` AS `websites` ON main_table.rule_id = websites.rule_id and website_id = 1
 LEFT JOIN `mailchimp_sync_ecommerce` AS `m4m` ON m4m.related_id = main_table.rule_id and m4m.type = 'PRL' and m4m.mailchimp_store_id = '379206f1ff2b67dee58088a62f7c8440' WHERE (m4m.mailchimp_sync_deleted = 1) AND (main_table.created_in <= '1509512341') AND (main_table.updated_in > '1509512341') LIMIT 100

Table salesrule_website does not have rule_id column in Enterprise version of Magento.
It has only row_id and website_id columns.

Please, fix.

**Comment by dan-ding** [comment]
Yeah, this is definitely an issue.

**Comment by dan-ding** [comment]
@gonzaloebiz it's a runtime issue - there's no actual or expected outcome or course of action; deal with it.

**Comment by gonzaloebiz** [comment]
until next version, change the lines
https://github.com/mailchimp/mc-magento2/blob/2e445882180a742f22227dada14251f33b972dd4/Model/Api/PromoCodes.php#L116 and https://github.com/mailchimp/mc-magento2/blob/bd0908e1708b7cc9fa1a0ed835e26faacaac43e6/Model/Api/PromoRules.php#L88
change websites.rule_id with websites.row_id

Best

**Comment by dan-ding** [comment]
I take it is lines 88 and 126 in mc-magento2/Model/Api/PromoRules.php
