### ISSUE TITLE
Unable to create credit memo with offline refund

### ISSUE THREAD

**Issue by key-dev** [mailchimp/mc-magento2#1441]
## Issue Description

I have recently upgraded magento version from 2.2.11 to 2.4.3
And installed module using composer require command
composer require: mailchimp/mc-magento2
Module installed correctly with Ebizmarts library

### Actual and Expected result

Everything else seems to work fine except credit memo. As soon as i hit refund offline button in new credit memo, i get the following error.
`TypeError: Argument 2 passed to Ebizmarts\MailChimp\Model\Plugin\Creditmemo::afterSave() must implement interface Magento\Sales\Api\Data\CreditmemoInterface, instance of Magento\Sales\Model\Order\CreditmemoRepository\Interceptor given, called in /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php on line 146 and defined in /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/mailchimp/mc-magento2/Model/Plugin/Creditmemo.php:33
Stack trace:

#0 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(146): Ebizmarts\MailChimp\Model\Plugin\Creditmemo->afterSave()
#1 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Order\CreditmemoRepository\Interceptor->Magento\Framework\Interception\{closure}()
#2 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/generated/code/Magento/Sales/Model/Order/CreditmemoRepository/Interceptor.php(59): Magento\Sales\Model\Order\CreditmemoRepository\Interceptor->___callPlugins()
#3 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/module-sales/Model/Service/CreditmemoService.php(169): Magento\Sales\Model\Order\CreditmemoRepository\Interceptor->save()
#4 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Service\CreditmemoService->refund()
#5 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Service\CreditmemoService\Interceptor->___callParent()
#6 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Service\CreditmemoService\Interceptor->Magento\Framework\Interception\{closure}()
#7 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/generated/code/Magento/Sales/Model/Service/CreditmemoService/Interceptor.php(50): Magento\Sales\Model\Service\CreditmemoService\Interceptor->___callPlugins()
#8 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/module-sales/Controller/Adminhtml/Order/Creditmemo/Save.php(119): Magento\Sales\Model\Service\CreditmemoService\Interceptor->refund()
#9 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save->execute()
#10 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->___callParent()
#11 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->Magento\Framework\Interception\{closure}()
#12 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/generated/code/Magento/Sales/Controller/Adminhtml/Order/Creditmemo/Save/Interceptor.php(23): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->___callPlugins()
#13 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/App/Action/Action.php(111): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->execute()
#14 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#15 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#16 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->___callParent()
#17 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/app/code/WeltPixel/Backend/Plugin/Utility.php(76): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->Magento\Framework\Interception\{closure}()
#18 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(135): WeltPixel\Backend\Plugin\Utility->aroundDispatch()
#19 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->Magento\Framework\Interception\{closure}()
#20 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#21 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->Magento\Framework\Interception\{closure}()
#22 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/generated/code/Magento/Sales/Controller/Adminhtml/Order/Creditmemo/Save/Interceptor.php(32): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->___callPlugins()
#23 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/App/FrontController.php(245): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->dispatch()
#24 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#25 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#26 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#27 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#28 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#29 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#30 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#31 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#32 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#33 /home/770730.cloudwaysapps.com/rstxdbpzav/public_html/pub/index.php(29): Magento\Framework\App\Bootstrap->run()
#34 {main}`

Please help

**Comment by gonzaloebiz** [comment]
Hi @key-dev 

what version of mc-magento2 do you have?
I'm just testing with magento 2.4.3 and mc-magento2 103.4.45 and works ok for me

**Comment by key-dev** [comment]
Hi @gonzaloebiz 

Its:  "mailchimp/mc-magento2": "^103.4"

Thank you

**Comment by gonzaloebiz** [comment]
what exact version? run 

`composer show | grep -i Mailchimp`

Best

**Comment by key-dev** [comment]
That command showed below.
![image](https://user-images.githubusercontent.com/17259817/176089264-32b6dcf1-05eb-4a2c-8311-219b8b425d32.png)


I found the following versions in composer.json of those modules.
ebizmarts/mailchimp-lib: 3.0.35
mailchimp/mc-magento2: 103.4.45

Thank you

**Comment by gonzaloebiz** [comment]
Hi @key-dev 

what payment method are you using in the original order?

Best

**Comment by gonzaloebiz** [comment]
close the issue until we have news

**Comment by key-dev** [comment]
Hi @gonzaloebiz 
Sorry i wasn't around.

Any payment method that i used, including paypal or authorize.net or anyother.

I have even installed latest mailchimp/mc-magento2: 103.4.46
But same thing is happening. It can't let me refund, throws the following error.

TypeError: Argument 2 passed to Ebizmarts\MailChimp\Model\Plugin\Creditmemo::afterSave() must implement interface Magento\Sales\Api\Data\CreditmemoInterface, instance of Magento\Sales\Model\Order\CreditmemoRepository\Interceptor given, called in /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php on line 146 and defined in /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/mailchimp/mc-magento2/Model/Plugin/Creditmemo.php:33
Stack trace:
#0 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(146): Ebizmarts\MailChimp\Model\Plugin\Creditmemo->afterSave()
#1 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Order\CreditmemoRepository\Interceptor->Magento\Framework\Interception\{closure}()
#2 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/generated/code/Magento/Sales/Model/Order/CreditmemoRepository/Interceptor.php(59): Magento\Sales\Model\Order\CreditmemoRepository\Interceptor->___callPlugins()
#3 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/module-sales/Model/Service/CreditmemoService.php(169): Magento\Sales\Model\Order\CreditmemoRepository\Interceptor->save()
#4 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Service\CreditmemoService->refund()
#5 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Service\CreditmemoService\Interceptor->___callParent()
#6 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Service\CreditmemoService\Interceptor->Magento\Framework\Interception\{closure}()
#7 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/generated/code/Magento/Sales/Model/Service/CreditmemoService/Interceptor.php(50): Magento\Sales\Model\Service\CreditmemoService\Interceptor->___callPlugins()
#8 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/module-sales/Controller/Adminhtml/Order/Creditmemo/Save.php(119): Magento\Sales\Model\Service\CreditmemoService\Interceptor->refund()
#9 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save->execute()
#10 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->___callParent()
#11 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->Magento\Framework\Interception\{closure}()
#12 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/generated/code/Magento/Sales/Controller/Adminhtml/Order/Creditmemo/Save/Interceptor.php(23): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->___callPlugins()
#13 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/App/Action/Action.php(111): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->execute()
#14 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#15 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#16 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->___callParent()
#17 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/app/code/WeltPixel/Backend/Plugin/Utility.php(76): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->Magento\Framework\Interception\{closure}()
#18 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(135): WeltPixel\Backend\Plugin\Utility->aroundDispatch()
#19 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->Magento\Framework\Interception\{closure}()
#20 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#21 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->Magento\Framework\Interception\{closure}()
#22 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/generated/code/Magento/Sales/Controller/Adminhtml/Order/Creditmemo/Save/Interceptor.php(32): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->___callPlugins()
#23 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/App/FrontController.php(245): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->dispatch()
#24 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#25 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#26 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#27 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#28 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#29 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#30 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#31 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#32 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#33 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/pub/index.php(29): Magento\Framework\App\Bootstrap->run()

**Comment by gonzaloebiz** [comment]
Try changing this line https://github.com/mailchimp/mc-magento2/blob/develop-2.4/etc/di.xml#L83 with this one

    <type name="Magento\Sales\Api\CreditmemoRepositoryInterface">

**Comment by key-dev** [comment]
Here is the error on refund, after updating the code in di.xml
TypeError: Argument 2 passed to Ebizmarts\MailChimp\Model\Plugin\Creditmemo::afterSave() must implement interface Magento\Sales\Api\Data\CreditmemoInterface, instance of Magento\Sales\Model\Order\CreditmemoRepository\Interceptor given, called in /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php on line 146 and defined in /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/mailchimp/mc-magento2/Model/Plugin/Creditmemo.php:33
Stack trace:
#0 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(146): Ebizmarts\MailChimp\Model\Plugin\Creditmemo->afterSave()
#1 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Order\CreditmemoRepository\Interceptor->Magento\Framework\Interception\{closure}()
#2 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/generated/code/Magento/Sales/Model/Order/CreditmemoRepository/Interceptor.php(59): Magento\Sales\Model\Order\CreditmemoRepository\Interceptor->___callPlugins()
#3 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/module-sales/Model/Service/CreditmemoService.php(169): Magento\Sales\Model\Order\CreditmemoRepository\Interceptor->save()
#4 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Service\CreditmemoService->refund()
#5 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Service\CreditmemoService\Interceptor->___callParent()
#6 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Service\CreditmemoService\Interceptor->Magento\Framework\Interception\{closure}()
#7 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/generated/code/Magento/Sales/Model/Service/CreditmemoService/Interceptor.php(50): Magento\Sales\Model\Service\CreditmemoService\Interceptor->___callPlugins()
#8 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/module-sales/Controller/Adminhtml/Order/Creditmemo/Save.php(119): Magento\Sales\Model\Service\CreditmemoService\Interceptor->refund()
#9 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save->execute()
#10 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->___callParent()
#11 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->Magento\Framework\Interception\{closure}()
#12 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/generated/code/Magento/Sales/Controller/Adminhtml/Order/Creditmemo/Save/Interceptor.php(23): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->___callPlugins()
#13 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/App/Action/Action.php(111): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->execute()
#14 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#15 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#16 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->___callParent()
#17 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/app/code/WeltPixel/Backend/Plugin/Utility.php(76): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->Magento\Framework\Interception\{closure}()
#18 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(135): WeltPixel\Backend\Plugin\Utility->aroundDispatch()
#19 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->Magento\Framework\Interception\{closure}()
#20 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#21 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->Magento\Framework\Interception\{closure}()
#22 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/generated/code/Magento/Sales/Controller/Adminhtml/Order/Creditmemo/Save/Interceptor.php(32): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->___callPlugins()
#23 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/App/FrontController.php(245): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->dispatch()
#24 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#25 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#26 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#27 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#28 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#29 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#30 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#31 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#32 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#33 /home/795356.cloudwaysapps.com/rstxdbpzav/public_html/pub/index.php(29): Magento\Framework\App\Bootstrap->run()

**Comment by key-dev** [comment]
I have replaced the below line and it worked.
`<type name="Magento\Sales\Model\Order\CreditmemoRepository\Interceptor">`

Not sure if its correct.

**Comment by key-dev** [comment]
Thats fixed but another issue is there now, its not related to this fix but its a separate issue. When saving store in Mailchimp>Mailchimp Stores in Magento.

1 exception(s):
Exception #0 (Exception): Notice: Undefined index: list_id in /home/320175.cloudwaysapps.com/rstxdbpzav/public_html/vendor/mailchimp/mc-magento2/Controller/Adminhtml/Stores/Save.php on line 95

Exception #0 (Exception): Notice: Undefined index: list_id in /home/320175.cloudwaysapps.com/rstxdbpzav/public_html/vendor/mailchimp/mc-magento2/Controller/Adminhtml/Stores/Save.php on line 95
<pre>#1 Ebizmarts\MailChimp\Controller\Adminhtml\Stores\Save->_updateMailchimp() called at [vendor/mailchimp/mc-magento2/Controller/Adminhtml/Stores/Save.php:31]
#2 Ebizmarts\MailChimp\Controller\Adminhtml\Stores\Save->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#3 Ebizmarts\MailChimp\Controller\Adminhtml\Stores\Save\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#4 Ebizmarts\MailChimp\Controller\Adminhtml\Stores\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#5 Ebizmarts\MailChimp\Controller\Adminhtml\Stores\Save\Interceptor->___callPlugins() called at [generated/code/Ebizmarts/MailChimp/Controller/Adminhtml/Stores/Save/Interceptor.php:23]
#6 Ebizmarts\MailChimp\Controller\Adminhtml\Stores\Save\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#7 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:151]
#8 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#9 Ebizmarts\MailChimp\Controller\Adminhtml\Stores\Save\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#10 Ebizmarts\MailChimp\Controller\Adminhtml\Stores\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#11 WeltPixel\Backend\Plugin\Utility->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#12 Ebizmarts\MailChimp\Controller\Adminhtml\Stores\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#13 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#14 Ebizmarts\MailChimp\Controller\Adminhtml\Stores\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#15 Ebizmarts\MailChimp\Controller\Adminhtml\Stores\Save\Interceptor->___callPlugins() called at [generated/code/Ebizmarts/MailChimp/Controller/Adminhtml/Stores/Save/Interceptor.php:32]
#16 Ebizmarts\MailChimp\Controller\Adminhtml\Stores\Save\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:245]
#17 Magento\Framework\App\FrontController->getActionResponse() called at [vendor/magento/framework/App/FrontController.php:212]
#18 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:147]
#19 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#20 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#21 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/m2e/ebay-amazon-magento2/Plugin/HealthStatus/Magento/Framework/App/FrontController.php:81]
#22 Ess\M2ePro\Plugin\HealthStatus\Magento\Framework\App\FrontController->processDispatch() called at [vendor/m2e/ebay-amazon-magento2/Plugin/AbstractPlugin.php:45]
#23 Ess\M2ePro\Plugin\AbstractPlugin->execute() called at [vendor/m2e/ebay-amazon-magento2/Plugin/HealthStatus/Magento/Framework/App/FrontController.php:45]
#24 Ess\M2ePro\Plugin\HealthStatus\Magento\Framework\App\FrontController->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#25 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#26 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#27 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#28 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#29 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#30 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]
