### ISSUE TITLE
Ecommerce Sync not working mailchimp for Magento2.

### ISSUE THREAD

**Issue by trushangsuthartri** [mailchimp/mc-magento2#145]
**Issue Description:**

I have installed ebizmart_mailchimp extension in my magento 2.1.8 and it has many issues. Users are not subscribing well and ecommerce tracking is not working.

While I am checking "cron_schedule" table for "ebizmarts_ecommerce" job it is showing error and cron never get success

Notice: Undefined property: Mailchimp_Ecommerce::$promoCodes in vendor/mailchimp/mc-magento2/Model/Api/PromoRules.php on line 143

I already upgraded extension to 1.0.25 by downloading latest version from git and running setup upgrade command

It was working with 1.0.24 but inconsistance so I have upgraded to 1.0.25 but after upgrade it stop working completely. In many cases email is also not subscribe to mailchimp.

So can you please help me to troubleshoot issue?

Magento CE  ver: 2.1.8
mc-magento2 ver: 1.0.25

**Steps to reproduce:**
When someone place an order it is not going into mailchimp ecommerce.

**Actual and Expected result**
Order data shoulds be there in mailchimp ecommerce.

**Comment by gonzaloebiz** [comment]
Update the ebizmarts/mailchimp-lib

**Comment by dan-ding** [comment]
updating doesn't fix it.

**Comment by gonzaloebiz** [comment]
What version of ebizmarts/mailchimp-lib do you have

**Comment by dan-ding** [comment]
ee 2.1.10, mailchimp/mc-magento2 1.0.25, ebizmarts/mailchimp-lib 3.0.16

**Comment by trushangsuthartri** [comment]
After upgrading mailchimmp library to version 3.0.16 it is giving me error "Requested country is not available." in ebizmarts_ecommerce cron. Can you please reopen ticket and check what is wrong?

I did perform
composer require ebizmarts/mailchimp-lib
composer require mailchimp/mc-magento2 dev-develop

**Comment by gonzaloebiz** [comment]
@trushangsuthartri take a look at #58

**Comment by trushangsuthartri** [comment]
@gonzaloebiz 
We already checked that code and code is up to date as that issue is fixed in previous version and I have 1.0.25

**Comment by dan-ding** [comment]
Can we get this re-opened?

**Comment by gonzaloebiz** [comment]
why?

**Comment by dan-ding** [comment]
Cause we're not seeing commerce data synced? I can open a new ticket for it if you like

**Comment by dan-ding** [comment]
@gonzaloebiz ?

**Comment by gonzaloebiz** [comment]
Open a new ticket, in fact, you use EE not CE

**Comment by dan-ding** [comment]
ok!

**Comment by sam110386** [comment]
i was also getting same error after update ebizmarts/mailchimp-lib ,
I made a temporary fix for this at line # 143 in Ebizmarts\MailChimp\Model\Api\PromoRules.php
I replaced
` $mailchimpRule = $api->ecommerce->promoCodes->getAll($mailchimpStoreId,$ruleId);`
             
with following 

`if(!is_object($api->ecommerce->promoCodes)){continue;}
            $mailchimpRule = $api->ecommerce->promoCodes->getAll($mailchimpStoreId,$ruleId);
            `

Hope it will help someone.

**Comment by tonybluebadger** [comment]
Any update on this?

**Comment by shreddieb** [comment]
@gonzaloebiz I know this is an old / closed ticket, but I am experiencing what appears to be the same or very similar ebizmarts_ecommerce sync error now with newer releases: 
Warning: Invalid argument supplied for foreach()
vendor/mailchimp/mc-magento2/Model/Api/PromoRules.php on line 154

![ebizmarts_ecommerce-error](https://user-images.githubusercontent.com/7809650/74381140-c8aad880-4d9f-11ea-981b-fc652b6c2efe.png)

details:
magento: 2.3.4
ebizmarts/mailchip-lib: 3.0.30
mailchimp/mc-magento2: 102.3.37

Thoughts?
