### ISSUE TITLE
error(s) with ee 2.1.x and 1.025, no commerce syncing

### ISSUE THREAD

**Issue by dan-ding** [mailchimp/mc-magento2#146]
Issue Description:
Cron logs errors about missing columns.
No ecommerce syncing occurs.

Preconditions:
install ee 2.1.x
install this extension

steps to reproduce:
install ee
install this extension
let it run and have customers buy stuff
running ee 2.1.10, mailchimp/mc-magento2 1.0.25, ebizmarts/mailchimp-lib 3.0.16

expected result:
no errors!
commerce data syncs to mailchimp!

actual result:
errors!
no commerce data sync!

Additional information:
see closed tickets
https://github.com/mailchimp/mc-magento2/issues/144
https://github.com/mailchimp/mc-magento2/issues/145

**Comment by gonzaloebiz** [comment]
the issues you refer are clearly different issues.
Please, specify your error

**Comment by dan-ding** [comment]
Well, I couldn't tell you if they are different or related.

I do know that
(a) no commerce data is being sent to mailchimp
(b) there are errors in the cron logs similar to #144 like:
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'websites.rule_id' in 'on clause', query was: SELECT main_table., rule_coupons.code, websites., m4m.* FROM salesrule AS main_table
LEFT JOIN salesrule_coupon AS rule_coupons ON main_table.rule_id = rule_coupons.rule_id AND rule_coupons.is_primary = 1
LEFT JOIN salesrule_website AS websites ON main_table.rule_id = websites.rule_id and website_id = 1
LEFT JOIN mailchimp_sync_ecommerce AS m4m ON m4m.related_id = main_table.rule_id and m4m.type = 'PRL' and m4m.mailchimp_store_id = 'xxx' WHERE (m4m.mailchimp_sync_deleted = 1) AND (main_table.created_in <= '1509512341') AND (main_table.updated_in > '1509512341') LIMIT 100
```

**Comment by dan-ding** [comment]
As to the mailchimp log, I don't see much which appears helpful:

Undefined property: Magento\Customer\Model\Data\Customer::$getDefaultShipping in vendor/mailchimp/mc-magento2/Helper/Data.php on line 610
.... 
Undefined property: Magento\Customer\Model\Data\Customer::$getDefaultBilling in vendor/mailchimp/mc-magento2/Helper/Data.php on line 610

**Comment by dan-ding** [comment]
Duplicate of what?

**Comment by gonzaloebiz** [comment]
see at referred issue #144

**Comment by dan-ding** [comment]
Ok! Great. Do you think that fixes the commerce data as well?

**Comment by dan-ding** [comment]
Ok. I will go over to #145, thanks!
