### ISSUE TITLE
Magento 2.2.1: Changes like "unsubscribe" and "delete" to subscribers in Magento backend aren't synched

### ISSUE THREAD

**Issue by jhruehl** [mailchimp/mc-magento2#147]
Though the initial sync worked fine with two Mailchimp Stores configured for both store views and given lists in our Mailchimp test account, later changes made by backend users in the Magento newsletter backend section aren't synced.

### Preconditions
1. Magento 2.2.1
2. PHP 7.1.12
3. MySQL 5.5.5-10.1.23-MariaDB
4. Ebizmart_MailChimp 1.0.24 extension installed
5. MailChimp extension completely configured for two different store views with webhook enabled
6. Mailchimp lists sync finished (though it says otherwise on the MailChimp account page 'Connected sites")

### Steps to reproduce
1. Unsubscribe a subscribed user 
2. Delete another subscribed user

### Expected result
1. Both changes will be synced with Mailchimp list after the next 5 min cron

### Actual result
1. No changes at all in the Mailchimp list.

### Comments
I found a similar issue with the Magento 1 Mailchimp extension, which was dated around 2014.

Otherwise I looked deeply into the Mailchimp extensions code and saw only plugins for the frontend to make an immediate call to the API, if customers or guests subscribe to the newsletter. There was nothing similar in place for the backend newsletter section. At least nothing that I could figure out that would do the trick.

Maybe you should think about implementing a plugin for the Magento 2 backend newsletter section that does the same trick as in the frontend.

**Comment by gonzaloebiz** [comment]
Please take a look at http://docs.magento.com/m2/ce/user_guide/magento/system-requirements.html
PHP 7.1 is not supported and mysql 5.5 neither

**Comment by jhruehl** [comment]
This has nothing to do with the PHP version. Once the subscriber or customer id is set in the `related_id` column of the `mailchimp_ecommerce`  table, there won't be any syncing of that subscriber/customer anymore, because only subscriber entries, which aren't already related to in that table are synced according to your code.

A solution would be to add an observer to the backend/newsletter-subscriber section, which sends any changes made there via the api to mailchimp or just adds it to the current batch, which will be send to the Mailchimp API every 5 minutes.

**Comment by MaxKonstructive** [comment]
Hey @gonzaloebiz, I am facing a similar issue, Magento 2.1.11, php 7.0.27.

Unsubscribe works both ways.
However, deleting a user in Magento will not change anything in Mailchimp.

Is there a fix planned for this?

**Comment by MaxKonstructive** [comment]
Hi @gonzaloebiz, any update?

**Comment by shreddieb** [comment]
Same issue here. Would expect the unsubscribe / deleted subscriber accounts on the Magento db to sync to Mailchimp list as I have "Enable Two Way Sync" set to "Yes".
I'm on Magento 2.2.3; php 7.0.28
