### ISSUE TITLE
Custom boolean customer attribute not synced correctly to Mailchimp

### ISSUE THREAD

**Issue by kamilszewczyk** [mailchimp/mc-magento2#1474]
## Issue Description

Mapping custom boolean customer attribute into Audience field in Mailchimp works only half-way. Enabling the boolean syncs to Mailchimp, but disabling does not.

### Preconditions

    1. Magento Cloud 2.4.3-p1
    2. mc-magento2 103.4.44.
    3. Custom boolean customer attribute created
    4. Custom text Audience field in Mailchimp list created
    5. New boolean attribute set to the audience field in Magento Mailchimp Configuration -> Customer Fields Mapping

### Steps to reproduce

Open admin
Go to Customers view
Select a customer and edit
Mark new boolean attribute as 1 and save Customer
Wait for sync with Mailchimp and confirm Yes is visible in custom Audience field
Mark the boolean attribute as 0 and save Customer

### Actual and Expected result
    Expected result:
    Custom audience fields set to No
    Actual result:
    Custom audience fields remains as Yes

### Additional information

This is caused by a non strict type condition check in mailchimp/mc-magento2/Helper/Data.php::715
`if ($value) {`
For a boolean attribute the value sent is integer 1 or 0. For the second scenario the value is not passing the simple condition.
Based on the getData definition in magento/framework/DataObject.php::119 when attribute value is not found `null` will be returned which potentially means the bug could be fixed by changing condition to:
`if (!is_null($value)) {`

**Comment by gonzaloebiz** [comment]
Hi @kamilszewczyk 

we will check it and back to you

best

**Comment by gonzaloebiz** [comment]
Thanks @kamilszewczyk for pointing that
