### ISSUE TITLE
Add a button to truncate the error table BUT not to retry the objects with erros

### ISSUE THREAD

**Issue by gonzaloebiz** [mailchimp/mc-magento2#1498]
### Preconditions

    1. Magento CE without sample data is installed.
    2. mc-magento2 installed in a version <= 10x.x.46
    3. magento cron configured and running and wait until the store is completely synched

### Steps to reproduce

    1. Go to the Mailchimp error grid, you can see something like
    
![image](https://user-images.githubusercontent.com/6222792/183907697-4d994e56-edfb-4c1b-987b-837d70213c48.png)

    2. Go to the configuration page of the extension and click on the reset errors button
    
![image](https://user-images.githubusercontent.com/6222792/183908209-da533477-f2b7-4c3e-940d-b188c60b2f15.png)

    3. Wait until the sync runs 

### Actual and Expected result

The sync runs and sends the objects to Mailchimp, and the objects already contain errors and are saved in the error grid.
Need to have an option to truncate the errors table and prevent that the objects will be synced

**Comment by steverobbins** [comment]
This is a good start, but it would be nice if there was a `created_at` column on this table, then a setting/cron to delete anything older than X days.  This table grows to 10GB+ for my site, our admins don't know they need to clear it out, it should be automatic.
