### ISSUE TITLE
Sync only works, if eCommerce is enabled

### ISSUE THREAD

**Issue by jhruehl** [mailchimp/mc-magento2#150]
I was wondering why the sync doesn't work, if the eCommerce option is disabled. So I had to again look into your code and only found one if-clause in `www/app/code/Ebizmarts/MailChimp/Cron/Ecommerce.php`
` if ($this->_helper->getConfigValue(\Ebizmarts\MailChimp\Helper\Data::XML_PATH_ECOMMERCE_ACTIVE, $storeId))`

So. Of cource subscribers aren't synced. Please implement another if-clause to check if Syncing is enabled and eCommerce is not and just copy the code from the existing one into that and remove all processes, which don't concern subscribers.

This would definitely solve the problem (checked it myself) and can be done in less than an hour.

**Comment by gonzaloebiz** [comment]
Thanks for your contribution @jhruehl
