### ISSUE TITLE
Magento 2.1.9: Checkout hangs when enabling Mailchimp extension

### ISSUE THREAD

**Issue by aumayr** [mailchimp/mc-magento2#151]
When enabling the Mailchimp extension, the `.checkout-loader` (spinner image) loads indefinitely on the Checkout page.

There are no JS errors or any other signs of failure, except the spinner not getting removed. When removing it "by hand" (via "Inspect element"), the checkout works correctly. 

I commented-out the call of the `campaigncatcher`-JS to avoid this behaviour, which is the only change in the HTML source the enabling of the Mailchimp extension I could detect: https://github.com/aumayr/mc-magento2/commit/a2314da4c17e50d9f4f99ad78740fcdff50d2571

Did anyone else experience this issue on the Checkout page before?

Magento: 2.1.9
Mailchimp: 1.0.25

**Comment by TimQSO** [comment]
Exact same behaviour here on 2.1.8.

**Comment by gonzaloebiz** [comment]
Hi @aumayr,

check if the file campaigncatcher.min.js is in your pub directory and with the correct permissions.
Be sure to run bin/magento setup:static-content:deploy
And be sure that your webserver is configured correctly (if you use nginx, use the nginx.conf.sample file)

Best

**Comment by aumayr** [comment]
Thanks for the quick reply!

I’ve checked your suggestions. The file is loaded in `<header>` and it has also the right permissions.
I ran the static:deploy command and my apache is correctly configured (also in pub/static folder).

Still the loader on the checkout page doesn’t disappear when the module is enabled.
If it is disabled everything works smoothly.

**Comment by deepak-netwin** [comment]
@aumayr were you able to fix this issue?

**Comment by aumayr** [comment]
@deepak-netwin No, unfortunately not. In the meantime we switched to a different system, not integrating Mailchimp into Magento.

I will close this issue, as it is not relevant to me anymore, but feel free to reopen if this is an issue for someone else.

**Comment by peterjaap** [comment]
We're experiencing this issue as well. It amazes me how many bugs there are in this extension, while I feel the whole running is running Maillchimp. We can't be the only ones running into this issue.

**Comment by peterjaap** [comment]
We've decided to drop Mailchimp as well for now.

**Comment by deepak-netwin** [comment]
@peterjaap @aumayr We did the same and remove mailchimp until they release stable version.

**Comment by gonzaloebiz** [comment]
Hi @peterjaap 

if you share more information about, would be useful.
We have more than 40K installations and 3 reports of this.
Can you be more specific to try to replicate it?

Best

**Comment by alvaialex** [comment]
Im also getting the same issue on checkout page chrome browser.

Firefox is working perfectly.

**Comment by snirouk** [comment]
We are having same problem. Any solution to this issue?
