### ISSUE TITLE
Observer name "sales_order_save_after" is too generic.

### ISSUE THREAD

**Issue by mpvdk** [mailchimp/mc-magento2#1516]
There is an observer named "sales_order_save_after" in etc/adminhtml/events.xml. This name is too generic. Magento merges all observers in a keyed array, so if any have the same name, they override one another. 

Suggested solution:

Rename observer to "mailchimp_sales_order_save_after". Which adheres to the logic all your other observers are named.

**Comment by gonzaloebiz** [comment]
Thanks @mpvdk for pointing that
