### ISSUE TITLE
Guest Abandoned Carts not associating email address at checkout

### ISSUE THREAD

**Issue by SantiParagarino** [mailchimp/mc-magento2#152]
Pre-conditions:
PHP 7.0.17
Magento 2.2.0
MailChimp For Magento 1.0.25

Steps to reproduce:
1. Add items in the cart as a guest
2. Go to the checkout process
3. Enter email address.
4. Go to next input and wait for the loading animation to finish.

Expected result:
Email address is associated to correspondent entry in the quote row.

Actual result:
Nothing happens in the quote row.

Additional Information:
The installation has no other third party extensions.

**Comment by gonzaloebiz** [comment]
Fixed in 2.2.1

**Comment by SantiParagarino** [comment]
Thank you very much @gonzaloebiz
