### ISSUE TITLE
bad address calls for mergevars

### ISSUE THREAD

**Issue by dan-ding** [mailchimp/mc-magento2#154]
Am seeing quite often in logs:

Notice: Undefined property: Magento\Customer\Model\Data\Customer::$getDefaultBilling in /x/vendor/mailchimp/mc-magento2/Helper/Data.php on line 610
 [] []
Notice: Undefined property: Magento\Customer\Model\Data\Customer::$getDefaultShipping in /x/vendor/mailchimp/mc-magento2/Helper/Data.php on line 610
 [] []

ee 2.1.10, mailchimp/mc-magento2 1.0.25, ebizmarts/mailchimp-lib 3.0.16

**Comment by gonzaloebiz** [comment]
Please follow the issue guidelines to report an issue

**Comment by dan-ding** [comment]
@gonzaloebiz seriously? it's a log file with errors being thrown by this extension.
