### ISSUE TITLE
Multi website/stores in magento - mailchimp loads randomly products from stores

### ISSUE THREAD

**Issue by ktsixit** [mailchimp/mc-magento2#1543]
### Preconditions

    1. Magento ver. 2.4.2
    2. ebizmarts/mailchimp-lib 3.0.34
    3. mailchimp/mc-magento2 103.4.44
    4. Integration magento-mailchimp is complete and working. Ecommerce is enabled
    5. Two websites in magento, with one store each

### Steps to reproduce

1. Create a new campaign in mailchimp
2. Insert a Product block
3. Select product by name
4. Product is added to template but has random url. Sometimes from first website, others from second. Default website/store is not taken into consideration by mailchimp

### Actual and Expected result

There should be an option in magento mailchimp extension about multiple websites/stores. I should be able to include/exclude stores. Or at least mailchimp should use the default website/store.

**Comment by gonzaloebiz** [comment]
Hi @ktsixit 

i need some other information.
1 - You have 2 magento stores right? And 2 Mailchimp stores right?
2 - Each magento store point to a different Mailchimp store?
3 - The Mailchimp stores, points to differents audiences or to the same audience?
4 - When you create the campaign, the audience and the maichimp store matches?

When you select the store to specify the product
![image](https://user-images.githubusercontent.com/6222792/186422609-454bf453-2aa2-468a-83cd-a06bb6e08968.png)

And the audience in the campaign 

![image](https://user-images.githubusercontent.com/6222792/186423062-b40b9a7f-e6d7-4e4f-8e16-79d4a32cc99f.png)

5 - You have 2 differents domains for each magento store? keep in mind that Mailchimp doesn't support 2 stores linked to the same domain, if you have 2 stores in the same installation at least you must use a subdomain for each one

Best

**Comment by ktsixit** [comment]
> 

I have two stores in magento, with different domain each. Second store is not used at the moment (it's under construction).

I have created one mailchimp store, in magento. Which looks like this
![Mailchimp-Store-Magento-Admin](https://user-images.githubusercontent.com/2758872/186594885-47841a0f-2ff5-4868-9740-63c634cc9600.png)

In mailchimp though there are two stores available: the store i created and one more auto generated by mailchimp. 
They both use incorrect urls. Actually each one uses the url of the other:
![Untitled-2](https://user-images.githubusercontent.com/2758872/186595952-58a75bb0-a639-4ac2-9311-88eb7f6a8529.jpg)

Adding a second mailchimp store to magento doesn't solve the issue. It just creates a THIRD store.

**Comment by ktsixit** [comment]
I solved this by deleting mailchimp store in magento configuration.
![Configuration-Settings-Stores-Magento-Admin (3)](https://user-images.githubusercontent.com/2758872/186597816-8b1f0beb-5247-4ff0-831a-7824cceb061d.png)
Now there is only one store available in mailchimp, as it should be.
