### ISSUE TITLE
Error when deleting a store

### ISSUE THREAD

**Issue by rafaelstz** [mailchimp/mc-magento2#1544]
<img width="1312" alt="Capture d’écran, le 2022-09-01 à 17 27 48" src="https://user-images.githubusercontent.com/610598/188016500-88c2e5b1-82ec-4339-858d-3058cbc9da11.png">

### Preconditions

    1. Magento CE 2.4.4 with sample data

### Steps to reproduce

Create and try to delete a store.

**Comment by gonzaloebiz** [comment]
Hi @rafaelstz 

apply this fix https://github.com/mailchimp/mc-magento2/issues/1533

Best
