### ISSUE TITLE
"Magento always manage emails" configuration blocking default Magento newsletter confirm email sending

### ISSUE THREAD

**Issue by lytesaber** [mailchimp/mc-magento2#1545]
### Preconditions

- Magento Open Source 2.4.4-p1
- mc-magento2 103.4.46
- System Configuration (Stores > Configuration > Customers > Newsletter > Subscription Options > Need to confirm > Yes)
- System Configuration (Stores > Configuration > Mailchimp > Mailchimp > Mailchimp General Configuration > Enabled > No)
- System Configuration (Stores > Configuration > Mailchimp > Mailchimp > Mailchimp General Configuration > Magento always manage emails > No)

### Steps to reproduce

1. Apply system configuration as outlined in preconditions
2. Subscribe to Magento default newsletter through frontend subscription form OR via customer account newsletter subscriptions view

### Actual and Expected result

Expected result: 
Magento's default newsletter subscription confirm email is sent to the subscribers email address. 

Actual result:
Magento's default newsletter subscription confirm email **IS NOT** sent to the subscribers email address.

### Additional information

Mailchimp's enabled configuration (Stores > Configuration > Mailchimp > Mailchimp > Mailchimp General Configuration > Enabled) value is not being applied correctly. If Enabled = No then Mailchimp should not affect any of Magento's default newsletter sending functionality. In this case above Mailchimp is blocking Magento's default newsletter subscription confirm email from being sent even though Mailchimp is disabled in config.

**Comment by gonzaloebiz** [comment]
Hi @lytesaber 

thanks for pointing that


Best
