### ISSUE TITLE
bad address calls for mergevars redux

### ISSUE THREAD

**Issue by dan-ding** [mailchimp/mc-magento2#155]
# description
Errors logged a multitude of times:
Undefined property: Magento\Customer\Model\Data\Customer::$getDefaultBilling in /x/vendor/mailchimp/mc-magento2/Helper/Data.php on line 610
 [] []
Undefined property: Magento\Customer\Model\Data\Customer::$getDefaultShipping in /x/vendor/mailchimp/mc-magento2/Helper/Data.php on line 610

## preconditions
ee 2.1.10, mailchimp/mc-magento2 1.0.25, ebizmarts/mailchimp-lib 3.0.16

## steps to reproduce
install and use the extension

## expected result
not to have these errors

## actual result
having these errors

**Comment by gonzaloebiz** [comment]
I can't reproduce it.
I try with a clean magento ee 2.1.10 and no problem for me.
Can you specify how to exactly replicate?

**Comment by dan-ding** [comment]
Are you engaging in a dialogue/question here or just closing the issue?

I have no idea how to replicate. It just occurs.
One would think the log would provide a hint.

**Comment by gonzaloebiz** [comment]
We can't fix an issue that we can't replicate.
If you give us more information, such if the customer is registered or is a guest associated to an order, or something more specific to your installation/reallity
With the information that you provide, we can't replicate the issue.
Try to figure, magento is piece of software with thousand of lines of code and a lot of possibilities of configurations, and you can install any kind of extensions. 
M4m self has more than 15k lines
Sometimes is impossible to replicate without detailed instructions.

Best

**Comment by dan-ding** [comment]
Wha...
I have no idea under what conditions it occurs. It just does.
How about we make one up... it occurs when a customer doesn't have any addresses saved. That's my guess.

**Comment by gonzaloebiz** [comment]
I try creating a new customer (only registered and nothing more), and works.

**Comment by springerin** [comment]
Same error on magento 2.1.10 and mailchimp 1.0.23
MailChimpLogger.INFO: Notice: Undefined property: Magento\Customer\Model\Data\Customer::$getDefaultBilling in /var/www/current/vendor/mailchimp/mc-magento2/Helper/Data.php on line 558
[] []
[2018-01-05 10:33:07] MailChimpLogger.INFO: Notice: Undefined property: Magento\Customer\Model\Data\Customer::$getDefaultShipping in /var/www/current/vendor/mailchimp/mc-magento2/Helper/Data.php on line 558
[] []
[2018-01-05 10:33:07] MailChimpLogger.INFO: No such entity with addressId = 
[] []
[2018-01-05 10:33:07] MailChimpLogger.INFO: No such entity with addressId = 
[] []
[2018-01-05 10:33:07] MailChimpLogger.INFO: No such entity with addressId = 
[] []
[2018-01-05 10:33:07] MailChimpLogger.INFO: No such entity with addressId = 
[] []

**Comment by SantiParagarino** [comment]
Hello @springerin , 

Please note the latest version is 1.0.25. I suggest you to update your extension.

Regards.
