### ISSUE TITLE
Cronjobs stuck after a while

### ISSUE THREAD

**Issue by downforce80** [mailchimp/mc-magento2#1568]
## Issue Description
Cronjobs stuck after a while, maybe the second run and trhows an error. 

### Preconditions

    1. Magento CE 2.4.4
    2. Mailchimp v103.4.48 & 103.4.49

### Steps to reproduce

    1. Let magento cronjobs run per schedule

### Actual and Expected result

Expected result:
All cronjobs have run 

Actual result:
Cronjobs get stuck on mailchimp job. Giving following error 

Mailchimp_Error: Resource Not Found for Api Call: https://us1.api.mailchimp.com/3.0/lists//interest-categories?count=200 - The requested resource could not be found. in /data/web/magento2/vendor/ebizmarts/mailchimp-lib/src/Mailchimp.php:245

API Key Invalid for Api Call: https://us1.api.mailchimp.com/3.0/lists/78544f1058/interest-categories?count=200 - Your request did not include an API key.

### Additional information

This error was inside v103.4.48 we have updated the latest Mailchimp module in staging env nevertheless this error is still coming.

**Comment by gonzaloebiz** [comment]
Hi @downforce80 

be sure that all the stores that have the extension enabled has an associated Mailchimp store

Best

**Comment by downforce80** [comment]
Installing 103.4.49 solved the issue, there were old job stuck, probably.

**Comment by gonzaloebiz** [comment]
great
