### ISSUE TITLE
ecommerce data not sent/synced in ee

### ISSUE THREAD

**Issue by dan-ding** [mailchimp/mc-magento2#157]
# description
Ecommerce data does not appear to be synced/sent to mailchimp
similar to #145

not really sure what to look at for further information.

## preconditions
ee 2.1.10, mailchimp/mc-magento2 1.0.25, ebizmarts/mailchimp-lib 3.0.16

## steps to reproduce
install and use the extension
place some orders

## expected result
when an order is placed, some data goes to mailchimp;
to have ecomm data synced

## actual result
when an order is placed, no data goes to mailchimp;
no ecomm data synced

**Comment by gonzaloebiz** [comment]
If you have EE, comment this lines https://github.com/mailchimp/mc-magento2/blob/develop/Cron/Ecommerce.php#L177-L180 until we fix the issue with the fields names.

Best

**Comment by dan-ding** [comment]
Hey @gonzaloebiz I get that you think that the issue is fixed or addressed in some manner, however could you maybe not close the issue before there's a chance to try it out and reply? Closing right away comes across a bit dismissive and makes it unclear to resolving. Thanks.
Will let you know how the changes go.

**Comment by dan-ding** [comment]
removing those lines appears to allow ecomm data to be synced on ee (along with changes https://github.com/mailchimp/mc-magento2/issues/144#issuecomment-349442207)
