### ISSUE TITLE
javascript campaigncatcher.js returns 404

### ISSUE THREAD

**Issue by nelero** [mailchimp/mc-magento2#1570]
Mailchimp v103.4.49 
Magento CE 2.4.3
When loading front office pages, a javascript file is not found in theme folder : campaigncatcher.js 

Expected result : 
no error and file deployed

Actual result : 
file is not deployed and returns 404 not found

I've done again the following steps : 
bin/magento setup:uprade
bin/magento setup:di:compile
bin/magento setup:static-content:deploy en_US fr_FR -s -f
bin/magento c:c

but without success

**Comment by gonzaloebiz** [comment]
Hi @nelero 

remove the pub/static content and retry

Best

**Comment by nelero** [comment]
Hi @gonzaloebiz 
Thanks for your quick reply.
Unfortunately, removing pub/static content and deploying static content didn't solve the 404 issue.
Can you reopen the issue ?
Regards,

**Comment by nelero** [comment]
In fact, file is deployed in /static/frontend/Companytheme/theme_name/fr_FR/Ebizmarts_MailChimp/js/campaigncatcher.js
but it's called in front by /static/frontend/Companytheme/theme_name/fr_FR/campaigncatcher.js (404)
so a fix from Mailchimp seems to be mandatory.
Regards

**Comment by gonzaloebiz** [comment]
Hi @nelero 

the fr is a store view or what?

Best

**Comment by nelero** [comment]
Hi, just my localization
like en_US for default localization on backoffice
So nothing to deal with that (Magento takes care) but it's the end of the path which is incorrect.
The path is stored in config table mailchimp/general/mailchimpjsurl
this path is incorrect because doesn't contain Ebizmarts_MailChimp/js/ whereas require-config.js in web folder contains it

**Comment by gonzaloebiz** [comment]
Hi @nelero 

i set my default localization like this

![image](https://user-images.githubusercontent.com/6222792/189971965-6b830f77-e2bd-4e12-af43-71f865324104.png)

run
```
bin/magento setup:static-content:deploy en_US fr_FR -s -f
bin/magento cache:flush
```

Access to my frontend and all looks ok

![image](https://user-images.githubusercontent.com/6222792/189972843-ed2849c2-0f72-4e03-8ffa-024d49100ceb.png)

**Comment by nelero** [comment]
Yes as I said it's not a localization problem. I was just answering you for
the fr_FR in the URL

**Comment by gonzaloebiz** [comment]
Sorry by i don't understand what your issue is.
I think I already test your case, and work OK, the files are deployed ok and the frontend work as expected.
Contact our support at mailchimp@ebizmarts-desk.zendesk.com to try to help you with more specific data

Best

**Comment by nelero** [comment]
My issue is that mailchimp called a path where the file isn't deployed.
It misses Ebizmarts_MailChimp/js/ in the path (the file is well deployed in that path)
Maybe you could just check in the config table in database what value you're having in mailchimp/general/mailchimpjsurl row.
Quite sure it hasn't updated well when i upgraded mailchimp.
I will reach support.
Thanks
