### ISSUE TITLE
No newsletter confirmation email when mailchimp is installed

### ISSUE THREAD

**Issue by evilprophet** [mailchimp/mc-magento2#158]
After installed mc-magento2 also when extension is disabled in admin panel, Magento doesn't send a confirmation email for the new subscription.

1. Go to My Account > Newsletter Subscriptions.
2. Mark checkbox to sign to the newsletter. Save
3. Mail should be sent but this doesn't happen.
For Unsubscribe works fine.

This was because in: vendor/mailchimp/mc-magento2/Model/Plugin/Subscriber.php
one method set import_mode = true and in this case magento skip mail sending.

```
public function beforeSubscribeCustomerById(
        $subscriber,
        $customerId
    ) {
        $subscriber->loadByCustomerId($customerId);
        $subscriber->setImportMode(true); << this line is a reason
        $storeId = $subscriber->getStoreId();
        if ($this->_helper->isMailChimpEnabled($storeId)) {
            $customer = $this->_customer->getById($customerId);
            $email = $customer->getEmail();
            $mergeVars = $this->_helper->getMergeVars($customer, $email);
            $api = $this->_api;
```

After this small change works:
```
public function beforeSubscribeCustomerById(
        $subscriber,
        $customerId
    ) {
        $subscriber->loadByCustomerId($customerId);
        $storeId = $subscriber->getStoreId();
        if ($this->_helper->isMailChimpEnabled($storeId)) {
            $subscriber->setImportMode(true); << moved to if block
            $customer = $this->_customer->getById($customerId);
            $email = $customer->getEmail();
            $mergeVars = $this->_helper->getMergeVars($customer, $email);
            $api = $this->_api;
```

**Comment by gonzaloebiz** [comment]
Hi @evilprophet 

can you please let us know your magento version and your m4m version?

Best

**Comment by evilprophet** [comment]
Hi @gonzaloebiz 

Magento 2.1.10
mailchimp/mc-magento2 1.0.25

**Comment by gundamkid** [comment]
I got it too,

Magento 2.2
mailchimp/mc-magento2 1.0.27

still don't know what is Import Mode.

Thank you,

**Comment by gonzaloebiz** [comment]
Hi @evilprophet, @gundamkid 

what is your configuration in stores/newsletter/Confirmation Email Sender and in MailChimp in settings/list names and defaults/enable double opt-in

the setImportMode is to tell to magento that never send a confirmation email, if you need to send a confirmation email you must enable double opt-in in mailchimp

best

**Comment by evilprophet** [comment]
@gonzaloebiz Thanks for a hint. I know that setImportMode disabling sending confirmation emails from Magento but I didn't know that this will be sent after enable double opt-in.

IMO import mode should be ignored when MailChimp is installed but disabled.
Now we temporary uninstalled MailChimp so I cannot confirm configuration but I'm almost sure that we didn't use double opt-in

Thanks.

**Comment by gonzaloebiz** [comment]
No news in 9 days, so close the issue

**Comment by dan-ding** [comment]
Can we reopen? :)
I see this a problem on 2.2.x -- 
mailchimp only lets you do so much. some things need to be done with magento.

magento is just as capable of doing a double optin -- no reason to restrict it to mailchimp only. Right?

one could write an beforeplugin which runs after this modules plugin to change that if desired. however I think it'd be better to either have an admin configurable option (send confirmation from mailchimp?) or .... something.
