### ISSUE TITLE
Unsubscribed customer even if its email is subscribed

### ISSUE THREAD

**Issue by paolobattistella** [mailchimp/mc-magento2#1583]
# Preconditions

* Magento EE 2.3.5 without sample data is installed.

# Steps to reproduce

* The user subscribes to the newsletter.
* Then the same user registers to Magento as "logged customer" with the above email address.
* The customer receives the email "Newsletter unsubscription success" from MailChimp
* The customer, registered into Magento, appears as not subscribed to newsletter. The customer into MailChimp is settled as eligle for transactional emails only.

# Actual and Expected result

The module should be check the email addresses already subscribed and set just logged customer as already subscribed.

**Comment by gonzaloebiz** [comment]
Hi @paolobattistella 

what version of the extension do you have?
What is your double opt-in configuration in magento?
![image](https://user-images.githubusercontent.com/6222792/192297123-b24a130e-1124-4528-a557-ecf4f673e0b7.png)
Do you subscribe the customer in the registration process by selecting the "signup for newsletter" field?
![image](https://user-images.githubusercontent.com/6222792/192304411-08a18f94-f4e4-4914-90da-929de2862962.png)

or use the "my account" once you are logged to subscribe?

Best

**Comment by paolobattistella** [comment]
Hi @gonzaloebiz ,

the module version is 101.2.37.
It's not needed to confirm the newsletter subscription.
There is not "newsletter checkbox" into registration form. The customer can subscribe to newsletter into its account.

Thank you
Paolo

**Comment by gonzaloebiz** [comment]
Hi @paolobattistella 

you have a mailchimp version with more than 3 years. Update the extension and try (by the way, if you have magento 2.3.5 you must use the right version which is 101.2.49 take a look at https://github.com/mailchimp/mc-magento2/releases)
We try with Release 101.2.49 and work OK

Best
