### ISSUE TITLE
Errors in API Call

### ISSUE THREAD

**Issue by rossworth** [mailchimp/mc-magento2#159]
Mail chimp API call history shows
PATCH /ecommerce/stores/ | php | 0.012s | Mailchimp4Magento1.0.25 | 3.0 | 

The requested method and resource are not compatible. See the Allow header for this resource's available methods.

**Comment by gonzaloebiz** [comment]
Hi @rossual 

sorry but really i don't understand your issue.
Pelase follow [this guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines) to report an issue.

Best
