### ISSUE TITLE
MailChimp List field not populated in Magento 2

### ISSUE THREAD

**Issue by Weltpixel** [mailchimp/mc-magento2#161]
MailChimp 1.0.25 with Magento 2.1.6 CE - After filling in API credentials, the Mailchimp Lists are not retrieved in Magento 2 Admin. It Just shows a selector with no options. 

**Issue1**
1.Go to Magento 2 admin -> MailChimp -> Configuration -> API and add the API key. 
2. Save credentials.
3. Account credentials will show up but the MailChimp List field is not populated with the lists from MailChimp account. 

![image](https://user-images.githubusercontent.com/6595979/34299312-f20876e8-e72a-11e7-8b05-3eb63fc265ea.png)

**Issue2**
The same issue is encountered when trying to create a new store.
1. Go to Magento 2 Admin -> MailChimp Stores -> Create New Store
2. Select API
3. Select List and you will get the message: "Select first an API key" even though the API key is already selected.

![image](https://user-images.githubusercontent.com/6595979/34299280-cb5d0b58-e72a-11e7-9a37-5ad68cc1efc4.png)

Issue 1&2 may be related as both should retrive the Lists from mailchimp account, based on the API key.

**Comment by gonzaloebiz** [comment]
Hi @Weltpixel 

thanks for your feedback.
The first one is not an issue, the list is filled automatically when you select a MailChimp store. Keep in mind, one MailChimp store has one and only one associated list, once you define a MailChimp store you can't change the associated list. So when you select the MailChimp store the list is unique

For the second one, can you open the developer tool in your browser and take a look at the ajax call and back to us with the result?

Best

**Comment by Weltpixel** [comment]
Hi @gonzaloebiz ,

Thanks for the fast reply. 

Please find below the 2 errors that are shown in the console:
monkeyapikey.js Failed to load resource: the server responded with a status of 404 ()
require.js:141 Uncaught Error: Script error for: monkeyapikey
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:166)
    at HTMLScriptElement.onScriptError (require.js:1681)


![image](https://user-images.githubusercontent.com/6595979/34308311-7c213796-e755-11e7-9b33-6311d36f8f81.png)

**Comment by gonzaloebiz** [comment]
Review if the file exists in your pub/static and if the file permission is right

Best

**Comment by shinesoftware** [comment]
Set the English language in your Admin profile. There is a problem in the JS compilation code and the path of those files are wrong.

**Comment by ecommage** [comment]
there is no file monkeyapikey.js in the source code of the extension mailchimp and in pub/static also.
I have searched where call the file monkeyapikey.js in the extension but don't see anywhere calls to that file. I just wonder why the page calls to that file and how to fix that.

**Comment by gonzaloebiz** [comment]
Hi @longnguyenmagento 

take a look at https://github.com/mailchimp/mc-magento2/blob/develop/view/adminhtml/requirejs-config.js#L14 and https://github.com/mailchimp/mc-magento2/blob/develop/view/adminhtml/web/js/apikey.js

The real file is the last one, monkeyapikey is an alias for this file

Best

**Comment by alevashov** [comment]
Hi 

I had almost identical issue with brand new Magento 2.2.5 install: drop-down to select store list doesn't open.

Browser dev console shows me:

```
Failed to load resource: the server responded with a status of 404 ()
(index):1 Refused to execute script from 'https://www.mydomain.com/pub/static/version1536917370/adminhtml/Magento/backend/en_AU/monkeyapikey.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
/pub/static/version1536917370/adminhtml/Magento/backend/en_AU/mage/apply/main.js:37 Error: Script error for: monkeyapikey
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:166)
    at HTMLScriptElement.onScriptError (require.js:1681)
```

Was able to resolve by disabling extension through CLI, uninstalling extension, switching Magento to developer mode and re-installing the extension with new API key from Mailchimp.

**Comment by captainarmchair** [comment]
Tried above solution to reinstall the mailchimp extension and also keep server in dev mode. Not successful the lists does not get updated and it is not possible to create a new store.

**Comment by hugoruivo** [comment]
Hi,

I had this issue with a fresh Magento 2.3 install. The problem was with the curl call to retrieve the list, it was giving a SSL error. You can fix it by downloading: http://curl.haxx.se/ca/cacert.pem

Then updating / editing you php.ini file:

```
[curl]
curl.cainfo="<FULL PATH TO DOWNLOADED CACERT>/cacert.pem"
openssl.cafile="<FULL PATH TO DOWNLOADED CACERT>/cacert.pem"
```

**Comment by potticus** [comment]
I had the exact same issue.

monkeyapikey.js didnt exist anywhere on the server.

However, simply deleting my browser history / cache solved the problem.

You should always do this after installing new plugins to save you pulling your hair out for hours.

Remember, if something seems illogical, its nearly always a cache issue.
