### ISSUE TITLE
Bad class name

### ISSUE THREAD

**Issue by gonzaloebiz** [mailchimp/mc-magento2#1613]
According to https://github.com/mailchimp/mc-magento2/pull/1599#issuecomment-1324830914

### Steps to reproduce

Install version 10x.x.50 of mailchimp/mc-magento2
Run composer dump-autoload -o
You get this error: Class Ebizmarts\MailChimp\Controller\Adminhtml\Batch\Getresponse located in ./vendor/mailchimp/mc-magento2/Controller/Adminhtml/Batch/GetResponse.php does not comply with psr-4 autoloading standard. Skipping.

**Comment by hostep** [comment]
Thanks for the fix @agustinbv, but shouldn't [the url you call](https://github.com/mailchimp/mc-magento2/blob/develop-2.4/Ui/Component/Batch/Grid/Column/Batches.php#L82) then also change to `mailchimp/batch/getResponse`? (might be wrong, haven't tested it)
