### ISSUE TITLE
Issue with Porto Theme

### ISSUE THREAD

**Issue by antonioste** [mailchimp/mc-magento2#1619]
Hi,
I've a big trouble with latest version of Magento (2.4.5-p1) , latest version of MailChimp (103.4.50 and lib 3.0.35) and latest version of Porto Theme.

After installating and activate frontend show me:

Exception #0 (Magento\Framework\Exception\ValidatorException): Invalid template file: 'subscribe_popup.phtml' in module: 'Ebizmarts_MailChimp' block's name: 'porto_newsletter_popup'

Now the questios is:
How the extension works and what elements of themes it overrides?

I think there is some elements of Subscribe module that be overrides and than the theme not work.

Can someone help me please?

**Comment by gonzaloebiz** [comment]
Hi @antonioste 

thanks for choosing our extension.
The extension is free and open-source, so you can look at the entire code of the extension. The porto theme is not free and we don't have access to the code of the theme.
As per other users that use the porto theme, commenting this entry https://github.com/mailchimp/mc-magento2/blob/develop-2.4/etc/di.xml#L93 will work

Best

**Comment by medspec** [comment]
or copy folder 

Smartwave/porto/Magento_Newsletter/templates/
-- to --
Smartwave/porto_child/Ebizmarts_MailChimp/templates/

worked for me

**Comment by antonioste** [comment]
hello and thanks for your reply.
I tried copying the folder from:

app/design/frontend/Smartwave/porto/Magento_Newsletter

to

app/design/frontendSmartwave/porto_child/Ebizmarts_MailChimp/templates/

In porto_child there was no Ebiz folder, I created it

Then I recompiled magento but the error didn't change.

if I try to change theme, from porto to porto_child or luma I get an error
on lots of database tables.

I've also try to create the directory Ebiz... directly to
app/design/frontend/Smartwave/porto but I get an error on lots of database
tables

Il giorno mar 29 nov 2022 alle ore 15:26 Thuis ***@***.***>
ha scritto:
