### ISSUE TITLE
High MySQL CPU Usage on Ecommerce Sync

### ISSUE THREAD

**Issue by dsimich06** [mailchimp/mc-magento2#162]
Server Conditions
    1. Magento CE 2.1.10
    2. mc-magento2 1.0.24
    3. Production Server

Steps to reproduce
Unknown

Actual and Expected result
Expected:  The following query should complete in a reasonable time.
SELECT `main_table`.*, `m4m`.* FROM `sales_order` AS `main_table` LEFT JOIN `mailchimp_sync_ecommer 

Actual:  There is currently 4 identical queries that have been running from 330 to 3200s and a fifth just started 10 seconds ago.

MySQL server has been restarted because I noticed MySQL was using a lot of CPU.  After the restart, CPU usage was good for a while and then the processes started building up again.  Persistent connections are not enabled.

Edit:
Also, I'm not sure if any data is even being sent to MailChimp because we have never had any orders on the MailChimp dashboard, even though multiple orders have the Chimp in the Magento Orders grid.

**Comment by gonzaloebiz** [comment]
Hi @dsimich06 

thanks for your feedback.
Wheel, this depends on your server size, your server configuration and the amount of data of your magento installation.
Do you have any of this information?

Best

**Comment by dsimich06** [comment]
Right now, it is on a standard single DigitalOcean 8G server.  Eventually, I will be moving the database to a separate server.  MariaDB is the database.  We receive about 30-50 orders per day, so it is a smaller Magento installation.  There are 110 products.  Does that give you the info you were looking for?

**Comment by gonzaloebiz** [comment]
You already look at the table cron_schedule for the job_code =  'ebizmarts_ecommerce'?

**Comment by dsimich06** [comment]
When I run this search, I get 793 results.  Narrowing it down to just tasks with "running" as their status brings the total to 789, which leaves 1 "pending" and 4 "success".  I re-enabled the sync and everything seems to be running smoothly, which is bizarre.  The only change that I made in re-enabling was adding a start date, so perhaps too much data was being sent to Mailchimp.

**Comment by gonzaloebiz** [comment]
You mean the ecommerce first date i think.
What date you put?

**Comment by dsimich06** [comment]
I had put in January 19.  We have again been having significant issues with this module causing the high CPU usage.  We have disabled other modules that might be adding additional information the module is trying to send over and it still causes the high usage. 

Does the module send over all of the order data, or just the value, when it was placed, and whether it was a Mailchimp related transaction or not?

**Comment by gonzaloebiz** [comment]
If you enable the ecommerce, all data for orders are sent, this information is required if you want to use some MailChimp features like automations or revenue

Best
