### ISSUE TITLE
Class Ebizmarts\MailChimp\Controller\Adminhtml\Batch\Getresponse does not comply with psr-4 autoloading standard

### ISSUE THREAD

**Issue by 0xMatt** [mailchimp/mc-magento2#1620]
As the title states, the file gets skipped during compilation.

- Magento Open Source 2.4.5-p1
- PHP 8.1.13 (cli) (built: Nov 22 2022 14:42:07) (NTS gcc x86_64)

Full error:
```
Class Ebizmarts\MailChimp\Controller\Adminhtml\Batch\Getresponse located in ./vendor/mailchimp/mc-magento2/Controller/Adminhtml/Batch/GetResponse.php does not comply with psr-4 autoloading standard. Skipping.
```

Expected result:
No issues when deploying my app.

**Comment by gonzaloebiz** [comment]
See https://github.com/mailchimp/mc-magento2/issues/1613
