### ISSUE TITLE
Question regarding a modified magento store

### ISSUE THREAD

**Issue by OvalMedia** [mailchimp/mc-magento2#1626]
Hi,

I would like to integrate mailchimp with a modified magento 2 store. 

The modification is that an email address can now be used multiple times even on a store level. In order to maintain unique identification of a magento account I added a third field to the customer login (customer no.) so the combination of customer no., email address and the password will point to one particular account.

In order to do that I had to remove the unique constraint of the email field in the customer_entity table. I also plugged into the login process to make the verification with a customer no. work. But other than that the customer handling works as usual in magento 2.

My question is now if you think this could interfere with the synchronization process. Is an email address truly the one identifying and unique attribute. I would guess that if one account with email X subscribes to a newsletter another account with the same address would also be subscribed. It would make sense if it did but I don't want this to go haywire so I thought I better ask.

Thx for any input

**Comment by gonzaloebiz** [comment]
Hi,

this is not the place to make this kind of question, if you have questions or doubts we have a support email to this.
Punctually to your question, in Mailchimp the id of the subscribers is the MD5 hash of the lowercase version of the list member's email address, so your use case is not possible from the Mailchimp perspective

Best
