### ISSUE TITLE
Webhook URL generated from magento ist wrong

### ISSUE THREAD

**Issue by OvalMedia** [mailchimp/mc-magento2#1632]
1. Magento CE 2.4.3-p1
    2. mc-magento2 v103.4.50.

### Steps to reproduce

When creating a webhook from the magento admin the URL of that hook looks like this:
`https://www.example.com/admin/mailchimp/webhook/index/wkey/12345567673456/`

Calling this URL results in a 404 error.

### Actual and Expected result

The correct URL should look like this:
`https://www.example.com/mailchimp/webhook/index/wkey/12345567673456/` (no "admin" in the URL)

I checked by calling this URL in the browser. In the beginning of `Ebizmarts\MailChimp\Controller\WebHook\Index` I just killed the execution with a `die('test')` to see if the proper controller will be accessed.

**Comment by gonzaloebiz** [comment]
As you can see here https://github.com/mailchimp/mc-magento2/blob/develop-2.4/Controller/Adminhtml/Ecommerce/CreateWebhook.php#L71 when you click in the "create webhook" button
![image](https://user-images.githubusercontent.com/6222792/207863415-1805b3a0-ff98-4990-b7b8-0521b4e10f82.png)
You can check check the web URL by adding a line after this line https://github.com/mailchimp/mc-magento2/blob/develop-2.4/Helper/Data.php#L1070 like this:

`$this->log($hookUrl);
`

then click the button and take a look at the var/log/MailChimp.log file
And this is the result

`[2022-12-15T12:46:18.256553+00:00] MailChimpLogger.INFO: http://mc-magento24.local.com/mailchimp/webhook/index/wkey/7eac6b647bc61bf2/
`

As you can see, the URL is OK

Keep in mind that if your site is not public or is password protected, the creation of the webhook will fail.

Best
