### ISSUE TITLE
Error resubscribe to mailchimp

### ISSUE THREAD

**Issue by mohammedTBB** [mailchimp/mc-magento2#1639]
## Issue Description

The clients that unsubscribe from the newsletter cannot resubscribe using the widget of Magento.

### Preconditions

-Magento 2.4.5-p1
-Mailchimp 103.4.50

### Steps to reproduce

1- subscribe to Mailchimp using Magento widget
2- unsubscribe using the link sent to the email
3- resubscribe in Magento widget

### Actual result

Error "This email address is already subscribed." on the top of the page

### Expected result

Resubscribe succesfully

### Additional information

What actually happens is that when someone unsubscribes, will unsubscribe from Mailchimp but not from Magento.
so when you resubscribe this error appears.

**Comment by gonzaloebiz** [comment]
Hi @mohammedTBB 

when the subscriber click in the email link and unsubscribe from your audience, this produces a webhook from Mailchimp to magento.
The webhooks are processed each 5 min (not immediately), so if you try to re-subscribe via magento so fast the most probably is that the integration will return that the email is already subscribed.
They must wait 5 min before re-subscribe, depends on the amount of webhooks you have spending

Best

**Comment by mohammedTBB** [comment]
Hi @gonzaloebiz 

I have unsubscribed using the email link, and I have noticed that I have unsubscribed immediately from Mailchimp,
then I waited 15 mins, monitoring the "ebizmarts_webhooks" in Magento and it shows success, but the email is still subscribed in Magento.

Regards.
