### ISSUE TITLE
script/get url path

### ISSUE THREAD

**Issue by Detzler** [mailchimp/mc-magento2#164]
## URL path

Not able to fetch Mailchimp JS when Magento runs in a subfolder.
The mailchimpjs.js contains the following:

```
require(["jquery"], function ($) {
    $.ajax({
        url: '/mailchimp/script/get',
        type: 'POST',
        dataType: 'json',
        showLoader: false
    }).done(function (data) {
        var imported = document.createElement('script');
        imported.src = data.url;
        document.head.appendChild(imported);

    });
});
```

The url doesn't make usage of the base url parameter

`url: '/mailchimp/script/get',`

### Preconditions

    1. Magento CE 2.2.2 without sample data is installed.
    2. mc-magento2 1.0.25.

### Steps to reproduce

    1. Open any page.

### Actual and Expected result

    Expected result:
    `url: '/my-shop-sub-folder/mailchimp/script/get',`
The url should contain the  base path.

    Actual result:
    `url: '/mailchimp/script/get',`

**Comment by lstellway** [comment]
I opened a pull request ([#172](https://github.com/mailchimp/mc-magento2/pull/172)) to fix the issue.

This is essentially reverting back to the change made in [issues/51](https://github.com/mailchimp/mc-magento2/issues/51), except that now the script will be included in the `head` section. 

Is there a reason this approach wouldn't work?

**Comment by Detzler** [comment]
hey @loganstellway, thanks for your effort but this PR is not satisfiable. I wrote some lines at the PR:
https://github.com/mailchimp/mc-magento2/pull/172#pullrequestreview-92160155

**Comment by maderlock** [comment]
Just a reminder that this should be a GET call, not POST. I've attempted to resurrect the ticket where this was supposed to have been changed.

**Comment by gonzaloebiz** [comment]
Take a look at this https://github.com/mailchimp/mc-magento2/issues/112
