### ISSUE TITLE
Chimpstatic JS 403 Forbidden

### ISSUE THREAD

**Issue by lytesaber** [mailchimp/mc-magento2#1649]
### Preconditions

    1. Magento CE 2.4.5-p1
    2. mc-magento2 103.4.49

### Steps to reproduce

    1. Setup integration in Magento as per guide
    2. Enable popup signup form for Magento 2 connected site in Mailchimp account
    3. Open homepage on frontend
    4. Open browser dev tools / console to view errors

### Actual and Expected result

    Expected result:
    Mailchimp sign up form popup should appear based on settings in Mailchimp
    
    Actual result:
    403 Forbidden error shown in console for https://chimpstatic.com/mcjs-connected/js/users/ js file and no popup shown

### Additional information

Not sure if this issue relates to the other chimpstatic js issue fix in 103.4.50 release?
https://github.com/mailchimp/mc-magento2/issues/1584

**Comment by gonzaloebiz** [comment]
Hi @lytesaber 

yes, in the 103.4.50 you have a button in the admin to fix this
