### ISSUE TITLE
Subscribers get added to other lists when enabling Mailchimp

### ISSUE THREAD

**Issue by Anton-PiercingMania** [mailchimp/mc-magento2#1696]
### Preconditions
We have 3 audiences in MailChimp under 1 account and 3 storeviews in our Magento Store. We want to keep these in sync separately.

- Magento 2.4.5-p1
- Mailchimp v103.4.50 by ebizmarts
- 3 audiences setup in Mailchimp
- 3 separate storeviews in Magento
- Settings configured so that the right list is attached to the right store
- Mailchimp & Magento both have active subscribers (I brought them in sync before trying this)
- Created 3 webhooks for the 3 separate storeviews/lists

So:
Mail list A added to Mailchimp Store "Store A" configured for storeview "domainA.com"
Mail list B added to Mailchimp Store "Store B" configured for storeview "domainB.com"
Mail list C added to Mailchimp Store "Store C" configured for storeview "domainA.com"

For all we created webhooks, they are basically the same (also same endpoint, since it's only storeviews).
F.E.
https://domainA.com/mailchimp/webhook/index/wkey/012503614b304539/
https://domainB.com/mailchimp/webhook/index/wkey/012503614b304539/
https://domainC.com/mailchimp/webhook/index/wkey/012503614b304539/

### Steps to reproduce

1. Create setup like described with 'preconditions'
2. Enable the profiles for the different storeviews
3. Wait for crons to do the work

We kept checking the "mailchimp_webhook_request" table for changes.

### Actual and Expected result

Expected result:
Subscribers would get in sync only with selected storeview / audience. 

Actual result:
Subscribers from different storeviews get mixed in with other audiences. So F.E. customer johndoe@test.com is a subscriber of domainA.com gets also subscribed to domainB.com. Also customers get assigned to store_id = 0 (which isn't a store).

**Comment by gonzaloebiz** [comment]
Look at https://github.com/mailchimp/mc-magento2/issues/1890
