### ISSUE TITLE
Error on Mailchimp Stores Grid

### ISSUE THREAD

**Issue by duckchip** [mailchimp/mc-magento2#170]
## Title
Error in **production environment** on the Mailchimp Stores grid

## Issue Description
When trying to go to the grid of Mailchimp stores I get following error: 
`Warning: Invalid argument supplied for foreach() in /home/xxxxxxxxxx/apps/default/releases/20180103105032/vendor/magento/framework/View/Element/UiComponent/DataProvider/DataProvider.php on line 252
`
### Preconditions
    1. Magento CE 2.1.9
    2. mc-magento2 1.0.25
    3. Three mailchimp stores are pre made 

### Steps to reproduce
1. Go to the grid of the Mailchimp stores
2. See the error 

### Actual and Expected result

1. Go to the grid of the Mailchimp stores
2. See the stores

### Additional information
I only get this issue on production environment. Not on develop

**Comment by blindsight** [comment]
I'm having the same issue. 

**Preconditions**
Magento: 2.1.6.
mc-magento2: 1.0.25

Same steps to reproduce and only in production as well.

**Comment by gonzaloebiz** [comment]
Hi @duckchip 

thanks for your feedback.
I can't reproduce the issue.
Are you sure you run the setup:upgrade, setup:static-content:deploy and cache:clean after install the extension? 
Please double check the permission of the files, perhaps you have a permission issue.
By the way, i don't have something like apps/default/releases/... 

Best

**Comment by gonzaloebiz** [comment]
What version of ebizmarts/mailchimp-lib do you have?

**Comment by duckchip** [comment]
When we deploy, all of " setup:upgrade, setup:static-content:deploy and cache:clean" are executed. 
apps/default/releases/... is our own implementation, so we can keep track of different deployed versions. Sorry for the confusion. 

I'm running on  3.0.16 version of ebizmarts/mailchimp-lib

**Comment by gonzaloebiz** [comment]
As i said, i can't reproduce the issue.
Can you specify more about your configuration and what is your deploy procedure?

Best

**Comment by blindsight** [comment]
Module is installed on local development machine, added to GIT then deployed using the magento 2 capistrano gem. (https://github.com/davidalger/capistrano-magento2)

setup:upgrade, setup:static-content:deploy and cache:clean are all ran during the deployment process.

Local Machine:
CentOS Linux release 7.3.1611 (Core)
PHP 7.0.25

Server:
CentOS release 6.9
PHP 7.0.23
MySql: 5.6.36-82.0

3.0.16 - ebizmarts/mailchimp-lib

**Comment by gonzaloebiz** [comment]
@duckchip 

you also use capistrano to deploy?

@blindsight 

i don't know much about capistrano, sorry.
Looks like some file is missing in your production installation, can you compare both? If the server is the same you can run
`diff --brief -r path_to_dev/vendor/mailchimp/mc-magento2/ pat_to_prod/vendor/mailchimp/mc-magento2/`

**Comment by blindsight** [comment]
@duckchip 

capistrano deploys (checks out GIT repo, runs set and clearing cache commands)

ran `diff --brief -r dev/mailchimp prod/mailchimp` nothing is missing. 

any other ideas?

**Comment by gonzaloebiz** [comment]
I think the only way is debugging the prod installation.
With a standard magento installation (without capistrano) the grid work OK in production mode, so will be useful to other capistrano users if you can debug on this.

Best

**Comment by duckchip** [comment]
@blindsight  We are using Fabric to deploy to production, 
http://www.fabfile.org/

**Comment by duckchip** [comment]
I've set my deploy mode to production on my local project and i got the same error.
