### ISSUE TITLE
Magento2  Data keeps on syncing but but doesn't sync 

### ISSUE THREAD

**Issue by Shreyash1295** [mailchimp/mc-magento2#1703]
**Version**
Magento version 2.4.3
PHP 7.4
Mailchimp 103.4

After Creating a store and trying to sync 

Account Details | Username: ""
Total Member Subscribers: 1
Total List Subscribers: 1Ecommerce 
Data uploaded to MailChimpTotal 
Customers: 0
Total Products: 0
Total Orders: 0
Total Carts: 0
This account is currently syncing

Tried re syncing but this doesn't seem to work 
any solution would help 

Expected Result should be able to get data in mailchimp panel but failed to do so

**Comment by gonzaloebiz** [comment]
You already configure your magento cron? Take a look at https://github.com/mailchimp/mc-magento2/wiki/Mailchimp-Guide-(part-1)-Installation#9configure-your-crontab

Best

**Comment by Shreyash1295** [comment]
Yes configured it seems like i have an issue with Cron but getting an error in ```magento.cron.log```
```PHP Deprecated:  Return type of phpseclib_mcrypt_filter::filter($in, $out, &$consumed, $closing) should either be compatible with php_user_filter::filter($in, $out, &$consumed, bool $closing): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/clients/magento-rnd/magento-playground/magento2.4.4-rnd/vendor/phpseclib/mcrypt_compat/lib/mcrypt.php on line 1107```
Even though the whole setup is working on php 7.4 double checked it

**Comment by gonzaloebiz** [comment]
Sorry, how can we replicate this issue? In our tests we can't replicate
Keep in mind mcrypt was deprecated in php 7.1 and removed in php 7.2 (take a look at https://www.php.net/manual/en/intro.mcrypt.php)
Our extension doesn't use it

Best
