### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages error Installing latest release on magento 2.4.6

### ISSUE THREAD

**Issue by Sharlyll** [mailchimp/mc-magento2#1731]
### Preconditions
Magento 2.4.6-p1
Nginx 1.18
Php 8.2

Other magento requirements observed

### Steps to reproduce
Cd into magento root folder
run the mailchimp magento 2 composer command
composer require mailchimp/mc-magento2:103.4.52

### Actual and Expected result
Got this error:

Running composer update mailchimp/mc-magento2
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires mailchimp/mc-magento2 103.4.52, it is satisfiable by mailchimp/mc-magento2[103.4.52] from composer repo (https://repo.packagist.org) but mailchimp/mc-magento2[1.0.18, ..., 1.3.33, 100.1.34, 101.2.34, 102.3.34, ..., 102.3.43, 103.4.43, ..., 103.4.51] from composer repo (https://repo.magento.com) has higher repository priority. The packages from the higher priority repository do not match your constraint and are therefore not installable. That repository is canonical so the lower priority repo's packages are not installable. See https://getcomposer.org/repoprio for details and assistance.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

    Expected result:
   Installation should be flawless

**Comment by gonzaloebiz** [comment]
Hi @Sharlyll 

this happens when we upload a new version to the marketplace, until they put live the new version.

Best
