### ISSUE TITLE
Order sync stopped after upgrade. Error in cron log related to bundle product.

### ISSUE THREAD

**Issue by Garde85** [mailchimp/mc-magento2#1755]
### Preconditions

    1. Magento CE 2.4.5-p3
    2. mc-magento2 103.4.53.

### Steps to reproduce

After mailchimp module upgrade I see that ordres checked out after system deploy are not marked as "Sync" in product listing, but they were in status "Resync".

### Actual and Expected result

    Expected result:

   Order are synked

    Actual result:

   Order are Resync

### Additional information

I found these error on var/log/cron.log, every time that mailchimp cron was execute:

`[2023-07-24T08:05:11.431438+00:00] main.CRITICAL: Magento\Framework\Validator\Exception: "title" è obbligatorio. Inseriscilo e riprova. in /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Model/AbstractModel.php:720
Stack trace:
#0 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/EntityManager/Observer/BeforeEntitySave.php(33): Magento\Framework\Model\AbstractModel->validateBeforeSave()
#1 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\Framework\EntityManager\Observer\BeforeEntitySave->execute()
#2 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod()
#3 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Event/Manager.php(65): Magento\Framework\Event\Invoker\InvokerDefault->dispatch()
#4 /var/www/www.xxxxx.it/htdocs/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch()
#5 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/EntityManager/EventManager.php(50): Magento\Framework\Event\Manager\Proxy->dispatch()
#6 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/EntityManager/Operation/Update.php(106): Magento\Framework\EntityManager\EventManager->dispatchEntityEvent()
#7 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/EntityManager/EntityManager.php(106): Magento\Framework\EntityManager\Operation\Update->execute()
#8 /var/www/www.xxxxx.it/htdocs/vendor/magento/module-bundle/Model/ResourceModel/Option.php(207): Magento\Framework\EntityManager\EntityManager->save()
#9 /var/www/www.xxxxx.it/htdocs/vendor/magento/module-bundle/Model/Option/SaveAction.php(112): Magento\Bundle\Model\ResourceModel\Option->save()
#10 /var/www/www.xxxxx.it/htdocs/vendor/magento/module-bundle/Model/Product/SaveHandler.php(168): Magento\Bundle\Model\Option\SaveAction->save()
#11 /var/www/www.xxxxx.it/htdocs/vendor/magento/module-bundle/Model/Product/SaveHandler.php(113): Magento\Bundle\Model\Product\SaveHandler->saveOptions()
#12 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/EntityManager/Operation/Update/UpdateExtensions.php(49): Magento\Bundle\Model\Product\SaveHandler->execute()
#13 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/EntityManager/Operation/Update.php(109): Magento\Framework\EntityManager\Operation\Update\UpdateExtensions->execute()
#14 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/EntityManager/EntityManager.php(106): Magento\Framework\EntityManager\Operation\Update->execute()
#15 /var/www/www.xxxxx.it/htdocs/vendor/magento/module-catalog/Model/ResourceModel/Product.php(777): Magento\Framework\EntityManager\EntityManager->save()
#16 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Model\ResourceModel\Product->save()
#17 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callParent()
#18 /var/www/www.xxxxx.it/htdocs/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(58): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}()
#19 /var/www/www.xxxxx.it/htdocs/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(28): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->addCommitCallback()
#20 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->aroundSave()
#21 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}()
#22 /var/www/www.xxxxx.it/htdocs/generated/code/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(32): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callPlugins()
#23 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Model/AbstractModel.php(658): Magento\Catalog\Model\ResourceModel\Product\Interceptor->save()
#24 /var/www/www.xxxxx.it/htdocs/generated/code/Magento/Catalog/Model/Product/Interceptor.php(1706): Magento\Framework\Model\AbstractModel->save()
#25 /var/www/www.xxxxx.it/htdocs/vendor/mailchimp/mc-magento2/Helper/Sync.php(133): Magento\Catalog\Model\Product\Interceptor->save()
#26 /var/www/www.xxxxx.it/htdocs/vendor/mailchimp/mc-magento2/Model/Api/Product.php(671): Ebizmarts\MailChimp\Helper\Sync->saveEcommerceData()
#27 /var/www/www.xxxxx.it/htdocs/vendor/mailchimp/mc-magento2/Model/Api/Product.php(239): Ebizmarts\MailChimp\Model\Api\Product->_updateProduct()
#28 /var/www/www.xxxxx.it/htdocs/vendor/mailchimp/mc-magento2/Model/Api/Product.php(135): Ebizmarts\MailChimp\Model\Api\Product->_markSpecialPrices()
#29 /var/www/www.xxxxx.it/htdocs/vendor/mailchimp/mc-magento2/Cron/Ecommerce.php(212): Ebizmarts\MailChimp\Model\Api\Product->_sendProducts()
#30 /var/www/www.xxxxx.it/htdocs/vendor/mailchimp/mc-magento2/Cron/Ecommerce.php(142): Ebizmarts\MailChimp\Cron\Ecommerce->_processStore()
#31 [internal function]: Ebizmarts\MailChimp\Cron\Ecommerce->execute()
#32 /var/www/www.xxxxx.it/htdocs/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(368): call_user_func_array()
#33 /var/www/www.xxxxx.it/htdocs/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(879): Magento\Cron\Observer\ProcessCronQueueObserver->_runJob()
#34 /var/www/www.xxxxx.it/htdocs/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(840): Magento\Cron\Observer\ProcessCronQueueObserver->tryRunJob()
#35 /var/www/www.xxxxx.it/htdocs/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(280): Magento\Cron\Observer\ProcessCronQueueObserver->processPendingJobs()
#36 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Cron\Observer\ProcessCronQueueObserver->execute()
#37 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Cron\Observer\ProcessCronQueueObserver\Interceptor->___callParent()
#38 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Cron\Observer\ProcessCronQueueObserver\Interceptor->Magento\Framework\Interception\{closure}()
#39 /var/www/www.xxxxx.it/htdocs/generated/code/Magento/Cron/Observer/ProcessCronQueueObserver/Interceptor.php(23): Magento\Cron\Observer\ProcessCronQueueObserver\Interceptor->___callPlugins()
#40 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\Cron\Observer\ProcessCronQueueObserver\Interceptor->execute()
#41 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod()
#42 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Event/Manager.php(65): Magento\Framework\Event\Invoker\InvokerDefault->dispatch()
#43 /var/www/www.xxxxx.it/htdocs/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch()
#44 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/App/Cron.php(86): Magento\Framework\Event\Manager\Proxy->dispatch()
#45 /var/www/www.xxxxx.it/htdocs/vendor/magento/module-cron/Console/Command/CronCommand.php(117): Magento\Framework\App\Cron->launch()
#46 /var/www/www.xxxxx.it/htdocs/vendor/symfony/console/Command/Command.php(255): Magento\Cron\Console\Command\CronCommand->execute()
#47 /var/www/www.xxxxx.it/htdocs/vendor/symfony/console/Application.php(1021): Symfony\Component\Console\Command\Command->run()
#48 /var/www/www.xxxxx.it/htdocs/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand()
#49 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Console/Cli.php(116): Symfony\Component\Console\Application->doRun()
#50 /var/www/www.xxxxx.it/htdocs/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()
#51 /var/www/www.xxxxx.it/htdocs/bin/magento(23): Symfony\Component\Console\Application->run()
#52 {main}

Next Magento\Framework\Exception\CouldNotSaveException: L'opzione non può essere salvata. in /var/www/www.xxxxx.it/htdocs/vendor/magento/module-bundle/Model/Option/SaveAction.php:114
Stack trace:
#0 /var/www/www.xxxxx.it/htdocs/vendor/magento/module-bundle/Model/Product/SaveHandler.php(168): Magento\Bundle\Model\Option\SaveAction->save()
#1 /var/www/www.xxxxx.it/htdocs/vendor/magento/module-bundle/Model/Product/SaveHandler.php(113): Magento\Bundle\Model\Product\SaveHandler->saveOptions()
#2 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/EntityManager/Operation/Update/UpdateExtensions.php(49): Magento\Bundle\Model\Product\SaveHandler->execute()
#3 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/EntityManager/Operation/Update.php(109): Magento\Framework\EntityManager\Operation\Update\UpdateExtensions->execute()
#4 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/EntityManager/EntityManager.php(106): Magento\Framework\EntityManager\Operation\Update->execute()
#5 /var/www/www.xxxxx.it/htdocs/vendor/magento/module-catalog/Model/ResourceModel/Product.php(777): Magento\Framework\EntityManager\EntityManager->save()
#6 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Model\ResourceModel\Product->save()
#7 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callParent()
#8 /var/www/www.xxxxx.it/htdocs/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(58): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}()
#9 /var/www/www.xxxxx.it/htdocs/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(28): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->addCommitCallback()
#10 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->aroundSave()
#11 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}()
#12 /var/www/www.xxxxx.it/htdocs/generated/code/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(32): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callPlugins()
#13 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Model/AbstractModel.php(658): Magento\Catalog\Model\ResourceModel\Product\Interceptor->save()
#14 /var/www/www.xxxxx.it/htdocs/generated/code/Magento/Catalog/Model/Product/Interceptor.php(1706): Magento\Framework\Model\AbstractModel->save()
#15 /var/www/www.xxxxx.it/htdocs/vendor/mailchimp/mc-magento2/Helper/Sync.php(133): Magento\Catalog\Model\Product\Interceptor->save()
#16 /var/www/www.xxxxx.it/htdocs/vendor/mailchimp/mc-magento2/Model/Api/Product.php(671): Ebizmarts\MailChimp\Helper\Sync->saveEcommerceData()
#17 /var/www/www.xxxxx.it/htdocs/vendor/mailchimp/mc-magento2/Model/Api/Product.php(239): Ebizmarts\MailChimp\Model\Api\Product->_updateProduct()
#18 /var/www/www.xxxxx.it/htdocs/vendor/mailchimp/mc-magento2/Model/Api/Product.php(135): Ebizmarts\MailChimp\Model\Api\Product->_markSpecialPrices()
#19 /var/www/www.xxxxx.it/htdocs/vendor/mailchimp/mc-magento2/Cron/Ecommerce.php(212): Ebizmarts\MailChimp\Model\Api\Product->_sendProducts()
#20 /var/www/www.xxxxx.it/htdocs/vendor/mailchimp/mc-magento2/Cron/Ecommerce.php(142): Ebizmarts\MailChimp\Cron\Ecommerce->_processStore()
#21 [internal function]: Ebizmarts\MailChimp\Cron\Ecommerce->execute()
#22 /var/www/www.xxxxx.it/htdocs/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(368): call_user_func_array()
#23 /var/www/www.xxxxx.it/htdocs/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(879): Magento\Cron\Observer\ProcessCronQueueObserver->_runJob()
#24 /var/www/www.xxxxx.it/htdocs/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(840): Magento\Cron\Observer\ProcessCronQueueObserver->tryRunJob()
#25 /var/www/www.xxxxx.it/htdocs/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(280): Magento\Cron\Observer\ProcessCronQueueObserver->processPendingJobs()
#26 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Cron\Observer\ProcessCronQueueObserver->execute()
#27 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Cron\Observer\ProcessCronQueueObserver\Interceptor->___callParent()
#28 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Cron\Observer\ProcessCronQueueObserver\Interceptor->Magento\Framework\Interception\{closure}()
#29 /var/www/www.xxxxx.it/htdocs/generated/code/Magento/Cron/Observer/ProcessCronQueueObserver/Interceptor.php(23): Magento\Cron\Observer\ProcessCronQueueObserver\Interceptor->___callPlugins()
#30 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\Cron\Observer\ProcessCronQueueObserver\Interceptor->execute()
#31 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod()
#32 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Event/Manager.php(65): Magento\Framework\Event\Invoker\InvokerDefault->dispatch()
#33 /var/www/www.xxxxx.it/htdocs/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch()
#34 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/App/Cron.php(86): Magento\Framework\Event\Manager\Proxy->dispatch()
#35 /var/www/www.xxxxx.it/htdocs/vendor/magento/module-cron/Console/Command/CronCommand.php(117): Magento\Framework\App\Cron->launch()
#36 /var/www/www.xxxxx.it/htdocs/vendor/symfony/console/Command/Command.php(255): Magento\Cron\Console\Command\CronCommand->execute()
#37 /var/www/www.xxxxx.it/htdocs/vendor/symfony/console/Application.php(1021): Symfony\Component\Console\Command\Command->run()
#38 /var/www/www.xxxxx.it/htdocs/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand()
#39 /var/www/www.xxxxx.it/htdocs/vendor/magento/framework/Console/Cli.php(116): Symfony\Component\Console\Application->doRun()
#40 /var/www/www.xxxxx.it/htdocs/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()
#41 /var/www/www.xxxxx.it/htdocs/bin/magento(23): Symfony\Component\Console\Application->run()
#42 {main} [] [`

As workaround I commented this lines, on \Ebizmarts\MailChimp\Helper\Sync.php

case \Ebizmarts\MailChimp\Helper\Data::IS_PRODUCT :
                    if ($sent || $error) {
                        $product = $this->productFactory->create()->load($entityId);
                        $product->setSync(true);
                        if ($sent) {
                            $product->setMailchimpSent($sent);
                        }
                        if ($error) {
                            $product->setMailchimpSyncError($error);
                        }
                        $product->save();
                    }
                    break;

And in this way orders restart to syncking.

**Comment by gonzaloebiz** [comment]
Hi @Garde85 

i just try with magento 2.4.5-p3 and php 8.1 in both ways, upgrading from 103.4.51 to 103.4.53 and directly installing 103.4.53 with no problems, so we can't replicate your issue.
Any other information that help us to replicate it?

Best

**Comment by Trio-web** [comment]
Did you have bundle products on your catalog/orders when sync process is run? As you can see in exception log, error seems to concern bundle products.

**Comment by Garde85** [comment]
Did you have bundle products on your catalog/orders when sync process is run? As you can see in exception log, error seems to concern bundle products.

**Comment by gonzaloebiz** [comment]
Yes, the sample data has bundle products

**Comment by gonzaloebiz** [comment]
No news in 1 month, close the issue for now
