### ISSUE TITLE
Upgrade to 103.4.53 caused UPDATE on over 60% of the existing (old) orders

### ISSUE THREAD

**Issue by lbajsarowicz** [mailchimp/mc-magento2#1772]
## Issue Description

My Client has 130.000 orders in their store. As Mailchimp official extension is full of bugs, I decided to upgrade the extension from `103.4.51` to `103.4.53`, which is considered a patch version, thus should not introduce any backwards incompatible changes.

The Data Patch introduced in the scope of release 

https://github.com/mailchimp/mc-magento2/blob/develop-2.4/Setup/Patch/Data/Migrate452.php

Caused update of `80000` out of `130000` orders in the database. As a result, the ERP synchronization queue is already stuck for 2 days.

### Preconditions

1. Regular 103.4.51 to 103.4.53 upgrade.

### Steps to reproduce

A/A

### Actual and Expected result

---

### Additional information

When you introduce changes that affect existing data in the database:

1. Change the minor (second), not patch (third) version number,
2. Make it optional (i.e. as CLI command that Developer needs to call through CLI),
3. Just don't.

**Comment by dverkade** [comment]
This caused issues for several of our customers when deploying to production.
