### ISSUE TITLE
 Deprecated Functionality

### ISSUE THREAD

**Issue by drinkingsouls** [mailchimp/mc-magento2#1783]
## Issue Description

Unable to deploy static content.

Deprecated Functionality: Optional parameter $isMailChimpStoreId declared before required parameter $mailchimpStoreId is implicitly treated as a required parameter in /app/code/Ebizmarts/MailChimp/Model/Api/Result.php on line 77

### Steps to reproduce

Download this repo.
Unzip and install to app/code/Ebizmarts/MailChimp
Run bin/magento setup:static-content:deploy -f

### Actual and Expected result

Expected Result: Should compile correctly
Actual Result: Fails to compile

### Additional information

Temp workaround is to declate $mailchimpStoreId before $isMailChimpStoreId
Line 77 change:
`public function processResponses($storeId, $mailchimpStoreId, $isMailChimpStoreId = false)`

**Comment by gonzaloebiz** [comment]
Hi @drinkingsouls 

what version of the extension are your trying with what version of php?

Best

**Comment by drinkingsouls** [comment]
This was PHP 8.1. 
The default develop when downloading here seems to be Magento 2.3x. Looks like I've downloaded that expecting it to be the latest 2.4x release line.

**Comment by gonzaloebiz** [comment]
Hi @drinkingsouls keep in mind, magento 2.3.x doesn't support php 8.1 ([take a look at](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements.html))

**Comment by drinkingsouls** [comment]
I am aware of this. I mistakenly downloaded the develop 2.3 branch as that is what the default is set to here.
Of my Github experience, the latest version is always the default download option rather than a dated version.
Perhaps the latest version should be set default here.

**Comment by agelospanagiotakis** [comment]
this breaks magento upgrade (2.4.6) with php 8.2

**Comment by gonzaloebiz** [comment]
Hi @agelospanagiotakis what version of the extension do you have?
Keep in mind, this was fixed in version 103.4.57
