### ISSUE TITLE
After Upgrading from 103.4.51 to 103.4.53 all product attributes are re-saved in the store view scope

### ISSUE THREAD

**Issue by andrewdallow** [mailchimp/mc-magento2#1789]
## Issue Description

A client site was upgraded from 103.4.51 to 103.4.53 and after a week or so we noticed product attributes for random products were being re-saved at the store view scope. The products did not previously have attributes saved in this scope. 

Note that ALL product attributes within these products were re-saved at the store view (not just some), excluding attributes that are empty or global attributes. 

We have 2 separate client sites that have experienced the same problem.

I suspect it is related to this change:
* https://github.com/mailchimp/mc-magento2/issues/1714

### Preconditions

1. Magento CE 2.4.5-p4 (also occurs on 2.4.4-p5)
2. mc-magento2 version 103.4.53
3. Store has only 1 store view (single storefront)
4. Have existing products where attributes are only saved in the 'All Stores' Scope only. 
5. Ensure product sync to Mailchimp is enabled

### Steps to reproduce

* Upgrade to version  mc-magento2 version 103.4.53
* Make some changes to a product to trigger a re-sync (not sure if this will cause it)
* After some time, some products suddenly have all attributes saved in the store view scope

### Actual and Expected result

Expected result: 
Products with attributes only saved at the 'All Stores' scope should remain saved at that scope.
Actual result:
Some products suddenly have all attributes saved in the store view scope.

**Comment by tschirmer** [comment]
Was this ever confirmed / solved? We're experiencing the same thing, when products sync into Mailchimp.

**Comment by tschirmer** [comment]
This was reported here
https://github.com/mailchimp/mc-magento2/issues/1758
