### ISSUE TITLE
Unable to register customer - The website with id 2 that was requested wasn't found. Verify the website and try again.

### ISSUE THREAD

**Issue by jomin-jolly** [mailchimp/mc-magento2#1801]
The website with id 2 that was requested wasn't found. Verify the website and try again.

The issue is from this file,
vendor/mailchimp/mc-magento2/Observer/Customer/SaveBefore.php:73

$subscriber->loadBySubscriberEmail($customer->getEmail(), $customer->getStoreId());

this line is using customer storeID but it should be websiteID

function loadBySubscriberEmail requires a website ID

fix,

$subscriber->loadBySubscriberEmail($customer->getEmail(), $customer->getWebsiteId());

**Comment by gonzaloebiz** [comment]
Hi @jomin-jolly 

please follow the [issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)

Best

**Comment by gonzaloebiz** [comment]
close the issue until you follow the [issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)

**Comment by jonathanribas** [comment]
@gonzaloebiz, we are actually having this issue on our live website and our Customer Service can't save customers, I understand you have guidelines but you should leverage for those huge impact cases!

**Comment by gonzaloebiz** [comment]
Install the version 10x.x.56

**Comment by jonathanribas** [comment]
We actually have this issue on 103.4.56

**Comment by gonzaloebiz** [comment]
Need more information, open a new issue with all the required information

Best

**Comment by jonathanribas** [comment]
@gonzaloebiz here you go: https://github.com/mailchimp/mc-magento2/issues/1818
