### ISSUE TITLE
MailChimp Customer Tab Empty

### ISSUE THREAD

**Issue by drinkingsouls** [mailchimp/mc-magento2#1804]
### Preconditions

- Magento 2.4.6-p2
- Mailchimp 103.4.55
- PHP 8x

### Steps to reproduce

- Log in to Magento Dashboard
- Navigate to Customers - All Customers
- Click "Edit" for any customer
- Click on the "MailChimp" tab

### Actual and Expected result

**Expected Result**
Customer MailChimp subscription information is shown.

**Actual Result**
Only the title shows. The rest of the tab content is not shown:

![mc-tab](https://github.com/mailchimp/mc-magento2/assets/45666862/b36a7669-0e7c-4839-9a10-09b39b8b5f54)

**Comment by arronmoss** [comment]
For us this throws an exception

Too few arguments to function Magento\Newsletter\Model\Subscriber\Interceptor::loadByCustomer(), 

1 passed in /home/magento/htdocs/vendor/mailchimp/mc-magento2/Block/Adminhtml/Customer/Edit/Tabs/View/Customer.php on line 58 and exactly 2 expected

**Comment by gonzaloebiz** [comment]
Hi @drinkingsouls,

this is because the page shows only the interest groups and you can select interest groups, if you don't have any interest group we will put a message on this page

@arronmoss take a look at https://github.com/mailchimp/mc-magento2/issues/1802
