### ISSUE TITLE
loadBySubscriberEmail() error on checkout

### ISSUE THREAD

**Issue by HyperC** [mailchimp/mc-magento2#1819]
After updating to the latest version, 103.4.56 (also on 103.4.55), we get an error on the checkout when clients try to continue the the payment provider. When they select a payment method and continue, the error appears. The log shows the following:

`Exception: Magento\Newsletter\Model\Subscriber\Interceptor::loadBySubscriberEmail(): Argument #2 ($websiteId) must be of type int, null given, called in /vendor/mailchimp/mc-magento2/Observer/Customer/SaveBefore.php on line 73`

They only experience this error when they check the checkbox to create an account. 'Guests' can continue without issues.

We are on 2.4.6-p2 and also experienced this issue: https://github.com/mailchimp/mc-magento2/issues/1807
A second deploy also 'fixed' that for us.

**Comment by gonzaloebiz** [comment]
Take a look at https://github.com/mailchimp/mc-magento2/issues/1818 the fix must fix your issue
