### ISSUE TITLE
chimpstatic script not inserted directly into head, so retargeting ads cannot be made

### ISSUE THREAD

**Issue by maderlock** [mailchimp/mc-magento2#182]
Attempting to create a retarget automation in MailChimp, it fails because it cannot detect the connection with the site due to the javascript not being inserted in a standard way.

### Preconditions

    1. Magento CE 2.1.9
    2. mc-magento2 develop branch a757eb3f1ac640d3988095ee489ddf7cb0702bcc
    3. Connected and pushing data. Can see it working from both ends

### Steps to reproduce

Attempt to create a google retarget ad from within MailChimp

### Actual and Expected result

Expected: To be able to create the advert
Actual: A warning is shown "Connect your site - To continue with Google remarketing ads, you’ll need to connect your site with MailChimp." And the advert creation button is disabled. Clicking on this warning takes you to a list of connected sites, which may not have any warnings.

### Additional information

According to MailChimp, because the chimpstatic javascript is not inserted in the standard way (a static script in the head that inserts the javascript from MC), they cannot detect the connection correctly. Currently, this is inserted by getting the endpoint from the API via a Magento controller and then inserting. All of this is mediated via requireJS. And it's all non-standard.

I do not understand why this is a problem, but the issue remains that google ads cannot be created through MailChimp because of this issue.

**Comment by maderlock** [comment]
**MC**
Do you know what line the code was added in order to connect the site to MailChimp?
**Me**
It is done via requireJS, so it's not a single line of code. But I'll dig out how it's included
I think this is what does it:
var imported = document.createElement('script');
imported.src = data.url;
document.head.appendChild(imported);
And the data.url contains: "https://chimpstatic.com/mcjs-connected/js/users/68ded3d0c0e1446b30c769d0c/329ffccbc8a808de3777ab923.js"
**MC**
Okay, taking a look.
**Me**
Looks like the javascript id retrieved from the MC API using the path ecommerce/stores/<store_id> and then getting the URL from the return->connected_site->site_script->url
**MC**
Okay, thanks for your patience while I took a look. In order for our script to work as expected and for our system to be able to recognize it on your site, this code:
<script id="mcjs">!function(c,h,i,m,p){m=c.createElement(h),p=c.getElementsByTagName(h)[0],m.async=1,m.src=i,p.parentNode.insertBefore(m,p)}(document,"script","https://chimpstatic.com/mcjs-connected/js/users/68ded3d0c0e1446b30c769d0c/aec22ef0aa4dc8901bbfee519.js");</script> 

needs to be placed directly on the page source just before the closing </head> tag. If it is added to the site in any other way, we will not be able to detect it.
**Me**
If I add that to the site it'll be including two instances of the javascript. Won't that cause a problem? This is added by the official Magento 2 extension that I pull in directly from github. To be clear, because of the way Ebizmarts have created the extension, retargeting ads cannot be created?
**MC**
We would expect Magento 2 to add that script directly to the site. I am not seeing the script there currently, so this should not create any conflicts. That said, if you do see some conflicts with this, we'd be happy to take a look.
**Me**
I'll pass that back to Ebizmarts, thanks.

**Comment by maderlock** [comment]
Further update: This has to go as the _very last thing before the end of head_ (really, MaiChimp? REally?!)

From their dev:
> Unfortunately, this code does need to be added directly before the closing header tag in order to use Google Remarketing Ads through MailChimp. I definitely understand this isn't ideal for your store's setup and I'm happy to pass this along as feedback to our team.

**Comment by IsaacHoffmann** [comment]
I am running into a very similar issue with a webpack/angular setup deployed to an s3 bucket. The source code correctly forms the tags, but mailchimp seems incapable of detecting it.

**Comment by maderlock** [comment]
Hold tight on this for now, as I manually inserted the code where they requested and that did not resolve the issue. I'll report back here either way, but it looks like support at MC might have been barking up the wrong tree.

**Comment by IsaacHoffmann** [comment]
So I did find a resolution finally. It turns out if you gzip your files it breaks the webhook. We were about to get it to work by just not zipping the index.html (were the script lives), but still zipping everything else.

**Comment by gonzaloebiz** [comment]
@maderlock 

can you please put a log like
`$this->log($storeData):`
after https://github.com/mailchimp/mc-magento2/blob/develop/Helper/Data.php#L805

and let me know the result?

Best

**Comment by gonzaloebiz** [comment]
I think your issue is related to https://github.com/mailchimp/mc-magento2/issues/214

**Comment by maderlock** [comment]
I did have to delete the mailchimp store and create it from the Magento side again before the connection worked. Now it's detected on both sides and retargeting ads can be made. I've removed the frontend javascript of the module and manually inserted the sync code as the last item of <head> as they requested.

**Comment by maderlock** [comment]
So quite possibly I had both this issue and #214.

In the end the only way I could make Mailchimp happy was to insert the code directly into the header template so that it bypassed anything Magento tried to do for ordering - forcing it to be the last element of  <head>. Eurgh.

**Comment by gonzaloebiz** [comment]
Hi @maderlock you try my suggestion?
