### ISSUE TITLE
Mass unsubscribes from audience since connecting MC via extension

### ISSUE THREAD

**Issue by alexjamesbrown** [mailchimp/mc-magento2#1853]
Since installing this extension, there have been around 35,000 unsubscribes from our Mailchimp list.
It feels like this extension is calling MC to unsubscribe?
Is that something it could / would do?

**Comment by gonzaloebiz** [comment]
Please, follow the [issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)
