### ISSUE TITLE
No revenues showing up inside Mailchimp

### ISSUE THREAD

**Issue by OvalMedia** [mailchimp/mc-magento2#1854]
This is not really a bug report so please forgive me.

I have connected a magento 2 store (B2B) to MC and so far everything is working fine except one thing: there are no revenue numbers showing up inside MC. Newsletter have been sent and they do have created orders in magento. I have a couple of orders that have IDs in the field `mailchimp_campaign_id` which I take as an indicator.

Here is the catch: due to special circumstances the store operates with orders that are never being completed. They are always stuck at "processing". I know in the magento world those orders usually do not count as purchases.

So my question is: am I right that this would be the cause for revenue numbers not showing up in MC?

If so: can you point me to the part of the module where I could modify the code so orders with the status "processing" do count as purchases?

Thank you.

**Comment by gonzaloebiz** [comment]
If you have questions about how the extension works, please send us an email to mailchimp@ebizmarts-desk.zendesk.com

Best
