### ISSUE TITLE
User Cannot Register and Subscribe To Newsletter

### ISSUE THREAD

**Issue by sprankhub** [mailchimp/mc-magento2#1859]
### Preconditions

1. Adobe Commerce 2.4.5-p5 without sample data.
2. mc-magento2 103.4.57.
3. Second store under same website set up - store ID does not match website ID.

### Steps to reproduce

1. Navigate to customer account create page.
2. Enter data and check "subscribe to newsletter" checkbox.
3. Click "Create an Account" button.

### Actual and Expected result

Expected result: Customer can register successfully.

Actual result: Customer cannot register. Error is displayed:

    The website with id 2 that was requested wasn't found. Verify the website and try again.

### Additional information

This is pretty much the same as https://github.com/mailchimp/mc-magento2/issues/1818. The issue has not been fixed yet here:

https://github.com/mailchimp/mc-magento2/blob/0e2e6cae34dc45fef08d480b8e24dcc2da962ae2/Observer/Subscriber/SaveAfter.php#L65

**Comment by Albinoty** [comment]
Hello everyone, I have the same problem on 2.4.6-p3 with the version of the extension 103.4.57. 

I've checked the values I have and the error message id is linked to a storeview and not a website.

Example of website/storeviews

| website | ID |
| ----- | ----- |
| my-website | 5 |

| storeview | ID |
| ----- | ----- |
| store_A | 10 |
| store_B | 11 |

````markdown
The website with id 10 that was requested wasn't found. Verify the website and try again.
````

It should be the id from the website and not the storeview. Any idea ?

**Comment by ciroTBB** [comment]
The problem happens to me too

**Comment by ainigma32** [comment]
We are experiencing the same problem on 2.4.6-p3 as well. As @sprankhub mentioned this is is caused by calling the [loadBySubscriberEmail](https://github.com/magento/magento2/blob/2807445b74e4e982b632f29e31343b209b4c984d/app/code/Magento/Newsletter/Model/Subscriber.php#L388) function
As you can see the function signature states the **websiteId** as the second parameter, not the **storeId**

**Comment by Albinoty** [comment]
I created this patch and it works well

````patch
--- Observer/Subscriber/SaveAfter.php	2023-09-12 21:45:59
+++ Observer/Subscriber/SaveAfter.php	2023-11-27 11:06:33
@@ -13,6 +13,7 @@
 namespace Ebizmarts\MailChimp\Observer\Subscriber;

 use Magento\Framework\Event\Observer;
+use Magento\Store\Model\StoreManagerInterface;

 class SaveAfter implements \Magento\Framework\Event\ObserverInterface
 {
@@ -44,7 +45,8 @@
         \Ebizmarts\MailChimp\Model\MailChimpSyncEcommerce $ecommerce,
         \Ebizmarts\MailChimp\Helper\Data $helper,
         \Ebizmarts\MailChimp\Model\Api\Subscriber $subscriberApi,
-        \Magento\Newsletter\Model\SubscriberFactory $subscriberFactory
+        \Magento\Newsletter\Model\SubscriberFactory $subscriberFactory,
+        protected StoreManagerInterface $storeManager
     ) {

         $this->_ecommerce           = $ecommerce;
@@ -61,8 +63,9 @@
         $factory = $this->_subscriberFactory->create();
         $subscriber = $observer->getSubscriber();
         $isCustomer = $subscriber->getCustomerId();
+        $websiteId = $this->storeManager->getStore($subscriber->getStoreId())->getWebsiteId();
         if ($isCustomer) {
-            $subscriberOld = $factory->loadBySubscriberEmail($subscriber->getCustomerId(), $subscriber->getStoreId());
+            $subscriberOld = $factory->loadBySubscriberEmail($subscriber->getCustomerId(), $websiteId);
         }
         if ($this->_helper->isMailChimpEnabled($subscriber->getStoreId())&&$isCustomer&&
             $subscriberOld->getEmail()&&$subscriber->getEmail()!=$subscriberOld->getEmail()) {

````

**Comment by norgeindian** [comment]
This is a really urgent issue, and we're facing it as well.
Even worse, it still appears even if you disable the module in the admin configuration. So the only way to properly fix it would be to remove the whole module again.

**Comment by Albinoty** [comment]
> This is a really urgent issue, and we're facing it as well. Even worse, it still appears even if you disable the module in the admin configuration. So the only way to properly fix it would be to remove the whole module again.

@norgeindian Have you tried to correct the issue with the patch?

**Comment by norgeindian** [comment]
@Albinoty, yes, that seems to work. Thanks a lot for the patch.
