### ISSUE TITLE
Unable to view order grid & customer grid

### ISSUE THREAD

**Issue by luantran1311** [mailchimp/mc-magento2#1861]
After I upgraded from v103.4.51 to v103.4.57, the order & customer grid were not inaccessible.
![image](https://github.com/mailchimp/mc-magento2/assets/19511189/86c980b5-e7fa-41b7-b3bb-58fea1e3fc82)
![image](https://github.com/mailchimp/mc-magento2/assets/19511189/7309b556-cf15-4c6f-8976-33d96a9af444)

I'm using Magento 2.4.6 Community.

**Comment by gonzaloebiz** [comment]
Hi @luantran1311,

send us an email to our support mailchimp@ebizmarts-desk.zendesk.com and we will help you

Best
