### ISSUE TITLE
Trinidad & Tobago country incorrectly synced

### ISSUE THREAD

**Issue by kamilszewczyk** [mailchimp/mc-magento2#1863]
## Issue Description

When a customer has an address with a Trinidad & Tobago country selected, when syncing to Mailchimp the contact information shows USA as the country

### Preconditions

    1. Magento Cloud 2.4.3-p1
    2. mc-magento2 103.4.57.
    3. ADDRESS added as the Audience field
    4. Ecommerce sync enabled

### Steps to reproduce

Register as a customer with an address of Trinidad & Tobago country
Wait/trigger mailchimp sync of new customer

### Actual and Expected result

    Expected result:
    Contact in mailchimp added with Trinidad and Tobago country
    Actual result:
    Contact in mailchimp added with USA country

### Additional information

I'm pretty sure it's cause by the & (&amp;) sign in the Magento country name, when mailchimp expects the "and".
I confirmed it, by hardcoding the country in the customer address data sent to mailchimp to "Trinidad and Tobago" and it has created correct address in mailchimp.
I'm not sure if it'll be enough to do a quick replace of ampersands with "and" keyword - this seems to be working correctly for Trinidad, however I have not tested it for any other countries with ampersands in their names.

**Comment by gonzaloebiz** [comment]
Hi @kamilszewczyk 

try the fix on here https://github.com/mailchimp/mc-magento2/commit/4dfc1689582e54c05d82788a7877f617d3c5546d
We will include this in the next release

Best

**Comment by gonzaloebiz** [comment]
No news in one month, close the issue
