### ISSUE TITLE
Magento 2 Mailchimp Guest customer fields are not sync on Mailchimp

### ISSUE THREAD

**Issue by sumeetmagento** [mailchimp/mc-magento2#1864]
## Title

Magento 2 Mailchimp Guest customer fields are not synced with Mailchimp after order placed.

### Preconditions

We are using Magento 2.4.5-p1 version and the Mailchimp version is 103.4.50

### Steps to reproduce

Except for Guest email other fields are not synced for Guest customers.

### Actual and Expected result

Fields like First Name, Last Name, etc... should be shown resync for Guest customers

### Extra note
Note: Magento 2 Register customer fields are synced with Mailchimp

**Comment by gonzaloebiz** [comment]
Hi @sumeetmagento 

you mean guest customers that never make an order? or they already make an order?

Best

**Comment by gonzaloebiz** [comment]
No news in 3 weeks, close the issue until have any news
