### ISSUE TITLE
Error when runnning Setup:upgrade after installing when table names are prefixed

### ISSUE THREAD

**Issue by msawyers** [mailchimp/mc-magento2#187]
**Issue Description**
Error received when running setup:upgrade on magento after installing version 1.0.26

**Steps to reproduce**
install mc-magento 1.0.26 
run setup:upgrade
magento table names should be prefixed

**Expected Result:**
Setup:upgrade should complete successfully

**Actual Result**
Setup:upgrade fails

Installing data... Upgrading data... SQLSTATE[42S02]: Base table or view not found: 1146 Table 'panel4te_dev.sales_order_grid' doesn't exist, query was: UPDATE `sales_order_grid` AS `G`
 INNER JOIN `sales_order` AS `O` ON O.entity_id = G.entity_id
SET `G`.`mailchimp_flag` = IF(mailchimp_abandonedcart_flag OR mailchimp_campaign_id OR mailchimp_landing_page, 1, 0)

**Comment by gonzaloebiz** [comment]
Please take a look at https://github.com/mailchimp/mc-magento2/issues/184

**Comment by msawyers** [comment]
Thanks
