### ISSUE TITLE
Customer account email address change isn't synched to Mailchimp/

### ISSUE THREAD

**Issue by jhruehl** [mailchimp/mc-magento2#189]
## Issue Description

If a customer changes the email address for his/her account and has a subscriber entry in the Magento 'newsletter_subscriber' table linked via an entry in the 'customer_id' row, the given subscriber entry gets updated in the 'newsletter_subscriber' table to the new email address, but the change isn't synced in any way to Mailchimp.

I don't know, if this doesn't happen, if the ecommerce option is enabled, but there is definitly no plugin or observer in the Magento 2 Mailchimp Extension, which handles that case.

### Expected result

Either the subscriber email address change linked with the customer account is synced to Mailchimp via update or replacement
or
it is synced as a new subscriber in Mailchimp and the entry with the old email address is set to unscribed.

### Additional information

This is not a feature, but simply a missed user case, so I guess this counts as a bug.

**Comment by gonzaloebiz** [comment]
Hi @jhruehl 

can you please specify what version of magento and M4M2 do you have?

Best

**Comment by jhruehl** [comment]
Right now we have the 1.0.25 version running, but it works fine with the adjustments I did, so I don't see any need to update to a newer version, because the fixes in 26 and 27 don't really matter in our store right now.

**Comment by gonzaloebiz** [comment]
We strongly recommend update to 1.0.27
