### ISSUE TITLE
"The website with id X that was requested wasn't found. Verify the website and try again"

### ISSUE THREAD

**Issue by KristofersOzolinsMagebit** [mailchimp/mc-magento2#1890]
# Issue Description

The `newsletter_subscriber_save_after` event listener causes this error to be thrown: "The website with id X that was requested wasn't found. Verify the website and try again"

![image](https://github.com/mailchimp/mc-magento2/assets/58505474/c1f8576d-3e4f-4dcd-ad3a-a3fd4fe03243)

The second argument for `Magento\Newsletter\Model\Subscriber` `loadBySubscriberEmail` method is `websiteId` not `storeId`

https://github.com/mailchimp/mc-magento2/blob/590da6c9caac7b4c076233aa0f43f791761162eb/Observer/Subscriber/SaveAfter.php#L65

![image](https://github.com/mailchimp/mc-magento2/assets/58505474/a6d90031-1429-4e59-b408-ef7bb27be6fc)

### Preconditions
Mailchimp 103.4.57
Magento 2.4.3

Happens when the store_id does not match website_id

**Comment by gonzaloebiz** [comment]
Take a look at https://github.com/mailchimp/mc-magento2/issues/1840 the fix will be available next release this week

**Comment by evilprophet** [comment]
@gonzaloebiz I'm not sure if this bug is properly fixed because you are using customerId in the method which loading subscriber by email
```$subscriberOld = $factory->loadBySubscriberEmail($subscriber->getCustomerId(), $subscriber->getStoreId()); ```

**Comment by gonzaloebiz** [comment]
Hi @evilprophet 

you are right, my fault, working in a fix

Thanks
