### ISSUE TITLE
Error etc/adminhtml/system.xml is invalid

### ISSUE THREAD

**Issue by mohammedTBB** [mailchimp/mc-magento2#1904]
Hi,

We have encountered an error when throwing command "php bin/magento setup:upgrade"
mailchimp/mc-magento2 103.4.58
magento 2.4.6-p4

The XML in file "vendor/mailchimp/mc-magento2/etc/adminhtml/system.xml" is invalid:
Element 'size': This element is not expected.
Line: 236

Verify the XML and try again.

**Comment by gonzaloebiz** [comment]
Hi @mohammedTBB 

ohh thanks, my fault

Thanks

**Comment by azambon** [comment]
@gonzaloebiz Sorry to post in a closed issue, but I have the same error with Magento 2.3.7-p2
Any chance you could also apply the same fix to the 2.3 branch?

**Comment by gonzaloebiz** [comment]
Hi @azambon sorry, will be available in the next version

**Comment by azambon** [comment]
Thank you very much @gonzaloebiz !
