### ISSUE TITLE
 Order Sync for eCommerce data fails to acknowledge and loops through orders with deleted products

### ISSUE THREAD

**Issue by MaxKonstructive** [mailchimp/mc-magento2#195]
## Issue Description

The constant on the number in a batch on the Order Api is 50.
If you have over 50 test orders where the products do no exist in Magento, the sync will cycle through them without marking them as complete or failed.
Every time the job will loop through the same failed orders, not updating any order data after them.
Therefore no orders will be synced if this limit is met by test orders / orders with a deleted product.

### Preconditions

50 Orders with a product that does not exist anymore

### Steps to reproduce

50 Orders with a product that does not exist anymore, notice that no other orders are sent to Mailchimp.

There is a 'Requested product doesn't exist' thrown in the logs and it skips to the next order.

### Actual and Expected result

Actual : Each job loops through the same 50 failed orders.
Expected : Failed orders should either be skipped in the batch count or marked as failed so they do not appear in the next sync job / query.

### Additional information

There is a query which gets these orders, if the sync has failed on a order it should be excluded from this query. (With possibly a mass action to reenable them).

**Comment by gonzaloebiz** [comment]
Hi @MaxKonstructive 

can you please specify what version of magento and M4M2 do you have?

Best

**Comment by MaxKonstructive** [comment]
Hey @gonzaloebiz , this was fixed in 1.0.27! 

It was this issue https://github.com/mailchimp/mc-magento2/commit/4a9a07207a2e9a6085b321620f6d2ddbbff4746a#diff-fe003b8459a9e927da04573571610777

Cheers

Max
