### ISSUE TITLE
Update Customer Data (names)

### ISSUE THREAD

**Issue by MaxKonstructive** [mailchimp/mc-magento2#196]
## Issue Description

Magento doesn't update customers names in Mailchimp.

### Preconditions

1. Magento CE 2.1.1 linked to a Mailchimp list using mailchimp/mc-magento2 module 1.0.25
2. Have a with an account in Magento linked to an Account in Mailchimp

### Steps to reproduce

Updated first or last name of a customer in Magento admin.

### Actual and Expected result

Actual result : Mailchimp name is not updated
Expected result : Mailchimp updated to match customers name

**Comment by gonzaloebiz** [comment]
Please follow the [issue report guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)

**Comment by MaxKonstructive** [comment]
Hey @gonzaloebiz, is this ok?

Kind regards

**Comment by MaxKonstructive** [comment]
Hi, is there any update surrounding this issue?

Is it something you intend to fix or should we look for another solution?

**Comment by gonzaloebiz** [comment]
This issue was fixed in 1.0.27

Best
