### ISSUE TITLE
Abandoned cart email product price has range starting at $0 when using configurable products

### ISSUE THREAD

**Issue by dmatthew** [mailchimp/mc-magento2#197]
## Issue Description

Same issue as https://github.com/mailchimp/mc-magento/issues/153

### Preconditions

    1. Magento CE 2.2.2.
    2. mc-magento2 1.0.27.
    3. MailChimp abandoned Cart functionality is enabled through Magento admin.
    4. Abandoned cart campaign is set up in your MailChimp account. Product prices are included in the email design.

### Steps to reproduce

    1. Add a product to your cart which has a configurable option. (Example: a product with color and size options)
    2. Go to checkout and fill in your email.
    3. Wait for your abandoned cart email to show up in your inbox.

### Actual and Expected result

    Expected result:
    On abandoned cart email, product prices match product prices in Magento cart.
    Actual result:
    Product prices in abandoned cart emails show a range of prices on each product line item like "$0.00 - $15.00".

### Additional information

In Magento, the configurable product does not have a price set but the simple products do.

**Comment by thetrybe** [comment]
This is happening again in the latest version 1.0.32

![download 1](https://user-images.githubusercontent.com/47203732/52088282-9056b300-25ff-11e9-8ed9-95d6c6a60115.png)
![download](https://user-images.githubusercontent.com/47203732/52088283-90ef4980-25ff-11e9-9684-799e26f8d2c2.png)

**Comment by gonzaloebiz** [comment]
Hi @thetrybe 

please take a look at https://github.com/mailchimp/mc-magento2/issues/513

Best
