### ISSUE TITLE
Where are the merge fields to sync/automate magento discount codes with email automation journey?

### ISSUE THREAD

**Issue by Saf98** [mailchimp/mc-magento2#1971]
We have installed the plugin to send automated emails when a customer leaves a product in their basket. So this is an abandoned basket .
However, I want to add the discount code to these emails but without manually copy/paste codes in the email templates.
Why can't we have some merge field for automation?

Preconditions
Adobe Commerce ver. 2.4.5-p7
Mailchimp v103.4.61

Steps to reproduce
Not Applicable

Actual and Expected result
Actual Result. - No option to merge fields

Expected Result - Should have merge fields for variables, for example, discount code, customers name, email, product details held from basket.

Actual Result -
There is no feature

Additional information
The documentation lacks a detailed explanation of how to set up custom fields.

**Comment by gonzaloebiz** [comment]
Hi @Saf98 

The merge fields work only for customer attributes, if you wish to sync a discount code for each customer, add it as a customer attribute and add to the merge fields

Best

**Comment by Saf98** [comment]
> Hi @Saf98 
> 
> The merge fields work only for customer attributes, if you wish to sync a discount code for each customer, add it as a customer attribute and add to the merge fields
> 
> Best

Where can i add a customer attribute?

**Comment by gonzaloebiz** [comment]
You can add it programmatically or with some module
