### ISSUE TITLE
Merge companyname field from guestorders

### ISSUE THREAD

**Issue by iverbunt** [mailchimp/mc-magento2#1978]
Hi,

In our checkout we have a Companyname field which is merge ok with accounts, but with guestorders who also subscribe for our the newsletter the name, address etc are merged/send to Mailchimp, except the Companyname field. Would it be able for guestorders to merge this field as well?

regards
Imre

**Comment by gonzaloebiz** [comment]
Hi @iverbunt 

the merge fields works only for customers

Best
