### ISSUE TITLE
No subscription in mailchimp after customer registration in 2.2.2 B2B

### ISSUE THREAD

**Issue by sippsolutions** [mailchimp/mc-magento2#198]
### Preconditions
    1. Magento Commerce B2B 2.2.2
    2. mc-magento2 1.0.27.

### Steps to reproduce
    1. Register as a new customer / add subscription in customer account area

### Actual and Expected result
     Expected result:
     - You receive an email asking to confirm your subscription sent by MailChimp

     Actual result:
     - You receive an email asking to confirm your subscription sent by Magento
     - Clicking on the confirmation link does not add the customer as a subscriber

**Comment by evilprophet** [comment]
I think that this may be the same/similar issue like here: https://github.com/mailchimp/mc-magento2/issues/158
