### ISSUE TITLE
mailchimp order && customer is not syncing issue

### ISSUE THREAD

**Issue by prabhu123-dev** [mailchimp/mc-magento2#1982]
This is log file error
[2024-07-26 12:01:05] MailChimpLogger.INFO: Notice: Undefined offset: 1649 in /var/www/html/screwman/app/code/Ebizmarts/MailChimp/Helper/Data.php on line 459
 [] []
[2024-07-26 12:01:06] MailChimpLogger.INFO: Generate Carts payload

 public function getMapFields($storeId = null)
    {
        if (!$this->_mapFields) {
            $customerAtt = $this->getBindableAttributes();
            $data = $this->getConfigValue(self::XML_MERGEVARS, $storeId);
            try {
                $data = $this->unserialize($data);
                if (is_array($data)) {
                    foreach ($data as $customerFieldId => $mailchimpName) {
                        $this->_mapFields[] = [
                            'mailchimp' => strtoupper($mailchimpName),
                            'customer_field' => $customerAtt[$customerFieldId]['attCode'],
                            'isDate' => $customerAtt[$customerFieldId]['isDate'],
                            'isAddress' => $customerAtt[$customerFieldId]['isAddress'],
                            'options' => $customerAtt[$customerFieldId]['options']
                        ];
                    }
                }
            } catch (\Exception $e) {
                $this->log($e->getMessage());
            }
        }
        return $this->_mapFields;
    }
    public function getDateFormat()
    {
        return 'm/d/Y';
    }

    /**
     * @param $apiKey
     * @param bool $encrypted
     * @return \Mailchimp
     * @throws \Magento\Framework\Exception\LocalizedException
     */

![image (7)](https://github.com/user-attachments/assets/4e17ef12-f6f2-4447-a224-0cf985fab530)

**Comment by gonzaloebiz** [comment]
Hi @prabhu123-dev 

please. follow the [Issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)
We will re open the issue once you follow it

Best
