### ISSUE TITLE
Possibililty to sync only confirmed customers

### ISSUE THREAD

**Issue by nelero** [mailchimp/mc-magento2#1984]
When on Magento you enable the option to confirm email address, the customer newly created is in "required confirmation" state for email column.
When the customer clicks on the link he has received, the state is now "confirmed".
So it would be great to be able to sync to mailchimp only confirmed customers.

Regards,

**Comment by gonzaloebiz** [comment]
Hi @nelero 

you can set the double opt in in magento like this

![image](https://github.com/user-attachments/assets/b37753d4-6216-49f2-9fa3-fd4a6efaded9)

And the double opt in in mailchimp

![image](https://github.com/user-attachments/assets/d3089dcc-d84c-4c08-a12f-cba2f9a3b0d6)


Best
