### ISSUE TITLE
Unable to edit customer without API key

### ISSUE THREAD

**Issue by t-richards** [mailchimp/mc-magento2#200]
## Preconditions

  1. PHP 7.1.11
  2. Magento CE 2.2.1 without sample data
  3. mc-magento2 1.0.27
  4. mc-magento2 module enabled but _not_ configured (no API key entered, no store connected, etc.)
  5. At least one customer account

## Steps to reproduce

  1. In the admin panel, visit Customers > All Customers
  2. Select a customer and then select the "Edit" option.

##  Expected result:

Customer edit tabs should be shown like normal (account information, addresses, etc.).

## Actual result:

No tabs are shown. An error message is displayed, clobbering nearly the entire edit interface. The error displayed is:

>API Key Invalid : Your API key may be invalid, or you've attempted to access the wrong datacenter.

## Additional information

![screenshot from 2018-02-08 16-44-07](https://user-images.githubusercontent.com/3905798/35999938-6b942c3e-0cef-11e8-882b-18925d250a15.png)

**Comment by gonzaloebiz** [comment]
Hi @t-richards 

thanks for your feedback, we will confirm the issue.

Best

**Comment by gonzaloebiz** [comment]
Hi @t-richards 

i can't replicate the issue.
I try with magento 2.1.10 and magento 2.2.1 following your steps.
If you put more information to replicate it we will re open the issue

Best

**Comment by jehunter** [comment]
I have run into this exact same issue, except my case is a bit strange in the fact that the mc-magento2 extension works fine on our development server where I performed the installation. I saw the issue when I pulled our code repo (with the extension included) to our staging server.

## Preconditions

1. PHP 7.0.25
2. Magento CE 2.1.10 without sample data
3. mc-magento2 1.0.27
4. mc-magento2 module enabled but not configured (no API key entered, no store connected, etc.)
5. At least one customer account

## Steps to Reproduce

1. Create new GIT repo of Magento 2.1.10 with mc-magento2 extension installed.
2. Pull repo to separate but identical server instance and recompile codebase
3. In the admin panel, visit Customers > All Customers
4. Select a customer and then select the "Edit" option.

## Result
No tabs are shown. An error message is displayed, clobbering nearly the entire edit interface. The error displayed is:
   `API Key Invalid : Your API key may be invalid, or you've attempted to access the wrong datacenter.`
