### ISSUE TITLE
loadBySubscriberEmail() error registering customer account via checkout

### ISSUE THREAD

**Issue by vanmelick** [mailchimp/mc-magento2#2000]
Magento 2.4.7-p1
mailchimp/mc-magento2 103.4.62

In the checkout, when a guest customer indicates he wants to create an account, he is not redirected to the payment service provider page. The order is created in Magento, but the customer is NOT created.

Error message in logs:
main.CRITICAL: TypeError: Magento\Newsletter\Model\Subscriber\Interceptor::loadBySubscriberEmail(): Argument #2 ($websiteId) must be of type int, null given, called in /magento-root-folder/vendor/mailchimp/mc-magento2/Observer/Customer/SaveBefore.php on line 72 and defined in /magento-root-folder/generated/code/Magento/Newsletter/Model/Subscriber/Interceptor.php:20

We applied this patch to fix it:
```
--- Observer/Customer/SaveBefore.php	2024-09-09 12:12:12.551523556 +0000
+++ Observer/Customer/SaveBefore.php	2024-09-09 12:14:27.428282120 +0000
@@ -26,6 +26,10 @@
      */
     private $syncHelper;
     /**
+     * @var \Magento\Store\Model\StoreManagerInterface
+     */
+    private $_storeManager;
+    /**
      * @var \Magento\Newsletter\Model\SubscriberFactory
      */
     protected $subscriberFactory;
@@ -38,11 +42,13 @@
     public function __construct(
         \Ebizmarts\MailChimp\Helper\Data $helper,
         SyncHelper $syncHelper,
-        \Magento\Newsletter\Model\SubscriberFactory $subscriberFactory
+        \Magento\Newsletter\Model\SubscriberFactory $subscriberFactory,
+        \Magento\Store\Model\StoreManagerInterface $storeManager
     ) {
         $this->_helper              = $helper;
         $this->syncHelper           = $syncHelper;
         $this->subscriberFactory    = $subscriberFactory;
+        $this->_storeManager = $storeManager;
     }
 
     public function execute(\Magento\Framework\Event\Observer $observer)
@@ -52,7 +58,8 @@
          */
         $customer = $observer->getCustomer();
         $storeId  = $customer->getStoreId();
-        $websiteId = $customer->getWebsiteId();
+        $websiteId = $this->_storeManager->getStore()->getWebsiteId();
+
         if ($this->_helper->getConfigValue(\Ebizmarts\MailChimp\Helper\Data::XML_PATH_ACTIVE)) {
             if ($this->_helper->getConfigValue(\Ebizmarts\MailChimp\Helper\Data::XML_PATH_ECOMMERCE_ACTIVE)) {
                 $mailchimpStoreId = $this->_helper->getConfigValue(
```

However this reverts (in that file) what was merged via https://github.com/mailchimp/mc-magento2/pull/1823

**Comment by gonzaloebiz** [comment]
Hi @vanmelick 

can you please upload some screen shots?
I follow the steps (see the screen shots)

![image](https://github.com/user-attachments/assets/2a5c0f69-76fe-4e41-97b2-1b324efbb245)

![image](https://github.com/user-attachments/assets/031c295b-147e-458e-ae77-6e63dc90ea72)

![image](https://github.com/user-attachments/assets/bd660f15-326f-4374-b73d-1b379f8d076f)

![image](https://github.com/user-attachments/assets/6ab05d83-b3d5-419f-a2d9-8168836608fb)

![image](https://github.com/user-attachments/assets/047a4c77-85d2-4754-9430-1bec0e84aa4f)

And works like a charm

Best
