### ISSUE TITLE
Abandoned cart info is not triggering custom journey or classic automations

### ISSUE THREAD

**Issue by NTimJuist** [mailchimp/mc-magento2#2001]
Magento ver. CE 2.4.4-p2
mailchimp/mc-magento2: "103.4.63"
ebizmarts/mailchimp-lib: "3.0.38"

### Preconditions
Single mailchimp store
Multistore site (4 stores) that both sync to the same mailchimp store.
Magento Mailchimp configuration settings:

![Screenshot 2024-09-11 at 09 49 04](https://github.com/user-attachments/assets/ea523899-6b85-41fa-8a89-8200fdb8cef9)
![Screenshot 2024-09-11 at 09 49 10](https://github.com/user-attachments/assets/1a8ecda4-fe8b-48cf-a14a-5605b3154693)
![Screenshot 2024-09-11 at 09 48 20](https://github.com/user-attachments/assets/b05a533f-f766-4d62-96b8-2e03252bddbb)
![Screenshot 2024-09-11 at 09 48 01](https://github.com/user-attachments/assets/efcc6b06-0db9-43e0-8de1-e3199a5d7042)

Mailchimp classic automation settings:
![Screenshot 2024-09-11 at 10 20 19](https://github.com/user-attachments/assets/0176b886-1491-4a8a-968d-f57db5b17142)

Custom journey setting (paused for the screenshot) only.
![Screenshot 2024-09-11 at 10 23 01](https://github.com/user-attachments/assets/b68b0cde-aa97-4f59-b436-00350a990dc5)

### Actual and Expected result
Expected result:
When placing a product in the cart of a subscribed email adres, then abandoning the cart. I expect to receive an email in the next 6 hours using the classic automation

Or an email from the custom journey
After abandoning the cart for 1 hour + 1 day delay.

Actual result:
No email is sent, subscribers are not placed in the 'contacts started' list.

I looked with mailchimp support and they confirmed it was not a configuration issue on the side of mailchimp.

All other info (orders based on campaigns) and customer data/subscription status IS being synced to mailchimp.

I've tested it with the custom journey and mailchimp classic automation separately too without any difference.

There are no errors in the magento 2 logs.

**Comment by gonzaloebiz** [comment]
Hi @NTimJuist 

please contact our support team at mailchimp@ebizmarts-desk.zendesk.com

Best
