### ISSUE TITLE
Unable to create a Webhook in the admin area to activate "Two Way Sync"

### ISSUE THREAD

**Issue by pierre-jeanbonazzi** [mailchimp/mc-magento2#2014]
Hi, 
I want to add a webhook to my Magento instance so that the ‘Two Way sync’ can take place. When I try to perform this action in the admin section, I get an error.

**Requirements**

    1. Adobe Commerce 2.4.6-p7
    2. mailchimp/mc-magento2 103.4.63
    3. ebizmarts/mailchimp-lib 3.0.38

### Steps to reproduce

Go to the admin section and Mailchimp configuration and click on the ‘Create Webhook’ button.

![image](https://github.com/user-attachments/assets/3878d66d-0157-42ba-b9f9-421dea739cf1)

### Actual and Expected result

**Expected result:**

A success message is displayed and a webhook is created on Magento and linked to the Mailchimp platform.

**Actual result:**

An error message appears and the webhook is never created

![image](https://github.com/user-attachments/assets/376df187-274e-47f4-8204-a417fdf74e19)

### Additional information

After investigating the problem, I was able to find a few clues: 

Everything is fine in this file and in the execute() method [Ebizmarts\MailChimp\Controller\Adminhtml\Ecommerce\CreateWebhook] : 

![image](https://github.com/user-attachments/assets/485982f3-0c9f-43b4-8e38-725449fc352b)

Then everything is fine until you use the add() function in the createWebhook() function [Ebizmarts\MailChimp\Helper\Data] : 

![image](https://github.com/user-attachments/assets/bf10d5b4-728d-468c-b07f-8f7223c907b1)

Then, when you add it using the add() function, everything works fine too [mailchimp-lib\src\Mailchimp\Mailchimp_ListsWebhooks] : 

![image](https://github.com/user-attachments/assets/003667ca-3783-4bc7-b1ec-33f3d673f8b1)

The problem occurs once in the lib file where the call is made: 

![image](https://github.com/user-attachments/assets/31d6507a-0261-4f48-82ff-ae5e66fb82a1)

The error occurs at this point when the url is supposed to be called, i.e. the url : www.magento.com/mailchimp/webhook/index/wkey/xxxxxxxxxxxxxx

and finally, the error I can find when adding a webhook is the following: : 

![image](https://github.com/user-attachments/assets/2d3ed798-8264-417b-875b-9794340225cd)

I understand that the error occurs when the call is made to this url, which means that there's a problem with this access path.

After examining the corresponding controller [Ebizmarts\MailChimp\Controller\WebHook\Index], I can't find any information that might help me.

What is the purpose of this controller? And what does the linked action (the www.magento.com/mailchimp/webhook/index/wkey/xxxxxxxxxxxxxx url) do? 

Thank you in advance for your help and information.

Best regards

**Comment by gonzaloebiz** [comment]
Is your site private or password protected?
You already create the webhook? Look at this

![image](https://github.com/user-attachments/assets/5dcfdb8c-e2d5-49f8-8f6f-db229ca01916)

and be sure that you don't have already the webhook created

Best

**Comment by pierre-jeanbonazzi** [comment]
Hi @gonzaloebiz 

Our site is not password-protected and is not private.

In the “Webhook” section on Mailchimp, I haven't created any webhooks.

![image](https://github.com/user-attachments/assets/6edb8fd5-b400-4c8a-ae80-2859de76dd49)

If I try to force the creation of a webhook via this menu, I also get the error  : 

![image](https://github.com/user-attachments/assets/72e3e99d-20a3-4509-a31b-7c03b8d3b527)

Is the problem related to the controller Ebizmarts\MailChimp\Controller\WebHook\Index ? Could the problem be due to a problem with the POST made by Mailchimp on the callback URL ? Are there any IPs that need to be whitelisted ?

Thanks in advance.

Best regards

**Comment by gonzaloebiz** [comment]
Hi @pierre-jeanbonazzi 

can you please send a ticket to [mailchimp@ebizmarts-desk.zendesk.com](mailto:mailchimp@ebizmarts-desk.zendesk.com) mentioning the issue

Best
