### ISSUE TITLE
Requested product doesn't exist Error 

### ISSUE THREAD

**Issue by msawyers** [mailchimp/mc-magento2#205]
Cron ebizmarts_ecommerce outputs error:
Requested product does not exist.

Version: 1.0.27
Magento: 2.2.1

[2018-02-13 01:30:34] main.CRITICAL: Requested product doesn't exist {"exception":"[object] (Magento\Framework\Exception\NoSuchEntityException(code: 0): Requested product doesn't exist at /home/public_html/uat/dev/vendor/magento/module-catalog/Model/ProductRepository.php:240)"} []

Process to synchronize breaks due to critical error.

**Comment by gonzaloebiz** [comment]
This was fixed in 1.0.26, plase be sure that you are in 1.0.27

**Comment by msawyers** [comment]
HI, I upgraded from Version: 1.0.23 to 1.0.27.
How should I upgrade? should I uninstall before installing new version?
![image](https://user-images.githubusercontent.com/8907629/36517404-e9c847b0-174f-11e8-9b68-8b4967a8b140.png)

**Comment by msawyers** [comment]
[2018-02-22 18:16:28] main.CRITICAL: Requested product doesn't exist {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): Requested product doesn't exist at /home/public_html/vendor/magento/module-catalog/Model/ProductRepository.php:240)"} []

I am seeing where product number 240 exist, I do not understand this error?

![image](https://user-images.githubusercontent.com/8907629/36556701-17b8fd52-17d4-11e8-9a78-598374a71ef4.png)

**Comment by gonzaloebiz** [comment]
@msawyers 

i need a way to reproduce the issue.

Thanks

**Comment by msawyers** [comment]
@gonzaloebiz  what is your recommendation?

**Comment by gonzaloebiz** [comment]
@msawyers 

240 is not the product id, 240 is the line # in the file ;)

**Comment by msawyers** [comment]
@gonzaloebiz I realized that after, how do i find which product the issue is pointing to?

**Comment by gonzaloebiz** [comment]
Debugging

**Comment by gonzaloebiz** [comment]
Close the issue until we you can provide more information

**Comment by benfung3** [comment]
My version 2.2.4,Same problem here.Solved it.
find this php file :
vendor/magento/module-catalog/Ui/DataProvider/Product/Form/Modifier/Related.php
find the code below
                
              $linkedProduct = $this->productRepository->get(
                    $linkItem->getLinkedProductSku(),
                    false,
                    $this->locator->getStore()->getId()
                );
                $data[$productId]['links'][$dataScope][] = $this->fillData($linkedProduct, $linkItem);

and replace above code by this 
                
             if($linkItem->getLinkedProductSku()){
                   $linkedProduct = $this->productRepository->get(
                        $linkItem->getLinkedProductSku(),
                        false,
                        $this->locator->getStore()->getId()
                    );
                    $data[$productId]['links'][$dataScope][] = $this->fillData($linkedProduct, $linkItem);
               }

but my best advise is override this function by add custom module.

**Comment by msawyers** [comment]
Thank you , will try this out.

**Comment by sneha-sukumaran** [comment]
Tried but still the error persists

**Comment by sneha-sukumaran** [comment]
Tried this but did not work.

**Comment by khnaim** [comment]
Issues in version 1.0.28 and 1.0.29 , did you find a solution for this fix ?

**Comment by teamcrisis** [comment]
I'm having this issue as well on v1.0.30. Has anyone find a solution?
