### ISSUE TITLE
Can't send transactional email after update to 1.0.27

### ISSUE THREAD

**Issue by tanolalano** [mailchimp/mc-magento2#208]
PRECONDITION

    1. Magento CE 2.2.2 
    2. mc-magento2 1.0.27.
    3. Apache/2.4.29

Steps to reproduce

After update to the last version (1.0.27) transactional emails send with external provider aren't send anymore.
No error in exception.log or in apache log 
The only error I get in exception.log is:
`
[2018-02-18 13:03:26] main.CRITICAL:  :  {"exception":"[object] (Mailchimp_Error(code: 0):  :  at ......../htdocs/vendor/ebizmarts/mailchimp-lib/src/Mailchimp.php:222)"} []

Any thoughts?
Regards

**Comment by gonzaloebiz** [comment]
Hi @tanolalano 

what version of the ebizmarts/mailchimp-lib do you have?

Best

**Comment by gonzaloebiz** [comment]
One week without news. Close the issue

**Comment by tanolalano** [comment]
Sorry for delay.
ebizmarts/mailchimp-lib 3.0.16

**Comment by gonzaloebiz** [comment]
Can you specify how can we replicate this?

**Comment by AndreyAnd** [comment]
I have it error  in magento 2.2.2    
ebizmarts/mailchimp-lib  "version": "3.0.16"
PHP 7.0.22

In exception.log i have:
main.CRITICAL: Resource Not Found : The requested resource could not be found. {"exception":"[object] (Mailchimp_Error(code: 0): Resource Not Found : The requested resource could not be found. at      /vendor/ebizmarts/mailchimp-lib/src/Mailchimp.php:222)

**Comment by stefanocapitanio** [comment]
Same issue, same configurations (Magento 2.2.3 CE)...

**Comment by sajidunnar** [comment]
Having same issue with Magetnto 2.2.1

[2018-05-11 00:10:04] main.CRITICAL: Resource Not Found : The requested resource could not be found. {"exception":"[object] (Mailchimp_Error(code: 0): Resource Not Found : The requested resource could not be found. at /***/vendor/ebizmarts/mailchimp-lib/src/Mailchimp.php:222)"} []
