### ISSUE TITLE
Notice being thrown in MailChimpLogger.INFO: Notice: Undefined property

### ISSUE THREAD

**Issue by toshz** [mailchimp/mc-magento2#209]
## Issue Description
PHP notice being thrown in mail chimp log file.

### Preconditions

    1. Magento CE 2.1.5 without sample data is installed.
    2. PHP 5.6
    2. mc-magento2 1.0.24.

### Steps to reproduce

Steps for reproducing this are irrelevant.

### Actual and Expected result

PHP notices are being shown in MailChimpLogger.

### Additional information

I think the issue can be reproduced in versions 1.0.24 and 1.0.25 because of this line in \Ebizmarts\MailChimp\Helper\Data::_updateMergeVars:
![method_call_01](https://user-images.githubusercontent.com/31688149/36372877-1731aa94-156f-11e8-971d-cb78aaf94f34.png)

It should be a method call like this:
`$address = $this->_addressRepositoryInterface->getById($customer->{'getDefault' . $type}());`

Adding the missing parentheses for method should fix the issue.

**Comment by gonzaloebiz** [comment]
Hi @toshz 

thanks for your feedback.
Please update the extension, this issue is already fixed.

Best
