### ISSUE TITLE
No Abandoned Cart Data Sent

### ISSUE THREAD

**Issue by maderlock** [mailchimp/mc-magento2#220]
### Preconditions

1. Magento 2.1.9
2. Extension v 1.0.27
3. Store connected (can see both ends)
4. Admin says that everything is synced
5. Ecommerce data says is synced and abandoned carts turned on
6. Abandoned cart series exists and active - was working under MageMonkey

### Steps to reproduce

1. Create cart, add email, abandon cart
2. Run ebizmarts_ecommerce cron job

### Actual Result

1. [Mailchimp_Error]
Resource Not Found : The requested resource could not be found.

### Additional information

When running the cron manually and adding in some extra logging I can see that the error is caused when fetching updates to promo rules:

```
[Mailchimp_Error]
ecommerce/stores/[storeIDredacted]/promo-rules/46/promo-codes: 404 Resource Not Found : The requested resource could not be found.

Exception trace:
 () at .../web-root/vendor/ebizmarts/mailchimp-lib/src/Mailchimp.php:222
 Mailchimp->call() at .../web-root/vendor/ebizmarts/mailchimp-lib/src/Mailchimp/EcommercePromoCodes.php:31
 Mailchimp_EcommercePromoCodes->getAll() at .../web-root/vendor/mailchimp/mc-magento2/Model/Api/PromoRules.php:141
 Ebizmarts\MailChimp\Model\Api\PromoRules->_getModifiedPromoRules() at .../web-root/vendor/mailchimp/mc-magento2/Model/Api/PromoRules.php:85
 Ebizmarts\MailChimp\Model\Api\PromoRules->sendRules() at .../web-root/vendor/mailchimp/mc-magento2/Cron/Ecommerce.php:177
 Ebizmarts\MailChimp\Cron\Ecommerce->_processStore() at .../web-root/vendor/mailchimp/mc-magento2/Cron/Ecommerce.php:124
 Ebizmarts\MailChimp\Cron\Ecommerce->execute() at n/a:n/a
 call_user_func_array() at .../web-root/vendor/magento/framework/App/State.php:171
 Magento\Framework\App\State->emulateAreaCode() at phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Command/System/Cron/RunCommand.php:80
 N98\Magento\Command\System\Cron\RunCommand->execute() at phar:///usr/local/bin/n98-magerun2.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Command/AbstractMagentoCommand.php:437
 N98\Magento\Command\AbstractMagentoCommand->run() at phar:///usr/local/bin/n98-magerun2.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:882
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/n98-magerun2.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Application.php:526
 N98\Magento\Application->doRun() at phar:///usr/local/bin/n98-magerun2.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Application.php:564
 N98\Magento\Application->run() at /usr/local/bin/n98-magerun2.phar:8
```

It does look like there is an error because a promotion stored in the Magento ecommerce table is not found in MailChimp. Is this an exception that should be caught and dealt with?

I can see that after the initial sync there have been no quotes marked with mailchimp abandoned flag.

**Comment by maderlock** [comment]
I put a try catch around the getAll() request which allowed the cron to run, though I still haven't seen any quotes marked over the last 6 weeks, which is odd. I'll continue to look into the abandoned cart issue, which may or may not be related.

**Comment by gonzaloebiz** [comment]
Perhaps your issue is related to the response processing
Take a look at https://github.com/mailchimp/mc-magento2/issues/216 an https://github.com/mailchimp/mc-magento2/issues/210
Apply the corresponding fixes and let me know

Best

**Comment by gonzaloebiz** [comment]
What version of ebizmarts/mailchimp-lib do you have?

**Comment by maderlock** [comment]
Mailchimp module currently running 232db41478d1f199bccd7f4eadffbd63c726689d tracking dev-develop due to some bug fixes I needed that hadn't been in a release
ebizmarts/mailchimp-lib: 3.0.16

**Comment by gonzaloebiz** [comment]
sorry but i don't understand, you have 1.0.26 modified by you or 1.0.27?

**Comment by gundamkid** [comment]
@maderlock I got same issue, 

In my case, data in _mailchimp_sync_ecommerce_ table have some promotion rule that mailchimp didn't have it (i don't know why the proccess sync is corrupted). 

Can you try to call Mailchimp API to get all your promotion rules, and check your database, maybe you can find something.

**Comment by gonzaloebiz** [comment]
No new since feb 26, so close the issue until we see any news

**Comment by gonzaloebiz** [comment]
Related to #208
