### ISSUE TITLE
mailchimp/script/get should use GET rather than POST

### ISSUE THREAD

**Issue by andrewkett** [mailchimp/mc-magento2#224]
### Preconditions

    1. Magento CE 2.2.2
    2. mc-magento2 1.0.27.
    3. PHP 7.1

### Issue Description

The current approach to load in the store config is to first load `static/frontend/Mytheme/default/en_NZ/Ebizmarts_MailChimp/js/mailchimpjs.js` which then returns makes another POST request to mailchimp/script/get to load in a dynamic url. Ideally it wouldn't take 3 requests to load in the dynamic url but if it must be done this way then mailchimp/script/get should at least use GET rather than POST.

The main reason why I am suggesting this is that on my current project mailchimp/script/get is the slowest request made on a page load. This seems kind of crazy given it only returns a few lines of JSON. I want to cache this on our edge but given that it's a POST request it cannot be cached in our CDN. Simply changing the request to GET means the request can be cached significantly improving page load performance. Given no data is actually being POSTed I don't foresee this change causing any issues. 

I realise that this could cause issues if the store id changes but given this would only be a problem if a CDN is set up it is on the developer to configure the CDN to cater for this.

### Expected result:
mailchimp/script/get is loaded with GET request

##Actual result:
mailchimp/script/get is loaded with POST request

**Comment by andrewkett** [comment]
this was mentioned https://github.com/mailchimp/mc-magento2/issues/164 but I couldn't find the referenced ticket

**Comment by andrewkett** [comment]
Sorry just realised this has already been changed in the develop branch. Will this be included in the next release?

**Comment by gonzaloebiz** [comment]
Yes, the fix will be included in the next release, please see at https://github.com/mailchimp/mc-magento2/milestone/5?closed=1
