### ISSUE TITLE
Product update in magento admin is not passed to mailchimp

### ISSUE THREAD

**Issue by rogersv** [mailchimp/mc-magento2#227]
## Issue Description
Product updates are not sent to mailchimp. Changes to price and quantity is not sent after the first sync to mailchimp.

### Steps to reproduce

    1. Create a product
    2. run cron for ebizmarts_ecommerce
    3. Check product data in mailchimp (using the api)
    4. update price or quantity for product inside magento admin.
    5. run cron for ebizmarts_ecommerce again
    6. check product data in mailchimp again. The price and quantity has not changed.

### Actual and Expected result
    
    Expected result:
    Price and quantity should be updated in mailchimp when changed in magento
    Actual result:
    Price and quantity is never changed after the first sync to mailchimp

### Possible solution
$parentIds on line https://github.com/mailchimp/mc-magento2/blob/a14f55a87fe3bad84415f908d5e4b341229cc887/Model/Api/Product.php#L279 
are empty for products with TYPE_SIMPLE. Change the if statement on line https://github.com/mailchimp/mc-magento2/blob/a14f55a87fe3bad84415f908d5e4b341229cc887/Model/Api/Product.php#L269
and add code $variantProducts[] = $product; only for products with type=TYPE_SIMPLE.

**Comment by gonzaloebiz** [comment]
Hi @rogersv 

check it with 1.0.28 version

I will close for now, let me know if the issue persist and will re open the issue

Best
