### ISSUE TITLE
An email address may not be changed once a customer is created.

### ISSUE THREAD

**Issue by danharper83** [mailchimp/mc-magento2#230]
## Issue Description
Mailchimp module is not synching anymore.

### Preconditions

   1. Magento 2.2.3 installed with my data
   2. Magento Mailchimp module 1.0.27
   3. Created mailchimp store
   4. Synched customers to mailchimp
   5. Customer changed email address (maybe this happened I'm not sure)
   6. Mailchimp stopped synching and I get the following errors in the log file.

> An email address may not be changed once a customer is created.

The problem is that it doesn't tell me which user the issue is being caused by or how to solve the problem.

Status on the mailchimp configuration page

> Account Synced since: 2018-02-13

**Comment by gonzaloebiz** [comment]
Take a look at this https://github.com/mailchimp/mc-magento/issues/17

**Comment by danharper83** [comment]
Thank @gonzaloebiz, I already read that but there wasn't a resolution.

I'm not proposing this as a feature I'm searching for a workaround for when it happens or at least better error reporting, I haven't been able to sync the contacts for months and not sure how to resolve it.

Cheers
