### ISSUE TITLE
column "address_address1" does not exist in table "mailchimp_store"

### ISSUE THREAD

**Issue by shenmusam** [mailchimp/mc-magento2#235]
![1520994210 1](https://user-images.githubusercontent.com/37282394/37380089-e5427f94-2771-11e8-9962-c5b72d7e0a58.jpg)
I used the composer to install it，
then ,"php bin/magento setup:upgrade"，The above problems arise

**Comment by gonzaloebiz** [comment]
Hi @shenmusam 

plase follow the [Issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)

Best

**Comment by gonzaloebiz** [comment]
No news in one week.
We will reopen the issue when you update it

Best
