### ISSUE TITLE
Product alerts cron warnings No such entity with customerId

### ISSUE THREAD

**Issue by NiteshKuyate** [mailchimp/mc-magento2#237]
### Preconditions

    1. Magento CE 2.1.5 without sample data is installed.
    2. mc-magento2 1.0.27.
    3. mailchimp-lib 3.0.16
    4. Created mailchimp store.
    5. Synched customers to mailchimp.

### Steps to reproduce

    1. Navigate to Magento admin.
    2. Open All Customers.
    3. Delete Customer.

### Actual and Expected result

Expected result:
No error message email sent by Mailchimp.

Actual result:
We have been getting an error message about 5 emails every hour since early last week. "Product alerts cron warnings No such entity with customerId = 33" @customerservice@domain.com via 
email address(See attached).
[Product Alerts Cron Error - user@domain.com.pdf](https://github.com/mailchimp/mc-magento2/files/1810573/Product.Alerts.Cron.Error.-.user@domain.com.pdf) or see here
https://screenshots.firefox.com/HofyTVPTN2kqfRk1/storage.googleapis.com

We deleted customer with ID 33 from Magento. We also removed all e-mail addresses associated with that customer from Mailchimp. Why would we still be getting e-mails everyday?  
Shouldn’t we be able to delete a customer from Magento without having this happen?

**Comment by centerax** [comment]
@NiteshKuyate Please reach MailChimp support (ecommercehelp@mailchimp.com) since this problem is on the automations system not on the Magento integration. Thanks.

**Comment by NiteshKuyate** [comment]
Thanks for the update.
We already did chat with mailchimp support and they suggested us to contact with you guys.
We will contact them again and let you know.

**Comment by NiteshKuyate** [comment]
@centerax Just discussed with MailChimp support and they are saying The automations are not working properly because the chrons jobs that was created is causing the errors.

Here is the part of chat:
```
---------------------------------------------------------------------------------------------------------------------------
Blauparts Marketing Dept.
We have already posted issue https://github.com/mailchimp/mc-magento2/issues/237
Stefan
To give a little bit more context about the error message that is being sent; it is sent whenever a certain error threshold is being met. And unfortunately, this isn't something we can control from the MailChimp side of things, since the errors are coming from outside of MailChimp. And they would need to be addressed by the developer who created them to prevent the errors.
Blauparts Marketing Dept.
OK. So we should contact ebiz support again?
Did you check the Github link ?
Stefan
Yes, I reviewed the thread in the Github link. I would suggest working with a developer who created the chron jobs since this is outside of MailChimp scope of things.
Whoever set up the calls, would have better knowledge as to what the calls are and how to fix them.
Blauparts Marketing Dept.
But they are saying its happening due to automations which is in scope of MailChimp. Isn't that the thing?
Stefan
The automations are not working properly because the chrons jobs that was created is causing the errors.
This is why I suggested working with a developer who created the chron jobs to find out what the calls are and how to fix it.
Blauparts Marketing Dept.
OK. Thanks!
---------------------------------------------------------------------------------------------------------------------------
```

```
Can you please suggest.

**Comment by centerax** [comment]
Hi @NiteshKuyate, thanks for that update. We have concluded that the issue is not due to cron jobs creating errors. 
That said, we have reached out to the MailChimp Support team on your behalf, and they are more than willing to take another look at this behavior.
They will be reaching out soon to investigate this matter further.

**Comment by NiteshKuyate** [comment]
Thanks for the update.
We have received email by mailchimp support regarding this issue.
They started investigating.

**Comment by ziofonta** [comment]
Hi, how was this issue solved? We are still recieving these emails about product alerts cron warning with "No such entity with customerId = xxxx"  in Magento version 2.4.6-p1 with mailchimp/mc-magento2 version 103.4.51
