### ISSUE TITLE
Abandoned Cart customers not imported into Mailchimp

### ISSUE THREAD

**Issue by stevenlavine** [mailchimp/mc-magento2#238]
### Preconditions
   1. Magento CE 2.2.2
    2. mc-magento2 1.0.25.
    3. Abandoned Cart enabled in backend.
    4. Abandoned Cart campaign setup in MailChimp.

We have installed the MailChimp mc-magento2 extension into our store, however the Abandoned cart functionality is not working. I can see the customer's with abandoned carts in the backend reports section, however no emails are sent to the customer. The subscriber list side of the extension is working. I do have the Mandrill extension working as well.

Any assistance would be appreciated

**Comment by gonzaloebiz** [comment]
Hi @stephenmartin 

are your store already completely synced?
If the store is synced you can view something like:
**Account Synced since: 2018-03-12**
in the Account details of the configuration


By the way, is recommended to update the extension to the current version (1.0.27)

Best

**Comment by stevenlavine** [comment]
sorry it is 1.0.27 looked at a previous version of the extension on my dev environment

**Comment by stevenlavine** [comment]
This is the info I'm getting in account details
Username: ****** *****
Total Subscribers: 3683
Ecommerce Data uploaded to MailChimp
Total Customers: 0
Total Products: 0
Total Orders: 0
Total Carts: 0
This account is currently syncing

**Comment by gonzaloebiz** [comment]
The abandoned cart automation will be starting when the store ends the sync.
You case don't look as an issue, please contact our support team at mailchimp@ebizmarts-desk.zendesk.com

Best
