### ISSUE TITLE
Not getting Abandoned cart emails.

### ISSUE THREAD

**Issue by tousif12** [mailchimp/mc-magento2#239]
I am not getting Abandoned cart emails.
Magento 2.1.8
Mailchimp 1.0.26

As list was not syncing on both sides so I manually ran cron job for it. Now list is sync but not getting any abandoned cart email.

Account info
Username: XXXXX
Total Subscribers: 32892
Ecommerce Data uploaded to MailChimp
Total Customers: 142
Total Products: 28
Total Orders: 7
Total Carts: 45
Account Synced since: 2018-03-14

And on magento side in Reports- > abandoned cart all user how abandoned cart are adding perfectly. So I think I am not getting webhook from magento to mailchimp ? or something like this ?

**Comment by gonzaloebiz** [comment]
Hi @tousif12 

thanks for your feedback.
The webhook is not related on this.
When the customer abandon a cart, the cart is synced to MailChimp and MailChimp never ask to magento for this cart.
Keep in mind, if you create the abandoned cart automation in MailChimp after the cart was synced so this cart will not be sent, only the carts synced after the automation was created will be sent.

Best

**Comment by tousif12** [comment]
Hi Thanks for reply. okay then what may possible issue ?  After appearing   **Account Synced since: 2018-03-14**   .  I abandon cart 5,6 times from diff accounts but still didn't get any email .

**Comment by tousif12** [comment]
@gonzaloebiz   When I run cronjob manually for this module  recently abandonment cart email I got after 1 hour. But If I don't run manually I didn't get trigger :(

**Comment by gonzaloebiz** [comment]
Take a look at core_schedule for job_code = ebizmarts_ecommerce, and check the status, if the status remains running the most probably is that your cron is canceling, typically for the php cli configuration

Best

**Comment by tousif12** [comment]
@gonzaloebiz     Its in pending   like this       ` |          15 | ebizmarts_ecommerce                           | pending | NULL     | 2018-03-15 01:00:57 | 2018-03-15 01:00:00 | NULL        | NULL        |`
. Any idea what may issue ?

**Comment by gonzaloebiz** [comment]
Hi @tousif12 typically this is memory amount issue, look at your cli php.ini and seach for memory_limit 
I close the issue, because this is not an issue in the extension

Best

**Comment by portchris** [comment]
@tousif12 When you say you manually ran a cron task, which one? 

`php bin/magento cron:run --group="ebizmarts_ecommerce"` 

For example?
