### ISSUE TITLE
Error when attempting to edit a customer from the backend

### ISSUE THREAD

**Issue by ebizmarts-keller** [mailchimp/mc-magento2#240]
## Issue Description

When trying to edit a customer from the backend, will get a "Resource Not Found : The requested resource could not be found." and will not be able to edit the customer.

![editcusm2](https://user-images.githubusercontent.com/19838935/37467243-6fb9c796-283e-11e8-91c1-4325570bb40a.png)

### Preconditions

    1. Magento CE 2.2.3 without sample data is installed.
    2. mc-magento2 1.0.27
    
### Steps to reproduce

There is more than one scenario that can cause this, even though it doesn't always happen with that specific scenario, but trying different configurations eventually triggers it.

For example:

**Default scope:** Module Disabled
**Default store view:** Module Disabled
**Store view 2 (on a different website):** Module enabled, with store and list selected. With or without ecommerce enabled.

**Comment by gonzaloebiz** [comment]
closed by https://github.com/mailchimp/mc-magento2/pull/271

**Comment by sjimenez77** [comment]
Still facing the same issue with Magento 2.1.5 and mc-magento2 module version 1.0.29 installed.
