### ISSUE TITLE
Not necessary mailchimp/script/get requests

### ISSUE THREAD

**Issue by wojtekn** [mailchimp/mc-magento2#248]
Recently I reported a bug which was causing `mailchimp/script/get` script connecting to MailChimp API all the time, it is fixed at this point. With that fix this action runs much faster as it doesn't connect to MailChimp API on each request, but I see in New Relic monitoring tool that it is still responsible for about 8% of all transactions. 

What is the reason to load this JavaScript using AJAX request? Wouldn't it work with a standard block which loads value from the stores configuration (or MailChimp API if it's not cached yet) and then renders it into HTML?

**Comment by gonzaloebiz** [comment]
@wojtekn 

thanks for your feedback.
Can you try with the change in the associated commit?

Best

**Comment by wojtekn** [comment]
@gonzaloebiz yes, we tried that on local and it worked fine. Please just remove that debug `echo $url;` line.
