### ISSUE TITLE
After installing Not sending confirmations mail to new subscribers from magento 2

### ISSUE THREAD

**Issue by tousif12** [mailchimp/mc-magento2#250]
I installed mailchimp 1.0.26
Magento 2.1.8 

Now after syncing lists etc , I wanted to just use mailchimp for abandon cart. all things were fine. I mistakenly started sending emails to new subscribers from mailchimp . Now I pause from there but when I tried to resume then Now I am unable to send from magento .

In cronjob   cron_scheudal   I am getting maybe somehow related to issue ? mailchimp again and again producing this issue.

```
 ebizmarts_webhooks                            | error   | "First Name" is a required value.
"First Name" length must be equal or greater than 1 characters.
"Last Name" is a required value.
"Last Name" length must be equal or greater than 1 characters. | 2018-03-20 20:01:08 | 2018-03-20 20:05:00 | 2018-03-20 20:05:08 | NULL   
```
`

**Comment by alloylab** [comment]
having this same issue on magento 2.2.1 & mailchimp 1.0.27

here is full error message from the exception log,
2018-03-22 00:05:58] main.CRITICAL: "First Name" is a required value.
"First Name" length must be equal or greater than 1 characters.
"Last Name" is a required value.
"Last Name" length must be equal or greater than 1 characters. {"exception":"[object] (Magento\\Framework\\Validator\\Exception(code: 0): \"First Name\" is a required value.
\"First Name\" length must be equal or greater than 1 characters.
\"Last Name\" is a required value.
\"Last Name\" length must be equal or greater than 1 characters. at /var/www/vendor/magento/module-customer/Model/ResourceModel/Customer.php:170)"} []

**Comment by gonzaloebiz** [comment]
Hi @tousif12 @alloylab 

can you share the mailchimp_webhook_request table from your database?
Yo can send it to my personal email gonzalo at ebizmarts with a mention to this issue.

Best

**Comment by gonzaloebiz** [comment]
No news since Mar 21, close the issue until we have any new

**Comment by ahmadalkaid** [comment]
Hi Guys,

I am having the same issue, this is from my mailchimp_webhook_request

a:7:{s:2:"id";s:10:"6d2522861c";s:5:"email";s:21:"CustomerEmail@gmail.com";s:10:"email_type";s:4:"html";s:6:"ip_opt";s:12:"35.178.29.44";s:6:"web_id";s:8:"74027791";s:6:"merges";a:3:{s:5:"EMAIL";s:21:"CustomerEmail@gmail.com";s:5:"FNAME";s:0:"";s:5:"LNAME";s:0:"";}s:7:"list_id";s:10:"f3e3db0fcf";}


--

Thanks,
-Kaid

**Comment by gonzaloebiz** [comment]
Hi @ahmadalkaid 

thanks for your feedback.
Please open a new issue with a complete description ([please see at](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)

Best
