### ISSUE TITLE
PHP warning in Helper/Data.php line 340

### ISSUE THREAD

**Issue by toshz** [mailchimp/mc-magento2#266]
## Issue Description
This isn't really a bug, but I see this error in MailChimp.log:
`MailChimpLogger.INFO: Warning: Invalid argument supplied for foreach() in /var/www/html/thirdman-m2/vendor/mailchimp/mc-magento2/Helper/Data.php on line 340`

### Preconditions
This happens if the config path "mailchimp/general/map_fields" doesn't exist in core_config_data or if the unserialized value isn't an array.

Example:

    1. Magento CE 2.1.5 without sample data is installed.
    2. mc-magento2 1.0.28.
    3. PHP 7.0

### Steps to reproduce

    1. Go to the customer dashboard.
    2. Newsletter subscription.
    3. Subscribe or unsubscribe while watching var/log/MailChimp.log

### Actual and Expected result
It would be preferred to not have any warnings in the log. 

This can be fixed by using is_array() before the foreach() statement in Helper/Data.php at line 340.

**Comment by gonzaloebiz** [comment]
Hi @toshz 

thanks for your feedback.

**Comment by s00071609** [comment]
This issue seems to have reappeared in magento 2.3.1. Not sure if mailchimp fixes these issues. I am getting cron errors
warning: Invalid argument supplied for foreach() in /mailchimp/mc-magento2/Helper/Data.php on line 1028

**Comment by gonzaloebiz** [comment]
Please open a new issue with all the data to replicate

Best
