### ISSUE TITLE
Cancelled or pending orders added to revenue in mailchimp

### ISSUE THREAD

**Issue by mathijsm** [mailchimp/mc-magento2#274]
# Description
When customer does not pay his order and the order is cancelled or stays in pending. the order is send to Mailchimp and added to the revenue as sold. We do a campaign on first placed order. these orders  that are still pending or canceled are seen as completed order and campaign is the send. 
 
# Preconditions
Magento2 v. 2.2.3
mc-magento2  v. 1.0.28

# Steps to reproduce
Place order and cancel when on payment provider page or abandon payment provider page. 

# Actual and Expected result
Goto Mailchimp lookup customer 
## Expected result:
Order should NOT be added to revenu. 
## Actual result: 
Order IS added to revenu.

**Comment by gonzaloebiz** [comment]
Hi @mathijsm 

what is the status of the order in magento? and in mailchimp?

Best

**Comment by mathijsm** [comment]
Hello @gonzaloebiz 

Here you can see the magento backend of the order # 000000349 
as you can see the order is canceld and not paid. 

<img width="871" alt="schermafbeelding 2018-04-11 om 08 27 50" src="https://user-images.githubusercontent.com/3367373/38599942-ac5ece9c-3d62-11e8-9fe8-eb8b75b7d6ea.png">

In Mailchimp you can see that the order # 000000349  is registered as purchased.

<img width="576" alt="schermafbeelding 2018-04-11 om 08 29 41" src="https://user-images.githubusercontent.com/3367373/38599943-ac7b0742-3d62-11e8-9c62-8b778ff65661.png">

**Comment by gonzaloebiz** [comment]
Hi @mathijsm 

we found an issue with this and fix it with the associated PR.
Thanks for your contribution

**Comment by shreddieb** [comment]
Hi @gonzaloebiz, 
I'm having a similar issue where canceled magento orders are showing up as revenue/purchased items on customer profile pages in mailchimp. And not sure if it's related, but my total store revenue shown on the mailchimp dashboard is not including all of the revenue amounts and days.

preconditions:
Magento 2.2.4
mc-magento2 v. 1.0.32
mailchimp-lib v. 3.0.29
php v. 7.0.32

I "was" seeing an ebizmarts_ecommerce cron_schedule table error "Unable to unserialize value." But then I applied your fix from commit 645a10d and that fixed the cron error. Unfortunately though the revenue shown in mailchimp didn't update. Two way sync is enabled in Magento 2 mailchimp configuration.
