### ISSUE TITLE
Magento 2.2.2 install error command line sales_order_grid

### ISSUE THREAD

**Issue by MikGyv** [mailchimp/mc-magento2#276]
I have tried to install Mailchimp 1.0.28 to Magento 2.2.2 with command line.
During installation command line gives error:
" SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magentoinstallfolder.sales_order_grid' doesn't exist, query was: DESCRIBE `sales_order_grid` "

After this website gives error:
" There has been an error processing your request
Exception printing is disabled by default for security reasons.

Error log record number: 2137705158 "

I have tried also Mailchimp 1.0.27. Do you know where could be the problem? After removing all Mailchimp files and flushing/cleaning caches all works great again.

**Comment by gonzaloebiz** [comment]
Hi @MikGyv 

sales_order_grid is a base magento table, so must be there. You have a db prefix? You split your database?

Best

**Comment by gonzaloebiz** [comment]
16 days without response, close the issue until new data is available
