### ISSUE TITLE
Ecommerce data sync failing if a quote contain giftcard type product

### ISSUE THREAD

**Issue by sanutryzens** [mailchimp/mc-magento2#287]
## Description
We have one giftcard product and already have a quote including this gift card product. The issue is when sync is trying import this quote. It will try to send associated giftcard product as well.

But as per you implementation giftcard type product is not supporting, the flow will return an empty array if the product is giftcard type.

Ebizmarts\MailChimp\Model\Api\Product::_buildNewProductRequest(); Line no :243

and this empty array is appending to the batch body without checking if the array is empty.

Ebizmarts\MailChimp\Model\Api\Product::sendQuoteModifiedProduct(); Line no :537

This empty array export to maichimp batch API will fail and throwing the below exception while running batch

> array (
  'type' => 'http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/',
  'title' => 'Invalid Resource',
  'status' => 400,
  'detail' => 'The resource submitted could not be validated. For field-specific details, see the \'errors\' array.',
  'instance' => 'd3865ef8-0e44-4304-9f8d-7daa877a443b',
  'errors' => 
  array (
    0 => 
    array (
      'field' => 'operations.item:214',
      'message' => 'Schema describes object, array found instead',
    ),
  ),
)

I have removed the giftcard product and verified everything working properly and sync after that.

On the other hand on product sync you are checking the if product array is empty and if it is, it will not append to export

Ebizmarts\MailChimp\Model\Api\Product::_sendProducts(); Line no: 141

This check need to be add on sendModifiedProduct() and sendQuoteModifiedProduct() methods.
## Steps to reproduce

- Create a giftcard type product
- Add it into basket
- Wait this to sync to Maichimp

**Comment by gonzaloebiz** [comment]
Hi @sanutryzens 

take a look at #277 

Best
