### ISSUE TITLE
Multistore with different Mailchimp accounts not saving correctly

### ISSUE THREAD

**Issue by ebizmarts-keller** [mailchimp/mc-magento2#289]
mc-magento 1.0.28
Magento 2.2.2

Steps to reproduce:

Have 2 websites each with its own store view
Set 1 API key (from different Mailchimp accounts) in each store view
Create 2 stores (1 store for each api key)
Configure store view 1, it will save the configuration and load the account information properly
Configure store view 2, it retrieves the correct account information at first, but when saving the configuration it brings the account information from what is set in store view 1

**Comment by gonzaloebiz** [comment]
Hi @ebizmarts-keller 

i just try with the develop version and works fine for me.
Can you try with the develop version?

Best

**Comment by gonzaloebiz** [comment]
@ebizmarts-keller 

can you retry with the current development version?

Best
