### ISSUE TITLE
Not storing the data from custom columns from newsletter_subscriber table(only stores the data of customer attribute).

### ISSUE THREAD

**Issue by triabhishek95** [mailchimp/mc-magento2#290]
Magento 2.2.2 (it is a live site)
Mailchimp Module version 1.0.27

We are having custom fields for our newsletter subscription & we have stored that data into custom columns in the `newsletter_subscriber` table. When we were using magemonkey it was storing the from the our custom columns to the mailchimp data base but now in Mailchimp it is accepting the extra data through the customer attribute only means we can store the extra data of our customers only but what if the newsletter subscriber is not a customer of our site we can store the details of those users to our database in the custom fields but what to do if we want to save them into the mailchimp data base also. But as of Mailchimp is now accepting the extra data from the customer attributes only & any customer attribute is can be accessed through the customer_id only we are not able to store that data to the mail chimp database from our magento's database.

**Comment by gonzaloebiz** [comment]
Hi @triabhishek95 

you can use an observer or a plugin for the function https://github.com/mailchimp/mc-magento2/blob/develop/Helper/Data.php#L613-L635 

Best
