### ISSUE TITLE
Newsletter group interests checkbox / radios don't work

### ISSUE THREAD

**Issue by ebachmeier** [mailchimp/mc-magento2#291]
### Issue Description
When a newsletter group set to display as radio or checkboxes is created, the markup for these inputs does not allow them to be selected on the Magento frontend.

### Preconditions
1. Magento EE 2.2.3 without sample data is installed.
2. mc-magento2 1.0.28.
3. Newsletter group created with interests, set to display as checkboxes or radio.
4. Any browser.

### Steps to reproduce
1. Sign into a customer account
2. View your newsletter subscriptions with the created group set to available in the admin panel.
3. The checkbox or radio options for interests do not work.

### Actual and Expected result
It is expected that the checkboxes or radio inputs are able to be selected.

### Additional information
It seems as if the label for these inputs does not have the attribute `for="input_id_here"`.

**Comment by gonzaloebiz** [comment]
Hi @ebachmeier 

thanks for your feedback
I just try with same version of magento and mc-magento2 with firefox and that is working OK for me. (with both, a checkboxes and radio)
Can you give more information to try to replicate?

Best

**Comment by ebachmeier** [comment]
@gonzaloebiz try Chrome 63

**Comment by gonzaloebiz** [comment]
I don't have chrome 63, but try with chrome Version 65.0.3325.18 on both, linux and mac and works fine.

**Comment by gonzaloebiz** [comment]
one week without response, close the issue until new data is available
