### ISSUE TITLE
Why after customer deletion, mailchimp disconnect/connect need to perform?

### ISSUE THREAD

**Issue by NiteshKuyate** [mailchimp/mc-magento2#292]
We had installed Mailchimp 1.0.26 to Magento 2.1.5

After deleting a customer in Magento admin, revenue statistics in mailchimp doesn't show anything after the date of customer deletion, then getting

> Resource Not Found : The requested resource could not be found.

After that we update  Mailchimp extension to 1.0.27 then above issue resolved.
But after deletion of customer again that issue appear.

We are wondering if in the future we need to delete a customer would deleting the customer first in MailChimp and then Magento admin prevent this same 'extension updation' from happening again?

**Comment by gonzaloebiz** [comment]
Hi @NiteshKuyate 

thanks for your feedback.
Can you be clear on how to reproduce the issue step by step.

Best

**Comment by NiteshKuyate** [comment]
Hello @gonzaloebiz 

1) Installed Mailchimp 1.0.26 to Magento 2.1.5.
2) Store sync like products, customers, orders etc complete.
3) Revenue statistics in mailchimp showing currectly.
4) Delete customer in magento store.
5) Revenue statistics in mailchimp doesn't show anything after the date of customer deletion.
6) Update Mailchimp 1.0.26 to 1.0.27.
7) Store sync like products, customers, orders etc complete.
8) Revenue statistics in mailchimp showing currectly.
9) Delete customer in magento store.
10) Revenue statistics in mailchimp doesn't show anything after the date of customer deletion.

Kind Regards
