### ISSUE TITLE
abandoned cart email didn't send

### ISSUE THREAD

**Issue by curkle** [mailchimp/mc-magento2#300]
**Case:** Magento 1 store migrate to magento 2, connected to existing account. disconnect old site and click reset ecommerce data.

newsletter subscribe works fine but abandoned cart email never send out. check log and find batch error

"status_code":400,
"operation_id":"PRO_1524375303_8507",
"response":"{"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Bad Request","status":400,"detail":"We were unable to process the request. A product with the provided ID already exists in the account.","instance":""}"
},

"status_code":200,
"operation_id":"QUO_2018-04-22-05-35-04-52509800_3321",
"response":"{"id":"3321","customer":{"id":"2","email_address":"***@1`111.com",\

Any idea how we can make abandoned cart work?

**Comment by gonzaloebiz** [comment]
Hi @curkle 

thanks for your feedback.
Sorry but the data synced in a magento1 store can't be managed in a magento2 store, you must create a new MailChimp store and re sync all the data

Best
