### ISSUE TITLE
Ecommerce Sync not working

### ISSUE THREAD

**Issue by antoniogarcia78** [mailchimp/mc-magento2#303]
Hi

I have installed the last version and apply the patch that recommended in 
https://github.com/mailchimp/mc-magento2/issues/280

Now the ecommerce section in Mailchimp page still no without data and in the core_schedule we have a lot of row with this error  

-- SQLSTATE[42S22]: Column not found: 1054 Unknown column 'at_special_from_date_default.value' in 'on clause', query was: 

SELECT `e`.*, IF(at_special_price.value_id > 0, at_special_price.value, at_special_price_default.value) AS `special_price`, 
`at_special_from_date`.`value` AS `special_from_date`, `at_special_to_date`.`value` AS `special_to_date`, `mc`.* 
FROM `catalog_product_entity` AS `e`
 LEFT JOIN `catalog_product_entity_decimal` AS `at_special_price_default` ON (`at_special_price_default`.`entity_id` = `e`.`entity_id`) AND (`at_special_price_default`.`attribute_id` = '567') AND `at_special_price_default`.`store_id` = 0
 LEFT JOIN `catalog_product_entity_decimal` AS `at_special_price` ON (`at_special_price`.`entity_id` = `e`.`entity_id`) AND (`at_special_price`.`attribute_id` = '567') AND (`at_special_price`.`store_id` = 7)
 LEFT JOIN `catalog_product_entity_datetime` AS `at_special_from_date` ON (`at_special_from_date`.`entity_id` = `e`.`entity_id`) AND (`at_special_from_date`.`attribute_id` = '568') AND (`at_special_from_date`.`store_id` = 0)
 LEFT JOIN `catalog_product_entity_datetime` AS `at_special_to_date` ON (`at_special_to_date`.`entity_id` = `e`.`entity_id`) AND (`at_special_to_date`.`attribute_id` = '569') AND (`at_special_to_date`.`store_id` = 0)
 LEFT JOIN `mailchimp_sync_ecommerce` AS `mc` ON mc.type = 'PRO' AND mc.related_id = e.entity_id AND mc.mailchimp_sync_modified = 0  
 AND  mc.mailchimp_store_id = '5cf8dfcd757d60254b1298e2bb26a2d3' 
 AND mc.mailchimp_sync_delta < (IF(at_special_from_date.value_id > 0, at_special_from_date.value, at_special_from_date_default.value)) 
 WHERE (IF(at_special_price.value_id > 0, at_special_price.value, at_special_price_default.value) > 0) 
 AND (((((at_special_from_date.value <= '2018-05-04 23:59:59') OR (at_special_from_date.value IS null))))) 
 AND (((((at_special_to_date.value >= '2018-05-04 00:00:00') OR (at_special_to_date.value IS null))))) 
 AND (mc.mailchimp_sync_delta is not null)

**Comment by antoniogarcia78** [comment]
IMHO this change is in the 1.0.28 version

**Comment by gonzaloebiz** [comment]
This fix will be available in 1.0.29 (you can see it in the original issue)

Best

**Comment by antoniogarcia78** [comment]
Estimated date release?

**Comment by gonzaloebiz** [comment]
We don't have it for now, think 2/3 weeks

**Comment by antoniogarcia78** [comment]
Do you know what is the last stable version to install?

**Comment by gonzaloebiz** [comment]
You always can see it at https://github.com/mailchimp/mc-magento2/releases
Or use composer to install it.
You can always install any branch, simply specify the branch in the composer command:
composer require mailchimp/mc-magento2:dev-develop
or you can download the zip from the "clone or download" button

Best

**Comment by girishtiwari** [comment]
I am also facing the same issue and I think the problem is with "_markSpecialPrices()" function which is declared on the "/app/code/Ebizmarts/MailChimp/Model/Api/Product.php" file.
