### ISSUE TITLE
Abandoned cart email not sent when Magento customer is not logged in to their account

### ISSUE THREAD

**Issue by dmatthew** [mailchimp/mc-magento2#305]
## Issue Description

If a user with a Magento account abandons their cart while not logged in, then the abandoned cart email does not get sent.

It's this bit of code here which is the problem: https://github.com/mailchimp/mc-magento2/blob/develop/Model/Api/Cart.php#L243-L247

What is the reasoning for "avoid carts abandoned as guests when customer email associated to a registered customer."? Wouldn't we want to send abandoned cart emails to these customers? If not, can you please add this as a Store Configuration option so different websites can choose whether they sync these carts or not?

### Expected result

Logged out customers who have an account associated with the email they use in checkout who abandon their cart should still receive an abandoned cart email.

### Actual result

No abandoned cart email is sent to that customer.

**Comment by gonzaloebiz** [comment]
Hi @dmatthew 

thanks for your feedback.
This is not an issue, and this is the expected behavior.
When a customer has an account (thus is, a registered email), we can only be sure that is the real customer if is logged, otherwise anyone can pretend to be him

Best
