### ISSUE TITLE
Column "address_address1" does not exist in table "mailchimp_stores".

### ISSUE THREAD

**Issue by msawyers** [mailchimp/mc-magento2#306]
**Issue Description**: After running php bin/magento setup:upgrade error is received - Column "address_address1" does not exist in table "mailchimp_stores".

**Steps to reproduce**
install mc-magento 1.0.28
run setup:upgrade

**Expected Result:**
Setup:upgrade should complete successfully

**Actual Result**
Setup:upgrade fails

**Comment by gonzaloebiz** [comment]
See #283
