### ISSUE TITLE
reopen #158

### ISSUE THREAD

**Issue by dan-ding** [mailchimp/mc-magento2#310]
see #158 
:)

**Comment by gonzaloebiz** [comment]
Hi @dan-ding 

as always, thanks for your feedback.
I don't think, why someone that use MailChimp and use the extension would use the magento double optin and not the one from MailChimp?
MailChimp for sure react more quickly and securely to changes (as GDPR) than each particular magento installation, because is their business
If you use MailChimp, why not leave the logic in MailChimp?
I know, perhaps a configurable option sounds more "open", but personally think i not agree philosophically with this option.
But of course, we can discuss the point

Best

**Comment by dan-ding** [comment]
@gonzaloebiz 
sure maybe mailchimp does some things "better". but it's still limited in what it "can" do. 

by extension of your logic of "leaving things to mailchimp" -- why then, have any newsletter data in magento? why do anything at all in magento?

also setting the "setImportMode" also will disable the final success email from magento, not just the confirmation email.

this one little modification you all made with the setImportMode, means we have have to either (a) completely change, from top to bottom if it's possible, our customization to newsletters; (b) rewrite parts of the magento core (to prevent this module from mucking it up); or (c) fork this extension;
none of which is any fun.

**Comment by gonzaloebiz** [comment]
First of all, i want to say that i think this is an interesting discussion and we are open to hear arguments.

I think is not the same logic...
Maintain basic newsletter data in magento, keeps the option of the store owner to get back from MailChimp and use any other provider, in my opinion really a few users once they install the extension use magento to send newsletters (perhaps i am wrong), but it would be dishonestly from our end to force the user to use MailChimp forever. So the best option is save some basic data in magento, even if the store never use it. (and of course, this data is useful in the sync process)

What gain would you get if would be magento who does the double optin? I'm trying to do a list with pros and cons... do you have one?

Best

**Comment by subbu1993** [comment]
hey @gonzaloebiz 

from what I understand with the Double optin feature documentation here - https://kb.mailchimp.com/lists/signup-forms/about-double-opt-in and https://kb.mailchimp.com/lists/signup-forms/single-opt-in-vs.-double-opt-in, it is designed to mimick Magento's **Require Confirmation** setting. 

For some stores, a confirmation link/email is not required BUT a subscription success email is desired. In cases like these setting the `import_mode` value to true before magento can run the `sendConfirmationSuccessEmail` method causes the success email to not be sent out. 

If you agree this to be a problem - a fix for this would be 

1) A change to https://github.com/mailchimp/mc-magento2/blob/develop/Model/Plugin/Subscriber.php#L125 to set the importMode to false
2) An after plugin to change the importMode back again to true. 

I can also try and make this an around plugin to achieve the results above. 

LMK  - and I can get a PR in.

Thanks

**Comment by dan-ding** [comment]
while I agree with @subbu1993 that
> For some stores, a confirmation link/email is not required BUT a subscription success email is desired. In cases like these setting the import_mode value to true before magento can run the sendConfirmationSuccessEmail method causes the success email to not be sent out.

however I think it's only part of the issue.  A more comprehensive solution to setting the `import_value `or not is whether a person wants to **manage the the registration actions (single or double, success, unsub, etc) in magento or in mailchimp**. 

So I think looking at it as a pros/cons is misleading because I think that's not the issue. The issue is setting, without a choice the `import_option`, **screws the default magento behavior up**. This change breaks magento actions around newsletter management, without providing an equivalent option alternative. It's really that simple.

If this extension wants to provide the option to manage double-optins in mailchimp, then it should explicitly do that by offering a configuration setting to enable/disable such a choice, and the code should follow through to that feature.

**Comment by gonzaloebiz** [comment]
Take a look at https://github.com/mailchimp/mc-magento2/issues/372
