### ISSUE TITLE
https://chimpstatic.com/mcjs-connected/js/users/..... 502 error

### ISSUE THREAD

**Issue by lano-vargas** [mailchimp/mc-magento2#318]
We have installed mailchimp for Magento 2.2.2 and is very sporadic we have complains about not syncing  now and then we have monitored over a week and I can see in the browser console very frequently gives 502 error:

![chimpstatic com-error](https://user-images.githubusercontent.com/3495481/40786226-7905c350-64e2-11e8-91f6-bcd53848eab7.png)

I've also tested uptime using online tool https://www.uptrends.com/tools/uptime 
here is the result every time it will give a very different result : 

<img width="1267" alt="screen shot 2018-05-31 at 14 33 48" src="https://user-images.githubusercontent.com/3495481/40786413-e48946e2-64e2-11e8-92c2-20b0b0756e21.png">

and loading in the browser :  

![chimpstatic-error-2](https://user-images.githubusercontent.com/3495481/40786532-25998c5a-64e3-11e8-86b1-16d580c407fe.png)

Is there an issue? can you fixe it?

Thank you.
Regards.

**Comment by gonzaloebiz** [comment]
Hi @lano-vargas 

thanks for your feedback.
Sorry but this is not something that we can fix, sound like a infrastructure issue not a extension issue

Best

**Comment by lano-vargas** [comment]
@gonzaloebiz thanks for reply .
I understand but for this reason then the extension fails to do its job can you pass this to the infrastructure department?

**Comment by gonzaloebiz** [comment]
You can contact directly to MailChimp support for this.

Best
