### ISSUE TITLE
Disabling Amazon Pay in Setup Wizard breaks Checkout

### ISSUE THREAD

**Issue by maderlock** [mailchimp/mc-magento2#323]
### Steps to reproduce

    1. Install 2.2.4 via composer using magento/product-community-edition
    2. Start web wizard
    3. During install choose to leave Amazon Payments disabled
    4. Add a product and enable an offline payment method
    5. Add product to cart on frontend and visit checkout

### Actual and Expected result

Expected:

To see checkout

Actual:

Following Exception:

Exception #0 (UnexpectedValueException): Payment model name is not provided in config!
--
#0 .../vendor/magento/module-payment/Model/PaymentMethodList.php(46): Magento\Payment\Helper\Data->getMethodInstance('amazon_payment')

### Additional information

I can see the admin options for Amazon Payments even though it is disabled in app/etc/config.php, so it may be that there is close coupling between Amazon payments and another module.

**Comment by maderlock** [comment]
Whoops - this was supposed to be on the Magento 2 repo. Please delete.

**Comment by gonzaloebiz** [comment]
No problem
