### ISSUE TITLE
High CPU load when API not available

### ISSUE THREAD

**Issue by ghost** [mailchimp/mc-magento2#325]
Magento 2.2.1
MailChimp v1.0.25

We are running a 64GB 16 Core Server and yesterday the Mailchimp API went down and suddenly our whole shop had  a lot of 502 Bad Gateways or very long loading times.
Our PHP-FPM was 100%

Mailchimp was trying to reach the API but it couldn't therefore I quess the request was staying open and blocking the server. But I am not sure.

You can simply reproduce this by manually blocking the mailchimp api on the server while having crons set up and visitors browsing the website.

**Comment by gonzaloebiz** [comment]
Hi @marcmayo 

thanks for your feedback.
We can't do so much to prevent this, we will try to put something like a 'ping' at the start of the cron

Best

**Comment by springerin** [comment]
@gonzaloebiz any update on when will this be released? We're experiencing a lot of troubles because of this.

**Comment by gonzaloebiz** [comment]
Hi @springerin 

we don't have an ETA for the release.
You can apply the fix for yourself or use the development version

Best
