### ISSUE TITLE
Multistore pulling in default store url for links

### ISSUE THREAD

**Issue by willwright111** [mailchimp/mc-magento2#327]
Preconditions

Magento 2.2.3
Module version 1.0.29
Steps to reproduce

Setup 1 Magento install with multiple website views
Install Mailchimp Module
Configure Mailchimp Module
Sync catalog from Magento to Mailchimp
Go to create a campaign in Mailchimp the url links to the products are for the default website not the specified website.
Expected result

Links in mailchimp to products in website 1 link to website 1
Links in mailchimp to products in website 2 link to website 2
Actual result

All links from products in mailchimp go to the default website rather than the website the products are from

**Comment by gonzaloebiz** [comment]
Hi @willwright111 

thanks for your feedback.
Are you using one MailChimp store per magento website or the same MailChimp store for all?

Best

**Comment by willwright111** [comment]
@gonzaloebiz one Mailchimp store per magento website

**Comment by gonzaloebiz** [comment]
@willwright111 

the MailChimp stores, has the same list or 2 different list?

Best

**Comment by willwright111** [comment]
@gonzaloebiz sorry what do you mean? What list?

**Comment by gonzaloebiz** [comment]
Each MailChimp store has an associated MailChimp list

**Comment by willwright111** [comment]
2 different lists

**Comment by gonzaloebiz** [comment]
Please send an email to mailchimp@ebizmarts-desk.zendesk.com mentioning the issue
