### ISSUE TITLE
Cron exception "Resource Not Found : The requested resource could not be found."

### ISSUE THREAD

**Issue by sanutryzens** [mailchimp/mc-magento2#328]
The cron scheduler for ebizmart_ecommerce is throwing exception "Resource Not Found : The requested resource could not be found." and sync stopped working. There for order confirmation, abandoned cart emails, etc are not sending.

We are using latest version 1.0.29 

**Step to reproduce**
There is no defined steps. We configured mailchimp around months back and everything going fine and suddenly stopped working with above error on cron.

Thanks
Sanu

**Comment by gonzaloebiz** [comment]
There's not enough data to reproduce the issue, please follow the [issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)

Best

**Comment by teamcrisis** [comment]
This is possibly related to https://github.com/mailchimp/mc-magento2/issues/344 where Mailchimp API connection failures cause other magento functionality to fail.

**Comment by gonzaloebiz** [comment]
No news in 18 days, so close the issue.
If you update the required information we will re open it

Best
