### ISSUE TITLE
Mailchimp error after creating new store 

### ISSUE THREAD

**Issue by lano-vargas** [mailchimp/mc-magento2#329]
Installed MailChimp v1.0.28 by ebizmarts on Magento 2.2.2  3 months ago at the time there were 2 stores running now we've set ip a 3 store and mailchimp is now giving exception errors:

All the stores has the same setup in mailchimp when loading any stores url the bellow error shows.

1 exception(s):
Exception #0 (Mailchimp_Error): Resource Not Found : The requested resource could not be found.

> Exception #0 (Mailchimp_Error): Resource Not Found : The requested resource could not be found.
> #0 /var/www/vhosts/magento2/htdocs/vendor/ebizmarts/mailchimp-lib/src/Mailchimp/EcommerceStores.php(66): Mailchimp->call('ecommerce/store...', Array, 'GET')
> #1 /var/www/vhosts/magento2/htdocs/app/code/Ebizmarts/MailChimp/Helper/Data.php(819): Mailchimp_EcommerceStore->get('-1') ......

After mailchimp has been installed setting has been done and working then on new store setup  it should not cause Exception/Error. None of the store is now loading. 

Thank you
Regards!

**Comment by lano-vargas** [comment]
It should have some simple check as: 

`if($id >= 0){
                return $this->master->call('ecommerce/stores/' . $id, $_params, Mailchimp::GET);
            }`

Doing this it fixes the problem But.....

But yet it doesn't help why my newly created store which id is `3` for mailchimp it thinks it's id is `-1` ?? or even mean none at all false.

**Comment by lano-vargas** [comment]
This is what happened in Configuration->Mailchimp->Mailchimp General Configuration->Mailchimp Store if in `Store View:` Default Config isn't set this values it causes the warning. once I've set per store view everything was fine. 

Shouldn't this be take in consideration as if it isn't set it should just load the website  without Exceptions?

Thanks.

**Comment by gonzaloebiz** [comment]
Please, follow the [issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)
We need specific steps to reproduce the issue.
Once you meet the issue reporting guidelines we will re open the issue

Best
