### ISSUE TITLE
reopen #239

### ISSUE THREAD

**Issue by megastormweb** [mailchimp/mc-magento2#331]
Anything are working fine on Magento site, but still not receive any Abandoned cart emails.
Current MC version is: 1.0.29
Current Magento 2 version: 2.2.4
My mailchimp account is: megastormweb
https://github.com/mailchimp/mc-magento2/issues/239

**Comment by gonzaloebiz** [comment]
Please follow the [issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)
