### ISSUE TITLE
Products data does not sync with Mailchimp backoffice

### ISSUE THREAD

**Issue by arioch1984** [mailchimp/mc-magento2#332]
### Preconditions
We are running Magento 2.1.9 for our customer Drogheria Pedrelli with the latest version (1.0.29) of your module.
We have two environment (staging and production) each with a Mailchimp account connected (staging with a free account and production with a paid account).
Our problem is when our customer create a new product (even simple products) or edit an existing product in production environment they will not be synced to his Mailchimp backoffice.
In staging environment this not happen and the synchronisation works as intended with the same Magento and module version.
This is a help request and not properly a bug report but we need help to debug the problem, if you could please.

### Steps to reproduce
If we:
1. edit the title of a already synced product or edit edit the title of a never synced product or create a new product
2. we see the corresponding row in mailchimp_sync_ecommerce changing and the column mailchimp_sync_modified become 1 from 0
3. but when the cron job ebizmarts_ecommerce success the row in mailchimp_sync_ecommerce remain the same and we will not see any changes in Mailchimp backoffice for the related product

### Additional information
I will attach to this report:
1. the transcription of the Mailchimp support chat
2. a csv with the row of the table mailchimp_sync_ecommerce for a example product
3. the screenshot of our production configuration

Please may you help us?

Thanks a lot.
[Mailchimp chat transcription.pdf](https://github.com/mailchimp/mc-magento2/files/2133228/Mailchimp.chat.transcription.pdf)
[pedrelli problem.txt](https://github.com/mailchimp/mc-magento2/files/2133230/pedrelli.problem.txt)
![screenshot 2018-06-25 14 14 13](https://user-images.githubusercontent.com/5476141/41852519-abcfc044-788b-11e8-828d-00076e8fccd3.png)
![screenshot 2018-06-25 14 14 20](https://user-images.githubusercontent.com/5476141/41852520-abfab380-788b-11e8-8baf-b725f7418223.png)
![screenshot 2018-06-25 14 14 27](https://user-images.githubusercontent.com/5476141/41852521-ac277f0a-788b-11e8-80c3-c7990b477f88.png)
![screenshot 2018-06-25 14 14 30](https://user-images.githubusercontent.com/5476141/41852522-ac48a93c-788b-11e8-9109-c9f17fb293a5.png)

**Comment by gonzaloebiz** [comment]
Hi @arioch1984 

please, delete urgently your Api Key and generate a new one

Best

**Comment by arioch1984** [comment]
Hi @gonzaloebiz 

Done :) thanks for the alert!

Please may you help us with in debugging our problem?

**Comment by gonzaloebiz** [comment]
Hi @arioch1984 

once the cron runs, the mailchimp_sync_modified field for this product, returns to 0? or remains in 1?

Best

**Comment by arioch1984** [comment]
Hi @gonzaloebiz 

tanks for your reply!
After the cron runs the mailchimp_sync_modified remain in 1

**Comment by gonzaloebiz** [comment]
That's typically means that your cron not run
Take a look at the table cron_schedule for job_code = 'ebizmarts_ecommerce' if you have job with status 'running' that means that your php cli configuration has not enough memory for run the magento crons, so double check this parameter.

Best

**Comment by arioch1984** [comment]
Hi @gonzaloebiz, 

thanks for your quickly reply!
Unfortunately this task is correctly executed, in cron_schedule table I could see the success operation log every 15 minutes.
The VM where the production environment is running is a 16GB memory 4 CPU machine and while monitoring resources I could see the average use of memory is low because the ecommerce does not have a lot of visitors.

**Comment by gonzaloebiz** [comment]
Hi @arioch1984 

i just test it, and works OK for me.
Keep in mind, the memory of the machine is not relevant if you don't assign it to php, also keep in mind the magento cron runs by the php cli environment, so you can execute
php --info | grep memory_limit
to see if you meet the magento requirements
Can you please provide more specific information to replicate it.

Best

**Comment by arioch1984** [comment]
Hi @gonzaloebiz 

again thanks for your help.
Here is my CLI PHP memory limit:

ubuntu@pedrelli:~$ php --info | grep memory_limit
memory_limit => -1 => -1

I'm happy to provide more detailed informations, but please may you tell me what kind of information may I tell you?

thanks again

**Comment by gonzaloebiz** [comment]
You should put some debug information.

You can start with the management of the modified products there

https://github.com/mailchimp/mc-magento2/blob/develop/Model/Api/Product.php#L115-L125

Put a
```php
$this->_helper->log((string)$collection->getSelect());
```
after these lines and be sure that the query return your modified product.

**Comment by arioch1984** [comment]
Hi @gonzaloebiz 

thanks for your reply and for your help!

I will require to my managers time for this debug, I will do and then post the result here, but I have to take some time, please may you don't close this issue meantime please?

Thanks in advance.

**Comment by gonzaloebiz** [comment]
No news in 10 days, so close the issue
If you have any updated information we will re open the issue

Best
