### ISSUE TITLE
Not getting Abandoned cart emails

### ISSUE THREAD

**Issue by megastormweb** [mailchimp/mc-magento2#333]
**Description**

**Preconditions**
We are running Magento 2.2.4 with the latest version (1.0.29) of your module.
We have an environment (staging) with a Mailchimp account connected (a free account).

The list is synced but not getting any abandoned cart email.
Already create the abandoned cart automation in MailChimp before the cart was synced.
My mailchimp account is: megastormweb

**Steps to reproduce**
As a guest, add items to cart and get to payment step of checkout so that email address is captured in quote
Ensure that ecommerce cron job is running
Wait 1, 6, 12 hours but still not getting any emails.

**Actual and Expected result**
An abandoned cart email and listing at least 1 email sent in MailChimp

Please help me with it.

Thanks a lot.

**Comment by gonzaloebiz** [comment]
If you create the abandoned cart email automation before the store is 100% synced, no email will be sent.

Best
