### ISSUE TITLE
The List Settings section in the Connected Sites MailChimp page syncs seemingly forever

### ISSUE THREAD

**Issue by i95devdivya** [mailchimp/mc-magento2#338]
**1.1.	Preconditions:**
1.	Magento EE 2.1.3
2.	MailChimp for Magento 2 1.0.23
3.	PHP 7.0.X
**1.2.	Steps to reproduce:**
1.	Install MailChimp for Magento 2 with composer require mailchimp/mc-magento2 1.0.23.
2.	Configure MailChimp for Magento 2 following this guide.
3.	Ensure that the "Enable Two Way Sync" option is enabled.
4.	Wait for the Magento customers to sync to the assigned MailChimp list.
5.	Wait for the Magento products to sync to the assigned MailChimp list.
6.	Wait for the Magento carts to sync to the assigned Mailchimp list.
**1.3.	Expected result:**
•	The Carts sync properly for automated emails such as the abandoned cart email to be used.
•	The List Settings section in the Connected Sites MailChimp page finishes syncing.
**1.4.	Actual result:**
•	Even Carts synced properly but automated emails such as the abandoned cart email not sending.
•	The List Settings section in the Connected Sites MailChimp page syncs seemingly forever.

**Comment by gonzaloebiz** [comment]
Hi @i95devdivya 

please update the version of the extension to the current (1.0.29)

Best
