### ISSUE TITLE
Visible section not found error message

### ISSUE THREAD

**Issue by teamcrisis** [mailchimp/mc-magento2#343]
Magento 2.2.5, Mailchimp 1.0.29

When I try to view any of the Mailchimp configuration tabs under Ststem > Configuration > Mailchmp > Mailchimp General Configuration, I get booted out of the admin with the error message:
Visible section not found.

I tried magento cache clean/flush and it did not help.

**Comment by teamcrisis** [comment]
Strangely this problem seems to have resolved itself after some time has passed. Possibly related to PHP Opcache but we have never had this issue with any of the other 40+ extensions we have installed.

**Comment by gonzaloebiz** [comment]
Hi @teamcrisis 

please follow the [issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)
Once you meet the requirements we will re open the issue

Best
