### ISSUE TITLE
Undefined index 'sku' warning/error

### ISSUE THREAD

**Issue by ebizmarts-keller** [mailchimp/mc-magento2#347]
mc-magento 1.0.29

In some installations, a warning is thrown that makes the cronjob ebizmarts_ecommerce fail (can't be reproduced on all systems, depends on server configuration)

In this line: https://github.com/mailchimp/mc-magento2/blob/1.0.29/Model/Api/Order.php#L338

**Comment by gonzaloebiz** [comment]
this index MUST exists
