### ISSUE TITLE
Invalid argument supplied for foreach in Getresponse.php when requesting error response

### ISSUE THREAD

**Issue by prathers** [mailchimp/mc-magento2#348]
### Preconditions
Magento 2.2.5
mc-magento 1.0.29
Shop connected to MC

### Steps to reproduce
1. The sync between the shop and mailchimp has stopped working.
2. I look in the Mailchimp -> Error
3. There is a Bad Request: 'The requested resource could not be found.'
4. Click on link Download Response to download json report 

### Expected result
The json is downloaded locally for further investigation

### Actual result
Response throws an error in var/report:
`{"0":"Warning: Invalid argument supplied for foreach() in \/vendor\/mailchimp\/mc-magento2\/Controller\/Adminhtml\/Errors\/Getresponse.php on line 69","1":"#0 \/vendor\/mailchimp\/mc-magento2\/Controller\/Adminhtml\/Errors\/Getresponse.php(69): Magento\\Framework\\App\\ErrorHandler->handler(2, 'Invalid argumen...', '\/...', 69, Array)\n#1 \/vendor\/magento\/framework\/App\/Action\/Action.php(107): Ebizmarts\\MailChimp\\Controller\\Adminhtml\\Errors\\Getresponse->execute()\n#2 \/vendor\/magento\/module-backend\/App\/AbstractAction.php(229): Magento\\Framework\\App\\Action\\Action->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#3 \/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Backend\\App\\AbstractAction->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#4 \/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Ebizmarts\\MailChimp\\Controller\\Adminhtml\\Errors\\Getresponse\\Interceptor->___callParent('dispatch', Array)\n#5 \/vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php(143): Ebizmarts\\MailChimp\\Controller\\Adminhtml\\Errors\\Getresponse\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#6 \/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch(Object(Ebizmarts\\MailChimp\\Controller\\Adminhtml\\Errors\\Getresponse\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#7 \/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Ebizmarts\\MailChimp\\Controller\\Adminhtml\\Errors\\Getresponse\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#8 \/generated\/code\/Ebizmarts\/MailChimp\/Controller\/Adminhtml\/Errors\/Getresponse\/Interceptor.php(26): Ebizmarts\\MailChimp\\Controller\\Adminhtml\\Errors\\Getresponse\\Interceptor->___callPlugins('dispatch', Array, NULL)\n#9 \/vendor\/magento\/framework\/App\/FrontController.php(55): Ebizmarts\\MailChimp\\Controller\\Adminhtml\\Errors\\Getresponse\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#10 \/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#11 \/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n#12 \/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#13 \/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, Array)\n#14 \/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#15 \/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#16 \/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#17 \/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#18 {main}","url":"\/admin_1gtcl2\/mailchimp\/errors\/getresponse\/id\/497\/key\/40e2030dd5f80a4944174ff15f8583f146e6d6fa89f57b2cf0a5c64a3341065a\/","script_name":"\/index.php"}`

### Additional information
We have no clue why the synchronization has stopped working, so this issue is our first step to get an idea. More issues might be necessary.

**Comment by gonzaloebiz** [comment]
Hi @prathers 

please be sure that you have the directory var/Mailchimp and have the right permission

Best

**Comment by prathers** [comment]
@gonzaloebiz,
I can confirm that - the dir exists and permissions are fine. And I'm able to download other errors.
BTW: var/Mailchimp is empty..

**Comment by gonzaloebiz** [comment]
Hi @prathers 

please see at #351

Best

**Comment by s00071609** [comment]
In magento 2.3.1 cron shows error and nothing gets synced with mailchimp. I have the latest version of mailchimp and lib - i used composer to install the extension

ERROR:

Warning: Invalid argument supplied for foreach() in /........../public_html/vendor/mailchimp/mc-magento2/Helper/Data.php on line 1028

I guess this issue was there in previous versions and was supposed to be fixed but its still there. There is no info on how to fix this anywhere i can see.

Any help would be great
