### ISSUE TITLE
ERROR: Notice: Undefined variable: active in ApiKey.php

### ISSUE THREAD

**Issue by Sam-PUMP** [mailchimp/mc-magento2#349]
# Undefined variable: active

## ERROR: Notice: Undefined variable: **$active** in latest release 1.0.29

/vendor/mailchimp/mc-magento2/Model/Config/Backend/ApiKey.php

> Unable to deploy Magento on Commerce Cloud

### /vendor/mailchimp/mc-magento2/Model/Config/Backend/ApiKey.php line 81
```
 if ($active && $this->isValueChanged()) {
            $mailchimpStore = $this->_helper->getConfigValue(\Ebizmarts\MailChimp\Helper\Data::XML_MAILCHIMP_STORE, $generalData['scope_id']);
            $this->resourceConfig->deleteConfig(\Ebizmarts\MailChimp\Helper\Data::XML_MAILCHIMP_STORE, $generalData['scope'], $generalData['scope_id']);
            foreach ($this->_storeManager->getStores() as $storeId => $val) {
                if ($this->_helper->getConfigValue(\Ebizmarts\MailChimp\Helper\Data::XML_MAILCHIMP_STORE, $storeId) == $mailchimpStore) {
                    $found++;
                }
            }
            if ($found==1) {
                $this->_helper->markAllBatchesAs($mailchimpStore, 'canceled');
            }
        }
```

### /vendor/magento/module-config/Model/Config/Importer.php
```
catch (\Exception $e) {
            throw new InvalidTransitionException(__('%1', $e->getMessage()), $e);
```

* Magento EE 2.2.5
* mc-magento2 1.0.29

**Comment by Sam-PUMP** [comment]
Just saw this was already fixed here:
https://github.com/mailchimp/mc-magento2/blob/537c392add145a3680ec2bef901af376c26d9bf1/Model/Config/Backend/ApiKey.php#L73

**Comment by avaldi** [comment]
Guys, this issue is fixed since July, can we get a new release please?

**Comment by kamilszewczyk** [comment]
I just encountered this issue. When can we expect new release?

**Comment by gonzaloebiz** [comment]
Hi @avaldi, @kamilszewczyk 

we are working in a new release for next 2 or 3 weeks.

Best
