### ISSUE TITLE
Offload API call for subscription to list to cron

### ISSUE THREAD

**Issue by peterjaap** [mailchimp/mc-magento2#350]
Subscribing to a Mailchimp list now happens in the user flow during checkout using an API call (see `Subscriber.php > beforeSubscribe() & beforeSubscribeCustomerById()`). This is dangerous because when the Mailchimp API is offline (which has happened several times during the past few weeks), the checkout process halts and the customer cannot place an order.

My suggestion would be to, for example, add a column to the `newsletter_subscriber` table named `magemonkey_queued` (default `0`) and set that to `1` during the checkout. The cron can then be run to fetch these rows from the table and subscribe these customers to the list. Maybe we need to add another column `magemonkey_list_id` when the option to select a list is enabled in the checkout.

This way, there is no dependency on the API needing to be available during a customers' checkout process.

Even nicer would be that for EE it will use RabbitMQ.

# Preconditions
- Magento 2.x
- Any version of this module

# Steps to reproduce
1. Make the Mailchimp API go down somehow (or wait for it to happen, happens a lot lately)
1. Place an order

# Expected result
1. The order should be placed

# Actual result
1. The order isn't placed

**Comment by gonzaloebiz** [comment]
Hi @peterjaap 

please follow the [issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)
We will re open the issue when you meet this requeriment

Best

**Comment by peterjaap** [comment]
@gonzaloebiz i updated it.

**Comment by gonzaloebiz** [comment]
Thanks @peterjaap 
We will look at

**Comment by gonzaloebiz** [comment]
Hi @peterjaap 

just try and work OK for me.
Can you please let me know version of the extension, version of magento, what configuration do you have?

Best

**Comment by peterjaap** [comment]
@gonzaloebiz how did you simulate the Mailchimp API being down?

**Comment by gonzaloebiz** [comment]
I use Domain Blocker, but i don't think this really matters

**Comment by gonzaloebiz** [comment]
Close for now until we have any new
