### ISSUE TITLE
Unable to install extension:  Base table or view not found

### ISSUE THREAD

**Issue by ravinsky** [mailchimp/mc-magento2#353]
There is a problem with installing the extension if you have custom table prefix.
`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'default.mailchimp_stores' doesn't exist, query was: DESCRIBE 'mailchimp_stores'`
To fix this you need to replace this:
`$connection->tableColumnExists('mailchimp_stores'...`
with this:
`$connection->tableColumnExists($setup->getTable('mailchimp_stores')...`
in UpgradeSchema.php in lines 299 and 312

**Comment by gonzaloebiz** [comment]
Hi @ravinsky 

please follow the [issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)

Best
