### ISSUE TITLE
Mailchimp part configuration break store front

### ISSUE THREAD

**Issue by LordHansolo** [mailchimp/mc-magento2#354]
## Issue Description

If we set API credentials and not choose Mailchimp Store entire store front stop work.

### Preconditions

Magento 2.2.4

### Steps to reproduce

1. Set up api credentials for mailchimp in admin panel.
2. Set "Mailchimp Store" configuration to value "Select one Mailchimp Store".
3. Go to store front.

### Actual result

Store front breaks.

![mailchimp_error](https://user-images.githubusercontent.com/22025597/43159214-0806005a-8f82-11e8-81a6-9c0375dc3590.png)

### Expected result

Store front works normally.

**Comment by gonzaloebiz** [comment]
Hi @LordHansolo 

thanks for your feedback

Best

**Comment by tilkor-software** [comment]
I am also getting this issue after installation mailchimp on Magento 2.2.5 version. What is the solution?

**Comment by gonzaloebiz** [comment]
Hi @tilkor-software 

simple, select a mailchimp store.

Best

**Comment by tilkor-software** [comment]
Hi @gonzaloebiz ,

Thanks for your message.
I am not able to open frontend and admin panel after mailchimp setup. How can I select a mailchimp store?
Please suggest.

**Comment by gonzaloebiz** [comment]
What version of mc-magento2 do you have?

**Comment by gonzaloebiz** [comment]
No news on one week, so close the issue until no news
