### ISSUE TITLE
Wrong website set on customer

### ISSUE THREAD

**Issue by alepane21** [mailchimp/mc-magento2#357]
## Wrong website set on customer filter
In the following snippet, the loadByEmail is made with the storeId set as websiteId:
- https://github.com/mailchimp/mc-magento2/blob/1f3b4b7eee51b567f476088f5699a9988bb8d1bb/Model/Api/Cart.php#L221
- https://github.com/mailchimp/mc-magento2/blob/1f3b4b7eee51b567f476088f5699a9988bb8d1bb/Model/Api/Cart.php#L324

### Actual and Expected result

The loadByEmail  will load the user in the website with the same id of the store. If the ids are not aligned, this could be a real problem. 

Maybe I'm missing something?

**Comment by gonzaloebiz** [comment]
Hi @alepane21 

thanks for pointing that

Best
