### ISSUE TITLE
Use a checkbox on Checkout to determine Opt-in status.

### ISSUE THREAD

**Issue by lduh** [mailchimp/mc-magento2#36]
Add a Subscribe checkbox to the Checkout process, use that to determine opt-in status.

If the user opts in via checkbox, they should be passed to MailChimp as subscribed.
If the user does not opt in via checkbox, they should be passed to MailChimp as nonsubscribed.
If the user had previously subscribed and does not check the box on a later purchase, the user should remain subscribed.
If the user creates a cart without a checkout, they should be passed to MailChimp as nonsubscribed.

Inital sync: without checkbox data for previous orders, Customers should be passed to MailChimp as subscribed. Email addresses associated with orders who are not Customers should be passed to MailChimp as nonsubscribed.

**Comment by thaddeusmt** [comment]
This is a must-have feature. When I installed the extension today I couldn't believe this isn't part of the core functionality.

It should integrate with the core Magento Newsletter extension if possible, so the user can manage their Subscription on the user Account page "Newsletter Subscriptions", too.

**Comment by thaddeusmt** [comment]
I appears that the latest version of this extension is using the default Magento Newsletter subscription status to sync with Mailchimp - so if you have the standard Newsletter Subscribe checkbox in the checkout, it is now synced to Mailchimp as expected. Yay!
