### ISSUE TITLE
 Sync Process seems stuck

### ISSUE THREAD

**Issue by duyang79** [mailchimp/mc-magento2#362]
Hi Guys,

I am not sure if it is a bug from the extension or from my data, but I can't repeat it on my stage site (working fine on the stage but stuck on the production). I post this issue on ebizmarts forums one week ago but no one replies me, so I hope maybe someone here could give me some clues and help me figure it out.

1. Magent2 version is 2.1.8, mailchimp extension version is 1.0.29. We have 7226 simple products, 18772 website customers and 10431 subscribers. 

2. All data had been synced about one week, the status was like the following, and actually those number hadn’t changed for quite a few days.

> Total Subscribers: 19972
> Ecommerce Data uploaded to MailChimp
> Total Customers: 892
> Total Products: 1208
> Total Orders: 68
> Total Carts: 25
> Account Synced since:

3. I have checked the “cron_schedule” table, and the interesting point is that although most “ebizmarts_ecommerce” jobs are success, there are still some running jobs which were created in the past and have the same “created/scheduled/excuted” times (21:57):

> schedule_id,job_code,status,messages,created_at,scheduled_at,executed_at,finished_at
> 2818210,ebizmarts_ecommerce,pending,NULL,31/07/2018 6:27,31/07/2018 6:30,NULL,NULL
> 2818199,ebizmarts_ecommerce,success,NULL,31/07/2018 6:22,31/07/2018 6:25,31/07/2018 6:25,31/07/2018 6:25
> 2818190,ebizmarts_ecommerce,success,NULL,31/07/2018 6:17,31/07/2018 6:20,31/07/2018 6:20,31/07/2018 6:20
> 2818181,ebizmarts_ecommerce,success,NULL,31/07/2018 6:12,31/07/2018 6:15,31/07/2018 6:15,31/07/2018 6:15
> 2818156,ebizmarts_ecommerce,success,NULL,31/07/2018 6:07,31/07/2018 6:10,31/07/2018 6:10,31/07/2018 6:10
> 2818146,ebizmarts_ecommerce,success,NULL,31/07/2018 6:02,31/07/2018 6:05,31/07/2018 6:05,31/07/2018 6:05
> 2818121,ebizmarts_ecommerce,success,NULL,31/07/2018 5:57,31/07/2018 6:00,31/07/2018 6:00,31/07/2018 6:00
> 2818111,ebizmarts_ecommerce,success,NULL,31/07/2018 5:52,31/07/2018 5:55,31/07/2018 5:55,31/07/2018 5:55
> 2818103,ebizmarts_ecommerce,success,NULL,31/07/2018 5:47,31/07/2018 5:50,31/07/2018 5:50,31/07/2018 5:50
> 2818075,ebizmarts_ecommerce,success,NULL,31/07/2018 5:42,31/07/2018 5:45,31/07/2018 5:45,31/07/2018 5:45
> 2818065,ebizmarts_ecommerce,success,NULL,31/07/2018 5:37,31/07/2018 5:40,31/07/2018 5:40,31/07/2018 5:40
> 2818053,ebizmarts_ecommerce,success,NULL,31/07/2018 5:32,31/07/2018 5:35,31/07/2018 5:35,31/07/2018 5:35
> 2818027,ebizmarts_ecommerce,success,NULL,31/07/2018 5:27,31/07/2018 5:30,31/07/2018 5:30,31/07/2018 5:30
> 2818017,ebizmarts_ecommerce,success,NULL,31/07/2018 5:22,31/07/2018 5:25,31/07/2018 5:25,31/07/2018 5:25
> 2816694,ebizmarts_ecommerce,running,NULL,30/07/2018 21:57,30/07/2018 22:00,30/07/2018 22:01,NULL
> 2812236,ebizmarts_ecommerce,running,NULL,29/07/2018 21:58,29/07/2018 22:00,29/07/2018 22:01,NULL
> 2807920,ebizmarts_ecommerce,running,NULL,28/07/2018 21:57,28/07/2018 22:00,28/07/2018 22:01,NULL
> 2803639,ebizmarts_ecommerce,running,NULL,27/07/2018 21:57,27/07/2018 22:00,27/07/2018 22:01,NULL
> 2799372,ebizmarts_ecommerce,running,NULL,26/07/2018 21:57,26/07/2018 22:00,26/07/2018 22:01,NULL
> 2795049,ebizmarts_ecommerce,running,NULL,25/07/2018 21:57,25/07/2018 22:00,25/07/2018 22:01,NULL
> 2786447,ebizmarts_ecommerce,running,NULL,23/07/2018 21:57,23/07/2018 22:00,23/07/2018 22:01,NULL
> 2751836,ebizmarts_ecommerce,running,NULL,20/07/2018 21:57,20/07/2018 22:00,20/07/2018 22:01,NULL
> 2747462,ebizmarts_ecommerce,running,NULL,19/07/2018 21:57,19/07/2018 22:00,19/07/2018 22:01,NULL
> 2743199,ebizmarts_ecommerce,running,NULL,18/07/2018 21:57,18/07/2018 22:00,18/07/2018 22:01,NULL
> 2738896,ebizmarts_ecommerce,running,NULL,17/07/2018 21:58,17/07/2018 22:00,17/07/2018 22:01,NULL
> 2734482,ebizmarts_ecommerce,running,NULL,16/07/2018 21:57,16/07/2018 22:00,16/07/2018 22:01,NULL
> 2730192,ebizmarts_ecommerce,running,NULL,15/07/2018 21:57,15/07/2018 22:00,15/07/2018 22:01,NULL
> 2725814,ebizmarts_ecommerce,running,NULL,14/07/2018 21:57,14/07/2018 22:00,14/07/2018 22:01,NULL

5. The extension is running well on our stage site. The stage site has the same magento2 version and extensions, has similar number of products(7000+), but only 10 customers, subscribers, and a few testing orders. I guess the stuck maybe due to some invalid data from live site's products or customers, but don’t know how to find them out.

6. I tried to add some log printers in the \Cron\Ecommerce.php to check how many products, customers and orders have been pushed every time (printing out $countProducts, $countCustomers and $countOrders). The order number seems increasing, although the “Total Orders” in admin->mailchimp general configuration-> account details is still 68. However, the $countproduct value is gradually decreasing from originally 100 to 76 now, and $countcustomer value is always 100. I tried to pick out elements from customer or product array to find out what exact data is syncing but both “get_class()” and “get _class method()” return nothing. Can any magento2 expert tell me why? 

7. There is no MailChimp Error records on magento backend. 

Thanks for your help

**Comment by gonzaloebiz** [comment]
Hi @duyang79 

thanks for your feedback.
Looks like a data issue.
First of all i recommend update the ebizmarts/mailchimp-lib by running

composer requiere ebizmarts/mailchimp-lib

the new lib has some improvements to debug.
Try to put some log in https://github.com/mailchimp/mc-magento2/blob/develop/Cron/Ecommerce.php#L173-L187 to see if the extension process all the data.

Best

**Comment by duyang79** [comment]
Thanks @gonzaloebiz. Could you tell me what class the "$products"'s element is in [https://github.com/mailchimp/mc-magento2/blob/develop/Cron/Ecommerce.php#L173-L187](https://github.com/mailchimp/mc-magento2/blob/develop/Cron/Ecommerce.php#L173-L187) 
And $customers, and $orders?

Just like $countOrders does, I can count($products), but when I tried to output the class name and class methods by
```
get_class($products[0])
get_class_method($products[0])
```
they returned nothing.

**Comment by NiteshKuyate** [comment]
Hi @gonzaloebiz 
We are also facing same slow sync problem.
Under MailChimp errors we are getting below 2 errors continously:

>  variants.item:0.price : Schema describes number, NULL found instead

> A product with the provided ID does not exist in the account for this list.

PFA for detail error info.
[2c84e35e5f.txt](https://github.com/mailchimp/mc-magento2/files/2266235/2c84e35e5f.txt)
[MailChimp.log](https://github.com/mailchimp/mc-magento2/files/2266243/MailChimp.log)


Best Regards,
Nitesh K.

**Comment by gonzaloebiz** [comment]
Hi @NiteshKuyate 

thanks for your feedback.
Your issue is definitively not the same, please open a new issue.

Best

**Comment by gonzaloebiz** [comment]
Hi @duyang79 

as you can see at this https://github.com/mailchimp/mc-magento2/blob/develop/Cron/Ecommerce.php#L175 or this https://github.com/mailchimp/mc-magento2/blob/develop/Cron/Ecommerce.php#L181 both are arrays

Best

**Comment by NiteshKuyate** [comment]
Hi @gonzaloebiz ,

Is MailChimp v1.0.29 support Bundle, Grouped, Gift or Custom product types.
Please let us know which product types MailChimp v1.0.29 support.

Best Regards,
Nitesh

**Comment by gonzaloebiz** [comment]
Ni @NiteshKuyate 

no grouped or bundle products are supported.

Best

**Comment by NiteshKuyate** [comment]
Hi @gonzaloebiz ,

We have a quick question regarding MailChimp:
Is it possible to have bundled products live in the catalog and just have those products not sync with MailChimp? Or will having the bundles enabled even at all cause the sync of other non-bundle products in the catalog to fail? 

Best Regards

**Comment by gonzaloebiz** [comment]
Hi @NiteshKuyate 

you can have bundle products and they are simply ignored in the MailChimp sync process.

Best
