### ISSUE TITLE
MailChimpLogger.INFO: Warning: Invalid argument 

### ISSUE THREAD

**Issue by shibinvr** [mailchimp/mc-magento2#363]
in MailChimp, the log file contains error like, 

MailChimpLogger.INFO: Warning: Invalid argument supplied for foreach() in 
~/vendor/mailchimp/mc-magento2/Helper/Data.php on line 537

please give me feed back

**Comment by gonzaloebiz** [comment]
Hi @shibinyatnam 

please follow the [issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)

Best
