### ISSUE TITLE
Magento 2.2.3: Checkout hangs when enabling Mailchimp extension

### ISSUE THREAD

**Issue by desire-desire** [mailchimp/mc-magento2#364]
We are using ebizmarts_mailchimp (version - 1.0.29) extension  in our Magento2 website (version - 2.2.3).

When enabling the Mailchimp extension, the .checkout-loader (spinner image) loads indefinitely on the Checkout page.

We have checked the server error logs and magento error logs. But there is no error related to it.

There are no JS errors or any other signs of failure, except the spinner not getting removed. When removing it "by hand" (via "Inspect element"), the checkout works correctly.
When we tried to remove the loader using code, it stucks in payment without showing any error.

We have also checked with mailchimp team. They have asked to remove the mageMonkey from mailchimp account and reconfigure the mailchimp in magento. We removed mageMonkey and re-configured mailchimp. But still the same issue  occurs.

**Comment by gonzaloebiz** [comment]
Hi @desire-desire 

can you please send an email to our support mailchimp@ebizmarts-desk.zendesk.com

Best
