### ISSUE TITLE
Magento 2 store can't syncing. 

### ISSUE THREAD

**Issue by NiteshKuyate** [mailchimp/mc-magento2#375]
**Issue Description**

When running the ebizmarts_ecommerce job the following error is ocurring while syncing:
Note: There are many error like below

Resource Not Found : The requested resource could not be found.

> [
    {
        "status_code": 404,
        "operation_id": "QUO_2018-08-23-00-30-08-21785800_18100",
        "response": {
            "type": "http:\/\/developer.mailchimp.com\/documentation\/mailchimp\/guides\/error-glossary\/",
            "title": "Resource Not Found",
            "status": 404,
            "detail": "The requested resource could not be found.",
            "instance": ""
        }
    },
    {
        "status_code": 400,
        "operation_id": "QUO_2018-08-23-00-30-08-21785800_18100",
        "response": {
            "type": "http:\/\/developer.mailchimp.com\/documentation\/mailchimp\/guides\/error-glossary\/",
            "title": "Bad Request",
            "status": 400,
            "detail": "A product with the provided ID does not exist in the account for this list.",
            "instance": ""
        }
    }
]

A product with the provided ID does not exist in the account for this list.

> [
    {
        "status_code": 400,
        "operation_id": "QUO_2018-08-23-06-40-06-38520800_18107",
        "response": {
            "type": "http:\/\/developer.mailchimp.com\/documentation\/mailchimp\/guides\/error-glossary\/",
            "title": "Bad Request",
            "status": 400,
            "detail": "A product with the provided ID does not exist in the account for this list.",
            "instance": ""
        }
    }
]

**Preconditions**

1. Magento CE 2.1.5
2. mc-magento2 1.0.29.
3. mailchimp-lib 3.0.26

**Steps to reproduce**

Run the magento cronjob

**Comment by gonzaloebiz** [comment]
Hi @NiteshKuyate 

thanks for your feedback.
Please take a look at https://github.com/mailchimp/mc-magento2/issues/335 this issue is already fixed and will be available on next release

Best

**Comment by NiteshKuyate** [comment]
@gonzaloebiz Can you please tell us when new version will launch?

**Comment by gonzaloebiz** [comment]
Hi @NiteshKuyate 

think 2/3 weeks

Best
