### ISSUE TITLE
CPU Usage Very High

### ISSUE THREAD

**Issue by justin-at-bounteous** [mailchimp/mc-magento2#383]
## Issue Description
Since installing this module to our Staging environment, CPU usage has increased significantly. To the point that we routinely observe mailchimp action using up more than one CPU core on its own.

The logfile is predominately populated with "**MailChimpLogger.INFO: []**". Occasionally (but still frequently) "**MailChimpLogger.INFO: no customer found**". And very rarely "**MailChimpLogger.INFO: MailChimp is not available**"

I found the commit here where pinging mailchimp first was added, I've added those revisions. Following that, the CPU appears to be alright when viewing htop but the memory usage continue to steadily rise until it ultimately dies. About once a day we hit a limit and have to restart our environment.

### Preconditions

    1. Magento EE 2.1.14
    2. mc-magento2 1.0.29.

### Additional information

I've looked at the following tickets:
- https://github.com/mailchimp/mc-magento2/issues/325 (applied these commits, end result still the same)
- https://github.com/mailchimp/mc-magento2/issues/162 (business requirements dictate that we cannot disable this feature)

**Comment by pmckesson** [comment]
I get this message on my Safari browser using MC for a few .csv uploads of contacts and the moving around on the site.  Ugh!  "this web page is taking a significant amount of CPU ...  
Is anyone else experiencing this?
