### ISSUE TITLE
Cronjobs stuck at pending forever

### ISSUE THREAD

**Issue by OvalMedia** [mailchimp/mc-magento2#387]
Magento 2.2.4
mc-magento2 1.0.29

The module installation and mailchimp setup went fine. Syncs from magento to MC do work. E.g. I entered a customer account and subscribed to the newsletter. The subscription in MC gets updated.

But the subscribers status (subscribed) was not synced back to magento, the checkbox in my account stayed empty.

I checked the table mailchimp_webhook_request and found an entry:

```
id: 1
type: subscribe
fired_at: 2018-09-11 08:08:01
data_request: a:8:{s:2:"id";s:10:"3171d78083";s:5:"email";s:18:"test@example.com";s:10:"email_type";s:4:"html";s:6:"ip_opt";s:11:"11.11.11.11";s:9:"ip_signup";s:13:"12.12.12.12";s:6:"web_id";s:8:"18219219";s:6:"merges";a:6:{s:5:"EMAIL";s:18:"test@example.com";s:5:"FNAME";s:4:"test";s:5:"LNAME";s:6:"tester";s:7:"ADDRESS";s:0:"";s:5:"PHONE";s:0:"";s:8:"BIRTHDAY";s:0:"";}s:7:"list_id";s:10:"98c66486c2";}
processed: 0
```

So I assume the webook works fine.

But the issue seems to be the cron_schedule table. I have multiple ebizmarts_* entries which are scheduled but never executed or finished. They all have the status "pending" and seem to be ignored by the scheduler. 

Other cronjobs in that table get executed just fine.

Since on the live system I do not have access to crontab, I created a script that gets executed every minute instead:

```
#!/bin/bash

PHP_BIN=`which php7-71STABLE-CLI`;

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BIN="$DIR/bin/magento"
INI="$DIR/php.ini"

$PHP_BIN -d max_execution_time=180 -d memory_limit=756M -c $INI $BIN cron:run | grep -v "Ran jobs by schedule" >> $DIR/var/log/magento.cron.log
$PHP_BIN -d max_execution_time=180 -d memory_limit=756M -c $INI $DIR/update/cron.php >> $DIR/var/log/update.cron.log
$PHP_BIN -d max_execution_time=180 -d memory_limit=756M -c $INI $BIN setup:cron:run >> $DIR/var/log/setup.cron.log
```

Please help. 
Thank you

**Comment by gonzaloebiz** [comment]
Hi @OvalMedia 

thanks for your feedback.
Please be sure that you don't have an ebizmarts_ecommerce job running in the cron_schedule table, if you have it, delete the entry

Best

**Comment by OvalMedia** [comment]
There are just as many ebizmarts_ecommerce jobs scheduled but none of them is running. They are all pending as well. No progress. The ecommerce option is disabled btw.

**Comment by OvalMedia** [comment]
Ok, weird. Module disabled and re-enabled. Now the crons are being processed.
