### ISSUE TITLE
Adding extra logging on import parts of the Cronjob

### ISSUE THREAD

**Issue by maximbaibakov** [mailchimp/mc-magento2#393]
## Execution visibility, extra logging

Sometimes some part of the process could fail to some reason without any errors.
It would be good to have a bit of extra logging around main parts of the process. 
It would help to dig into problem easier.

## Issue Description

There is a bit lack of visibility around execution of the sync process.
Would be awesome to see where the sync spends more time and helps to diagnose, if the sync stuck somewhere due to some reason.

E.g. Reasons:

Payload was not able to generate due to M2 Core issue and failed with warning or fatal error
You can see how much time been spent on specific part e.g. products, orders and etc. It helped me to diagnose that cart generation was taking about 20 minutes to generate due to some slow SQL query

**Comment by gonzaloebiz** [comment]
closed by https://github.com/mailchimp/mc-magento2/pull/377
