### ISSUE TITLE
Wrong total revenue in MailChimp

### ISSUE THREAD

**Issue by gonzaloebiz** [mailchimp/mc-magento2#395]
### Preconditions

    1. Any version of Magento with sample data
    2. Any version of mc-magento2

### Steps to reproduce

    1. Configure a store with at least 2 currencies
    2. Add an order with each currency

### Actual result

The revenue mix the total of the orders, even if they have distinct currencies

![image](https://user-images.githubusercontent.com/6222792/45641422-e16c6d00-ba8b-11e8-8ede-44ba39045159.png)

### Expected result

Show the right revenue.
One solution could be discriminate by currency

![image](https://user-images.githubusercontent.com/6222792/45641612-53dd4d00-ba8c-11e8-88f4-ef6b299d4e59.png)

**Comment by mike-diff** [comment]
We are not seeing any revenue data in our Mail Chimp campaigns from our connected Magento 2 store. Can we please get an update on the bug fix?

**Comment by pmonosolo** [comment]
> We are not seeing any revenue data in our Mail Chimp campaigns from our connected Magento 2 store. Can we please get an update on the bug fix?

Have you ever been able to figure this out? Having the same issue on 2.3
