### ISSUE TITLE
Problem Syncing "Old" Products 

### ISSUE THREAD

**Issue by josh-carter** [mailchimp/mc-magento2#396]
## Problem Syncing "Old" Products 

Looks like we have an issue whenever the method Ebizmarts\MailChimp\Model\Api\Product::sendQuoteModifiedProduct() is called within Ebizmarts\MailChimp\Model\Api\Cart

It ends up creating an error in the batch JSON due to the format of the product data. We end up with something like:

```
...
{"method":"POST","path".....}
{"method":"POST","path".....}
{"method":"POST","path".....}
[{"method":"PATCH","path".....}]
{"method":"POST","path".....}
...
```

The error occurs because of the array-wrapped object (PATCH request).

Seems to only be when sendQuoteModifiedProduct() leads to calling `_buildOldProductRequest()` I believe, this happens because the array of data thats passed back contains sequential array keys for the product data, something like:

```
[
    [0] => [
        [0] => {{productData}}
    ]
    [1] => [
        [0] => {{productData}}
    ]
]
```
Its due to the nesting in the returned array from `_buildOldProductRequest()`. 

Potential fix, that we're using at the moment:

Change **Ebizmarts\MailChimp\Model\Api\Cart: Lines 258-261**

```
foreach ($productData as $p) {
    $allCarts[$this->_counter] = $p;
    $this->_counter += 1;
}
```

To:

```
foreach ($productData as $p) {
    $pData = (isset($p[0])) ?
         $p[0]:
         $p;
    $allCarts[$this->_counter] = $pData;
    $this->_counter += 1;
}
```

This will catch any product array data in which the data is nested further than expecting, thus preventing the sequential array being passed to the $allCarts[] variable.

Its possible the fix really could lie inside the Model\Api\Product class, in fixing the array structure of the return in the `_buildOldProductRequest()` method instead, however, this may have other consequences, so i've not changed that for the time being. 

I'd be happy to provide a PR with the aforementioned fix, unless you guys would prefer to pick it up and fix the return in the old product request method.

**Comment by gonzaloebiz** [comment]
Hi @josh-carter 

thanks for your feedback.
Can you please format your issue according to our [issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)?
We will re open the issue once the format be OK

Best
