### ISSUE TITLE
Ecommerce cronjob stuck on customers with no address (error occurs)

### ISSUE THREAD

**Issue by stephan-cream** [mailchimp/mc-magento2#400]
### Preconditions
1. Any Magento version.
2. Any server setup
3. Customer without an address
4. Ecommerce cronjob active

### Steps to reproduce
1. Create a customer (frontend / backend both experience this).
2. Do not add an address to the customer.
3. Add 'Default Billing Address' or 'Default Shipping Address' to the configuration 'Customer Fields Mapping' in "Stores => Configuration => Mailchimp => Mailchimp General Configuration".
4. Allow the cronjob to run (or use magerun for manual execution).
5. Check the `cron_schedule` table in the database.

### Expected result
1. The customer is skipped altogether during the cronjob OR the customer is synchronised without an address.
2. The cronjob is executed fully without any exceptions occuring.

### Actual result
1. The customer is not skipped and an address is expected.
2. An error is thrown: `[2018-09-04 09:05:06] main.CRITICAL: Error when running a cron job {"exception":"[object] (RuntimeException(code: 0): Error when running a cron job at /vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:324, TypeError(code: 0): Argument 1 passed to Ebizmarts\\MailChimp\\Helper
Data::_getAddressValues() must be an instance of Magento\\Customer\\Model\\Address
AbstractAddress, boolean given, called in /vendor/mailchimp/mc-magento2/Helper/Data.php on line 563 at /vendor/mailchimp/mc-magento2/Helper/Data.php:583)"} []`
3. The cronjob stops execution and never synchronises any other customers as it keeps failing on the customer that had no address.

**Comment by gonzaloebiz** [comment]
Hi @stephan-cream 

thanks for your feedback.
I can't reproduce your issue, i follow your steps and the customer was synced fine.
Magento version 2.2.5 with sample data
mc-magento2 version 1.0.30
You have any other extensions installed? Try with a vanilla installation

Best

**Comment by stephan-cream** [comment]
My apologies, i forgot a step.
**After step 2:** Add 'Default Billing Address' or 'Default Shipping Address' to the configuration 'Customer Fields Mapping' in "Stores => Configuration => Mailchimp => Mailchimp General Configuration".
This is when the error occurs during the cronjob.
Although you could say it is required to have an address when this is set, it is obviously impossible to force this and it should not block the cronjob from synching the rest.

I updated the initial comment.

**Comment by gonzaloebiz** [comment]
Hi @stephan-cream 

i define this in the Customer Fields Mapping

![image](https://user-images.githubusercontent.com/6222792/46769017-b78c1c00-ccc0-11e8-88dc-9cf0f9392179.png)

(sorry but the development version include a new combo for the MC tags)
Then register a new customer without an address and the issue is not there, the customer was synced OK (with no address obviously)

Best

**Comment by stephan-cream** [comment]
I tried the module in a clean Magento 2.2.5 install.
The issue still persists.
Furthermore after checking the code based on the error i found out that there is an error in the logic.

`/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:324, TypeError(code: 0): Argument 1 passed to Ebizmarts\\MailChimp\\Helper Data::_getAddressValues() must be an instance of Magento\\Customer\\Model\\Address AbstractAddress, boolean given`

In the Ebizmarts\Mailchimp\Helper\Data on line 563 it executes the following:
`$this->_getAddressValues($customer->getPrimaryAddress($map['customer_field']));`

The problem with this is that the `private function _getAddressValues(\Magento\Customer\Model\Address\AbstractAddress $address)`
as you can see actually requires an address, but since there is no address it provides a boolean result 'false' in the parameter $address.
As such the earlier mentioned error is thrown during the cronjob's execution. 

Please change this so you first check whether there is an address before passing it to the function to avoid this error.

**Comment by TimQSO** [comment]
@gonzaloebiz were you able to reproduce it now?

**Comment by TimQSO** [comment]
@stephan-cream @alexeya-ven  supplied a fix as far as I can see?

**Comment by TimQSO** [comment]
Any updates on this @gonzaloebiz

**Comment by gonzaloebiz** [comment]
Hi @GuiltyNL 

no, we can't reproduce this issue

Best

**Comment by stephan-cream** [comment]
It is impossible that this is not reproducible with the current master branch...

**public function getPrimaryAddress($attributeCode) { ... }** 
// magento/module-customer/Model/Customer.php # 629~634
`return $primaryAddress ? $primaryAddress : false;`
It clearly shows that if there is no address it returns false.
As my steps to reproduce state there should be an customer without an address while the mapping is enabled for shipping or billing address.
This in turn will result in false thus throwing the earlier stated error when the method '$this-> _getAddressValues()' is called with 'false' as a value in Ebizmarts\Mailchimp\Helper\Data on line 563 .

PHP will ALWAYS throw an error when provided with a parameter of a different type than what is defined in the function.

Example taken from phptester:
![pastedgraphic-4](https://user-images.githubusercontent.com/12713337/47428038-5e2cee00-d792-11e8-9124-9201256ec299.png)

I find this incredibly strange that with all the given information you can't reproduce this.

**Comment by gonzaloebiz** [comment]
Sorry but i can't reproduce

Define the merge tag in mailchimp

![image](https://user-images.githubusercontent.com/6222792/48022822-e90ad280-e11a-11e8-99cf-ff798619394b.png)

Then assign the merge tag to the extension configuration

![image](https://user-images.githubusercontent.com/6222792/48022889-15beea00-e11b-11e8-900e-bac101d34f98.png)

Then register a new customer without an address and wait to run the sync

![image](https://user-images.githubusercontent.com/6222792/48022962-49017900-e11b-11e8-9146-30063707258a.png)

And after 5 min, the customer is in my list without problem

![image](https://user-images.githubusercontent.com/6222792/48023056-849c4300-e11b-11e8-8751-982f8077c14c.png)

**Comment by xpoback** [comment]
> Sorry but i can't reproduce
> 
> Define the merge tag in mailchimp

You say you can't reproduce it and then provide information on a workaround for this bug in the code. 
 :+1: :fist_right:  :-1:
