### ISSUE TITLE
After syncing data with MailChimp the wrong products are show for my stores

### ISSUE THREAD

**Issue by davidjones6459** [mailchimp/mc-magento2#404]
## Issue Description

After successfully syncing data to MailChimp from our Magento 2.1.9 instance, which runs 3 stores on different domains, the products shown within the Product Retargeting Notification automation setup screen are based on the whole product catalog and not the chosen website.

The websites do not share products, each product appears in only one of the stores.

### Preconditions

    1. Magento CE 2.1.9 with product data.
    2. mc-magento2 1.0.30
    3. Two or more different Magento stores setup with different products assign to each
    4. mc-magento2 configured with MailChimp account and data sync complete

### Steps to reproduce

    1. In the MailChimp account go to the connected sites area and choose a Magento 2 store
    2. Select the option to configure a Product Retargeting Email
    3. On the following page click the Edit Recipients button under the heading Sends to
    4. With this section expended you get to choose the delay after a customer views a product for the email to be sent and the products that when viewed will trigger an email, either best sellers or newest

### Actual and Expected result

    Expected result:
    Products shown in the preview area are specific to each website setup in Magento and reclected based on the connect site chosen in MailChimp
    
    Actual result:
    Regardless of the option chosen the products shown in the preview area are based on st across all websites setup in Magento

### Additional information

![best sellers - battery products for vape customers](https://user-images.githubusercontent.com/29301485/46216310-308d8a00-c337-11e8-9829-dc419fd0da20.png)
![newest - mixed battery and vape products for battery customers](https://user-images.githubusercontent.com/29301485/46216311-308d8a00-c337-11e8-9a18-39f970f34a25.png)

**Comment by gonzaloebiz** [comment]
Hi @davidjones6459 

thanks for your feedback.
We can confirm the issue and working in a fix

Best
