### ISSUE TITLE
Installation Magento 2.2.6 Setup:di:compile ReflectionException

### ISSUE THREAD

**Issue by KM-HM** [mailchimp/mc-magento2#408]
## Issue Description

While installing the Mail Chimp Magento 2 Module in version 1.0.30 or 1.0.29 from Magento Marketplace or Github an Exception will be thrown when you call "php bin/magento setup:di:compile"  

### Preconditions
1. PHP 7.0.32-0ubuntu0.16.04.1
2. Magento 2.2.6 composer installation in developer mode
3. Mail Chimp module in version  1.0.30 or 1.0.29

### Steps to reproduce

1. Download module version  1.0.30
2. Place files in app/code/Ebizmarts/MailChimp/
3. Enable module via CLI: "php bin/magento module:enable Ebizmarts_MailChimp"
4. Install module schema via CLI:  "php bin/magento setup:upgrade"
5. Follow the instructions of setup:upgrade and compile via CLI: "php bin/magento setup:di:compile"

## Expected result:
Magento CLI "setup:di:compile" will finish without issues

## Actual result:
Magento CLI "setup:di:compile" throws exception twice:

  [ReflectionException]           
  Class Mailchimp does not exist  
                                 
  [ReflectionException]           
  Class Mailchimp does not exist  

### Additional information

No exceptions or entries in debug.log, exception.log or system.log

Output of "setup:di:compile -vvv" as follows:

`# php bin/magento setup:di:compile -vvv
Compilation was started.
Area configuration aggregation... 5/7 [====================>-------]  71% 14 secs 278.0 MiB
                                  
  [ReflectionException]           
  Class Mailchimp does not exist  
                                  

Exception trace:
 () at /var/www/m2.dbox.local/html/vendor/magento/framework/Code/Reader/ClassReader.php:37
 Magento\Framework\Code\Reader\ClassReader->getConstructor() at /var/www/m2.dbox.local/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassReaderDecorator.php:35
 Magento\Setup\Module\Di\Code\Reader\ClassReaderDecorator->getConstructor() at /var/www/m2.dbox.local/html/setup/src/Magento/Setup/Module/Di/Code/Reader/Decorator/Area.php:53
 Magento\Setup\Module\Di\Code\Reader\Decorator\Area->getList() at /var/www/m2.dbox.local/html/setup/src/Magento/Setup/Module/Di/App/Task/Operation/Area.php:109
 Magento\Setup\Module\Di\App\Task\Operation\Area->getDefinitionsCollection() at /var/www/m2.dbox.local/html/setup/src/Magento/Setup/Module/Di/App/Task/Operation/Area.php:84
 Magento\Setup\Module\Di\App\Task\Operation\Area->doOperation() at /var/www/m2.dbox.local/html/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php:56
 Magento\Setup\Module\Di\App\Task\Manager->process() at /var/www/m2.dbox.local/html/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php:206
 Magento\Setup\Console\Command\DiCompileCommand->execute() at /var/www/m2.dbox.local/html/vendor/symfony/console/Command/Command.php:241
 Symfony\Component\Console\Command\Command->run() at /var/www/m2.dbox.local/html/vendor/symfony/console/Application.php:843
 Symfony\Component\Console\Application->doRunCommand() at /var/www/m2.dbox.local/html/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at /var/www/m2.dbox.local/html/vendor/magento/framework/Console/Cli.php:104
 Magento\Framework\Console\Cli->doRun() at /var/www/m2.dbox.local/html/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /var/www/m2.dbox.local/html/bin/magento:23

                                  
  [ReflectionException]           
  Class Mailchimp does not exist  
                                  

Exception trace:
 () at /var/www/m2.dbox.local/html/vendor/magento/framework/Code/Reader/ClassReader.php:29
 ReflectionParameter->getClass() at /var/www/m2.dbox.local/html/vendor/magento/framework/Code/Reader/ClassReader.php:29
 Magento\Framework\Code\Reader\ClassReader->getConstructor() at /var/www/m2.dbox.local/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassReaderDecorator.php:35
 Magento\Setup\Module\Di\Code\Reader\ClassReaderDecorator->getConstructor() at /var/www/m2.dbox.local/html/setup/src/Magento/Setup/Module/Di/Code/Reader/Decorator/Area.php:53
 Magento\Setup\Module\Di\Code\Reader\Decorator\Area->getList() at /var/www/m2.dbox.local/html/setup/src/Magento/Setup/Module/Di/App/Task/Operation/Area.php:109
 Magento\Setup\Module\Di\App\Task\Operation\Area->getDefinitionsCollection() at /var/www/m2.dbox.local/html/setup/src/Magento/Setup/Module/Di/App/Task/Operation/Area.php:84
 Magento\Setup\Module\Di\App\Task\Operation\Area->doOperation() at /var/www/m2.dbox.local/html/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php:56
 Magento\Setup\Module\Di\App\Task\Manager->process() at /var/www/m2.dbox.local/html/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php:206
 Magento\Setup\Console\Command\DiCompileCommand->execute() at /var/www/m2.dbox.local/html/vendor/symfony/console/Command/Command.php:241
 Symfony\Component\Console\Command\Command->run() at /var/www/m2.dbox.local/html/vendor/symfony/console/Application.php:843
 Symfony\Component\Console\Application->doRunCommand() at /var/www/m2.dbox.local/html/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at /var/www/m2.dbox.local/html/vendor/magento/framework/Console/Cli.php:104
 Magento\Framework\Console\Cli->doRun() at /var/www/m2.dbox.local/html/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /var/www/m2.dbox.local/html/bin/magento:23

setup:di:compile`

**Comment by gonzaloebiz** [comment]
Hi @kemexyz 

this is not an issue, please take a look at https://github.com/mailchimp/mc-magento2/blob/develop/composer.json#L26-L28

Best

**Comment by KM-HM** [comment]
@gonzaloebiz 

Some installation instructions would be nice. Its somewhat unusual to execute composer install in the module directory. Never had to do this before.

Edit:
Does not work for me at all.

**Comment by kemexyz** [comment]
Requiring "ebizmarts/mailchimp-lib": ">=3.0.27" in the magento root directory works. Not sure how I should have known this before.
