### ISSUE TITLE
field [operations.item:2] : Schema describes object, array found instead

### ISSUE THREAD

**Issue by gonzaloebiz** [mailchimp/mc-magento2#409]
### Preconditions

    1. Any version of Magento with sample data
    2. mc-magento2 1.0.30.

### Steps to reproduce

    Comment these lines https://github.com/mailchimp/mc-magento2/blob/develop/Cron/Ecommerce.php#L174-L177
    Go to the backend and modify a product
    Then make an order with this product

### Expected result
    
    The order was synced to MailChimp

### Actual result

    You can show this error in the Mailchimp.log file
    [2018-10-01 15:10:07] MailChimpLogger.INFO: Invalid Resource for Api Call: [https://us13.api.mailchimp.com/3.0/batches] using method [POST]
	Detail: [The resource submitted could not be validated. For field-specific details, see the 'errors' array.]
	Errors:
		 field [operations.item:2] : Schema describes object, array found instead

**Comment by ihor-sviziev** [comment]
Hi @gonzaloebiz,
After applying Pull Request #410  as a patch - we still have this issue, but we didn't commented that  lines that you listed in "steps to reproduce"

In json that listed below this error I see following issue - empty array between two orders data, it's in the middle of the json:
```json
{
    "operations": [
        ...
        {
            "method": "POST",
            "path": "\/ecommerce\/stores\/{STORE_ID}\/orders",
            "operation_id": "ORD_1541486703_1290333",
            "body": "{\"id\":\"1000717579\",\"currency_code\":\"USD\",\"order_total\":\"69.0000\",...}"
        },
        [],
        {
            "method": "POST",
            "path": "\/ecommerce\/stores\/{STORE_ID}\/orders",
            "operation_id": "ORD_1541486703_1290334",
            "body": "{\"id\":\"1000717580\",\"currency_code\":\"USD\",\"order_total\":\"50.0000\",...}"
        },
        ...
    ]
}
```

I checked both orders - order 1000717580 contains "E-Gift card" product type, that is not supported by this module, but it should NOT brake sync with Mailchimp

**Comment by gonzaloebiz** [comment]
@ihor-sviziev please see at https://github.com/mailchimp/mc-magento2/issues/406
