### ISSUE TITLE
Magento enterprise does not support the use of special from/to dates

### ISSUE THREAD

**Issue by ccrothers** [mailchimp/mc-magento2#411]
When checking whether to use special price, mailchimp extension does not properly check according to how it should be done on enterprise.
https://github.com/magento/magento2/issues/5984#issuecomment-360345397

Since special from/to dates aren't used on enterprise, having those values never caused us any problems. In addition, for enterprise users that use magento 2's versioning feature, mailchimp will not effectively pull the correct price (price vs special price) for those products since special from/to dates won't be set.

Please refer to Model/Api/Product.php:368

**Comment by gonzaloebiz** [comment]
Please follow [our issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)

Best

**Comment by ccrothers** [comment]
created new issue with updated formatting.
https://github.com/mailchimp/mc-magento2/issues/414
