### ISSUE TITLE
Store/website level prices not being pulled successfully in product sync/feed.

### ISSUE THREAD

**Issue by ccrothers** [mailchimp/mc-magento2#412]
We current have a multi-store website, and when a price is set at the store/website level (since a product might have a different price on one site vs the other), mailchimp error table says price is null when trying to sync product. When only setting price at default store view level, product syncs properly. We have one mailchimp store set at default left, and a different mailchimp store set at store/website level for the second store. The price that was set at store/website level was also for the second store.

**Comment by gonzaloebiz** [comment]
Hi @ccrothers 

please follow our [issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)

Best

**Comment by ccrothers** [comment]
created new issue with updated formatting.
https://github.com/mailchimp/mc-magento2/issues/413
