### ISSUE TITLE
Store/website level prices not being pulled successfully in product sync/feed.

### ISSUE THREAD

**Issue by ccrothers** [mailchimp/mc-magento2#413]
Preconditions:
• Have at least two stores created for your magento 2 instance
• Be using Magento 2 Enterprise, version 2.1.6 (do NOT use community)
• Be using mc-magento2 version 1.0.29
• have one monkeystore set at default level from stores > config > mailchimp
• have a second monkey store set at your second store's store view from stores > config > mailchimp

Steps to Reproduce:
• create a product
• set a price for the product
• complete any other required feilds and create the product
• edit the same product, and change the store view to be the second store's store view .
• set the price to be something different than what was set in the default store view
• trigger the product to sync with mailchimp via the ebizmart_ecommerce cron job for both monkey stores.

Expected Result: the product syncs successfully for both stores
Actual Result: the product does not sync, and an error in mailchimp_errors indicates that the product did not have a price.

Additional Information: 
• Not sure which store, if not both, the product failed to sync with.
• When unsetting the price at the second store view's level, making it inherit the default store view's price, the product is able to sync successfully.

**Comment by gonzaloebiz** [comment]
Hi @ccrothers 

please specify which version of mc-magento2 are you using

Best

**Comment by ccrothers** [comment]
done.

**Comment by gonzaloebiz** [comment]
Please take a look at #391
This issue is already fixed in 1.0.30 version

**Comment by ccrothers** [comment]
this issue is unrelated to special price. this one is for regular price (when set at various store levels).

Are you certain the "special price management" commit addresses this bug too?

**Comment by gonzaloebiz** [comment]
Please try with the 1.0.30 version, i'm pretty sure.
But we will be pleased to re open the issue if not

Best
