### ISSUE TITLE
Exentension uses special from/to dates, attributes which Magento enterprise does not support

### ISSUE THREAD

**Issue by ccrothers** [mailchimp/mc-magento2#414]
Preconditions:
• Be using Magento 2 Enterprise, version 2.1.6 (do NOT use community)
• Be using mc-magento2 version 1.0.29
Steps to Reproduce:
• create a product
• set the product to use special price
• Optional: unset the product's price
• special price is not sent to mailchimp

Expected Result: special price is used
Actual Result: the regular price (incorrect price) is used, not the special price. If optional step taken, price will be incorrectly set to null and mailchimp will show an error.

Additional Information:
• Enterprise special price confusion/clarification 
https://maxchadwick.xyz/blog/magento-2-enterprise-special-price-confusion
• Magento 2's stance on the use of special from/to date on Enterprise
https://github.com/magento/magento2/issues/5984#issuecomment-360345397
• Refer to Model/Api/Product.php:368 within your extension for the location in which this check occurs.
• If special from/to date IS used (ie, by another extension), mailchimp will improperly use the attribute to determine whether the use special price, and if no special price exists, it does not default back to using regular price.

**Comment by gonzaloebiz** [comment]
Hi @ccrothers

please specify which version of mc-magento2 are you using

Best

**Comment by ccrothers** [comment]
done.

**Comment by gonzaloebiz** [comment]
Please take a look at https://github.com/mailchimp/mc-magento2/issues/391
This issue is already fixed in 1.0.30 version
