### ISSUE TITLE
Checkout is not loading in the production environment

### ISSUE THREAD

**Issue by bcmageteam** [mailchimp/mc-magento2#415]
# Issue reporting guidelines

To maintain an effective bugfix workflow and make sure issues will be solved in a timely manner we kindly ask reporters to follow some simple guidelines.

Before creating an issue, please do the following:

* Make sure the behavior you are reporting is really a bug, not a feature.
* Check the existing [issues](https://github.com/mailchimp/mc-magento2/issues) to make sure you are not duplicating somebody’s work.
* Make sure, that information you are about to report is a technical issue, please refer to the [Community Forums](http://ebizmarts.com/mailchimp-for-magento-support)  for technical questions.

If you are sure that the problem you are experiencing is caused by a bug, file a new issue in a Github issue tracker following the recommendations below.

## Titlement
 
> Checkout is not loading in the production environment

## Issue Description
> We have integrated MailChimp extension on our store. Once we enable the Production environment for the store then checkout page is not getting loaded properly. It sticks to somewhere. In the developer environment, it is working fine. 

### Preconditions

> We have used the default settings only and followed the instructions as mentioned your official website.
    1. Magento CE 2.1.9 with sample data is installed.
    2. mc-magento2 1.0.29.
    3. Test category is set up.

### Steps to reproduce
>
    1. Navigate to storefront as a guest.
    2. Open Test Category.
    3. Click "Add to Cart" on any Product.
    4. Open mini shopping cart and click "Proceed to Checkout".
    5. The checkout page would be hanged up if you are in the production environment. The loader would be displayed 
### Actual and Expected result
>
    Expected result:
    Checkout should work perfectly for the guest customer and the logged in customer also.
    Actual result:
    The checkout page is not getting loaded

### Additional information

If the extension is enabled: https://drive.google.com/file/d/1YgTg8Syf2E-7NMQCs5FiVcL9sVd6zHr7/view
If the extension is disabled: https://drive.google.com/file/d/1ab4S-t1pvFaSiynKIka1WQsFXAAlotdx/view

**Comment by gonzaloebiz** [comment]
Hi @bcmageteam 

thanks for your feedback.
We can't reproduce your issue. The extension has more than 95K installations, should be impossible to use with this issue, so i think is more an issue in some of your side.
Open the developers tool in your browser and inspect the console and network tabs, perhaps you have some light there to start.

Best

**Comment by bcmageteam** [comment]
Hi @gonzaloebiz 
Thank you for your quick response. I understand that this extension is very popular and works perfectly. But I am using Magento 2.1.9 and have checked the multiple cases. Whenever I disable this extension then the checkout works perfectly. I have tried to set up this extension on Magento 2.2.5 and there it seems working fine. But not sure, why is not working for me. I have tried to upgrade the extension but doesn't work.

Please help if you can.

Thank you again!

**Comment by gonzaloebiz** [comment]
Open the developers tool in your browser and inspect the console and network tabs, perhaps you have some light there to start.

Best

**Comment by bcmageteam** [comment]
I have checked but can't see any error and failure

**Comment by bcmageteam** [comment]
I am using custom checkout and custom theme but I have tried to disable both of them and tried to run with default. Doesn't seem working

**Comment by gonzaloebiz** [comment]
Can you please send us your store url to mailchimp@ebizmarts-desk.zendesk.com mentioning this issue, and of course leave the extension enabled

Best

**Comment by bcmageteam** [comment]
Thank you. I will share the details with you by tomorrow as soon as possible.

**Comment by gonzaloebiz** [comment]
Hi @bcmageteam 

we only include these 2 js in the checkout page

![image](https://user-images.githubusercontent.com/6222792/46545644-45b96a00-c89d-11e8-9c84-7209c49c5a09.png)

![image](https://user-images.githubusercontent.com/6222792/46545698-67b2ec80-c89d-11e8-8469-307c8794993d.png)

you can see it in the network tab of the developer tools in your browser

In other hand, we see you have an error (see in the console tab)

![image](https://user-images.githubusercontent.com/6222792/46545812-c4160c00-c89d-11e8-989f-ed03bddf093e.png)

Try with the default checkout

**Comment by bcmageteam** [comment]
Hi @gonzaloebiz 

Thank you for updating me. Yes, I have checked that you are using only 2 JS files in the checkout page. Also, I have already tried with default checkout but doesn't seem working for me. 

The error displaying the console is not related to that. It is coming even after disabling the extension. 

Please help me out if possible. I can share the FTP and admin credentials with you. 

Thank you in advance and your support would be highly appreciated.

**Comment by bcmageteam** [comment]
Apart from this, as per your suggestion, I have posted my concern on the email mailchimp@ebizmarts-desk.zendesk.com. 

Looking forward to hearing from there also.

**Comment by gonzaloebiz** [comment]
Hi @bcmageteam 

as you can understand mc-magento2 is a FREE extension with more than [96K installations](https://packagist.org/packages/mailchimp/mc-magento2) and is not possible for us offer on site support.
As you can view, our 2 js are so simple.
Typically this happens because some request return an error, a 503 or some data invalid, as i can see is not your case. Or a js error, so i think you don't have other option than debug the js to found where the issue is.

Best

**Comment by bcmageteam** [comment]
Hi @gonzaloebiz 
Thank you for the update. I have tried to debug the code. I found the following file which is conflicting with our system. Would you please confirm the use of this code and file?

==============
Ebizmarts/MailChimp/view/frontend/templates/catcher.phtml

======
code: <div id="monkey_campaign" style="display:none;" data-mage-init='{"campaigncatcher":{}}'>
</div>

**Comment by gonzaloebiz** [comment]
Hi @bcmageteam 

yes sure, you can find the file here https://github.com/mailchimp/mc-magento2/blob/develop/view/frontend/templates/catcher.phtml
This template load the js defined in https://github.com/mailchimp/mc-magento2/blob/develop/view/frontend/requirejs-config.js

Best

**Comment by bcmageteam** [comment]
Hi @gonzaloebiz ,

Yes that I also have. When I am trying to debug campaigncatcher.js that doesn't allowing me. Debugger is not rendering. Also, I just wanted to know that is this JS file add some content to above template?

Thanks

**Comment by gonzaloebiz** [comment]
As this line say

https://github.com/mailchimp/mc-magento2/blob/develop/view/frontend/requirejs-config.js#L14

this is the file 

https://github.com/mailchimp/mc-magento2/blob/develop/view/frontend/web/js/campaigncatcher.js

Best
