### ISSUE TITLE
NULL price when special price is not set, but special price dates are set 

### ISSUE THREAD

**Issue by arendarenko** [mailchimp/mc-magento2#416]
## Description
Sometimes when syncing several products Mailchimp returns an error: "variants.item:0.price Schema describes number, NULL found instead", this also causes incorrect import of orders that contains those products.

## Steps to reproduce:

Create product with price $40
Set such advanced price options:
2.1. Special price = empty field
2.2. Special price from = any past date (for example: 30/09/2018)
Save & try to import it into MailChimp

**Expected result:**
Product will be exported with price $40

**Actual result:**
Product will try to exported with NULL price (because module tries to use special price if it's date range is correct, but didn't check exact value of advanced price!). As result, product will NOT exported to MailChimp and you will receive an error: "variants.item:0.price Schema describes number, NULL found instead".

**Comment by gonzaloebiz** [comment]
Closed by https://github.com/mailchimp/mc-magento2/pull/403
