### ISSUE TITLE
Product Image does not show on abandoned cart email template / order details 

### ISSUE THREAD

**Issue by maximbaibakov** [mailchimp/mc-magento2#425]
### Preconditions

There is no product image for order or abandoned cart email shown for a simple / configurable products combination in case of images are stored on configurable level.  

Example:

    1. Magento CE 2.2.3 without sample data is installed.
    2. mc-magento2 1.0.29

### Steps to reproduce

    1. Create an order using a configurable product where images stored on configurable level.
    2. Order is pushed to Mailchimp
    3. Look into order details, image url is empty

### Actual and Expected result

    Expected result:
    - See an image for the product in mailchimp

    Actual result:
    - No image is shown

**Comment by gonzaloebiz** [comment]
Hi @maximbaibakov 

thanks for your feedback.
I followed your steps and can't reproduce your issue. The images are there, for both the configurable and all the simples. (the configurable has the image of the first simple)

Best

**Comment by adamj88** [comment]
@gonzaloebiz we're seeing the same issue - unsure of the steps to replicate it, but we're seeing all simple products in Mailchimp without imagery where as their parent products do.

If there's any more information I can provide please let me know.

**Comment by gonzaloebiz** [comment]
Hi @adamj88 

we need a way to reproduce the issue, as you know the possibilities are really a lot. We can't fix something we can't reproduce.

Best

**Comment by maximbaibakov** [comment]
Hi @gonzaloebiz 

Probably a bit detailed steps would help.

**Precondition:** 
Magento 2.2.3 or latest
Mailchimp 1.0.30
Test set of products must not exist in Mailchimp

**Steps to reproduce**
1. Create a configurable product based on size
2. Create 5 simple products and assign them to the configurable. DO NOT ADD ANY IMAGES. 
3. Add images on configurable product
4. Wait 15-20 minutes to sync everything to Mailchimp
5. Go to frontend and open the configurable product
6. Select size and order the product. do not order a simple product, but configurable.
7.  Wait 15-20 minutes to sync everything to Mailchimp
8. Go to Magento Backend, edit a simple product which you have used in the order and change the title, save the product.
9. Wait 15-30 minutes to sync everything to Mailchimp
10. Go to Mailchimp and view E-commerce transaction of your customer, you should see your order, however, product associated for the order does not have image. 

Hope this helps.

The thing was working fine in 1.0.27 and got broken in 1.0.28 by this commit https://github.com/mailchimp/mc-magento2/commit/63d777a97b6d21a76bcf501050a771281f79e725
The export used to export configurable product ID instead of simple product ID.   

Regards,
Maxim
