### ISSUE TITLE
Subscriber which was added in MailChimp doesn't have storeId in Magento2

### ISSUE THREAD

**Issue by arendarenko** [mailchimp/mc-magento2#427]
### Preconditions

When enabled Two-way sync and you create new subscriber in List which is connected to Magento2 website, after syncing newly added to Magento2 subscriber didn't have any storeId. Which means that if there is a registrated customer for current website, it wouldn't be synced with this subscriber

    1. Magento 2.2.5 is installed
    2. mc-magento2 1.0.30.

### Steps to reproduce

1. Go to Mailchimp -> Lists -> Edit list that related to your store
2. Add new subscriber with email that didn't appearing in Magento2
3. Wait for syncing 

**Expected result:**

Subscriber in Magento2 would be created with storeId which related to your store

**Actual result:**

Subscriber in Magento2 is created with empty store.

**Comment by gonzaloebiz** [comment]
Closed by https://github.com/mailchimp/mc-magento2/pull/428
