### ISSUE TITLE
Store Configration page for Mailchimp went blank due to "map_fields" Field

### ISSUE THREAD

**Issue by nirajketan** [mailchimp/mc-magento2#435]
After installing module and mailchimp-lib i tried to go to mailchimp -> Configuration but page is blank when i open it

I debugged it and found its due to map_fields field

![image](https://user-images.githubusercontent.com/12871321/47255918-30dff780-d495-11e8-90f4-7c9e5d047557.png)

After I comment that field page loads well

Can you try give it try on latest and fresh magento 2.2.5 ?

**Comment by gonzaloebiz** [comment]
Hi @ngagestudios 

thanks for your feedback, please follow the [issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)
Yes of course, we test it before release each new version
