### ISSUE TITLE
Error in cron ebizmarts_webhooks

### ISSUE THREAD

**Issue by inelukipg** [mailchimp/mc-magento2#447]
### Preconditions

    1. Magento CE 2.2.3
    2. mc-magento2 1.0.30

### Steps to reproduce

    1. Add store
    2. Start sync with mailchimp

### Actual and Expected result
Error in cron logs and webhook doesnt't seem to work:
Notice: unserialize(): Error at offset 48 of 111 bytes in /www/magento2/vendor/mailchimp/mc-magento2/Cron/Webhook.php on line 82

    Expected result:
 No errors in cron-log.
Webhook should work.

### Additional information
Syncing data to mailchimp works fine.

**Comment by gonzaloebiz** [comment]
Hi @inelukipg 

thanks for your feedback.
The webhook cron process events that happens in MC, and are sent to magento. We need to know what do you do in MC to try to replicate.
You can see the these events in the table mailchimp_webhook_request

Best

**Comment by inelukipg** [comment]
Hi again,
I think all of the types throws errors?
Types: subscrible, profile, campaign all got processed=0.

![mailchimp_webhook](https://user-images.githubusercontent.com/23335844/47573272-3463fa80-d93d-11e8-871a-6a684eebec94.jpg)

**Comment by gonzaloebiz** [comment]
Hi @inelukipg 

can you please send me a dump of this table to our support email mentioning the issue number? mailchimp@ebizmarts-desk.zendesk.com

Best

**Comment by gonzaloebiz** [comment]
Hi @inelukipg 

the new version 1.0.32 fix this, you can take a look at this https://github.com/mailchimp/mc-magento2/issues/451 and this https://github.com/mailchimp/mc-magento2/issues/455

Best

**Comment by inelukipg** [comment]
HI @gonzaloebiz 
Webhooks seems to work now without errors in version 1.0.32! 
Thank you! Great work!
