### ISSUE TITLE
Don't use serialize function directly

### ISSUE THREAD

**Issue by gonzaloebiz** [mailchimp/mc-magento2#451]
Thanks @ihor-sviziev for note that
https://github.com/mailchimp/mc-magento2/issues/438#issuecomment-434654731

**Comment by gonzaloebiz** [comment]
https://github.com/mailchimp/mc-magento2/commit/a6159df0b5e1e83a3fb334e1aa928af5eef19b81

**Comment by ihor-sviziev** [comment]
Hi @gonzaloebiz,
It's not enough, in DB we still have serialized data, we have to covert it to JSON format

**Comment by gonzaloebiz** [comment]
i know, the issue is not closed, we are working on, don't worry about we know what we do
