### ISSUE TITLE
Error: MailChimpLogger.INFO: Resource Not Found for Api Call: https://us11.api.mailchimp.com/3.0/lists//interest-categories using method [GET]

### ISSUE THREAD

**Issue by arendarenko** [mailchimp/mc-magento2#459]
### Preconditions

Example:

    1. Magento CE 2.2.6 without sample data is installed.
    2. mc-magento2 1.0.30.
    3. Interests are not set
    ...

### Steps to reproduce

1. Setup mailchimp module without setting interests settings
2. Add new subscribers in Magento2
3. Run module cronjobs

### Expected result:

1. Subscribers will be sent to MailChimp successfully without any error

### Actual result:

1. Subscribers are added but we also receiving error in Mailchimp.log:
`[2018-11-06 09:48:08] MailChimpLogger.INFO: Resource Not Found for Api Call: https://us11.api.mailchimp.com/3.0/lists//interest-categories using method [GET]`

**Comment by duckchip** [comment]
Hi there!
Is there any progress on this issue? :)

**Comment by gonzaloebiz** [comment]
Hi @duckchip 

please read at https://github.com/mailchimp/mc-magento2/pull/460

Best

**Comment by pmathbliss** [comment]
#459 rereferences this issue.

**Comment by jaimiedijstra** [comment]
Just come across this error on my site too, Magento 2.3.5p2 and Mailchimp v102.3.41. Just wanted to check this here with the devs as this issue loop references issue #460 so no clear answer.
On my cron time and logs this issue just crops up now and again (only twice in the last 24 hours, no load issues on my server or other issues), but then works fine again, is this just connectivity Mailchimp side and no concern?
![image](https://user-images.githubusercontent.com/12552943/100606065-cff99d80-3343-11eb-8d59-6d50e6893db4.png)
