### ISSUE TITLE
Enabling the Mailchimp extension, the .checkout-loader (spinner image) loads indefinitely on the Checkout page.

### ISSUE THREAD

**Issue by snirouk** [mailchimp/mc-magento2#465]
When enabling the Mailchimp extension, the .checkout-loader (spinner image) loads indefinitely on the Checkout page.

There are no JS errors or any other signs of failure, except the spinner not getting removed. When removing it "by hand" (via "Inspect element"), the checkout works correctly.

Did anyone else experience this issue on the Checkout page before?

Magento ver. 2.1.8
MailChimp v1.0.30 by ebizmarts

See if anyone can help.

**Comment by gonzaloebiz** [comment]
Already has a ticket
