### ISSUE TITLE
Avoid getByEmail calls when sending Orders and Carts to Mailchimp

### ISSUE THREAD

**Issue by ihor-sviziev** [mailchimp/mc-magento2#468]
### Preconditions

    1. Magento CE 2.2.6 without sample data is installed.
    2. mc-magento2 1.0.30.
    3. ~100k orders that we want to sync to Mailchimp

### Steps to reproduce
N/A

### Actual and Expected result

Right now cron job ebizmart_ecommerce runs every 5 minutes and took ~4 minutes for me. Preparing orders info takes ~3.5 minutes of that time

### Additional information

During preparing orders export there is two calls to Mailchimp API for getting customer info:
1. https://github.com/mailchimp/mc-magento2/blob/0c5d37990dd4d20d3974e3cf45fb84751fa20ab5/Model/Api/Order.php#L369
2. https://github.com/mailchimp/mc-magento2/blob/0c5d37990dd4d20d3974e3cf45fb84751fa20ab5/Model/Api/Order.php#L391

As result of 2nd requests we usually getting following error in logs:
```
[2018-11-09 12:14:05] MailChimpLogger.INFO: Resource Not Found for Api Call: [https://us11.api.mailchimp.com/3.0/ecommerce/stores/c165314426294f1f4aff49977407e962/customers/353087?fields=email_address] using method [GET]
	Detail: [The requested resource could not be found.]
	Params:
		{"fields":"email_address"}
 [] []
```

Usually these requests took ~0.2 seconds each.

How it can be improved:
1. Create table with following info - mailchimp store id, mailchimp customer id and email. 
2. During customers export - export customers that are needed for orders at first, then fill up this table
3. When exporting customers - export customers that required for orders sync at first
4. during orders export - use data from table for getting this info.

**Comment by gonzaloebiz** [comment]
Hi @ihor-sviziev 

thanks for your feedback.
We are open to PR

Best
