### ISSUE TITLE
Setup some CI for running static tests

### ISSUE THREAD

**Issue by ihor-sviziev** [mailchimp/mc-magento2#469]
Would be great to add some CI for running tests, adding at lease static tests will significantly improve code style in the module.

Here is some CI tools that are free for open source projects:
https://travis-ci.org/
https://circleci.com/

You can start running https://github.com/magento/marketplace-eqp.

Also would be great to add some tool for validating supported php versions. Example: https://github.com/PHPCompatibility/PHPCompatibility

**Comment by gonzaloebiz** [comment]
We know, thanks
