### ISSUE TITLE
"Unable to unserialize value " when run the ecommerce cron process

### ISSUE THREAD

**Issue by gonzaloebiz** [mailchimp/mc-magento2#473]

**Comment by gonzaloebiz** [comment]
For Magento 2.1 apply commit https://github.com/mailchimp/mc-magento2/commit/edcb010b61b02910368019297960942cba717dea

For Magento 2.2 apply commit https://github.com/mailchimp/mc-magento2/commit/645a10d087d77b2fc0876aa7c2ef84b2cde544d4

**Comment by duckchip** [comment]
@gonzaloebiz Is there a reason why you are not fixing this in a new version?

**Comment by gonzaloebiz** [comment]
If you install the dev branch for your magento version you can see it fixed

**Comment by yaronuliel** [comment]
Is there any expected release date for the milestone that includes this fix (1.0.33)?
We are currently using `develop-2.2` - but I'd really prefer not to deploy development branch to live sites..
Thanks a lot!

**Comment by crankycyclops** [comment]
@yaronuliel, I'd like to ask the same question :) I'm having the same issue with my configuration and also need this fix. No rush, just wondering what the ETA will be on 1.0.33. Thank you!

**Comment by InishowenLabs** [comment]
Just tried deploying this using the 2.3-develop branch and still getting the error:

`[2018-12-30 20:05:13] main.ERROR: Cron Job ebizmarts_ecommerce has an error: Unable to unserialize value.. Statistics: {"sum":0,"count":1,"realmem":0,"emalloc":0,"realmem_start":48496640,"emalloc_start":47697072} [] []`

Other Mailchimp cron jobs work with no issue

**Comment by jbokhari** [comment]
@gonzaloebiz Pardon the ignorance, but can you elaborate on "apply commit ..." or "install the dev branch", I'm not sure how this is done. I have [installed using composer](http://wiki.ebizmarts.com/installation-guide-m4m2) and I've been waiting for a fix on the main branch.

Would either of these choices cause an issue updating later?

**Comment by gonzaloebiz** [comment]
you can install any branch with

composer require mailchimp/mc-magento2:dev-develop-2.2

you can use : to specify the branch

Best
