### ISSUE TITLE
Fake email error shows success message to customer

### ISSUE THREAD

**Issue by simonrl** [mailchimp/mc-magento2#476]
I have checked the current issues and have not found that behaviour there.

### Preconditions

    1. Magento CE 2.1.14 with production data in production mode
    2. mc-magento2 1.1.32
    3. "newsletter/subsciber/confirm" is set to "0" in global scope, but "1" in website & store view
    4. "Always use Magento to send mails" is set to "No"
    5. The MailChimp list is GDPR compliant, so it should also use double opt-in

### Steps to reproduce

Example:

    1. enter an email address from a fake provider, for example xxx@trash-mail.com
    2. subscribe

### Actual and Expected result

    Expected result:
    - the frontend shows the message "We have sent you a confirmation", or an error message
    - the user actually gets a confirmation if the success message is shown
    - if an error message is shown, the subscriber should not be created
   
    Actual result:
    - the frontend shows the message "We have sent you a confirmation"
    - no confirmation is sent
    - the subscriber is created as "pending" in Magento
    - the MailChimp.log shows:
```
MailChimpLogger.INFO: Invalid Resource for Api Call: [https://us14.api.mailchimp.com/3.0/lists/[...]] using method [PUT]
        Detail: [xxx@trash-mail.com looks fake or invalid, please enter a real email address.]
{"status":"pending","email_address":"nl2@trash-mail.com","status_if_new":"pending"}^M
```

**Comment by simonrl** [comment]
Could we get feedback on this please? Thanks!

**Comment by gonzaloebiz** [comment]
@simonrl 

the fake email control is made by mailchimp, if you add a fake email as a subscriber in magento we don't have how to know that is a fake, so the natural process of magento is add the email to the list but never confirmed

Best
