### ISSUE TITLE
Unable to unserialize value in customer view if $interestGroup->getGroupdata() is null

### ISSUE THREAD

**Issue by thisisme** [mailchimp/mc-magento2#478]
Magento 2.2.6
Customers in place and working
Install mailchimp with composer
Select any customer under Customers->All customers
Result: 'Unable to unserialize value.'
Result of $interestGroup->getGroupdata() is NULL in vendor/mailchimp/mc-magento2/Helper/Data.php::getSubscriberInterest

**Comment by gonzaloebiz** [comment]
Please see at https://github.com/mailchimp/mc-magento2/issues/473
