### ISSUE TITLE
Not activated subscribers are pushed to mailchimp

### ISSUE THREAD

**Issue by inelukipg** [mailchimp/mc-magento2#479]
### Preconditions

    1. Magento CE 2.2.3
    2. mc-magento2 1.0.32
    3. Stores / Configuration / Newsletter / Subscription Options / Need to Confirm = YES

### Steps to reproduce

Add a new customer that signs up for newsletter

### Actual and Expected result

Customers e-mail is pushed to mailschimp right away.

Expected result:
Only confirmed e-mail adresses should be pushed to mailchimp.

**Comment by gonzaloebiz** [comment]
Hi @inelukipg 

thanks for your feedback, what is the configuration of the field "Magento always manage emails"?

Best

**Comment by ihor-sviziev** [comment]
Hi @gonzaloebiz,
Issue was created not by me, so probably you wanted to ask @inelukipg the same question 🙂

**Comment by inelukipg** [comment]
HI @gonzaloebiz 
The setting is: No

I don´t really understand the meaning of that setting.

**Comment by gonzaloebiz** [comment]
Hi @inelukipg 

can you specify if you subscribe the customer in the same page that you create the customer 
![image](https://user-images.githubusercontent.com/6222792/49741162-8e621a80-fc74-11e8-9ca0-f42b5457a7a0.png)

or first your create the customer, and then subscribe like
![image](https://user-images.githubusercontent.com/6222792/49741048-522eba00-fc74-11e8-8eb4-f7d3252cb2d2.png)
