### ISSUE TITLE
Add option to not send Promo Codes and Promo Rules

### ISSUE THREAD

**Issue by ebizmarts-keller** [mailchimp/mc-magento2#481]
Add a setting in the configuration to not send Promo Codes and Promo Rules with the Ecommerce data.

**Comment by gonzaloebiz** [comment]
For magento 2.1 apply commit https://github.com/mailchimp/mc-magento2/commit/df27cd43186773d5cfc49dd5e7110f89d8d58a7a
For magento 2.2 apply commit https://github.com/mailchimp/mc-magento2/commit/05cab67e7ae6de208f5feb0a23965d7a0e7ac1b4
