### ISSUE TITLE
Installation Issue: sales_order_grid table not found

### ISSUE THREAD

**Issue by ghost** [mailchimp/mc-magento2#482]
Hello,

I am posting this issue with reference of the issues(#276, #184) that are already posted but did not got any solution from there.

I am facing issue while installing mailchimp. When I execute setup upgrade command after installing mailchimp I get following error and stops the upgrade there so site also stops working:

> Base table or view not found: 1146 Table 'db_name.sales_order_grid' doesn't exist, query was: DESCRIBE sales_order_grid

This table was there before we install mailchimp and ran setup upgrade command. It gets deleted when we try to run setup upgrade after installing mailchimp.

I have tried different versions(1.1.32, 1.0.32, 1.0.30) of mail chimp as well but got the same error in all three versions. We need to uninstall mailchimp and re-import the table than the site again works proper as before and all commanf executes proper.

We have database table prefix in our project.

**Comment by gonzaloebiz** [comment]
I just try with magento 2.2.6 with database prefix m2_

![image](https://user-images.githubusercontent.com/6222792/48913042-10b9a480-ee56-11e8-9845-bc266754ad2e.png)

 and install mc-magento2 version 1.0.30

![image](https://user-images.githubusercontent.com/6222792/48912921-ad2f7700-ee55-11e8-9029-f40ee504cd78.png)

run the corresponding bin/magento setup:upgrade and no problem, the sales_order_grid is still there

Also try updating the extension to 1.0.32 without any problem

We only add a column on the sales_order_grid there https://github.com/mailchimp/mc-magento2/blob/develop/Setup/UpgradeSchema.php#L399-L407

We close the issue for now, waiting some other data to try to replicate it

Best

**Comment by ghost** [comment]
Hello,

We are facing this error with all the above versions I mentioned.

I missed out one scenario that we have uninstalled Magemonkey and than installed this mailchimp and getting this error.

Let me know if this cause the above issue and provide me with solution if that is the case.

**Comment by gonzaloebiz** [comment]
Hi @NirmalRaval 

please let me know the steps your follow to uninstall Magemonkey

Best

**Comment by ghost** [comment]
Hello,

We have removed the Magemonkey extension from app/code folder and ran the setup upgrade command.

Let us know if we need to take care of anything else to uninstall that.

**Comment by gonzaloebiz** [comment]
Sorry, can you let me know step by step how to reproduce your issue. Please follow the [Issue reportig guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)

- What is your magento version
- What steps you follow to install Magemonkey, which version you install
- What steps you follow to uninstall it
- What steps your follow to install mc-magento2

Neither of the two extensions does something like drop the table

**Comment by ghost** [comment]
Here are the details:

- Magento version is 2.2.6
- We have downloaded the extension and added in code and executed Setup Upgrade command to install the extension. Magemonkey version was 3.0.7
- We have deleted the code of Magemonkey extension from project and executed Setup Upgrade command to uninstall the extension.
- We have first installed mc-magento2 using composer but faced above error while doing Setup Upgrade. Than we installed it by downloading the extension from ebizmart site and installing mailchimp lib using composer. We have tried three different versions(1.1.32, 1.0.32, 1.0.30) but faced same issue in all three.

Let me know if you need any more details.

**Comment by meetvora69** [comment]
Hello,

We have faced the same issue. 
We have used Magento version 2.1.7 .

Thanks,
