### ISSUE TITLE
marketplace version (1.1.32) doesn't install on fresh instances

### ISSUE THREAD

**Issue by heldchen** [mailchimp/mc-magento2#485]
## Title

`composer require mailchimp/mc-magento2` fails on fresh installations

### Preconditions

1. Magento CE 2.2.6 without sample data is installed
2. composer is up to date
3. no mailchimp package is installed

### Steps to reproduce

1. `composer require mailchimp/mc-magento2`

### Actual and Expected result

Expected Result:
Package is installed

Actual result:
Package has requirements that cannot be resolved:
``` 
#composer require mailchimp/mc-magento2
Using version ^1.1 for mailchimp/mc-magento2
./composer.json has been updated
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mailchimp/mc-magento2 ^1.1 -> satisfiable by mailchimp/mc-magento2[1.1.32].
    - Conclusion: remove magento/framework 101.0.6
    - Conclusion: don't install magento/framework 101.0.6
    - mailchimp/mc-magento2 1.1.32 requires magento/framework 100.1.* -> satisfiable by magento/framework[100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6, 100.1.7, 100.1.8, 100.1.9, 100.1.10, 100.1.11, 100.1.12, 100.1.13, 100.1.14, 100.1.15, 100.1.16].
    - Can only install one of: magento/framework[101.0.6, 100.1.0].
    - Can only install one of: magento/framework[101.0.6, 100.1.1].
    - Can only install one of: magento/framework[101.0.6, 100.1.2].
    - Can only install one of: magento/framework[101.0.6, 100.1.3].
    - Can only install one of: magento/framework[101.0.6, 100.1.4].
    - Can only install one of: magento/framework[101.0.6, 100.1.5].
    - Can only install one of: magento/framework[101.0.6, 100.1.6].
    - Can only install one of: magento/framework[101.0.6, 100.1.7].
    - Can only install one of: magento/framework[101.0.6, 100.1.8].
    - Can only install one of: magento/framework[101.0.6, 100.1.9].
    - Can only install one of: magento/framework[101.0.6, 100.1.10].
    - Can only install one of: magento/framework[101.0.6, 100.1.11].
    - Can only install one of: magento/framework[101.0.6, 100.1.12].
    - Can only install one of: magento/framework[101.0.6, 100.1.13].
    - Can only install one of: magento/framework[101.0.6, 100.1.14].
    - Can only install one of: magento/framework[101.0.6, 100.1.15].
    - Can only install one of: magento/framework[101.0.6, 100.1.16].
    - Installation request for magento/framework (locked at 101.0.6) -> satisfiable by magento/framework[101.0.6].


Installation failed, reverting ./composer.json to its original content.
```

### Additional information

there seems to be an attempt to have this fixed here on github (commit from a few days ago), but that still leaves the version on the magento repo in a broken state... _unless_ one explicitly requires `mailchimp/mc-magento2:1.0.*`

**Comment by gonzaloebiz** [comment]
Hi @heldchen 

you must specify which version you want to install, p.e.

composer require mailchimp/mc-magento2:1.0.32

best

**Comment by heldchen** [comment]
not according to setup docs floating around (f.e. http://wiki.ebizmarts.com/installation-guide-m4m2). can't you have magento remove the bogus 1.1.32 from the marketplace?

**Comment by gonzaloebiz** [comment]
Sorry, i don't understand the mention to the 1.1.32 version, this version as you can see there https://github.com/mailchimp/mc-magento2/releases is for magento 2.1

**Comment by heldchen** [comment]
~the magento marketplace composer (repo.magento.com)~ packagist still contains the broken 1.1.32 version:
```
composer show mailchimp/mc-magento2 -a
name     : mailchimp/mc-magento2
descrip. : Connect MailChimp with Magento
keywords :
versions : dev-master, 1.1.32, 1.0.32, 1.0.30, 1.0.29, 1.0.28, 1.0.27, 1.0.26, 1.0.25, 1.0.24, 1.0.23, 1.0.22, 1.0.21, 1.0.20, 1.0.19, 1.0.18, 1.0.17, 1.0.16, 1.0.15, 1.0.9, 1.0.8, 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0, dev-develop-2.2, dev-develop-2.1, dev-develop, dev-issue481-2.2, dev-Issue481-2.1, dev-issue473, dev-BadVersion
type     : magento2-module
license  : Open Software License 3.0 (OSL-3.0) (OSI approved) https://spdx.org/licenses/OSL-3.0.html#licenseText
license  : Academic Free License v3.0 (AFL-3.0) (OSI approved) https://spdx.org/licenses/AFL-3.0.html#licenseText
source   : [git] https://github.com/mailchimp/mc-magento2.git fda84242213888b37cff7d63409cceab54e8755c
dist     : [zip] https://api.github.com/repos/mailchimp/mc-magento2/zipball/fda84242213888b37cff7d63409cceab54e8755c fda84242213888b37cff7d63409cceab54e8755c
names    : mailchimp/mc-magento2

autoload
psr-4
Ebizmarts\MailChimp\ => .
files

requires
ebizmarts/mailchimp-lib 3.0.*
```
and as this is the currently highest version number, this is the target for new installations (without explicitly specifying the version)

edit: hmm ok I get it. 1.1.x is for magento 2.1, and 1.0.x for magento 2.2. this is unfortunate for those that are installing your extension on magento 2.2 (and soon 2.3), as the wrong version will be tried by composer.

**Comment by gonzaloebiz** [comment]
This is the way that composer work, always try to get the last released version, we can't do it nothing about

**Comment by heldchen** [comment]
well, you could make sure that an older magento release (here: 2.1) not suddenly has a newer extension version (here: 1.1.32) than the most recent magento release (2.2 / 1.0.32). I understand the reasoning behind it, but in the long run, it will cause confusions. especially as there's currently nowhere in the mailchimp.com installation steps noted anything about this particular versioning.

 in an optimal world, the next release for magento 2.2+ would now receive a version like 1.2.33 :)
