### ISSUE TITLE
Products data not sync

### ISSUE THREAD

**Issue by elisongit** [mailchimp/mc-magento2#491]
# Description

### Preconditions

- Magento version 2.1.9
- Mailchimp module version 1.0.30 (we not install new version 1.0.32 because not compatible with our version of Magento)
- 2 environment (staging and production), each with a Mailchimp account connected

### Problems

When we edit an existing product or add new product they will not be synced to his Mailchimp backoffice.

### Step to reproduce

- edit title an existing product
- this product not is present in table "mailchimp_sync_ecommerce"
- in table "mailchimp_sync_ecommerce" more row with type = "PRO" not have batch_id assigned
- in table "cron_schedule" job "ebizmarts_ecommerce" has status "success" but job "ebizmarts_webhooks" has always status "missed"

### Additional information

Attach the screenshot of our production configuration.

![mailchimpconfiguration](https://user-images.githubusercontent.com/7591295/49091775-ccb50e00-f260-11e8-8445-ed5bc04d715d.png)

Please may you help us?

**Comment by gonzaloebiz** [comment]
Hi @elisongit 

please contact our support team.

Best
