### ISSUE TITLE
v1.0.32: Abandoned carts not deleted from Mailchimp after conversion

### ISSUE THREAD

**Issue by crankycyclops** [mailchimp/mc-magento2#495]
I'm currently using the Abandoned cart feature of the module, but have noticed on more than one occasion that when a cart is at first abandoned, then later converts, that subscriber is never removed from my abandoned cart automation. I've confirmed that the abandoned cart is removed from Magento by looking at the abandoned cart report, but that doesn't appear to be syncing to Mailchimp.

Steps to reproduce:
1. Install and configure the mc-magento2 module, connect it to your Mailchimp account, and create an abandoned cart series.
2. Register a Magento user account, add items to your cart, start the checkout process and then abandon it.
3. Log out, log back in and compete the checkout.

Expected result:

The deletion of the abandoned cart should be synced to Mailchimp, and the user should be removed from Mailchimp's automation queue

Actual result:

While the abandoned cart is deleted from Magento, the cart doesn't appear to sync to Mailchimp, and the email is still sent to the user.

I've tested this on Magento 2.2.6 with PHP 7.1 and the latest version of the module, 1.0.32.

I had previously contacted Mailchimp support, who then told me I should get in touch with the developers directly. They did tell me that using a custom payment option might be the reason for this issue, but that seems dubious to me (but then I'm still new to Magento development, so if that is indeed the case, please let me know.) In case it's useful, a modified version of this is what I currently use to process payments: https://github.com/pmclain/module-stripe

**Comment by gonzaloebiz** [comment]
Hi @crankycyclops 

thanks for your feedback.
Are you waiting until your receive the first email and then modify the cart? or modify it before receive the first email?

Best

**Comment by crankycyclops** [comment]
Hi @gonzaloebiz, thanks for the reply. I'm modifying the cart before receiving the email. As an example, I had the abandoned cart email setup in Mailchimp for 6 hours, and the cart was modified about 30 minutes after it was abandoned. The email still got sent out after the 6 hour mark, even though the abandoned cart was deleted in Magento.

**Comment by gonzaloebiz** [comment]
Hi @crankycyclops 

i checked this use case yesterday, and works OK. See what value do you have in the column ```is_active``` in the table ```quote``` of your database for this specific quote

Best

**Comment by crankycyclops** [comment]
I'm testing this again on a fresh email address. I've just abandoned a cart and am waiting for Mailchimp to pick up on it and add the user to the automation's queue. How long should I wait for that to sync? Once I see my email address in the queue, I'll log back in and complete checkout, check to see if the user is eventually removed from the queue before the email gets sent and let you know what the value of is_active is after checkout.

**Comment by crankycyclops** [comment]
Now, I seem to be having another issue where I don't receive an abandoned cart email at all, so I'll have to dig more into that before I can provide more on this issue.

**Comment by gonzaloebiz** [comment]
Let me know if have more info and we will re open the issue

**Comment by crankycyclops** [comment]
I've finally had time to go back and resolve the other issue I was having (caused by the bug that was fixed in this commit: https://github.com/mailchimp/mc-magento2/commit/645a10d087d77b2fc0876aa7c2ef84b2cde544d4). Abandoned carts are syncing again, so I'm going to test this again soon and report back if the original issue is still a problem.
