### ISSUE TITLE
Timeout when editing a customer in the admin panel

### ISSUE THREAD

**Issue by t-richards** [mailchimp/mc-magento2#496]
### Preconditions

    1. Magento CE 2.2.6, NO sample data.
    2. mc-magento2 1.0.32.
    3. At least one customer with a newsletter subscription.
    4. Mailchimp service DOWN / API calls timing out

### Steps to reproduce

    1. As an admin user, visit Customers > All Customers.
    2. Select the "Edit" action link for a single customer.

### Actual and Expected result

    Expected result:
    The customer edit interface should be presented.

    Actual result:
    A "504 Gateway Timeout" message appears instead.

### Workaround

Disabling the module will allow the interface to work again:

```
bin/magento module:disable Ebizmarts_MailChimp
```

### Additional information

During a Mailchimp service outage, such as the one occurring now at this time of writing: https://twitter.com/MailchimpStatus/status/1069614009043877888, the Mailchimp API call(s) appear to have a very long timeout. This causes the edit interface to become completely unusable.

Ideally, during an outage, the interface would still be partially usable. It is understandable that things like the "Newsletter subscription" sync would not work, but the core Magento functionality should still be accessible.

**Comment by gonzaloebiz** [comment]
Hi @t-richards 

thanks for your feedback.
Update the ebizmarts/mailchimp-lib library
Run `composer require ebizmarts/mailchimp-lib` and be sure that the version installed is 3.0.29

Best
