### ISSUE TITLE
Unable to unserialize value in cron

### ISSUE THREAD

**Issue by dmatthew** [mailchimp/mc-magento2#497]
### Preconditions

MailChimp Version 1.0.32
Magento version 2.2.7

### Steps to reproduce

Run the cron

### Actual and Expected result

report.CRITICAL: Unable to unserialize value. {"exception":"[object] (InvalidArgumentException(code: 0): Unable to unserialize value.

report.ERROR: Cron Job ebizmarts_ecommerce has an error: Unable to unserialize value.

**Comment by dmatthew** [comment]
Will this fix be in 1.0.33?

**Comment by gonzaloebiz** [comment]
Look at https://github.com/mailchimp/mc-magento2/milestone/9?closed=1
