### ISSUE TITLE
Cart not updated in a Abandoned Cart Series

### ISSUE THREAD

**Issue by gonzaloebiz** [mailchimp/mc-magento2#498]
When define an Abandoned Cart Series and a cart is abandoned, wait until receive the first email and then try to modify the cart, this cause that the cart was deleted in Mailchimp and then a new cart is added.

As for updating the cart: The DELETE call for a cart removes the subscriber from the automation.  The DELETE call for cart #1 would need to come through _before_ the POST call for cart #2. If you POST a new cart in the same batch call as deleting the first cart, they won't be deleted in time to trigger the automation.

**Comment by AfreenScarlet** [comment]
is there any patch available for this fix.
