### ISSUE TITLE
Inaccurate numbers on Mailchimp Dashboard (Total store revenue, # of orders , transaction dates)

### ISSUE THREAD

**Issue by shreddieb** [mailchimp/mc-magento2#509]
## Issue Description
After installing Mailchimp for Magento, I "was" seeing an ebizmarts_ecommerce cron_schedule table error "Unable to unserialize value." But then I applied a fix noted on commit 645a10d that fixed the cron error (I now get ebizmarts_ecommerce cron status as "success" each time). Unfortunately though when viewing the Mailchimp dashboard, the dashboard info shown in Mailchimp doesn't update to properly reflect the Magento data. 

### Preconditions
Magento 2.2.4
mc-magento2 v. 1.0.32
mailchimp-lib v. 3.0.29
php v. 7.0.32
two-way sync is enabled in Magento config

### Steps to reproduce
Install Mailchimp for Magento and apply cron_schedule fix noted in commit 645a10d

### Actual result
Mailchimp dashboard data is not reflective of the Magento data

screenshot from Magento 2 orders page (showing just a subset of orders starting on Nov 29)
![orders-example](https://user-images.githubusercontent.com/7809650/49754810-ee07f800-fc6b-11e8-9ef6-a81dc0d102bd.png)

screenshot from Magento 2 admin Mailchimp General Configuration 
![config-dashboard](https://user-images.githubusercontent.com/7809650/49754881-227bb400-fc6c-11e8-96a7-0dc4d1a800d6.png)

screenshot from Mailchimp dashboard (showing incorrect revenue numbers, dates and # orders compared to the Magento data)
![mailchimp-dashboard](https://user-images.githubusercontent.com/7809650/49754833-feb86e00-fc6b-11e8-9b98-3a98e0ff321d.png)

### Expected result
Mailchimp revenue data should be the same as Magento data (revenue amounts, orders, dates ordered, etc.)

Hoping someone has info/ideas for me to try for a fix.
Thank you!

**Comment by gonzaloebiz** [comment]
Hi @shreddieb,

thanks for your feedback.
As you can see, in the last image you have orders from 12/03 thru 12/09, so you must check the same period in magento. Also keep in mind, the items "Revenues from Mailchimp", "From campaigns" and "From automations" refers to orders made thanks a Mailchimp campaign or automation (p.e. an abandoned cart email), so only those order are included (you can see in magento, a monkey image in the order grid that means that the order was made via a campaign or automation)
Also, keep in mind, orders with only grouped or bundle product are not synced to Mailchimp.

Best

**Comment by shreddieb** [comment]
Hi @gonzaloebiz.
Thank you for your info. I didn't realize that it wasn't all data. I appreciate the clarification. Unfortunately, though, the numbers are still not accurate for me, but your input has given me new info to dig deeper...

I now see that my Mailchimp dashboard revenue is showing transactions as of the evening of December 5th PST moving forward.....
6 "canceled" transactions that occurred on the evening of December 5th (pst) and 1 "good" transaction that occurred on the evening of December 8th
* 5 "canceled" transactions @ $173.09 = $865.45 
* 1 "canceled" transaction @ $159.90 
* 1 "good" transaction of $79.95 on the evening of Dec 8th (pst) 
= totals $1105.30 that we see on the dashboard.

So from this I see a couple issues
1) Canceled transactions are showing up as revenue
2) Transaction data before the canceled transactions are not being included

We opened our site to accept sales on November 29 of this year...however, I fixed the cron_schedule error on December 6th. Most of our orders were on that opening day as well as November 30, with some additional purchases made on Dec 1, 3, 5, 8th.
For Mailchimp revenues (mailchimp campaigns and automations..shown with a Mailchimp monkey icon next to the magento order) we see a total of $1458.10 since opening up for sales Nov 29. When I change Mailchimp to show "Past 30 days", it still shows the $1105.30 total listed above....doesn't include those late november/early december dates.
reference image:
![30days](https://user-images.githubusercontent.com/7809650/49774501-d3547400-fca9-11e8-9ef1-ec673871b475.png)

Here is a screenshot of a customer that should show "canceled" orders in Mailchimp but they are still coming through as "purchased"...
![mc-showing-purchased](https://user-images.githubusercontent.com/7809650/49774674-583f8d80-fcaa-11e8-800f-6c75cba166ce.png)

Here is a screenshot from my magento orders that show those orders are in fact canceled...
![canceled-m2](https://user-images.githubusercontent.com/7809650/49774751-a48acd80-fcaa-11e8-8ec3-86af1e0d4d02.jpg)

So, wondering if a complete uninstall / reinstall would correct this? or if there is something I should do that might correct the "canceled" orders showing up as "purchased"

Please let me know your thoughts and if you need any more information.
Thank you for your help!
Eddie

**Comment by gonzaloebiz** [comment]
Hi @shreddieb 

thanks for your detailed feedback.
The issue with the canceled orders is a know issue, and we are working with mailchimp to find a fix. The issue depends on how mailchimp show the results, not on the extension.

**Comment by shreddieb** [comment]
@gonzaloebiz 

Ok, thank you for the info on the canceled order issue. Do you by chance have an ETA on when a fix might happen?

Also, in re-reading the thread, I'm realizing I was confusing the Mailchimp Dashboard revenue totals....
"Total store revenue" is only showing transactions (which includes canceled transactions as you know) since December 6, even though we have sales beginning November 29th. Not sure why it's not pulling in the earlier data there. To me, it seems like it's only pulling data in after I applied the cron_schedule table fix noted above.

And Revenues from Mailchimp (Campaigns and Automations) are summing up at $0 even though the Magento orders that have the Mailchimp logo tied to it total up to $1458.10 since November 29th in the Magento Orders admin page. The orders thus far are all simple products, nothing grouped or bundled. 

Ultimately, the problem here seems to be that my data prior to December 6th is not being included in the dashboard tally.
Thoughts?
Thank you for your help!

**Comment by shreddieb** [comment]
Hi @gonzaloebiz,
My assumption above that only new data is being tallied in the dashboard is incorrect. Another order (mailchimp order) came in yesterday, which properly displays the data on the mailchimp customer profile but the results didn't add to the dashboard. The dashboard remains at the $1105.30 total with no new purchase showing for December 12. Magento properly shows the monkey icon next to the purchase in the Magento orders.

![purchase-activity](https://user-images.githubusercontent.com/7809650/49953097-344e9880-feb2-11e8-8080-7abf61180bf1.png)

So dashboard tally not working and canceled orders showing as purchased on customer profile (which you mention is a known issue and working with mailchimp)

Any thoughts or suggestions I can try for a solution?
Thank you,
Eddie

**Comment by shreddieb** [comment]
Hi @gonzaloebiz, I wanted to check in on the issue noted. Do you feel this Dashboard problem I'm seeing is a bug?

**Comment by bawinstead** [comment]
Hello @shreddieb . I am with Mailchimp and see that you were having issues with your dashboard and canceled orders. In regards to the canceled items, those will show up under the subscriber profiles and the revenue will remain in the system as @gonzaloebiz mentioned. 

Our engineers are aware of several dashboard data discrepancies that can affect some of our users. It appears you are being affected by two of these.  We are taking these reports seriously and are in the early stages of finding a solution to the various dashboard related issues. Due to the scope of the project, I am not able to give an accurate ETA on when this will be resolved. I will gladly get your account listed as affected. Thank you!

**Comment by shreddieb** [comment]
@bawinstead ... Thank you! I would definitely appreciate updates as you get them.

**Comment by mike-diff** [comment]
@bawinstead we are also having issues with revenue data. Has this issue been updated yet? Please let us know the status of the fix on Mail Chimp side. Thank you

**Comment by bawinstead** [comment]
@3daddict Hello! This particular issue is going to require some changes in logic to our e-commerce integrations. At this time, we do have this on our roadmap.

**Comment by mike-diff** [comment]
@bawinstead Thanks for the update. This is critical information we need to we will be eagerly anticipating a fix release.

**Comment by nielsclaes** [comment]
@gonzaloebiz
In the Mailchimp account of my customer we're also seeing cancelled orders showing up as revenue (and as valid purchases on the subscriber profiles in Mailchimp).

Is there any update on this issue?
