### ISSUE TITLE
Multiple storeviews / multiple mailchimp stores, status 'not connected' 

### ISSUE THREAD

**Issue by duckchip** [mailchimp/mc-magento2#511]
## Multiple storeviews / multiple mailchimp stores, status 'not connected' 

Hi guys, 

On our magento2 store, we currently have over 10 storeviews. Each with an own mailchimp store. 
We noticed that most of the e-commerce data is not being synced and that a lot of the stores have status 'not connected' 

Currently we have the following set-up:
- Magento 2.1.11
- mc-magento2 module on version 1.1.32

In a previous bug report (#214) you wrote the following: 
'f you create a MailChimp store with an already used domain, this store is created as 'not connected'. Only one MailChimp store can exists for a given domain (if you want to change the MailChimp store, you must delete first the existing one)'

Our setup shares the same domain for all the storeviews, with the only difference being the storecode after each domain such as /nl , /fr, /en, ..... 

Can I conclude that this set-up will not work? Or are we doing something wrong? We've been struggling with trying to get this set up for a while now. 

Is there anything you can recommend? 

Kind regards

Tristan Hofman 
![screen shot 2018-12-13 at 09 22 10](https://user-images.githubusercontent.com/9752966/49925267-acb85800-feb8-11e8-930e-d24f9289aa08.png)

**Comment by gonzaloebiz** [comment]
Please contact our support team

**Comment by simonrl** [comment]
Having the same issue, can you please give me the contact information of your support team or tell me how to resolve this? Thanks!

**Comment by SantiParagarino** [comment]
Hello @simonrl 
Our contact email for this extension is mailchimp@ebizmarts-desk.zendesk.com.

Kind Regards.

**Comment by simonrl** [comment]
Hi, I have already sent you an email after talking to the mailchimp support, thanks.

**Comment by onepack** [comment]
This doesn't help. I have the same issue for a customer. Just write down what the solution is.

**Comment by PMGroupJohn** [comment]
Like onepack said, we too are having the same issue where you have multiple stores sharing the same domain, identified with a country variation ie. /en /de

Could the resolution not just be posted here?

**Comment by gonzaloebiz** [comment]
Hi @PMGroupJohn 

mailchimp don't support more than 1 store for the same domain, the stores yourstore.com/en and yourstore.com/de have the same domain (yourstore.com)
You must use subdomains, en.yourstore.com and de.yourstore.com.
Is not an issue in the extension, is a MailChimp limitation

Best

**Comment by PMGroupJohn** [comment]
Hi @gonzaloebiz 

Thank you for confirming this, I thought this was the case.

Many thanks,

John

**Comment by gonzaloebiz** [comment]
you are welcome @PMGroupJohn

**Comment by prometheusone** [comment]
Was there ever a solution for subdirectories offered ?? im not going to change my entire store setup just to accomodate mailchimp

**Comment by gonzaloebiz** [comment]
Hi @prometheusone 

not for now.

Best
