### ISSUE TITLE
Invalid version number packagist

### ISSUE THREAD

**Issue by Axel29** [mailchimp/mc-magento2#521]
## Issue Description

When using PHP 7.1, it is impossible to install the package with composer.
In fact, the repository on packagist.org has a version "1.1.32" that requires "magento/framework: 100.1.*", which doesn't support PHP 7.1, whereas the version 1.0.32 requires "magento/framework: 100.1.*", which does.

I'm guessing that "1.1.32" version is a fail since the version on this github is stil "1.0.32".

### Preconditions

1. Magento 2.2.6
1. PHP 7.1

### Steps to reproduce

1. Install Magento 2.2.6 or later
1. Try to install MailChimp via composer (`composer require mailchimp/mc-magento2`).

### Actual and Expected result

Expected result: No error.

Actual result: full of errors due to dependency on magento/framework: 100.1.* (see screenshot bellow)

![image](https://user-images.githubusercontent.com/3015249/50091542-f633da80-020b-11e9-8446-e9cf8e777b61.png)

**Comment by gonzaloebiz** [comment]
Please read https://github.com/mailchimp/mc-magento2/releases
You must install 1.1.32, so specify the version you want to install

Best
