### ISSUE TITLE
Magento2 - Setup Compile Error - Class does not exist

### ISSUE THREAD

**Issue by rajupndt6** [mailchimp/mc-magento2#529]
## Issue Description
I upgraded from Magento 2.2.6 to 2.3.0  Community version successfully. Getting an error during compilation.
### Steps to reproduce
Now when I try to upgrade the setup I get the error "Please re-run Magento compile command".

So i run the compile command - magento setup:di:compile

but I am getting the following error:
![selection_089](https://user-images.githubusercontent.com/37099970/50203482-aa0da500-0387-11e9-99df-34cc3c892b9d.png)

Any ideas as to how this can be resolved?

**Comment by gonzaloebiz** [comment]
Hi @rajupndt6 

run `composer show | grep mailchimp`

and let me know the result

**Comment by rajupndt6** [comment]
Hi @gonzaloebiz

Get result- 
![selection_093](https://user-images.githubusercontent.com/37099970/50222645-ec9ea400-03be-11e9-8e86-cc23d0ad156e.png)

**Comment by gonzaloebiz** [comment]
Hi @rajupndt6 

so, your magento expect that the mailchimp extension is installed but is not.
run 

` composer require mailchimp/mc-magento2:dev-develop-2.3`

as we don't have a magento 2.3 release yet, you must install the develop-2.3 branch

Best
