### ISSUE TITLE
Error when attempting to edit a customer from the backend

### ISSUE THREAD

**Issue by kudja** [mailchimp/mc-magento2#530]
### Issue Description
When trying to edit a customer from the backend, will get a "Unable to unserialize value." and will not be able to edit the customer.

![image](https://user-images.githubusercontent.com/8101375/50232787-f62a0b00-03c2-11e9-92b4-2ae4301a2081.png)

### Preconditions
1. Magento CE 2.2.5
2. mc-magento2 1.0.32
3. Magento migrated from 1.9 (not sure if it can affect)

### Steps to reproduce
Just open any customer to edit in Admin / Customers / All Customers  then click Edit on some customer

### Details

Error occurs in vendor/mailchimp/mc-magento2/Block/Adminhtml/Customer/Edit/Tabs/View/Customer.php line 59, it sends null to json_decode.

**Comment by gonzaloebiz** [comment]
Hi @Kudja 

thanks for your feedback.
This issue is already fixed, replace the file https://github.com/mailchimp/mc-magento2/blob/develop-2.2/Helper/Data.php

Best

**Comment by simonrl** [comment]
We are also having this issue in Magento 2.1.14. The linked fix does not work there because it uses `\Magento\Framework\Serialize\Serializer\Json` which does not exist in that version. Any ideas?
