### ISSUE TITLE
Unable to unserialize group data of interestgroup

### ISSUE THREAD

**Issue by ghost** [mailchimp/mc-magento2#531]
**Preconditions:**
1. Magento CE 2.2.7 without sample data is installed
2. mc-magento2 1.0.32
3. Developer mode

**Steps to reproduce:**
1. Create a customer
2. Return to the customer, an error appears: Unable to unserialize value

The error comes from the following file:
`vendor/magento/framework/Serialize/Serializer/Json.php:39`
And is called in:
`vendor/mailchimp/mc-magento2/Helper/Data.php:1028`

Error can be fixed by checking if `$interestGroup->getGroupdata()` is not null:

```
// First part of code
if ($interestGroup->getGroupdata() == null) {
      return $interest;
}
$groups = $this->_serializer->unserialize($interestGroup->getGroupdata());
// Do rest of code
```

**Comment by ghost** [comment]
To fix the problem, I created the following plugin:

**adminhtml/di.xml:**
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Ebizmarts\MailChimp\Helper\Data">
        <plugin name="MailChimp_Fix_Group_Data_Serializer"
                type="Vendor\Module\Plugin\MailChimp\Helper\Data"/>
    </type>
</config>
```

**Vendor\Module\Plugin\MailChimp\Helper\Data:**
```
<?php

declare(strict_types=1);

namespace Vendor\Module\Plugin\MailChimp\Helper;

use Ebizmarts\MailChimp\Helper\Data as McData;

/**
 * Class Data
 * @package Vendor\Module\Plugin\MailChimp\Helper
 */
class Data
{
    /**
     * @var McData
     */
    private $data;

    /**
     * Data constructor.
     * @param McData $data
     */
    public function __construct(McData $data)
    {
        $this->data = $data;
    }

    /**
     * @param McData $subject
     * @param callable $proceed
     * @param $subscriberId
     * @param $storeId
     * @param null $interest
     * @return string
     */
    public function aroundGetSubscriberInterest(
        McData $subject,
        callable $proceed,
        $subscriberId,
        $storeId,
        $interest = null
    ) {
        try {
            $return = $proceed($subscriberId, $storeId, $interest);
        } catch (\InvalidArgumentException $e) {
            $return = $this->data->getInterest($storeId);
        }

        return $return;
    }
}

```

**Comment by gonzaloebiz** [comment]
The issue is already fixed

**Comment by s00071609** [comment]
In magento 2.3.1 cron shows error and nothing gets synced with mailchimp. I have the latest version of mailchimp and lib - i used composer to install the extension

ERROR:

Warning: Invalid argument supplied for foreach() in /........../public_html/vendor/mailchimp/mc-magento2/Helper/Data.php on line 1028

I guess this issue was there in previous versions and was supposed to be fixed but its still there. There is no info on how to fix this anywhere i can see.

Any help would be great
