### ISSUE TITLE
Feature Suggestion: Add Customer Group Name Mapping

### ISSUE THREAD

**Issue by beechyrb** [mailchimp/mc-magento2#547]
I would like to suggest adding a **Customer Group Name** mapping to the available "Customer Field Mapping" to map to Mailchimp merge fields. Currently it only maps **Customer Group ID** which is not helpful to map to Mailchimp as no one references ID's.

![unnamed](https://user-images.githubusercontent.com/7995987/50517421-50d7fc80-0a7e-11e9-9f1f-34be260d47cd.png)

**Comment by gonzaloebiz** [comment]
Hi @beechyrb 

thanks for your suggestion.
This is not possible, because the management of this is generic.
You can segment the list in mailchimp for the id, even you can define the group in mailchimp as a dropdown and map the values to a label

Best
