### ISSUE TITLE
Compatibility with Magento 2.3

### ISSUE THREAD

**Issue by Mandrino** [mailchimp/mc-magento2#550]
Hello,

when will this extension be compatible with Magento 2.3?

Thanks

**Comment by Lukas-G21** [comment]
What errors did you encounter?

**Comment by Mandrino** [comment]
None, as the plug-in is not available for 2.3, as per magento marketplace:
https://marketplace.magento.com/mailchimp-mc-magento2.html

**Comment by gonzaloebiz** [comment]
Please see the branch develop-2.3

**Comment by krombel** [comment]
Are there any known issues in that branch right now?


//EDIT: For others who want to try that branch with their composer setup:
```
composer config repositories.mailchimp_magento2 vcs git@github.com:mailchimp/mc-magento2.git
composer require mailchimp/mc-magento2:dev-develop-2.3
```
