### ISSUE TITLE
Mailchimp plugin vanished with Magento 2.2.7 update

### ISSUE THREAD

**Issue by vDeggial** [mailchimp/mc-magento2#551]
Hi there

Magento version: 2.2.7 CE
Mailchimp plugin version: 1.0.32
Malchimp: lib: 3.0.29

We have a client we setup magento store for and mailchimp integration was working fine, but ever since magento update to 2.2.7 on dec 11 2018 apparently mailchimp plugin just vanished from system (not in dashboard anymore) and attempts to reinstall it using system:upgrade with newest files in the file system dont do anything

client needs a fix for this asap as we just been notified by him that newsletter signups dont get added to mailchimp and last mailchimp logs are dec 11 2018

**Comment by SantiParagarino** [comment]
Hello @shinoamakusa 
This is not something that happens in normal installations. Please contact us via mailchimp@ebizmarts-desk.zendesk.com in order to handle this specific problem in a more personalized manner.

In case we learn this to be a bug we can re-open this issue.

Kind Regards.

**Comment by henkka01** [comment]
The exactly same thing happened to us yesterday, which I noticed today when I wanted to work with mailchimp. Is there a way to solve this ?

**Comment by vDeggial** [comment]
Had to reinstall the plugin through composer on local server and reupload whole thing to live server
