### ISSUE TITLE
Event after successful subscription

### ISSUE THREAD

**Issue by OvalMedia** [mailchimp/mc-magento2#552]
I have a module that automatically creates a coupon (5% discount) after an initial newsletter subscription.
This module uses a plugin to execute it's action before magento sends a confimation email to the subscriber.
Now that I am also using mailchimp, this function never gets executed as mailchimp takes care of the confirmation itself.

So I would like to fix this by creating my own plugin but am a little clueless where to hook into mailchimp. 
So my question is: at what point in the code would it be wise to attach my custom function. Preferably using a plugin function.

Thank you

**Comment by gonzaloebiz** [comment]
Hi @OvalMedia 

thanks for your feedback.
When mailchimp confirm the subscriber, this code is executed https://github.com/mailchimp/mc-magento2/blob/develop/Cron/Webhook.php#L120-L150 you can start there

Best
