### ISSUE TITLE
Resubscribing doesn't work

### ISSUE THREAD

**Issue by Hexmage** [mailchimp/mc-magento2#560]
Magento 2.1.10
Mailchimp module 1.0.29
Enable Two Way Sync - Yes
Ecommerce configuratie - Disabled

Steps to Reproduce:
- Subscribe for Newsletter through Magento.
- Unsubscribe for Newsletter through Magento.
- Subscribe again for Newsletter through Magento.

Expected result:
I'm subscribed in both Magento and Mailchimp.
Actual result:
I'm subscribed in Magento and I'm not subscribed in Mailchimp.

**Comment by gonzaloebiz** [comment]
Hi @Hexmage 

thanks for your feed back, please update the extension to the current version

Best
