### ISSUE TITLE
Error during sync: "A campaign with the provided ID does not exist in the account for this list."

### ISSUE THREAD

**Issue by arendarenko** [mailchimp/mc-magento2#561]
## Issue Description

As a customer, I can be subscribed on a different subscribers lists which is related to one website.
For example: "general subscribers" list, and "season sale subscribers" list. But website administrator can configure module to work only with one subscribers list for one website.

When customer follows link from letter which was sended for "season sale subscribers" list and make order, module doesn't import this order, because module works only with "general subscribers" list.

I think it's wrong behavior - not to import order at all. From my point of view it's better to import order without reference to mailchimp_campaign_id in this case.

### Preconditions

Example:

    1. Magento 2.2.7
    2. mc-magento2 1.0.32.
    3. two subscribers list: "list 1" and "list 2"
    3. Module is configured to work with "list 1"
    ...

### Steps to reproduce

1. Go to Mailchimp lists and create subscriber with the same email in two lists "list 1" and "list 2"
2. Create Mailchimp campaign for "list 1" and send letter
3. Follow link from letter and make order from email which was used in p.1

###  Expected result

Order will by synced without reference to mailchimp_campaign_id

### Actual result

Order is not synced. There is an error in Mailchimp.log: "A campaign with the provided ID does not exist in the account for this list."

**Comment by gonzaloebiz** [comment]
Hi @alexeya-ven 

thanks for your feedback.
One magento store can be linked to only one mailchimp store. A mailchimp store can be linked to only one mailchimp list (and the list can't be changed once you create the store).
If you wish to segment your list, use the mailchimp segments and not a new list. 
If you use a list that is linked to a wrong magento store or not linked to any magento store, when send the mailchimp campaign the result of click on the link and make the order will be wrong, not for an issue in the extension, this in an issue in the way that you use it

Best

**Comment by ihor-sviziev** [comment]
Hi @gonzaloebiz,
Issue itself that customer could go to our website from partner's email (for example), that also using Mailchimp.

In this case I can't control their lists and I can't give access to partners.

I think best option - in case of such error - send such orders to Mailchimp without link to campaign

**Comment by gonzaloebiz** [comment]
Hi @ihor-sviziev 

i see what the issue is.
I just commit a fix, but i'm not sure that is legal sent a campaign mentioning other store, i'm asking to mailchimp about.
Any way, try the fix

**Comment by ihor-sviziev** [comment]
@gonzaloebiz Thank you!
