### ISSUE TITLE
Orders with incorrect customer email is not marked as errors

### ISSUE THREAD

**Issue by arendarenko** [mailchimp/mc-magento2#578]
## Issue Description
I found that amount of orders which was synced successfully + orders which wasn't synced because of  errors is not equal no total synced orders which I can see in Configuration. So I investigated it and found that at least one issue when orders isn't syncing and it's not reported into mailchimp_errors table.

### Preconditions

Describing preconditions is a great start, provide information on system configuration settings you have changed, detailed information on entities created (Products, Customers, etc), Magento and mc-magento versions. Basically, everything that would help developer set up the same environment as you have.

Example:

    1. Magento CE 2.2.7 without sample data is installed.
    2. mc-magento2 1.0.32.

### Steps to reproduce
1. Create order with customer email "customer@example.com"
2. Run module crons or wait until they ran automatically 

### Expected result
1. Order will not be synced and you will recieve an error on "Errors" page

### Actual result
1. Order is not synced but there is no error on "Errors" page

**Comment by gonzaloebiz** [comment]
Hi @alexeya-ven 

I try a new order with a fake email

![image](https://user-images.githubusercontent.com/6222792/52215019-e894eb80-2871-11e9-9ec8-3b2bc9677534.png)

And the error is there in the error grid

![image](https://user-images.githubusercontent.com/6222792/52215054-006c6f80-2872-11e9-9d27-76945fd5aa6b.png)

I close the issue until we have more info to replicate it

Best

**Comment by arendarenko** [comment]
Please try to remake or re-order this order

**Comment by gonzaloebiz** [comment]
Same result

![image](https://user-images.githubusercontent.com/6222792/52218786-20079600-287a-11e9-9d2d-8638254639b0.png)
