### ISSUE TITLE
Cron error "Requested country is not available."

### ISSUE THREAD

**Issue by mikehenze** [mailchimp/mc-magento2#58]
Cron ebizmarts_ecommerce outputs error:
Requested country is not available.

Version: 1.0.22
Magento: 2.1.7
Multiple storefronts (languages) and multiple Mailchimp Stores (1 list for each language).

**Comment by mamreezaa** [comment]
i have the same issue. when i run the cron.

`[Magento\Framework\Exception\NoSuchEntityException]  
  Requested country is not available. `

in my case these are the country ids where this error occurred. 
1. `/var/www/magento/vendor/magento/module-directory/Model/CountryInformationAcquirer.php:103:
string(2) "GB"`

2. `/var/www/magento/vendor/magento/module-directory/Model/CountryInformationAcquirer.php:103:
NULL
`
i think the problem is 
'vendor/mailchimp/mc-magento2/Model/Api/Customer.php:184'
where mailchimp tried to get data from locale using store Id. 

actually mailchimp module call this function 
 'vendor/magento/module-directory/Model/CountryInformationAcquirer.php:90'
which is using storeId to get the values. 

After debugging this issue i did the following changes to make it work. This is a working solution, but i feel this is little slow. 

Solution.
` public function __construct(
            \Magento\Directory\Model\CountryFactory $countryFactory
        ) {
            $this->_countryFactory = $countryFactory;
        }

    protected function _buildCustomerData(\Magento\Customer\Model\Customer $customer)
    {
      ....
     if ($address->getCountry()) {
               $country = $this->_countryFactory->create()->loadByCode($address->getCountryId());
                $customerAddress["country"] = $country->getName();
                $customerAddress["country_code"] = $address->getCountryId();
            }
     .....
    }`

**Comment by gonzaloebiz** [comment]
Thanks for the feedback.
Please see the associated commit.

Best

**Comment by mikehenze** [comment]
Hi, this does not fix the "Requested country is not available".
Maybe it should also be changed in:
mc-magento2\Model\Api\Subscriber.php

**Comment by gonzaloebiz** [comment]
Hi @mikehenze 

if you have any ->getCountry() call in mc-magento2\Model\Api\Subscriber.php you must update the extension, because no calls to getCountry() in this file
Let me know

**Comment by mikehenze** [comment]
I see its all commented

//                                            "country" => $address->getCountry() ? Mage::getModel('directory/country')->loadByCode($address->getCountry())->getName() : ""

**Comment by mamreezaa** [comment]
Hi @all 

I think still the problem exist. i am looking into this now. :)

**Comment by mamreezaa** [comment]
@mikehenze  did you try my solution ? 
i did the same fix in  Model/Api/Cart.php, Customer.php, Order.php
Now i don't see the issue. 

Thanks.

**Comment by mikehenze** [comment]
@mamreezaa 
I am having trouble implementing your fix.
Do I need to edit: 
- vendor/mailchimp/mc-magento2/Model/Api/Customer.php
- vendor/mailchimp/mc-magento2/Model/Api/Cart.php
- vendor/mailchimp/mc-magento2/Model/Api/Order.php

And add:
\Magento\Directory\Model\CountryFactory $countryFactory
) {
$this->_countryFactory = $countryFactory;
}

to public function __construct
and add:
if ($address->getCountry()) {
           $country = $this->_countryFactory->create()->loadByCode($address->getCountryId());
            $customerAddress["country"] = $country->getName();
            $customerAddress["country_code"] = $address->getCountryId();
        }

to protected function _buildCustomerData ?

Maybe you can attach your versions ?

**Comment by mikehenze** [comment]
@gonzaloebiz Please fix this issue because we need this extension to work soon.
Thanks

**Comment by mikehenze** [comment]
After implementing commit "Add store id" everything works now.

**Comment by mikehenze** [comment]
Magento 2.2.1
Mailchimp 1.0.25

Still getting issue "Requested country is not available."

Please tell me what to do.

**Comment by gonzaloebiz** [comment]
Enable all the associated countries to customer, orders, etc.
If you have any problem, please open other issue

Best

**Comment by mikehenze** [comment]
Yes that fixed it.
Can I disable the countries we have stopped shipping to after the sync has completed?

**Comment by gonzaloebiz** [comment]
I think

**Comment by tonytrinh206** [comment]
@mikehenze I got the same issue. Could you please show me how to fix it? I got Magento 2.1

**Comment by gonzaloebiz** [comment]
@tonytrinh206 look 4 comments above

**Comment by tonytrinh206** [comment]
Hi @gonzaloebiz, thank you for your response. Do you mean I have to allow all countries to my shipping and billing address during the first sync? I went through all of my orders and customers and they have the same US country which has already allowed on our shopping cart.

**Comment by mikehenze** [comment]
Setting the sync date to after the date that you disabled certain countries does not fix it.
It will only sync with all countries enabled that have orders.
This is a problem.

**Comment by joshdavenport** [comment]
Yes, we disable countries because we no longer ship there or support those countries to any extent. Now for a sync we have to turn them on? This just confuses users, they'll think we now ship to that country again, but we don't.

**Comment by Tantuss** [comment]
Ticket is closed, but issue is not solved.

Solution is written in comment by:
mamreezaa commented on 10 Aug 2017 

Please apply this fix to the sources to get it working if you have disabled some countries where you was sending before to and now not anymore.

**Comment by robgt** [comment]
I am still encountering this same error in Magento 2.1.6 with MC-Magento plugin version 1.0.27.

ebizmarts_ecommerce | error | Requested country is not available

Any thoughts as to how this can be fully resolved?
