### ISSUE TITLE
Magento 2.2 - Mailchimp not letting Magento Orders know they have been sent

### ISSUE THREAD

**Issue by richardmcauleywed2b** [mailchimp/mc-magento2#580]
We disabled Magento Order E-mails, so that Mailchimp Order E-mails would be sent instead.

We have recently enabled the Magento Order E-mails again, however we get a batch of backlog e-mails that Magento has not sent (but mailchimp has sent).

These e-mails then get sent, even though the Mailchimp e-mails have already been sent.

**Comment by gonzaloebiz** [comment]
Hi @richardmcauleywed2b 

please follow the issue format

Best
