### ISSUE TITLE
Mailchimp not letting Magento Orders know they have been sent 

### ISSUE THREAD

**Issue by richardmcauleywed2b** [mailchimp/mc-magento2#581]
### Preconditions

1) We are using Magneto 2.2.2. 
2) We are using a dev site. 
3) We enabled the Mailchimp extension on our Magento 2 site last Semptember.
4) We disabled the Magento Out of the Box e-mails last september, to allow Mailchimp to handle the e-mails.

### Steps to reproduce

    1. Disable Magento Sale Emails (Stores > Sales > Sales Emails). Set all of the tabs be disabled, as well as Asynchronous sending.
    2. Create An Order as a user or guest.
    3. Mailchimp E-mail will send order confirmation e-mail.
    4. Once you have received the order confirmation e-mail from MailChimp, Enable the Magento Sales E-mails and set Asynchronous sending to be enabled.
5. Create another order using the user or guest account. You will then recieve the previoiusly ordered item's confirmation e-mail.

### Actual and Expected result

Expected Result:
I expect the Extension Functionality to flag to Magento to let it know that it has sent the confirmation e-mail. So then if the user ever wants to disable the mailchimp e-mail and reuse Magento e-mails, it will not send old e-mails which are still in the cron.

Actual Result:
Administrator enables Magento E-mails and users receive all of the backlog e-mails which Magento has not sent due the MailChimp e-mails being sent instead of them.

**Comment by gonzaloebiz** [comment]
Hi @richardmcauleywed2b 

what version of mc-magento2 do you have?

**Comment by richardmcauleywed2b** [comment]
Hi @gonzaloebiz - We are on MailChimp v1.0.28. Let me know if you need anything else.

**Comment by gonzaloebiz** [comment]
Please update the extension

**Comment by richardmcauleywed2b** [comment]
Sure thing. The most up to date extension is 1.0.32 correct?

**Comment by gonzaloebiz** [comment]
yes, we are close to release a new version this week, so you can wait it.
Please confirm the issue in the updated version and i will re open the issue

Thanks
