### ISSUE TITLE
Mailchimp fields not showing in Customer Fields Mapping

### ISSUE THREAD

**Issue by gvlasov** [mailchimp/mc-magento2#582]
```
$ composer show mailchimp/mc-magento2 | grep version
versions : * 1.0.32
$ composer show magento/product-community-edition | grep version
versions : * 2.2.3
magento/module-version 100.2.0
```

I expect Mailchimp field contain something like this (from #423): 

![image](https://user-images.githubusercontent.com/4467948/52358125-43d50280-2a59-11e9-822f-a1dbc39df623.png)

but instead I'm getting this:

![image](https://user-images.githubusercontent.com/4467948/52357642-4f73f980-2a58-11e9-81c6-96c2aad1f966.png)

The mailchimp select is empty.

**Comment by gonzaloebiz** [comment]
Hi @gvlasov 

the mailchimp select show the list fields and merge tags you has already defined in your mailchimp list

![image](https://user-images.githubusercontent.com/6222792/52359361-89251000-2a18-11e9-8f5d-747c62fb5ba9.png)

Confirm that you have it

**Comment by gvlasov** [comment]
I had only the default email field. When I add a test field, it does show up:

![image](https://user-images.githubusercontent.com/4467948/52360389-b5af4b00-2a5d-11e9-8c4e-c83d1104f40a.png)
<hr>

![image](https://user-images.githubusercontent.com/4467948/52360646-5b62ba00-2a5e-11e9-8bd9-74ed7bf9f90e.png)

I guess I'm not supposed to link the email field this way, is that so?

**Comment by gonzaloebiz** [comment]
you don't need to map the email address, the email always is synced

Best
