### ISSUE TITLE
Breaks whole website

### ISSUE THREAD

**Issue by coatesjonathan** [mailchimp/mc-magento2#59]
I have installed the extension, and immediately the website goes to a blank white screen, I get the following error in my error_log:

#0 /home/{cpanel_user}/public_html/{website_name}/vendor/magento/framework/Code/Generator.php(112): Magento\Framework\Code\Generator->tryToLoadSourceClass('\\Ebizmarts\\Mail...', Object(Magento\Framework\ObjectManager\Profiler\Code\Generator\Logger))

**Comment by jordanbrauer** [comment]
Steps to reproduce? e.g., method of installation (commands run, etc), configuration guide(s) followed, etc

**Comment by gonzaloebiz** [comment]
If you install the extension by copying the zip files into your magento, run

composer require ebizmarts/mailchimp-lib

Best
