### ISSUE TITLE
Magento shows no list

### ISSUE THREAD

**Issue by wdttilburg** [mailchimp/mc-magento2#592]
## Title
Magento show no lists in create store module in Mailchimp plugin

## Issue Description
When we create a connection with the API key between Magento 2.2.3 and Mailchimp and want to create a store we don't get any lists retreivel from Mailchimp.

### Steps to reproduce

1. - Connect Magento with mailchimp
2. - Create a shop with a API
3. - Select a list

### Actual and Expected result
Load the lists selectbox in mailchimp

### Additional information
Following error in Mage reports.

{"0":"Notice: Undefined index: apikey in \/data\/web\/magento2\/app\/code\/Ebizmarts\/MailChimp\/Controller\/Adminhtml\/Lists\/Get.php on line 49","1":"#0 \/data\/web\/magento2\/app\/code\/Ebizmarts\/MailChimp\/Controller\/Adminhtml\/Lists\/Get.php(49): Magento\\Framework\\App\\ErrorHandler->handler(8, 'Undefined index...', '\/data\/web\/magen...', 49, Array)\n#1 \/data\/web\/magento2\/vendor\/magento\/framework\/App\/Action\/Action.php(107): Ebizmarts\\MailChimp\\Controller\\Adminhtml\\Lists\\Get->execute()\n#2 \/data\/web\/magento2\/vendor\/magento\/module-backend\/App\/AbstractAction.php(229): Magento\\Framework\\App\\Action\\Action->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#3 \/data\/web\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Backend\\App\\AbstractAction->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#4 \/data\/web\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Ebizmarts\\MailChimp\\Controller\\Adminhtml\\Lists\\Get\\Interceptor->___callParent('dispatch', Array)\n#5 \/data\/web\/magento2\/vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php(143): Ebizmarts\\MailChimp\\Controller\\Adminhtml\\Lists\\Get\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#6 \/data\/web\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch(Object(Ebizmarts\\MailChimp\\Controller\\Adminhtml\\Lists\\Get\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#7 \/data\/web\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Ebizmarts\\MailChimp\\Controller\\Adminhtml\\Lists\\Get\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#8 \/data\/web\/magento2\/generated\/code\/Ebizmarts\/MailChimp\/Controller\/Adminhtml\/Lists\/Get\/Interceptor.php(26): Ebizmarts\\MailChimp\\Controller\\Adminhtml\\Lists\\Get\\Interceptor->___callPlugins('dispatch', Array, NULL)\n#9 \/data\/web\/magento2\/vendor\/magento\/framework\/App\/FrontController.php(55): Ebizmarts\\MailChimp\\Controller\\Adminhtml\\Lists\\Get\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#10 \/data\/web\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#11 \/data\/web\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n#12 \/data\/web\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#13 \/data\/web\/magento2\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, Array)\n#14 \/data\/web\/magento2\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#15 \/data\/web\/magento2\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http->launch()\n#16 \/data\/web\/magento2\/pub\/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#17 {main}","url":"\/beheer5613\/mailchimp\/lists\/get\/key\/6c1825fea040a9ccf5a00700907e1b3d69a453be0c772c1435b34a680aa82ed6\/?isAjax=true","script_name":"\/index.php"}

**Comment by gonzaloebiz** [comment]
Please follow the issue format

**Comment by wdttilburg** [comment]
> Please follow the issue format

Done.

**Comment by gonzaloebiz** [comment]
Please specify magento and mc-magento2 versions

**Comment by gonzaloebiz** [comment]
I try witn magento 2.2.3 and mc-magento 1.2.33 and works perfect for me

**Comment by wdttilburg** [comment]
Would you like to check on our environment?

**Comment by gonzaloebiz** [comment]
Yes sure, if you have more info to try to replicate your issue we will try

**Comment by wdttilburg** [comment]
I could give you the information about the website and credentials.

**Comment by gonzaloebiz** [comment]
Hi @wdttilburg 

sorry but we don't do this kind of services.

Best
