### ISSUE TITLE
Mailchimp module- 1.3.33 issues on Magento 2.3 version

### ISSUE THREAD

**Issue by vijaymagento1** [mailchimp/mc-magento2#616]
Hello MailChimp Support team,
I have installed the "mc-magento2-1.3.33" on our Latest "Magento 2.3.0" version then I am getting installation issues when run the command "php bin/magento setup:upgrade"

**Installing data... Class Mailchimp does not exist**

Also when I run the compile command(php bin/magento setup:di:compile) then it's giving following error.

**In ClassReader.php line 35:
 Class Mailchimp does not exist  
In ClassReader.php line 29:
Class Mailchimp does not exist**  

Please let us know ASAP and how can I solve above issues?

Is it compatible this module "Mailchimp-mc-magento2-1.3.33" with the Magento 2.3 version?

Please check screenshot

![screenshot from 2019 03 01 17 45 15](https://user-images.githubusercontent.com/10975189/53639055-33760900-3c4e-11e9-99cc-c7dd8cf84fe4.png)

Thanks!

**Comment by gonzaloebiz** [comment]
Hi @vijaymagento1 

this is not an issue at our end. If you install the extension manually, you must install the dependencies.

Best

**Comment by vijaymagento1** [comment]
Can you please let us know what dependencies are required?

**Comment by gonzaloebiz** [comment]
Take a look at https://github.com/mailchimp/mc-magento2/blob/develop-2.3/composer.json#L26-L29
