### ISSUE TITLE
Production mode

### ISSUE THREAD

**Issue by evilprophet** [mailchimp/mc-magento2#63]
After instalation this extension enable production mode is not possible.

`bin/magento deploy:mode:set production -vvv
Enabled maintenance mode
Starting compilation
Something went wrong while compiling generated code. See the error log for details.
Command returned non-zero exit code:
`/usr/bin/php -f /var/www/m2c/bin/magento setup:di:compile`
#0 /var/www/m2c/vendor/magento/module-deploy/Model/Filesystem.php(245): Magento\Framework\App\Shell->execute('/usr/bin/php -f...')
#1 /var/www/m2c/vendor/magento/module-deploy/Model/Filesystem.php(143): Magento\Deploy\Model\Filesystem->compile(Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/m2c/vendor/magento/module-deploy/Model/Mode.php(83): Magento\Deploy\Model\Filesystem->regenerateStatic(Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/m2c/vendor/magento/module-deploy/Console/Command/SetModeCommand.php(100): Magento\Deploy\Model\Mode->enableProductionMode()
#4 /var/www/m2c/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Magento\Deploy\Console\Command\SetModeCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/m2c/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/m2c/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Deploy\Console\Command\SetModeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/m2c/vendor/magento/framework/Console/Cli.php(96): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/m2c/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/m2c/bin/magento(23): Symfony\Component\Console\Application->run()
#10 {main}
You have new mail in /var/spool/mail/vagrant
[vagrant@localhost m2c]$`

**Comment by gonzaloebiz** [comment]
Hi @evilprophet 

thanks for your feedback.
Please, read the Issue reporting guidelines and re post your issue.

Best
