### ISSUE TITLE
Abandonned cart email sent without images

### ISSUE THREAD

**Issue by gabrieljadeau** [mailchimp/mc-magento2#658]
# Abandonned cart email sent without images

Hi, I am using Magento ver. 2.1.8 with the Mailchimp Module  MailChimp v1.0.30 by Ebizmarts, have a abandonned campaign setup in Mailchimp but the emails sent don't have an img. 

I have added a log at the end of the function \Ebizmarts\MailChimp\Model\Api\Product::_buildProductData in order to see what is sent to Mailchimp when syncing and the informations are here. 

Thant being said, having a deeper look I have found the error message in the logs which is linked to my test.

>19-03-19 17:05:18] MailChimpLogger.INFO: Invalid Resource for Api Call: [https://us18.api.mailchimp.com/3.0/batches] using method [POST]
	Detail: [The resource submitted could not be validated. For field-specific details, see the 'errors' array.]
	Errors:
		 field [operations.item:2] : Schema describes object, array found instead
{"operations":[{"method":"PATCH","path":"\/ecommerce\/stores\/14850a5b3f240bd2bc382f74e67e528d\/products\/22017","operation_id":"PRO_1553015106_22017","body":"{\"id\":\"22017\",\"title\":\"Robe Albane blanche \",\"url\":\"https:\\\/\\\/fr.antikbatik.com\\\/catalog\\\/product\\\/view\\\/id\\\/22017\\\/s\\\/robe-albane-blanche\\\/\",\"image_url\":\"https:\\\/\\\/media.antikbatik.com\\\/catalog\\\/product\\\/a\\\/l\\\/albane-dress.jpg\",\"published_at_foreign\":\"\",\"description\":\"Robe mi-longue en cr\\u00eape de coton l\\u00e9g\\u00e8re et fluide. Petites emmanchures r\\u00e9glables avec des cordons de serrage en coton. Col et encolure brod\\u00e9s d\\u2019une frise florale. Le fil des broderies se d\\u00e9grade en un joli cama\\u00efeu de bleus. Associez notre robe Albane avec nos sandales tress\\u00e9es Mina pour un total look boh\\u00e8me romantique. La robe Albane est livr\\u00e9e avec un fond de robe. L\\u00e9a mesure 1m72 et porte une taille 38. La robe mesure 105 cm de long pour une taille 38 (S).\",\"vendor\":\"Collection Printemps-\\u00c9t\\u00e9 - Robes\",\"type\":\"Collection Printemps-\\u00c9t\\u00e9 - Robes\",\"handle\":\"\",\"variants\":[{\"id\":\"22017\",\"title\":\"Robe Albane blanche \",\"url\":\"https:\\\/\\\/fr.antikbatik.com\\\/catalog\\\/product\\\/view\\\/id\\\/22017\\\/s\\\/robe-albane-blanche\\\/\",\"image_url\":\"https:\\\/\\\/media.antikbatik.com\\\/catalog\\\/product\\\/a\\\/l\\\/albane-dress.jpg\",\"published_at_foreign\":\"\",\"sku\":\"ALBANE1DRE-WHITE\",\"price\":0,\"inventory_quantity\":0,\"backorders\":\"0\",\"visibility\":\"true\"},{\"id\":\"22018\",\"title\":\"Robe Albane blanche \",\"url\":\"https:\\\/\\\/fr.antikbatik.com\\\/catalog\\\/product\\\/view\\\/id\\\/22017\\\/s\\\/robe-albane-blanche\\\/?size=62\",\"image_url\":\"https:\\\/\\\/media.antikbatik.com\\\/catalog\\\/product\\\/a\\\/l\\\/albane-dress.jpg\",\"published_at_foreign\":\"\",\"sku\":\"ALBANE1DRE-WHITE-36XS\",\"price\":\"195.0000\",\"inventory_quantity\":0,\"backorders\":\"0\",\"visibility\":\"false\"},{\"id\":\"22019\",\"title\":\"Robe Albane blanche \",\"url\":\"https:\\\/\\\/fr.antikbatik.com\\\/catalog\\\/product\\\/view\\\/id\\\/22017\\\/s\\\/robe-albane-blanche\\\/?size=63\",\"image_url\":\"https:\\\/\\\/media.antikbatik.com\\\/catalog\\\/product\\\/a\\\/l\\\/albane-dress.jpg\",\"published_at_foreign\":\"\",\"sku\":\"ALBANE1DRE-WHITE-38S\",\"price\":\"195.0000\",\"inventory_quantity\":6,\"backorders\":\"0\",\"visibility\":\"false\"},{\"id\":\"22020\",\"title\":\"Robe Albane blanche \",\"url\":\"https:\\\/\\\/fr.antikbatik.com\\\/catalog\\\/product\\\/view\\\/id\\\/22017\\\/s\\\/robe-albane-blanche\\\/?size=64\",\"image_url\":\"https:\\\/\\\/media.antikbatik.com\\\/catalog\\\/product\\\/a\\\/l\\\/albane-dress.jpg\",\"published_at_foreign\":\"\",\"sku\":\"ALBANE1DRE-WHITE-40M\",\"price\":\"195.0000\",\"inventory_quantity\":11,\"backorders\":\"0\",\"visibility\":\"false\"},{\"id\":\"22021\",\"title\":\"Robe Albane blanche \",\"url\":\"https:\\\/\\\/fr.antikbatik.com\\\/catalog\\\/product\\\/view\\\/id\\\/22017\\\/s\\\/robe-albane-blanche\\\/?size=65\",\"image_url\":\"https:\\\/\\\/media.antikbatik.com\\\/catalog\\\/product\\\/a\\\/l\\\/albane-dress.jpg\",\"published_at_foreign\":\"\",\"sku\":\"ALBANE1DRE-WHITE-42L\",\"price\":\"195.0000\",\"inventory_quantity\":2,\"backorders\":\"0\",\"visibility\":\"false\"}]}"},{"method":"POST","path":"\/ecommerce\/stores\/14850a5b3f240bd2bc382f74e67e528d\/orders","operation_id":"ORD_1553015106_63502","body":"{\"id\":\"000005370\",\"currency_code\":\"EUR\",\"order_total\":\"165.0000\",\"tax_total\":\"27.5000\",\"discount_total\":0,\"shipping_total\":\"0.0000\",\"financial_status\":\"paid\",\"processed_at_foreign\":\"2019-03-19 17:05:07\",\"updated_at_foreign\":\"2019-03-19 17:05:09\",\"lines\":[{\"id\":\"1\",\"product_id\":\"22091\",\"product_variant_id\":\"22091\",\"quantity\":1,\"price\":\"137.5000\",\"discount\":0}],\"customer\":{\"id\":\"18941\",\"first_name\":\"B\\u00e9atrice\",\"last_name\":\"BRETON\",\"address\":{\"address1\":\"R\\u00e9sidence Lagravere Mancel\",\"address2\":\"B\\u00e2t B\",\"city\":\"COLOMBES\",\"province\":\"Hauts-de-Seine\",\"province_code\":\"92\",\"postal_code\":\"92700\",\"country\":\"France\",\"country_code\":\"FR\"},\"company\":\"164 Bd Charles de Gaulle\",\"orders_count\":1,\"total_spent\":165},\"order_url\":\"https:\\\/\\\/fr.antikbatik.com\\\/sales\\\/order\\\/view\\\/order_id\\\/63502\\\/\",\"billing_address\":{\"address1\":\"R\\u00e9sidence Lagravere Mancel\",\"address2\":\"B\\u00e2t B\",\"city\":\"COLOMBES\",\"province\":\"Hauts-de-Seine\",\"province_code\":\"92\",\"postal_code\":\"92700\",\"country\":\"France\",\"country_code\":\"FR\",\"name\":\"M B\\u00e9atrice BRETON\",\"company\":\"164 Bd Charles de Gaulle\"},\"shipping_address\":{\"name\":\"M B\\u00e9atrice BRETON\",\"address1\":\"R\\u00e9sidence Lagravere Mancel\",\"address2\":\"B\\u00e2t B\",\"city\":\"COLOMBES\",\"province\":\"Hauts-de-Seine\",\"province_code\":\"92\",\"postal_code\":\"92700\",\"country\":\"France\",\"country_code\":\"FR\"}}"},[{"method":"PATCH","path":"\/ecommerce\/stores\/14850a5b3f240bd2bc382f74e67e528d\/products\/22017","operation_id":"PRO_1553015106_22017","body":"{\"id\":\"22017\",\"title\":\"Robe Albane blanche \",\"url\":\"https:\\\/\\\/fr.antikbatik.com\\\/catalog\\\/product\\\/view\\\/id\\\/22017\\\/s\\\/robe-albane-blanche\\\/\",\"image_url\":\"https:\\\/\\\/media.antikbatik.com\\\/catalog\\\/product\\\/a\\\/l\\\/albane-dress.jpg\",\"published_at_foreign\":\"\",\"description\":\"Robe mi-longue en cr\\u00eape de coton l\\u00e9g\\u00e8re et fluide. Petites emmanchures r\\u00e9glables avec des cordons de serrage en coton. Col et encolure brod\\u00e9s d\\u2019une frise florale. Le fil des broderies se d\\u00e9grade en un joli cama\\u00efeu de bleus. Associez notre robe Albane avec nos sandales tress\\u00e9es Mina pour un total look boh\\u00e8me romantique. La robe Albane est livr\\u00e9e avec un fond de robe. L\\u00e9a mesure 1m72 et porte une taille 38. La robe mesure 105 cm de long pour une taille 38 (S).\",\"vendor\":\"Collection Printemps-\\u00c9t\\u00e9 - Robes\",\"type\":\"Collection Printemps-\\u00c9t\\u00e9 - Robes\",\"handle\":\"\",\"variants\":[{\"id\":\"22017\",\"title\":\"Robe Albane blanche \",\"url\":\"https:\\\/\\\/fr.antikbatik.com\\\/catalog\\\/product\\\/view\\\/id\\\/22017\\\/s\\\/robe-albane-blanche\\\/\",\"image_url\":\"https:\\\/\\\/media.antikbatik.com\\\/catalog\\\/product\\\/a\\\/l\\\/albane-dress.jpg\",\"published_at_foreign\":\"\",\"sku\":\"ALBANE1DRE-WHITE\",\"price\":0,\"inventory_quantity\":0,\"backorders\":\"0\",\"visibility\":\"true\"},{\"id\":\"22018\",\"title\":\"Robe Albane blanche \",\"url\":\"https:\\\/\\\/fr.antikbatik.com\\\/catalog\\\/product\\\/view\\\/id\\\/22017\\\/s\\\/robe-albane-blanche\\\/?size=62\",\"image_url\":\"https:\\\/\\\/media.antikbatik.com\\\/catalog\\\/product\\\/a\\\/l\\\/albane-dress.jpg\",\"published_at_foreign\":\"\",\"sku\":\"ALBANE1DRE-WHITE-36XS\",\"price\":\"195.0000\",\"inventory_quantity\":0,\"backorders\":\"0\",\"visibility\":\"false\"},{\"id\":\"22019\",\"title\":\"Robe Albane blanche \",\"url\":\"https:\\\/\\\/fr.antikbatik.com\\\/catalog\\\/product\\\/view\\\/id\\\/22017\\\/s\\\/robe-albane-blanche\\\/?size=63\",\"image_url\":\"https:\\\/\\\/media.antikbatik.com\\\/catalog\\\/product\\\/a\\\/l\\\/albane-dress.jpg\",\"published_at_foreign\":\"\",\"sku\":\"ALBANE1DRE-WHITE-38S\",\"price\":\"195.0000\",\"inventory_quantity\":6,\"backorders\":\"0\",\"visibility\":\"false\"},{\"id\":\"22020\",\"title\":\"Robe Albane blanche \",\"url\":\"https:\\\/\\\/fr.antikbatik.com\\\/catalog\\\/product\\\/view\\\/id\\\/22017\\\/s\\\/robe-albane-blanche\\\/?size=64\",\"image_url\":\"https:\\\/\\\/media.antikbatik.com\\\/catalog\\\/product\\\/a\\\/l\\\/albane-dress.jpg\",\"published_at_foreign\":\"\",\"sku\":\"ALBANE1DRE-WHITE-40M\",\"price\":\"195.0000\",\"inventory_quantity\":11,\"backorders\":\"0\",\"visibility\":\"false\"},{\"id\":\"22021\",\"title\":\"Robe Albane blanche \",\"url\":\"https:\\\/\\\/fr.antikbatik.com\\\/catalog\\\/product\\\/view\\\/id\\\/22017\\\/s\\\/robe-albane-blanche\\\/?size=65\",\"image_url\":\"https:\\\/\\\/media.antikbatik.com\\\/catalog\\\/product\\\/a\\\/l\\\/albane-dress.jpg\",\"published_at_foreign\":\"\",\"sku\":\"ALBANE1DRE-WHITE-42L\",\"price\":\"195.0000\",\"inventory_quantity\":2,\"backorders\":\"0\",\"visibility\":\"false\"}]}"}],{"method":"POST","path":"\/ecommerce\/stores\/14850a5b3f240bd2bc382f74e67e528d\/carts","operation_id":"QUO_2019-03-19-17-05-16-68713800_86355","body":"{\"id\":\"86355\",\"customer\":{\"id\":\"GUEST-2019-03-19-17-05-17-36646800\",\"email_address\":\"gabriel+2019-03@gmail.com\",\"opt_in_status\":false,\"address\":{\"address1\":\"5 All\\u00e9e du Cadre Noir\",\"city\":\"Poitiers\",\"province\":\"Vienne\",\"province_code\":\"86\",\"postal_code\":\"86000\",\"shipping_address\":{\"country\":\"France\",\"country_code\":\"FR\"}}},\"checkout_url\":\"https:\\\/\\\/fr.antikbatik.com\\\/mailchimp\\\/cart\\\/loadquote\\\/id\\\/86355\\\/token\\\/cf0a92389d9e6efde84fb4264b3f8b6d\\\/\",\"currency_code\":\"EUR\",\"order_total\":\"195.0000\",\"tax_total\":0,\"lines\":[{\"id\":\"1\",\"product_id\":\"22019\",\"product_variant_id\":\"22019\",\"quantity\":1,\"price\":\"162.5000\"}]}"}]}

It seems that the Mailchimp API is expecting an object when calling it and the json when decoded look like that : 

>array (
  'operations' => 
  array (
    0 => 
    array (
      'method' => 'PATCH',
      'path' => '/ecommerce/stores/14850a5b3f240bd2bc382f74e67e528d/products/22017',
      'operation_id' => 'PRO_1553013607_22017',
      'body' => '{"id":"22017","title":"Vestido Midi Albane Blanco","url":"https:\\/\\/fr.antikbatik.com\\/catalog\\/product\\/view\\/id\\/22017\\/s\\/vestido-midi-albane-blanco\\/","image_url":"https:\\/\\/media.antikbatik.com\\/catalog\\/product\\/a\\/l\\/albane-dress.jpg","published_at_foreign":"","description":"Vestido Midi ALBANE Blanco de crep\\u00e9 de algod\\u00f3n ligero y fluido. Mangas ajustables con un cord\\u00f3n de algod\\u00f3n. Cuello y escote decorados con flores bordadas. El bordado en hilo crea un degradado en tonos azules. Conjunta nuestro vestido Albane con nuestras sandalias trenzadas Mina para un look boho rom\\u00e1ntico de la cabeza a los pies. Lea mide 1m72 (5\\u00276\\u0022) de altura y lleva la talla 38 (S). El vestido en la talla 38 (S) mide 105 cm de largo.","vendor":"Collection Printemps-\\u00c9t\\u00e9 - Robes","type":"Collection Printemps-\\u00c9t\\u00e9 - Robes","handle":"","variants":[{"id":"22017","title":"Vestido Midi Albane Blanco","url":"https:\\/\\/fr.antikbatik.com\\/catalog\\/product\\/view\\/id\\/22017\\/s\\/vestido-midi-albane-blanco\\/","image_url":"https:\\/\\/media.antikbatik.com\\/catalog\\/product\\/a\\/l\\/albane-dress.jpg","published_at_foreign":"","sku":"ALBANE1DRE-WHITE","price":0,"inventory_quantity":0,"backorders":"0","visibility":"true"},{"id":"22018","title":"Robe Albane blanche ","url":"https:\\/\\/fr.antikbatik.com\\/catalog\\/product\\/view\\/id\\/22017\\/s\\/vestido-midi-albane-blanco\\/?size=62","image_url":"https:\\/\\/media.antikbatik.com\\/catalog\\/product\\/a\\/l\\/albane-dress.jpg","published_at_foreign":"","sku":"ALBANE1DRE-WHITE-36XS","price":"205.0000","inventory_quantity":0,"backorders":"0","visibility":"false"},{"id":"22019","title":"Robe Albane blanche ","url":"https:\\/\\/fr.antikbatik.com\\/catalog\\/product\\/view\\/id\\/22017\\/s\\/vestido-midi-albane-blanco\\/?size=63","image_url":"https:\\/\\/media.antikbatik.com\\/catalog\\/product\\/a\\/l\\/albane-dress.jpg","published_at_foreign":"","sku":"ALBANE1DRE-WHITE-38S","price":"205.0000","inventory_quantity":6,"backorders":"0","visibility":"false"},{"id":"22020","title":"Robe Albane blanche ","url":"https:\\/\\/fr.antikbatik.com\\/catalog\\/product\\/view\\/id\\/22017\\/s\\/vestido-midi-albane-blanco\\/?size=64","image_url":"https:\\/\\/media.antikbatik.com\\/catalog\\/product\\/a\\/l\\/albane-dress.jpg","published_at_foreign":"","sku":"ALBANE1DRE-WHITE-40M","price":"205.0000","inventory_quantity":11,"backorders":"0","visibility":"false"},{"id":"22021","title":"Robe Albane blanche ","url":"https:\\/\\/fr.antikbatik.com\\/catalog\\/product\\/view\\/id\\/22017\\/s\\/vestido-midi-albane-blanco\\/?size=65","image_url":"https:\\/\\/media.antikbatik.com\\/catalog\\/product\\/a\\/l\\/albane-dress.jpg","published_at_foreign":"","sku":"ALBANE1DRE-WHITE-42L","price":"205.0000","inventory_quantity":2,"backorders":"0","visibility":"false"}]}',
    ),
    1 => 
    array (
      0 => 
      array (
        'method' => 'PATCH',
        'path' => '/ecommerce/stores/14850a5b3f240bd2bc382f74e67e528d/products/22017',
        'operation_id' => 'PRO_1553013607_22017',
        'body' => '{"id":"22017","title":"Vestido Midi Albane Blanco","url":"https:\\/\\/fr.antikbatik.com\\/catalog\\/product\\/view\\/id\\/22017\\/s\\/vestido-midi-albane-blanco\\/","image_url":"https:\\/\\/media.antikbatik.com\\/catalog\\/product\\/a\\/l\\/albane-dress.jpg","published_at_foreign":"","description":"Vestido Midi ALBANE Blanco de crep\\u00e9 de algod\\u00f3n ligero y fluido. Mangas ajustables con un cord\\u00f3n de algod\\u00f3n. Cuello y escote decorados con flores bordadas. El bordado en hilo crea un degradado en tonos azules. Conjunta nuestro vestido Albane con nuestras sandalias trenzadas Mina para un look boho rom\\u00e1ntico de la cabeza a los pies. Lea mide 1m72 (5\\u00276\\u0022) de altura y lleva la talla 38 (S). El vestido en la talla 38 (S) mide 105 cm de largo.","vendor":"Collection Printemps-\\u00c9t\\u00e9 - Robes","type":"Collection Printemps-\\u00c9t\\u00e9 - Robes","handle":"","variants":[{"id":"22017","title":"Vestido Midi Albane Blanco","url":"https:\\/\\/fr.antikbatik.com\\/catalog\\/product\\/view\\/id\\/22017\\/s\\/vestido-midi-albane-blanco\\/","image_url":"https:\\/\\/media.antikbatik.com\\/catalog\\/product\\/a\\/l\\/albane-dress.jpg","published_at_foreign":"","sku":"ALBANE1DRE-WHITE","price":0,"inventory_quantity":0,"backorders":"0","visibility":"true"},{"id":"22018","title":"Robe Albane blanche ","url":"https:\\/\\/fr.antikbatik.com\\/catalog\\/product\\/view\\/id\\/22017\\/s\\/vestido-midi-albane-blanco\\/?size=62","image_url":"https:\\/\\/media.antikbatik.com\\/catalog\\/product\\/a\\/l\\/albane-dress.jpg","published_at_foreign":"","sku":"ALBANE1DRE-WHITE-36XS","price":"205.0000","inventory_quantity":0,"backorders":"0","visibility":"false"},{"id":"22019","title":"Robe Albane blanche ","url":"https:\\/\\/fr.antikbatik.com\\/catalog\\/product\\/view\\/id\\/22017\\/s\\/vestido-midi-albane-blanco\\/?size=63","image_url":"https:\\/\\/media.antikbatik.com\\/catalog\\/product\\/a\\/l\\/albane-dress.jpg","published_at_foreign":"","sku":"ALBANE1DRE-WHITE-38S","price":"205.0000","inventory_quantity":6,"backorders":"0","visibility":"false"},{"id":"22020","title":"Robe Albane blanche ","url":"https:\\/\\/fr.antikbatik.com\\/catalog\\/product\\/view\\/id\\/22017\\/s\\/vestido-midi-albane-blanco\\/?size=64","image_url":"https:\\/\\/media.antikbatik.com\\/catalog\\/product\\/a\\/l\\/albane-dress.jpg","published_at_foreign":"","sku":"ALBANE1DRE-WHITE-40M","price":"205.0000","inventory_quantity":11,"backorders":"0","visibility":"false"},{"id":"22021","title":"Robe Albane blanche ","url":"https:\\/\\/fr.antikbatik.com\\/catalog\\/product\\/view\\/id\\/22017\\/s\\/vestido-midi-albane-blanco\\/?size=65","image_url":"https:\\/\\/media.antikbatik.com\\/catalog\\/product\\/a\\/l\\/albane-dress.jpg","published_at_foreign":"","sku":"ALBANE1DRE-WHITE-42L","price":"205.0000","inventory_quantity":2,"backorders":"0","visibility":"false"}]}',
      ),
    ),
    2 => 
    array (
      'method' => 'POST',
      'path' => '/ecommerce/stores/14850a5b3f240bd2bc382f74e67e528d/carts',
      'operation_id' => 'QUO_2019-03-19-16-40-18-06445900_86355',
      'body' => '{"id":"86355","customer":{"id":"GUEST-2019-03-19-16-40-18-83071200","email_address":"gabriel+2019-03@gmail.com","opt_in_status":false,"address":{"address1":"5 All\\u00e9e du Cadre Noir","city":"Poitiers","province":"Vienne","province_code":"86","postal_code":"86000","shipping_address":{"country":"France","country_code":"FR"}}},"checkout_url":"https:\\/\\/fr.antikbatik.com\\/mailchimp\\/cart\\/loadquote\\/id\\/86355\\/token\\/1e600b1b8697ba6848c04679bcfa2b91\\/","currency_code":"EUR","order_total":"195.0000","tax_total":0,"lines":[{"id":"1","product_id":"22019","product_variant_id":"22019","quantity":1,"price":"162.5000"}]}',
    ),
  ),
)

Is this a know issue? Could you please advise on what needs to be done ?

Thanks in advance for your help,

Best,

G

**Comment by gonzaloebiz** [comment]
Try with the current version.
If you have the same issue, we will re open the issue

Best
