### ISSUE TITLE
First and last name not being sent to MC for new customers

### ISSUE THREAD

**Issue by robbie-thompson** [mailchimp/mc-magento2#663]
## Issue Description

When a new users registers and subscribes to the newsletter, they are added as a subscriber to the MC list - however their first and last name is missing.

I'm not sure if this is a bug, or if this feature just hasn't been implemented.

Pre-conditions:

    1. Magento CE 2.2.6 without sample data is installed.
    2. mc-magento2 101.2.34

Steps to reproduce issue:

    1. Fill out first name, last name, email, password on register page
    2. Ensure newsletter subscription is unticked (I only tested this issue with subscribing after registration)
    3. Register account
    4. Go to Account > Mail Subscriptions
    5. Tick 'General Subscription' and save
    6. Newly added contact in MC list will have email but no names

**Comment by gonzaloebiz** [comment]
Hi @robbie-thompson 

thanks for your feedback.
Please update the issue with an step by step to reproduce the issue.

Best

**Comment by robbie-thompson** [comment]
@gonzaloebiz Done

**Comment by gonzaloebiz** [comment]
Thanks, we will check it

**Comment by robbie-thompson** [comment]
@gonzaloebiz Did you manage to reproduce this issue?

**Comment by gonzaloebiz** [comment]
Hi @robbie-thompson 

no, i try it but works OK for me

![image](https://user-images.githubusercontent.com/6222792/56987277-5bf18500-6b63-11e9-8c69-e0709f1d6216.png)

![image](https://user-images.githubusercontent.com/6222792/56987448-d6220980-6b63-11e9-8ec9-1f2fceecf911.png)
