### ISSUE TITLE
Magento2.3.1 Unable to unserialize value. Error: Syntax error 

### ISSUE THREAD

**Issue by Abdulkadiragoliya** [mailchimp/mc-magento2#668]
# Unable to unserialize value. Error: Syntax error
 PHP 7.2
 Magento 2.3.1 
 Emabizmarts_Mailchimp102.3.34 (mc-magento2)

## Issue Description
> Unable to Configure Mailchimp Configuration. 
When i go to admin section Mailchimp -> Configuration 
 
## 
     1. Login to Admin 
    2. Click on Menu Mailchimp - > Configuration.
 
### Actual and Expected result

Expected result:
Configuration Page should display without any error

Actual result:
Exception #0 (InvalidArgumentException): Unable to unserialize value. Error: Syntax error

Exception #0 (InvalidArgumentException): Unable to unserialize value. Error: Syntax error
<pre>#1 Ebizmarts\MailChimp\Helper\Data->unserialize() called at [vendor/mailchimp/mc-magento2/Helper/VarsMap.php:107]
#2 Ebizmarts\MailChimp\Helper\VarsMap->unserializeValue() called at [vendor/mailchimp/mc-magento2/Helper/VarsMap.php:42]
#3 Ebizmarts\MailChimp\Helper\VarsMap->makeArrayFieldValue() called at [vendor/mailchimp/mc-magento2/Model/Config/Backend/VarsMap.php:58]
#4 Ebizmarts\MailChimp\Model\Config\Backend\VarsMap->_afterLoad() called at [vendor/magento/framework/Model/AbstractModel.php:604]
#5 Magento\Framework\Model\AbstractModel->afterLoad() called at [generated/code/Ebizmarts/MailChimp/Model/Config/Backend/VarsMap/Interceptor.php:323]
#6 Ebizmarts\MailChimp\Model\Config\Backend\VarsMap\Interceptor->afterLoad() called at [vendor/magento/module-config/Block/System/Config/Form.php:431]
#7 Magento\Config\Block\System\Config\Form->getFieldData() called at [vendor/magento/module-config/Block/System/Config/Form.php:340]
#8 Magento\Config\Block\System\Config\Form->_initElement() called at [vendor/magento/module-config/Block/System/Config/Form.php:316]
#9 Magento\Config\Block\System\Config\Form->initFields() called at [vendor/magento/module-config/Block/System/Config/Form.php:256]
#10 Magento\Config\Block\System\Config\Form->_initGroup() called at [vendor/magento/module-config/Block/System/Config/Form.php:202]
#11 Magento\Config\Block\System\Config\Form->initForm() called at [vendor/magento/module-config/Block/System/Config/Form.php:538]
#12 Magento\Config\Block\System\Config\Form->_beforeToHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:667]
#13 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:557]
#14 Magento\Framework\View\Layout->_renderBlock() called at [vendor/magento/framework/View/Layout.php:533]
#15 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#16 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:488]
#17 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#18 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Element/AbstractBlock.php:508]
#19 Magento\Framework\View\Element\AbstractBlock->getChildHtml() called at [vendor/magento/module-config/view/adminhtml/templates/system/config/edit.phtml:28]
#20 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:59]
#21 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/View/Element/Template.php:271]
#22 Magento\Framework\View\Element\Template->fetchView() called at [vendor/magento/framework/View/Element/Template.php:301]
#23 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/module-backend/Block/Template.php:129]
#24 Magento\Backend\Block\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:668]
#25 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:557]
#26 Magento\Framework\View\Layout->_renderBlock() called at [vendor/magento/framework/View/Layout.php:533]
#27 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#28 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:488]
#29 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#30 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:585]
#31 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:535]
#32 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#33 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:488]
#34 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#35 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:585]
#36 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:535]
#37 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#38 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:488]
#39 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#40 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:585]
#41 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:535]
#42 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#43 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:488]
#44 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#45 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:585]
#46 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:535]
#47 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#48 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:488]
#49 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#50 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:585]
#51 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:535]
#52 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#53 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:488]
#54 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#55 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:585]
#56 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:535]
#57 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#58 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:488]
#59 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#60 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:585]
#61 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:535]
#62 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#63 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:488]
#64 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#65 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:585]
#66 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:535]
#67 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#68 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:488]
#69 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#70 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:954]
#71 Magento\Framework\View\Layout->getOutput() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:492]
#72 Magento\Framework\View\Layout\Interceptor->getOutput() called at [vendor/magento/framework/View/Result/Page.php:258]
#73 Magento\Framework\View\Result\Page->render() called at [vendor/magento/framework/View/Result/Layout.php:171]
#74 Magento\Framework\View\Result\Layout->renderResult() called at [generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php:193]
#75 Magento\Backend\Model\View\Result\Page\Interceptor->renderResult() called at [vendor/magento/framework/App/Http.php:140]
#76 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#77 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:258]
#78 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:105]

**Comment by gonzaloebiz** [comment]
Hi @Abdulkadiragoliya 

we can't reproduce your issue, please give us more information to try.
Are you migrating from a prior version of magento or mc-magento2?

Best

**Comment by grudado** [comment]
Check your composer.json.
I had this problem too. Solved after install some missing modules in composer.json
        "friendsofphp/php-cs-fixer": "~2.13.0",
        "lusitanian/oauth": "~0.8.10",
        "magento/magento2-functional-testing-framework": "~2.3.13",
        "pdepend/pdepend": "2.5.2",
        "phpmd/phpmd": "@stable",
        "phpunit/phpunit": "~6.5.0",
        "sebastian/phpcpd": "~3.0.0",
        "squizlabs/php_codesniffer": "3.3.1",
        "allure-framework/allure-phpunit": "~1.2.0"

**Comment by gonzaloebiz** [comment]
Hi @tratta 

sorry but i don't understand your comment, can you clarify

Best

**Comment by anatolij-p** [comment]
Try deleting/checking mailchimp/general/map_fields(or something like that) value.
I had something weird there and once i've deleted that field value it all worked fine.

**Comment by miteshdhaduk** [comment]
I have the same problem in Magento 2.3.1. Error: `main.CRITICAL: Unable to unserialize value. Error: Syntax error [] []`
