### ISSUE TITLE
Requested product doesn't exist

### ISSUE THREAD

**Issue by mamreezaa** [mailchimp/mc-magento2#67]
I have the following error when cron runs
'[Magento\Framework\Exception\NoSuchEntityException]  
  Requested product doesn't exist'

i can make sure this comes from Model/Api/Orders.php

Note : i think we need to skip the order if the product does not exist instead if breaking the process.

**Comment by mikehenze** [comment]
@mamreezaa 
After implementing your changes from https://github.com/mailchimp/mc-magento2/issues/58 I actually now get the same error.

I have many orders where the product does not exist anymore.

**Comment by mamreezaa** [comment]
The problem is 
$productData = $this->_apiProduct->sendModifiedProduct($order, $mailchimpStoreId, $magentoStoreId); in order.php

i did try and catch this statement to make sure not to break the loop. 
`try {
                    $productData = $this->_apiProduct->sendModifiedProduct($order, $mailchimpStoreId, $magentoStoreId);
                    if (count($productData)) {
                        foreach ($productData as $p) {
                            $batchArray[$this->_counter] = $p;
                            $this->_counter++;
                        }
                    }
                }catch (\Exception $e){
                    $this->_helper->log($e->getMessage());
                    continue;
                }`


NOte: there are two places we have to do the same fix in order.php

**Comment by mikehenze** [comment]
The commit does not fix this for me.
My log is filled with "Requested product doesn't exist" and the orders are not send to mailchimp.
Subscribers and products work fine.

Note: I have many orders (8000+) with products that do not exist anymore.

Edit: If i set the data to a couple of months ago it will add new orders again so I am guessing it hits a timeout error when trying to add many orders with the products deleted from it.

Please investigate,

**Comment by msawyers** [comment]
Hi, any fix for this issue?

**Comment by msawyers** [comment]
I am receiving same on version mc-magento 1.0.26


[2018-02-08 16:20:39] main.CRITICAL: Requested product doesn't exist {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): Requested product doesn't exist at /home/public_html/vendor/magento/module-catalog/Model/ProductRepository.php:240)"} []

**Comment by sneha-sukumaran** [comment]
Issues exists in version 1.0.29 too. When can we expect a fix for this?

**Comment by khnaim** [comment]
I have this Issues in version  1.0.28 and  1.0.29 , did you find a solution for this fix ?

**Comment by GideonBabu** [comment]
Hi @gonzaloebiz it looks like this issue still persist even after the commit code is implemented. Do we have any patch code to get this fixed in our environment also we are facing this issue? 

We have migrated a website from Magento 1 to Magento 2. Many orders are with products that do not exist in the new store. So the logs are filled with **requested product doesn't exist**

If you could provide us with a patch or code fix, that is appreciatable.

**Comment by cclohman** [comment]
@gonzaloebiz Same here for us @GideonBabu.  We've been working extensively with Pablo @ ebizmarts customer support on several issues and now that we are updated to 1.0.30, we are seeing our cron table fill with this error as well.  We are on Mage 2.2.1, Mailchimp 4 Magento 1.0.30, Mailchimp Lib 3.0.28.

**Comment by cjbelo** [comment]
I am also getting this error "Requested product doesn't exist" with my Magento 2.1.7 & MailChimp 1.0.27. Any update regarding this? Thanks!

**Comment by gonzaloebiz** [comment]
Hi @cjbelo 

yes sure, update the extension to the current version

Best

**Comment by duckchip** [comment]
@gonzaloebiz I still have this issue with 1.1.32 and Magento 2.1.11

**Comment by gonzaloebiz** [comment]
@duckchip if you have an issue, please open a new issue with all the corresponding data

Best
