### ISSUE TITLE
Multistore with different Mailchimp account wrong synchronization on customer delete/unsubcribe from magento admin

### ISSUE THREAD

**Issue by Garde85** [mailchimp/mc-magento2#674]
### Preconditions
    1. Magento Open source 2.3.1 with sample data installed.
    2. mc-magento2 102.3.34.
    3. Magento installation include multiwebsite www.website1.com & www.website2.com
    4. Every website is associated to a different mailchimp account
    5. Mailchimp configuration is setted in website scope, not in store view scope

### Steps to reproduce

    1. Navigate to storefront www.website1.com
    2. Subscribe to newsletter with email: test@test.com
    3. Navigate to storefront www.website2.com
    4. Subscribe to newsletter with email: test@test.com (yes, the same email in different website)

    5. Access to magento shared admin panel www.website1.com/admin
    6. Go to Maketing > Newsletter Scubscriber
    7. Delete test@test.com subscription form www.website2.com 

### Expected result:

Magento delete customer subscription in admin and synchronize mailchimp account associated to www.website2.com website.    

### Actual result:
 
Magento delete customer subscription in admin but synchronization is applied to the first site www.website1.com. 

### Additional information

I think that problem concern this file:

vendor/mailchimp/mc-magento2/Model/Plugin/Subscriber.php

on line 171, when this function is called:

`$api->lists->members->update($this->_helper->getDefaultList(), $md5HashEmail, null, 'unsubscribed');`

getDefaultList get a wrong value of 'mailchimp/general/monkeylist' variable. I think that the problem is caused by a bad use of variable's scope.

**Comment by luciaebizmarts** [comment]
Hi @Garde85, 

Thanks for your feedback.
Seems that you are right, we will look into this.

Best regards.

**Comment by Garde85** [comment]
Hi.... when this fix will be merged into master branch? Or could you tell me which branch/tags I have to insert in my composer.json? 

Thank you

**Comment by gonzaloebiz** [comment]
The fix is already merged in the develop branches, depending on the magento version
