### ISSUE TITLE
Website scope always taking list from default configuration

### ISSUE THREAD

**Issue by ebizmarts-keller** [mailchimp/mc-magento2#68]
Magento version: 2.1.7
Plugin version: 1.0.22

The website scope always loads the list configured in the default scope regardless of the store selected in the website scope, it will load the correct list when selecting it, but not when saving the configuration.

Even if the default scope is disabled this will happen, in this case it will not load any list in the website scope.

![websitescope](https://user-images.githubusercontent.com/19838935/29327256-f5422b2c-81c4-11e7-9cf7-8bb15e3b8515.png)

Note: Api key field has been hidden

**Comment by simonrl** [comment]
Still having this issue with Magento 2.1.14 and Mailchimp 1.1.32. Any idea why this still happens?
