### ISSUE TITLE
Sync guest newsletter subscribers to Mailchimp list

### ISSUE THREAD

**Issue by vDeggial** [mailchimp/mc-magento2#699]
Magento 2.2.8 CE
Mailchimp module: Version 101.2.34

When somebody subscribes to a newsletter as a guest via our client's Magento store they are not added to Mailchimp's list, if they create account and then subscribe to newsletter they do
get synced with Mailchimp and are sent the Welcome email

Is there a way for guests who just enter email address in the form for newsletter to be added to Mailchimp list as subscribers (they are in magento's Newsletetr Subscribers list as Guest)

**Comment by gonzaloebiz** [comment]
Hi @shinoamakusa 

if you subscribe p.e. in the bottom of the page

![image](https://user-images.githubusercontent.com/6222792/57470254-c3dc5580-725e-11e9-9afb-1810bdeb6c0b.png)

works perfectly
Enable the extension logs and take a look at var/log/Mailchimp.log

Best

**Comment by gonzaloebiz** [comment]
No news in 15 days
