### ISSUE TITLE
Campaign catcher does not work

### ISSUE THREAD

**Issue by mikehenze** [mailchimp/mc-magento2#71]
**Preconditions**

Magento 2.1.7
Mailchimp 1.0.22

**Steps to reproduce**

1. Send a mailing in Mailchimp
2. Clearly see visitors arriving with the mc_cid parameters (?mc_cid=xxx&mc_eid=xxx)
3. Visitor buys items

**Actual and Expected result**

Expected: Mailchimp campaign gets updated with the ecommerce results.
However this does not happen.

The ecommerce data is passing over to mailchimp but seems not to be connected with the campaign.
Looks like campaigncatcher.js is not working at all.

Please check.

**Comment by gonzaloebiz** [comment]
Hi @mikehenze 

i just test this, and works OK.
Keep in mind, the order is not synced to mailchimp instantly, and if the order contain a bundle or grouped product is not synced.
