### ISSUE TITLE
error after upgrade

### ISSUE THREAD

**Issue by glutenvrijemarkt** [mailchimp/mc-magento2#72]
Hi,

With install we get this error after php bin/magento setup:upgrade

  [Magento\Framework\Exception\SessionException]
  Area code not set: Area code must be set before starting a session.

  [Magento\Framework\Exception\LocalizedException]
  Area code is not set

Magento Latest M2 Version
Ebizmarts_MailChimp version - 1.0.22

What can we do to get this module working?

**Comment by gonzaloebiz** [comment]
Hi @glutenvrijemarkt 

plase run bin/magento deploy:mode:show and let me know the result

Best

**Comment by centerax** [comment]
"Magento Latest M2 Version" what version number specifically?

**Comment by gonzaloebiz** [comment]
no news after 1 week, close the issue

**Comment by glutenvrijemarkt** [comment]
Sorry, didn't see the update

Current application mode: production. (Note: Environment variables may override this value.)
--
