### ISSUE TITLE
Mailchimp Sync and Mageplaza Gift Card product

### ISSUE THREAD

**Issue by vDeggial** [mailchimp/mc-magento2#720]
Magento 2.2.8
Mailchimp version: 101.2.34
Mageplaza Gift Card plugin

There seems to be issue with Mailchimp Sync (in order to send order confirmation and invoice emails) when Gift Card type product (which is using Mageplaza Gift Card plugin)

Mailchimp log shows:

`MailChimpLogger.INFO: "Something went wrong when retreiving product information."`

Not sure if it is an issue with Mailchimp plugin or gift card one so i also have ticket open with mageplaza

**Comment by gonzaloebiz** [comment]
Hi @shinoamakusa 

since Mageplaza Gift Card is a paid extension, we can't access to it, sorry, we can't help you on this

Best

**Comment by vDeggial** [comment]
1) Mageplaza Gift Card products are of type mpgiftcard whcih is counted as custom type and ignored by mailchimp sync
2) Problem seems to be in GeneratePOSTPayload method which returns empty

**Comment by gonzaloebiz** [comment]
This is right when the order contains an unsupported product, the product is skipped and not added to the order to sync, and if the order has no product, the order is skipped and the message 'Something went wrong when retrieving product information.'  is saved in the log.

Best
