### ISSUE TITLE
Receiving two newsletter subscription confirmation emails, after subscribing through checkout

### ISSUE THREAD

**Issue by ktsixit** [mailchimp/mc-magento2#725]
## Issue Description
I have installed Mailchimp extension in my Magento website. I am using default magento checkout and set mailchimp setting "Magento always manage emails" to "Yes".

Subscribing to Newsletter via standard magento newsletter form, works ok. In this case I'm receing the magento Subscription Confirmation email.

Subscribing to Newsletter via checkout proccess has an issue though. I am receiving two Subscription Confirmation email, one form magento and on from Mailchimp.

### Preconditions

    1. Magento CE 2.3.0
    2. mc-magento2 102.3.34

### Steps to reproduce

    1. Checkout and during checkout pocces check "Subscribe me to Newsletter" checkbox

### Actual and Expected result

    Expected result:
    Receive Magento's Subscription Confirmation email
    Actual result:
    Receive Subscription Confirmation both from mailchimp and magento

**Comment by gonzaloebiz** [comment]
Hi @ktsixit 

thanks for your feedback,
What is the double opt-in configuration in MailChimp for this audience?

Best

**Comment by ktsixit** [comment]
Hi @gonzaloebiz ,
Double opt-in is **disabled** for this audience

**Comment by ktsixit** [comment]
I have also checked 
https://github.com/mailchimp/mc-magento2/issues/91
https://github.com/mailchimp/mc-magento2/commit/4417b7f88a90e9d452be122f33f0561307d66c7b

and the code is similar to the fix suggested.

I also tried to convert:
```
if (!$this->_helper->getConfigValue(\Ebizmarts\MailChimp\Helper\Data::XML_MAGENTO_MAIL, $subscriber->getStoreId())) {
                $subscriber->setImportMode(true);
}
```
to 
`$subscriber->setImportMode(true);`
but I still receive two emails for confirmation.

**Comment by gonzaloebiz** [comment]
Can you please share your checkout screens?

Best

**Comment by ktsixit** [comment]
Some screenshots below:
https://ibb.co/4ZqgR7L
https://ibb.co/zmXDfkG
https://ibb.co/DrvWgzt

**Comment by gonzaloebiz** [comment]
Hi @ktsixit 

but this

![image](https://user-images.githubusercontent.com/6222792/58479873-80735980-812f-11e9-8934-87ff1c289005.png)

is not part of the magento default checkout

**Comment by ktsixit** [comment]
@gonzaloebiz 
You're right, this was added to checkout proccess, using an extension. I disabled that extension but I can see the the same issue is happening to the standard newsletter subscription form. I'm receicing two emails.

What's the part of code that triggers sending that email from mailchimp and what's the factor/variable that prevents mailchimp from sending these emails?
Please provide some guidelines in order to debug and fix this.

**Comment by gonzaloebiz** [comment]
If you set the need to confirm in magento, 

![image](https://user-images.githubusercontent.com/6222792/58490932-6abc5f00-8144-11e9-8e8f-301ba3bc5eec.png)

you must put NO in 

![image](https://user-images.githubusercontent.com/6222792/58491008-8de70e80-8144-11e9-802a-40a5a13b63c3.png)

And mailchimp manage the double opt-in

Best

**Comment by ktsixit** [comment]
But I don't want mailchimp to handle the confirmation. I want **magento** to handle confirmation and prevent mailchimp to send any email that has to do with subscription or unsubscription. 
That's the point of "Magento always manage emails" setting, right?

**Comment by gonzaloebiz** [comment]
Sorry but no, if you enable the double opt-in, mailchimp manage the situation

**Comment by ktsixit** [comment]
The way I see it, this is misleading. 

Whether double-opt in is enabled ir not, the extension should allow synching magento subscribers with mailchimp subscribers, but let magento handle the subscription/unsubscription proccess. 
OR if "Magento always manage emails" is NO, then all magento emails should be disabled and let mailchimp handle the subscription/unsubscription proccess.

Can I request that as a feature?

**Comment by gonzaloebiz** [comment]
Hi @ktsixit 

i don't think. I can't imagine why you want that Magento sends the double opt-in email. In the other hand, i can give you some reasons why MailChimp is the best option.
