### ISSUE TITLE
Magento 2.28 installation via composer, Unknown mdoule(s)

### ISSUE THREAD

**Issue by gnikolopoulos** [mailchimp/mc-magento2#726]
Hi,

I am trying to install this on a fresh installation, but I am facing issue when trying to enable the module.
I have the required entries in my composer.json file and I can confirm that files are being downloaded by composer during update/install. The required library is also there.
Running
```
php bin/magento setup:upgrade
```
Does not seem to do anything since the module is not even detected, so the following command

```
php bin/magento module Ebizmarts_MailChimp
```
naturally fails with an unknown module(s) error.

I am using Magento 2.2.8 and trying version 101.2.34 of this plugin.
All plugin files (including ` registration.php` seem to be present in their respective folders.

**Comment by gonzaloebiz** [comment]
Hi @gnikolopoulos 

if you have issues installing the extension, contact our support team at mailchimp@ebizmarts-desk.zendesk.com.

Best
