### ISSUE TITLE
Magento Mailchimp Module internal server error

### ISSUE THREAD

**Issue by msawyers** [mailchimp/mc-magento2#73]
Preconditions:

Magento CE 2.1.7
MailChimp for Magento 2 1.0.21
PHP 5.6

Steps to reproduce:

Install MailChimp for Magento 2 with composer require mailchimp/mc-magento2.
Create Mailchimp Store via Mailchimp module in Magento2

Expected result:

Mailchimp store to be created successfully

Actual result:
Mailchimp store to be created successfully
Internal server error thrown on Magento application

Carts don't sync
The List Settings section in the Connected Sites MailChimp page syncs seemingly forever.
MailChimp > Connected Sites > List Settings

![mailchimperror](https://user-images.githubusercontent.com/8907629/29639242-b48a21e6-881f-11e7-84ca-a8838b6ecdf7.PNG)

**Comment by gonzaloebiz** [comment]
Hi @msawyers 

you already enter your api key in the configuration of the extension?

**Comment by msawyers** [comment]
Hi, 
Yes I did, it also created the store in mailchimp. However the list is taking forever to synchronize also

**Comment by gonzaloebiz** [comment]
Hi @msawyers 

Why you use 1.0.21 and not 1.0.22?
Please try with the current version (1.0.22)

Best

**Comment by msawyers** [comment]
Hi, sorry I am using 1.0.22.

Please check issue on my server. Let me know if you need credentials.

**Comment by gonzaloebiz** [comment]
@msawyers we don't enter to the customer's server.
Double check your ApiKey
Take a look at the apache/nginx error log

Best

**Comment by msawyers** [comment]
HI,

Where is the location of the referenced log.
I reattempted an am getting the same error, no change when creating Store.
and listing continues to synchronize.

**Comment by msawyers** [comment]
The API key is correct, otherwise the store would not have been created in Mailchimp

**Comment by gonzaloebiz** [comment]
Typically the logs are in

/var/log/apache2 if you use a debian/ubuntu like and apache
/var/log/httpd if you use a centos like and apache
/var/log/nginx if you use nginx

But ask to your support/infrastructure team.

Best

**Comment by msawyers** [comment]
Issue still exist. 

screen also shows invalid api though api is correct
![api](https://user-images.githubusercontent.com/8907629/30083285-7ffb98d6-9253-11e7-9cf2-aa7047504cb2.PNG)

**Comment by gonzaloebiz** [comment]
You already look at the logs?

**Comment by gonzaloebiz** [comment]
After a week without news. close the issue

**Comment by msawyers** [comment]
Hi,
Missing JS causing API not to load on screen.
Why is it referencing a missing file?
![jsmissing](https://user-images.githubusercontent.com/8907629/30823159-e9621816-a1f0-11e7-8b62-8ccb1c0f00c7.PNG)

**Comment by msawyers** [comment]
Ignore last issue, i fixed this by clearing cache

**Comment by msawyers** [comment]
![apache2log](https://user-images.githubusercontent.com/8907629/30824142-2a0eccd0-a1f4-11e7-8afd-c69929acd214.PNG)

there is nothing in log to suggest an issue with server

**Comment by msawyers** [comment]
I check logs and nothing suggest an issue on server
![apache2log](https://user-images.githubusercontent.com/8907629/30824210-66f8a38c-a1f4-11e7-9f2c-43e6beb41332.PNG)

**Comment by msawyers** [comment]
i even used a fresh version of magento and still getting same issue
