### ISSUE TITLE
Can't enable the Mailchimp on Admin portal

### ISSUE THREAD

**Issue by kllee824** [mailchimp/mc-magento2#74]
Preconditions:

Magento EE 2.0.11
MailChimp for Magento 2 1.0.22
PHP 5.6.14

Steps to reproduce:
1.Download "MailChimp For Magento2" in ebizmarts
2. Install "MailChimp for Magento2" with composer require mailchimp/mc-magento2
3. extract the contents in app/code/Ebizmarts/MailChimp
4. run setup:upgrade
5. login Admin portal and see Mailchimp icon on menu.
6. get the API key from Mailchimp and paste to API
7. click 'Save Config' as select 'enable' option under Mailchimp General Configuration

Expected result:
Enabled the Mailchimp on magento and obtain the Mailchimp list name and related information

Actual result:
Waiting without any errors message 
![enable_waiting](https://user-images.githubusercontent.com/20422500/29800535-2e859120-8c9d-11e7-9d96-189b93b925a7.PNG)

**Comment by gonzaloebiz** [comment]
Hi @kllee824 

apache/nginx error log?

**Comment by kllee824** [comment]
apache/logs/error.log

[Tue Aug 29 14:25:19.412563 2017] [ssl:warn] [pid 16644:tid 632] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Aug 29 14:25:19.451581 2017] [core:warn] [pid 16644:tid 632] AH00098: pid file D:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Tue Aug 29 14:25:19.575168 2017] [ssl:warn] [pid 16644:tid 632] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Aug 29 14:25:20.154354 2017] [mpm_winnt:notice] [pid 16644:tid 632] AH00455: Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.14 configured -- resuming normal operations
[Tue Aug 29 14:25:20.154354 2017] [mpm_winnt:notice] [pid 16644:tid 632] AH00456: Apache Lounge VC11 Server built: Oct 13 2015 10:54:13
[Tue Aug 29 14:25:20.154354 2017] [core:notice] [pid 16644:tid 632] AH00094: Command line: 'd:\\xampp\\apache\\bin\\httpd.exe -d D:/xampp/apache'
[Tue Aug 29 14:25:20.155854 2017] [mpm_winnt:notice] [pid 16644:tid 632] AH00418: Parent: Created child process 17412
[Tue Aug 29 14:25:20.634921 2017] [ssl:warn] [pid 17412:tid 656] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Aug 29 14:25:20.790032 2017] [ssl:warn] [pid 17412:tid 656] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Aug 29 14:25:20.836915 2017] [mpm_winnt:notice] [pid 17412:tid 656] AH00354: Child: Starting 150 worker threads.

**Comment by kllee824** [comment]
apache/logs/access.log

127.0.0.1 - - [29/Aug/2017:14:25:28 +0800] "GET /hktshop/admin_1eunke HTTP/1.1" 503 908 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [29/Aug/2017:14:25:29 +0800] "GET /hktshop/pub/errors/hkt/css/styles.css HTTP/1.1" 404 - "http://127.0.0.1:8080/hktshop/admin_1eunke" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [29/Aug/2017:14:25:29 +0800] "GET /hktshop/pub/errors/hkt/images/favicon.ico HTTP/1.1" 404 - "http://127.0.0.1:8080/hktshop/admin_1eunke" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [29/Aug/2017:14:25:32 +0800] "GET /hktshop/admin_1eunke HTTP/1.1" 503 907 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [29/Aug/2017:14:25:34 +0800] "GET /hktshop/pub/errors/hkt/css/styles.css HTTP/1.1" 404 - "http://127.0.0.1:8080/hktshop/admin_1eunke" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [29/Aug/2017:14:25:36 +0800] "GET /hktshop/admin_1eunke HTTP/1.1" 302 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [29/Aug/2017:14:25:37 +0800] "GET /hktshop/admin_1eunke/admin/dashboard/index/key/7bdc5ac33699a609aca973d314737d56807b1862394f304d088cc4874b7b9680/ HTTP/1.1" 200 123087 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [29/Aug/2017:14:25:40 +0800] "GET /hktshop/pub/media/favicon/default/favicon_trans.png HTTP/1.1" 200 434 "http://127.0.0.1:8080/hktshop/admin_1eunke/admin/dashboard/index/key/7bdc5ac33699a609aca973d314737d56807b1862394f304d088cc4874b7b9680/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [29/Aug/2017:14:25:45 +0800] "GET /hktshop/admin_1eunke/admin/system_config/edit/section/mailchimp/key/9286323460d57a03b9fdc1536bdb949934d2b8ef7c5eeee00042bb2c2a4063e7/ HTTP/1.1" 200 188002 "http://127.0.0.1:8080/hktshop/admin_1eunke/admin/dashboard/index/key/7bdc5ac33699a609aca973d314737d56807b1862394f304d088cc4874b7b9680/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
127.0.0.1 - - [29/Aug/2017:14:25:48 +0800] "GET /hktshop/pub/static/adminhtml/Magento/backend/en_US/configmonkeyapikey.js HTTP/1.1" 404 - "http://127.0.0.1:8080/hktshop/admin_1eunke/admin/system_config/edit/section/mailchimp/key/9286323460d57a03b9fdc1536bdb949934d2b8ef7c5eeee00042bb2c2a4063e7/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"

**Comment by gonzaloebiz** [comment]
Hi @kllee824 

think your error log not corresponding with the date of your issue. Please try again and post the correct error log,

Best

**Comment by kllee824** [comment]
Error when click Mailchimp Store:

![store_error](https://user-images.githubusercontent.com/20422500/29851716-48af52a4-8d68-11e7-9880-c91ad79adc09.PNG)


[2087982107.txt](https://github.com/mailchimp/mc-magento2/files/1262218/2087982107.txt)

**Comment by kllee824** [comment]
different time zone between apache and Magento +8, but it is take same time

Thanks

[apache_logs.zip](https://github.com/mailchimp/mc-magento2/files/1262234/apache_logs.zip)
[magento_log.zip](https://github.com/mailchimp/mc-magento2/files/1262233/magento_log.zip)

**Comment by gonzaloebiz** [comment]
Hi @kllee824 

think you miss some files when install the extension.
What steps you follow to install it?

**Comment by kllee824** [comment]
I follow the manual installation guide,
1. install composer
2. composer require mailchimp/mc-magento2
3. Download 'Mailchimp for Magento2'
4. extract the contents in app/code/Ebizmarts/MailChimp
5. run setup:upgrade
6. run cache:flush
7. run indexer:reindex

Result
1. vendor/ebizmarts/mailchimp-lib/* is created
2. Admin Portal ->Maichimp is created

**Comment by gonzaloebiz** [comment]
Why you download M4M2? you don't need to do this, composer do it for you.
You have 2 installations of the same extension, one by composer in vendor/mailchimp/mc-magento2 and one by you in app/code/Ebizmarts/MailChimp/
Try removing app/code/Ebizmarts/MailChimp/ and re run the magento upgrade (don't miss to run setup:static-content:deploy).
And please, read how to install extensions in the magento manuals before.

So i close the issue, that's not an issue

Thanks

**Comment by kllee824** [comment]
Hi,

Firstly, I try installed on app/code/Ebizmarts/MailChimp/, and run setup:upgrade

Then following error shown
[ReflectionException]
Class Mailchimp doest not exist

I follow Ebizmarts [semi-manual](https://store.ebizmarts.com/mailchimp4magento2.html) installation guide

Create the directory at app/code/Ebizmarts/MailChimp
Inside the downloaded package, you will find a directory named mc-magento2-x.x.xx, you must extract the contents of that directory in app/code/Ebizmarts/MailChimp
You must now install the Mailchimp library, this must be done via composer, for this from a text terminal go to the Magento root directory and run the following command: composer require ebizmarts/mailchimp-lib
Upgrade Magento with the setup command: bin/magento setup:upgrade

I try your suggestion today. 
Thanks 
Lun

**Comment by kllee824** [comment]
Sorry my typo mistake 
I follow the manual installation guide,

install composer
composer require mailchimp/mailchimp-lib <---------------------- 
Download 'Mailchimp for Magento2'
extract the contents in app/code/Ebizmarts/MailChimp
run setup:upgrade
run cache:flush
run indexer:reindex

Result
vendor\ebizmarts\mailchimp-lib
app/code/Ebizmarts/MailChimp

**Comment by gonzaloebiz** [comment]
Hi @kllee824 

At this point looks like a mess, i don't know what steps you followed
Please restore a backup from before all this and simply run
composer require mailchimp/mc-magento2

Remember, in magento2 the best option is always composer

**Comment by kllee824** [comment]
Hi,

OK, I will rollback to use composer to install tomorrow. Let you know the result.

Thanks
Lun

**Comment by kllee824** [comment]
Hi gonzaloebiz

I have installed mailchimp by composer on clean version EE 2.0.11 without data downloaded from Magento. Such that can eliminate any 3nd party code affect the Mailchimp configuration. 

But still can't enabled on Admin portal. Please help.

Thanks
Lun

**Comment by kllee824** [comment]
![c2](https://user-images.githubusercontent.com/20422500/30018135-539841e2-918e-11e7-9714-75b9d2e77902.PNG)

**Comment by kllee824** [comment]
Hi ,

Any update for EE 2.0.11? 

Thanks
Lun

**Comment by gonzaloebiz** [comment]
Hi @kllee824 

you already run 
bin/magento setup:upgrade
bin/magento setup:static-content:deploy
bin/magento cache:clean

any apache or magento log?

Best

**Comment by kllee824** [comment]
Hi @gonzaloebiz 

I can't find any related mailchimp log message in the log on 2.0.11. Please refer the logs.
BTW, I have try to install on Luma magento 2.1.18, and the installation is fine which can save the API key. 

[apache_logs.zip](https://github.com/mailchimp/mc-magento2/files/1302021/apache_logs.zip)

[var_report.zip](https://github.com/mailchimp/mc-magento2/files/1302020/var_report.zip)
[Magento2011_log.zip](https://github.com/mailchimp/mc-magento2/files/1302018/Magento2011_log.zip)

**Comment by arvin-narvaez** [comment]
same issue i can't save the API key any fix?
