### ISSUE TITLE
Mailchim Magento 2.3.1 Possible Bug - Data Not Syncing

### ISSUE THREAD

**Issue by s00071609** [mailchimp/mc-magento2#753]
**### Steps to reproduce**

- Install mailchimp using composer to magento 2.3.1
- Connect the store as per the mailchimp userguide

**Expected Result**
Data syncs to Mailchimp 

**Actual**

Magento cron errors
Webhook cron works but the cron related to ecommerce does shows error

warning: Invalid argument supplied for foreach() in /mailchimp/mc-magento2/Helper/Data.php on line 1028
![image](https://user-images.githubusercontent.com/19631643/59226522-816bb700-8c16-11e9-94fd-303f69dc55f3.png)

Mailchimp show status as syncing and orders show status syncing but nothing gets synced due to cron error. Please note that store other crons are running fine.

**Comment by gonzaloebiz** [comment]
What version of mc-magento2 do you have?
Are you using the sample data?
What version of php do you have?
Can you please copy screenshots of your configuration? (please hide your ApiKey and other sensible data)

Best

**Comment by s00071609** [comment]
PHP 7.1
No Sample Data

See the version details from composer file:

 "description": "Connect MailChimp with Magento",
  "type": "magento2-module",
  "version": "102.3.34",
  "authors": [
    {
      "name": "Ebizmarts Corp",
      "email": "mailchimp@ebizmarts-desk.zendesk.com",
      "homepage": "http://ebizmarts.com"
    }
  ],
  "license": [
    "OSL-3.0",
    "AFL-3.0"
  ],
  "support": {
    "email": "mailchimp@ebizmarts-desk.zendesk.com",
    "wiki": "https://connect.mailchimp.com/integrations/magento",
    "forum": "http://ebizmarts.com/forums/view/6"
  },
  "require" : {
    "magento/framework": "102.0.*",
    "ebizmarts/mailchimp-lib": ">=3.0.27"

Configuration:

![image](https://user-images.githubusercontent.com/19631643/59232667-b3861480-8c28-11e9-99be-3bcfd9ff4dfc.png)

**Comment by gonzaloebiz** [comment]
do you have groups for this audience?
Can you please copy a screenshot of the groups?

**Comment by s00071609** [comment]
I am not sure about groups? Where do i look for it. Its a new mailchimp account and i dont think i have any group.

Let me know where i can look for it

**Comment by gonzaloebiz** [comment]
In mailchimp, go to your audience and select manage contacts/groups

![image](https://user-images.githubusercontent.com/6222792/59278911-5777bc00-8c39-11e9-8d95-71481e3dd2fd.png)

**Comment by s00071609** [comment]
ok groups seems to be categorizing audience. I dont have any group. Actuall i tried in test version and live site, it did not work in either case. Same problem. because the cron is failing, its not syncing

![image](https://user-images.githubusercontent.com/19631643/59279023-8b3cfb00-8ca6-11e9-8d8b-8fd0a3785d60.png)

**Comment by gonzaloebiz** [comment]
@s00071609 

i try as per your description and i can't replicate the issue

![image](https://user-images.githubusercontent.com/6222792/59284388-8c3c4100-8c42-11e9-9038-63f51b3c46fb.png)

![image](https://user-images.githubusercontent.com/6222792/59284420-9b22f380-8c42-11e9-8fda-fe8fcd0f4b22.png)

![image](https://user-images.githubusercontent.com/6222792/59284564-d6bdbd80-8c42-11e9-8faa-8cecc69fdab3.png)

![image](https://user-images.githubusercontent.com/6222792/59284721-21d7d080-8c43-11e9-8fcd-6c7cc893805a.png)

If you give us some other specifications to try, we will be pleased to try

**Comment by s00071609** [comment]
do you think it might be due to PHP setting. Does it require stuffs like proc_open, etc. These are disabled by host

**Comment by gonzaloebiz** [comment]
Really i don't know.
Try to put a line before this line https://github.com/mailchimp/mc-magento2/blob/develop-2.3/Helper/Data.php#L1035 that looks like

`$this->log($allInterest);`

and then take a look at the var/log/Mailchimp.log file once the cron job runs

Best

**Comment by s00071609** [comment]
I added the above but the mailchimp log shows nothing

![image](https://user-images.githubusercontent.com/19631643/59333463-b887b880-8d3b-11e9-8451-4aa5654701ae.png)

**Comment by gonzaloebiz** [comment]
The getInterest should look like

![image](https://user-images.githubusercontent.com/6222792/59348133-bf3b0f00-8cec-11e9-8157-5006f73aef37.png)

**Comment by s00071609** [comment]
i copied the whole code from github for Data file. Now its giving this error - Warning: curl_setopt(): Curl option contains invalid characters (\0) in /home/......../public_html/vendor/ebizmarts/mailchimp-lib/src/Mailchimp.php on line 180

How come installation from composer has different code than this??

**Comment by s00071609** [comment]
And i havent got any log so far

**Comment by gonzaloebiz** [comment]
Hi @s00071609 

are you using some opcode cache like APC or xcache or accelerator?

Best

**Comment by s00071609** [comment]
I am using cloudflare and litespeed cache

**Comment by s00071609** [comment]
if you want you can check https://jostechecig.com.au/ as i am unsure about the above cache being used.

**Comment by s00071609** [comment]
I am getting this error in log now. I updated to latest version -

[2019-06-15 10:14:12] MailChimpLogger.INFO: User Disabled for Api Call: [https://us12.api.mailchimp.com/3.0/lists/506bfaac8c/merge-fields?count=100] using method [GET]
	Detail: [This account has been deactivated.]
	Params:
		{"count":100}

**Comment by s00071609** [comment]
This is also from log:

2019-06-15 10:05:19] MailChimpLogger.INFO: Resource Not Found for Api Call: [https://us3.api.mailchimp.com/3.0/lists//interest-categories] using method [GET]
	Detail: [The requested resource could not be found.]

 [] []
[2019-06-15 10:05:19] MailChimpLogger.INFO: Resource Not Found for Api Call: [https://us3.api.mailchimp.com/3.0/lists//merge-fields?count=100] using method [GET]
	Detail: [The requested resource could not be found.]
	Params:
		{"count":100}

**Comment by gonzaloebiz** [comment]
Can i ask what hosting service do you use? Godaddy perhaps?

**Comment by gonzaloebiz** [comment]
Close the issue until news

**Comment by potticus** [comment]
I solved this very issue by removing these lines from /vendor/mailchimp/mc-magento2/Helper/Data.php on line 1029

`            foreach ($allInterest['categories'] as $item) {
                if (in_array($item['id'], $interest)) {
                    $rc[$item['id']]['interest'] = ['id' => $item['id'], 'title' => $item['title'], 'type' => $item['type']];
                }
            }
            foreach ($interest as $interestId) {
                $mailchimpInterest = $api->lists->interestCategory->interests->getAll($listId, $interestId);
                foreach ($mailchimpInterest['interests'] as $mi) {
                    $rc[$mi['category_id']]['category'][$mi['display_order']] = ['id' => $mi['id'], 'name' => $mi['name'], 'checked' => false];
                }
            }
`

This allowed the cron task to run without error so the abandon baskets could sync. This will most likely remove the ability to see interested categories of the customer, but we are just glad to have the abandon carts working.

**Comment by PivitParkour94** [comment]
We're getting the same issue when trying to sync data. Found an error log at that says
```
MailChimpLogger.INFO: Resource Not Found for Api Call: [https<mailchimp>/3.0/lists//interest-categories] using method [GET] Detail: [The requested resource could not be found.] [] []
```

Note the double slash between the `lists/` and `/interest-categories` which seems like maybe some data is missing in the data that is used to build up that API call...

In our case we are using the Magento 2 sample data, with a custom product type. Seems that all the orders sync except for orders with the custom product type in them. That could definitely be related.

Although, there are 0 carts recorded in the system config section, which seems like something is breaking the cart sync entirely.

**Comment by KiranLankapalli** [comment]
Any solution for this mailchimp data sync stuck at some products count and showing the message "This account is currently syncing" since a month. Please help.
