### ISSUE TITLE
Abandoned cart email still send after successful purchase

### ISSUE THREAD

**Issue by mathijsm** [mailchimp/mc-magento2#754]
## Abandoned cart still send after successful purchase

When a new client place a successful order they still receive an abandoned cart mail. 

### Preconditions

    1. Magento CE 2.2.8
    2. mailchimp-lib 3.0.30.
    3. mc-magento2 101.2.34
   

### Steps to reproduce

1. Make a purchase with a new client
2. Let the Mailchimp module sync. 
3. Receive a abandoned cart email
<img width="670" alt="mailchimp error" src="https://user-images.githubusercontent.com/3367373/59255684-bab22000-8c32-11e9-934f-8b1f66ff1770.png">

### Actual and Expected result

 When client makes a purchase he should not receive a abandoned cart email

**Comment by gonzaloebiz** [comment]
Take a look at https://github.com/mailchimp/mc-magento2/issues/706
The issue will be available in the next release (i think this week)

Best
