### ISSUE TITLE
Unhandled `Magento\Framework\Serialize\Serializer\Json::(un)serialize` calls

### ISSUE THREAD

**Issue by tzyganu** [mailchimp/mc-magento2#758]
## All calls to `Magento\Framework\Serialize\Serializer\Json::unserialize` and `serialize` are not wrapped in a `try-catch` block

Module version: 1.0.32.
The magento `Magento\Framework\Serialize\Serializer\Json::unserialize` and `serialize` methods throw an `\InvalidArgumentException` exception if for some reason `json_encode` or `json_decode` fail.  
The mailchimp module does not handle these errors, resulting in 2 problems:
 - the log gets filled with "unable to (un)serialize value" rows
 - Some actions that call one of the extention methods will fail. (this is the worst part).

This issue has been reported before, but only partially.  
I'm adding below the list of all the unsafe calls to `serialize / unserialize`.  

Serialize:

 - https://github.com/mailchimp/mc-magento2/blob/1.0.32/Controller/Checkout/Success.php#L86
 - https://github.com/mailchimp/mc-magento2/blob/1.0.32/Controller/Checkout/Success.php#L97
 - https://github.com/mailchimp/mc-magento2/blob/1.0.32/Controller/WebHook/Index.php#L87
 - https://github.com/mailchimp/mc-magento2/blob/1.0.32/Helper/Data.php#L357
 - https://github.com/mailchimp/mc-magento2/blob/1.0.32/Helper/VarsMap.php#L106
 - https://github.com/mailchimp/mc-magento2/blob/1.0.32/Model/Plugin/Newsletter/Save.php#L85
 - https://github.com/mailchimp/mc-magento2/blob/1.0.32/Model/Plugin/Newsletter/Save.php#L96
 - https://github.com/mailchimp/mc-magento2/blob/1.0.32/Observer/Adminhtml/Customer/SaveAfter.php#L77
 - https://github.com/mailchimp/mc-magento2/blob/1.0.32/Observer/Adminhtml/Customer/SaveAfter.php#L87
 - https://github.com/mailchimp/mc-magento2/blob/1.0.32/Setup/UpgradeData.php#L112
 - https://github.com/mailchimp/mc-magento2/blob/1.0.32/Setup/UpgradeData.php#L137
 - https://github.com/mailchimp/mc-magento2/blob/1.0.32/Setup/UpgradeData.php#L164

Unserialize:

 - https://github.com/mailchimp/mc-magento2/blob/1.0.32/Cron/Webhook.php#L90
 - https://github.com/mailchimp/mc-magento2/blob/1.0.32/Helper/Data.php#L357
 - https://github.com/mailchimp/mc-magento2/blob/1.0.32/Helper/Data.php#L1028
 - https://github.com/mailchimp/mc-magento2/blob/1.0.32/Helper/VarsMap.php#L114

**Comment by gonzaloebiz** [comment]
Hi @tzyganu 

thanks for your feedback.
On this case https://github.com/mailchimp/mc-magento2/blob/develop-2.2/Controller/Checkout/Success.php#L82 you can view that is inside a try https://github.com/mailchimp/mc-magento2/blob/develop-2.2/Controller/Checkout/Success.php#L75-L99
Same case for https://github.com/mailchimp/mc-magento2/blob/develop-2.2/Controller/Checkout/Success.php#L93
Same case for https://github.com/mailchimp/mc-magento2/blob/develop-2.2/Helper/Data.php#L371-L383
And the same case for all UpgradeData

We are working on the others.
