### ISSUE TITLE
Merge field on old customers

### ISSUE THREAD

**Issue by vDeggial** [mailchimp/mc-magento2#766]
Magento CE 2.2.8
Mailchimp v101.2.36 

I have recently setup a new merge field in Mailchimp for the audience list linked in the plugin and mapped Group field from Magento to it in the plugin config. After that I did customer resync, but the field is not being mapped. 

Do I need to change customers' group for it to map sync? Like switch all users from General group to other one, wait for sync, then switch back to General?

Thanks

**Comment by vDeggial** [comment]
Even on new customers, it looks like it is syncing the Customer Group field only if they also subscribe to newsletter or something ...

**Comment by gonzaloebiz** [comment]
Hi @shinoamakusa 

can you share your magento and mailchimp configuration for these fields? A screenshot of the magento mapfields and the definition of the merge field in mailchimp

Best

**Comment by vDeggial** [comment]
Magento:
![image](https://user-images.githubusercontent.com/9992759/59785066-c330d900-9278-11e9-9bd1-31dd5d0554df.png)

Mailchimp:
![image](https://user-images.githubusercontent.com/9992759/59785108-d6dc3f80-9278-11e9-9c67-3835a6be2e81.png)

**Comment by gonzaloebiz** [comment]
The customer group is an integer, try with a number

**Comment by vDeggial** [comment]
But on few customers it seemed to have worked:
![image](https://user-images.githubusercontent.com/9992759/59785376-78fc2780-9279-11e9-9ddb-251e290c906f.png)

**Comment by gonzaloebiz** [comment]
Ok we will check the case and update the issue

**Comment by vDeggial** [comment]
> 
> 
> Ok we will check the case and update the issue

Thank you in advance :)

**Comment by gonzaloebiz** [comment]
OK, the point is... in mailchimp only subscribers have merge fields, and in magento only customer have customer group... so only those subscribers who are customers too will have a group in mailchimp. So the button to resync customers should be to resync subscribers
Try modifying the `mailchimp_sync_modified` = 1  for all the registers with type = 'SUB' in the mailchimp_sync_ecommerce table

Best

**Comment by vDeggial** [comment]
If that is the case, how do the customers get synced to Mailchimp. From what I can tell merge fields like FNAME & LNAME get synced for customers who dont subscribe for newsletter.

I will try and do the sql change you advised, but we would like to be able to sync the Customer Group to Mailchimp so later on we can target certain group(s) with segments when we implement membership feature in our store and those groups will reflect Membership tiers

**Comment by vDeggial** [comment]
Just for a bit of clarification here is what our client would like to happen:

In preparation for introducing Membership feature in the store (which will be in few weeks) we would like to be able to reflect the Groups of Magento store customers (regardless of newsletter subscription) in the Mailchimp list so that later on once membership feature is rolled out and customer groups in the store reflect those member tiers we would like to be able to segment the list based on those customer groups so only certain membership groups could be targeted by Mailchimp emails and campaigns

Also, I cannot fidn anywhere anything about merge fields only applying to subscribers and not all the contacts in Mailchimp lists ... if you could maybe reference that somewhere ... thanks :)

**Comment by gonzaloebiz** [comment]
Take a look at https://developer.mailchimp.com/documentation/mailchimp/reference/ecommerce/stores/customers/

**Comment by vDeggial** [comment]
Ok, I see that now. Next question is why only 2 of customers who subscribed to newsletter have been synced with the Group merge tag when there is way more 
![image](https://user-images.githubusercontent.com/9992759/59798004-f6ce2c00-9295-11e9-9584-0fbaa2643664.png)

**Comment by gonzaloebiz** [comment]
Because we need to fix the button to re sync subscribers, no customers

**Comment by vDeggial** [comment]
Oh ... makes sense :) Any ETA on the patch? ( I would imagine not a release just for one fix)

**Comment by gonzaloebiz** [comment]
next week surely we will have a fix

**Comment by vDeggial** [comment]
sounds like a plan :)

**Comment by gonzaloebiz** [comment]
@shinoamakusa 

the fix for magento 2.2 is here https://github.com/mailchimp/mc-magento2/pull/770

Best

**Comment by vDeggial** [comment]
thanks :) applying now

**Comment by vDeggial** [comment]
sync doesnt work ... must be related to #767
