### ISSUE TITLE
How to update the Magento 2 extension MageMonkey v3.0.8 to MailChimp 4 v1.0.22 ?

### ISSUE THREAD

**Issue by zhiyicai** [mailchimp/mc-magento2#77]
Hey, 

How to update the Magento 2 extension MageMonkey v3.0.8 to MailChimp 4 v1.0.22 ???

I have installed MageMonkey v3.0.8 with composer

Thank

**Comment by gonzaloebiz** [comment]
Hi @zhiyicai 

see at http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-uninstall-mods.html

Best
