### ISSUE TITLE
Mailchimp not working in Magento 2.3.2

### ISSUE THREAD

**Issue by sreenathnr** [mailchimp/mc-magento2#777]
# Mailchimp creates an error in compilation on Magento 2.3.2

## Compilation Problems
* Compilation breaks in Magento 2.3.2 and got the error Class Ebizmarts\MailChimp\Helper\Data does not exist  

### Preconditions

   1. Magento CE 2.3.2 without sample data is installed.
   2. Call MailChimp helper in the constructor 

`public function __construct( 
        \Magento\Backend\Block\Template\Context $context, 
        \Ebizmarts\MailChimp\Helper\Data $helper, 
        array $data = []
    )
    {    
        parent::__construct($context, $data);
        $this->_helper          = $helper;
    }`

### Result
- The compilation broke and seems the error message

```
Compilation was started.
Area configuration aggregation... 5/7 [====================>-------]  71% 41 secs 298.0 MiB
In ClassReader.php line 35:
                                                        
  Class Ebizmarts\MailChimp\Helper\Data does not exist  
                                                        

In ClassReader.php line 29:
                                                        
  Class Ebizmarts\MailChimp\Helper\Data does not exist 
```

**Comment by gonzaloebiz** [comment]
Please, specify what version of the extension are you trying

**Comment by sreenathnr** [comment]
@gonzaloebiz I tried using the Mailchimp versions **102.3.34**  and **102.3.36** *. Both have the same errors in the compilation.

**Comment by gonzaloebiz** [comment]
run

composer show | grep mailchimp and let me know the result

Best

**Comment by sreenathnr** [comment]
It shows the result
```
ebizmarts/mailchimp-lib                                           3.0.30                  API client library for the MailChimp
mailchimp/mc-magento2                                             dev-develop-2.3 dd61d0b Connect MailChimp with Magento
```

**Comment by sreenathnr** [comment]
@gonzaloebiz 
composer show | grep mailchimp shows the result
```
ebizmarts/mailchimp-lib                                           3.0.30                  API client library for the MailChimp
mailchimp/mc-magento2                                             dev-develop-2.3 dd61d0b Connect MailChimp with Magento
```

**Comment by gonzaloebiz** [comment]
Please don't use a develop version

**Comment by gonzaloebiz** [comment]
As you can see

![image](https://user-images.githubusercontent.com/6222792/60730248-11053c80-9f1b-11e9-8a0f-f24ecd24f970.png)

compiles without problems

**Comment by sreenathnr** [comment]
Thanks, @gonzaloebiz. I replaced develop version with Master that resolves my issue.

**Comment by gonzaloebiz** [comment]
You are welcome

**Comment by vkapsitsolutions** [comment]
> Thanks, @gonzaloebiz. I replaced develop version with Master that resolves my issue.

I am new in Magento and I have set up MailChimp for my website and having the latest version but that is not working for me so Can you please help me to know how you solve this issue using commands.

Looking for your reply

**Comment by gonzaloebiz** [comment]
Hi @futuretech123 

contact our support team

Best
