### ISSUE TITLE
I cannot install the extension on fresh Magento

### ISSUE THREAD

**Issue by scolandrea** [mailchimp/mc-magento2#79]
I added the Mailchimp extension (via composer) after I performed Magento installation. Extension works fine without any problem. After that I tried the same thing but in this time the Magento wasn't installed yet. The issue appear when Magento try to enable Mailchimp extension. The message says: "[ERROR] Magento\Framework\Exception\LocalizedException: Invalid entity_type specified: customer"

I'm running Magento 2.1.8 EE without any other third party extension.

Do you have any advice?

Regards!

**Comment by gonzaloebiz** [comment]
Hi @scolandrea 

take a look at https://github.com/mailchimp/mc-magento2/commit/16124cc40ecafea7658816519a62807ec810ce7c

This will be include in the next release.

Best
