### ISSUE TITLE
Fatal Error: 'Uncaught Error: Call to undefined method Magento\\Customer\\Model\\Data\\Address::getStreetLine()

### ISSUE THREAD

**Issue by rikardwissing** [mailchimp/mc-magento2#81]
I'm using version 1.0.23.

I get this when subscribing customer to Newsletter.

The issue is in _updateMergeVars() in Helper/Data.

**Comment by gonzaloebiz** [comment]
Hi @rikardwissing 

please, follow our [issue report guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)
I close the issue for now and re open it when you update the issue

Best
