### ISSUE TITLE
Can't access configuration page in Magento 2.2.7 throws an exception

### ISSUE THREAD

**Issue by panthar1** [mailchimp/mc-magento2#825]
I was looking through the other issues on here, and I see one that mentions a blank page, however, what we are seeing is a exception when I go to the mailchimp admin configuration. The module.xml shows module name="Ebizmarts_MailChimp" setup_version="101.2.34" for the version of the extension we are trying to setup, it was installed via composer. We are running magento 2.2.7. Any idea/help on how we could fix this? Thank you.

1 exception(s):
Exception #0 (Exception): Notice: Array to string conversion in /home/newagcom/public_html/vendor/magento/framework/View/Element/Html/Select.php on line 243

Exception #0 (Exception): Notice: Array to string conversion in /home/newagcom/public_html/vendor/magento/framework/View/Element/Html/Select.php on line 243
#0 /home/newagcom/public_html/vendor/magento/framework/View/Element/Html/Select.php(243): Magento\Framework\App\ErrorHandler->handler(8, 'Array to string...', '/home/newagcom/...', 243, Array)
#1 /home/newagcom/public_html/vendor/mailchimp/mc-magento2/Block/Adminhtml/System/Config/Form/Field/CustomerMap.php(68): Magento\Framework\View\Element\Html\Select->calcOptionHash(Array)
#2 /home/newagcom/public_html/vendor/magento/module-config/Block/System/Config/Form/Field/FieldArray/AbstractFieldArray.php(159): Ebizmarts\MailChimp\Block\Adminhtml\System\Config\Form\Field\CustomerMap->_prepareArrayRow(Object(Magento\Framework\DataObject))
#3 /home/newagcom/public_html/generated/code/Ebizmarts/MailChimp/Block/Adminhtml/System/Config/Form/Field/CustomerMap/Interceptor.php(37): Magento\Config\Block\System\Config\Form\Field\FieldArray\AbstractFieldArray->getArrayRows()
#4 /home/newagcom/public_html/vendor/magento/module-config/view/adminhtml/templates/system/config/form/field/array.phtml(117): Ebizmarts\MailChimp\Block\Adminhtml\System\Config\Form\Field\CustomerMap\Interceptor->getArrayRows()
#5 /home/newagcom/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/newagcom/...')
#6 /home/newagcom/public_html/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Ebizmarts\MailChimp\Block\Adminhtml\System\Config\Form\Field\CustomerMap\Interceptor), '/home/newagcom/...', Array)
#7 /home/newagcom/public_html/generated/code/Ebizmarts/MailChimp/Block/Adminhtml/System/Config/Form/Field/CustomerMap/Interceptor.php(245): Magento\Framework\View\Element\Template->fetchView('/home/newagcom/...')
#8 /home/newagcom/public_html/vendor/magento/framework/View/Element/Template.php(300): Ebizmarts\MailChimp\Block\Adminhtml\System\Config\Form\Field\CustomerMap\Interceptor->fetchView('/home/newagcom/...')
#9 /home/newagcom/public_html/vendor/magento/module-backend/Block/Template.php(126): Magento\Framework\View\Element\Template->_toHtml()
#10 /home/newagcom/public_html/vendor/magento/module-config/Block/System/Config/Form/Field/FieldArray/AbstractFieldArray.php(262): Magento\Backend\Block\Template->_toHtml()
#11 /home/newagcom/public_html/vendor/magento/module-config/Block/System/Config/Form/Field/FieldArray/AbstractFieldArray.php(116): Magento\Config\Block\System\Config\Form\Field\FieldArray\AbstractFieldArray->_toHtml()
#12 /home/newagcom/public_html/vendor/magento/module-config/Block/System/Config/Form/Field.php(73): Magento\Config\Block\System\Config\Form\Field\FieldArray\AbstractFieldArray->_getElementHtml(Object(Magento\Framework\Data\Form\Element\Text))
#13 /home/newagcom/public_html/vendor/magento/module-config/Block/System/Config/Form/Field.php(52): Magento\Config\Block\System\Config\Form\Field->_renderValue(Object(Magento\Framework\Data\Form\Element\Text))
#14 /home/newagcom/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Config\Block\System\Config\Form\Field->render(Object(Magento\Framework\Data\Form\Element\Text))
#15 /home/newagcom/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Ebizmarts\MailChimp\Block\Adminhtml\System\Config\Form\Field\CustomerMap\Interceptor->___callParent('render', Array)
#16 /home/newagcom/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Ebizmarts\MailChimp\Block\Adminhtml\System\Config\Form\Field\CustomerMap\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\Data\Form\Element\Text))
#17 /home/newagcom/public_html/generated/code/Ebizmarts/MailChimp/Block/Adminhtml/System/Config/Form/Field/CustomerMap/Interceptor.php(104): Ebizmarts\MailChimp\Block\Adminhtml\System\Config\Form\Field\CustomerMap\Interceptor->___callPlugins('render', Array, Array)
#18 /home/newagcom/public_html/vendor/magento/framework/Data/Form/Element/AbstractElement.php(459): Ebizmarts\MailChimp\Block\Adminhtml\System\Config\Form\Field\CustomerMap\Interceptor->render(Object(Magento\Framework\Data\Form\Element\Text))
#19 /home/newagcom/public_html/vendor/magento/framework/Data/Form/Element/Text.php(41): Magento\Framework\Data\Form\Element\AbstractElement->getHtml()
#20 /home/newagcom/public_html/vendor/magento/framework/Data/Form/Element/AbstractElement.php(473): Magento\Framework\Data\Form\Element\Text->getHtml()
#21 /home/newagcom/public_html/vendor/magento/module-config/Block/System/Config/Form/Fieldset.php(86): Magento\Framework\Data\Form\Element\AbstractElement->toHtml()
#22 /home/newagcom/public_html/vendor/magento/module-config/Block/System/Config/Form/Fieldset.php(66): Magento\Config\Block\System\Config\Form\Fieldset->_getChildrenElementsHtml(Object(Magento\Framework\Data\Form\Element\Fieldset))
#23 /home/newagcom/public_html/vendor/magento/framework/Data/Form/Element/AbstractElement.php(459): Magento\Config\Block\System\Config\Form\Fieldset->render(Object(Magento\Framework\Data\Form\Element\Fieldset))
#24 /home/newagcom/public_html/vendor/magento/framework/Data/Form/Element/AbstractElement.php(473): Magento\Framework\Data\Form\Element\AbstractElement->getHtml()
#25 /home/newagcom/public_html/vendor/magento/framework/Data/Form.php(325): Magento\Framework\Data\Form\Element\AbstractElement->toHtml()
#26 /home/newagcom/public_html/vendor/magento/framework/Data/Form.php(340): Magento\Framework\Data\Form->toHtml()
#27 /home/newagcom/public_html/vendor/magento/module-backend/Block/Widget/Form.php(101): Magento\Framework\Data\Form->getHtml()
#28 /home/newagcom/public_html/vendor/magento/module-backend/view/adminhtml/templates/widget/form.phtml(15): Magento\Backend\Block\Widget\Form->getFormHtml()
#29 /home/newagcom/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/newagcom/...')
#30 /home/newagcom/public_html/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Config\Block\System\Config\Form), '/home/newagcom/...', Array)
#31 /home/newagcom/public_html/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/home/newagcom/...')
#32 /home/newagcom/public_html/vendor/magento/module-backend/Block/Template.php(126): Magento\Framework\View\Element\Template->_toHtml()
#33 /home/newagcom/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Backend\Block\Template->_toHtml()
#34 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Element\AbstractBlock->toHtml()
#35 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(533): Magento\Framework\View\Layout->_renderBlock('system\\config\\f...')
#36 /home/newagcom/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system\\config\\f...')
#37 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system\\config\\f...')
#38 /home/newagcom/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system\\config\\f...', true)
#39 /home/newagcom/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout\Interceptor->renderElement('system\\config\\f...', true)
#40 /home/newagcom/public_html/vendor/magento/module-config/view/adminhtml/templates/system/config/edit.phtml(22): Magento\Framework\View\Element\AbstractBlock->getChildHtml('form')
#41 /home/newagcom/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/newagcom/...')
#42 /home/newagcom/public_html/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Config\Block\System\Config\Edit), '/home/newagcom/...', Array)
#43 /home/newagcom/public_html/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/home/newagcom/...')
#44 /home/newagcom/public_html/vendor/magento/module-backend/Block/Template.php(126): Magento\Framework\View\Element\Template->_toHtml()
#45 /home/newagcom/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Backend\Block\Template->_toHtml()
#46 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Element\AbstractBlock->toHtml()
#47 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(533): Magento\Framework\View\Layout->_renderBlock('system.config.e...')
#48 /home/newagcom/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system.config.e...')
#49 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system.config.e...')
#50 /home/newagcom/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system.config.e...', false)
#51 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('system.config.e...', false)
#52 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('content', false)
#53 /home/newagcom/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#54 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#55 /home/newagcom/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', false)
#56 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('content', false)
#57 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...', false)
#58 /home/newagcom/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#59 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#60 /home/newagcom/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', false)
#61 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...', false)
#62 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('main.col', false)
#63 /home/newagcom/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#64 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#65 /home/newagcom/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', false)
#66 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main.col', false)
#67 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.main.conta...', false)
#68 /home/newagcom/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#69 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#70 /home/newagcom/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', false)
#71 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...', false)
#72 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.content', false)
#73 /home/newagcom/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#74 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#75 /home/newagcom/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', false)
#76 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.content', false)
#77 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#78 /home/newagcom/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#79 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#80 /home/newagcom/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#81 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper', false)
#82 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('backend.page', false)
#83 /home/newagcom/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#84 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#85 /home/newagcom/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', false)
#86 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page', false)
#87 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('root', false)
#88 /home/newagcom/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#89 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#90 /home/newagcom/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#91 /home/newagcom/public_html/vendor/magento/framework/View/Layout.php(954): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#92 /home/newagcom/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#93 /home/newagcom/public_html/vendor/magento/framework/View/Result/Page.php(257): Magento\Framework\View\Layout\Interceptor->getOutput()
#94 /home/newagcom/public_html/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#95 /home/newagcom/public_html/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#96 /home/newagcom/public_html/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#97 /home/newagcom/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#98 /home/newagcom/public_html/vendor/magento/framework/App/Bootstrap.php(257): Magento\Framework\App\Http\Interceptor->launch()
#99 /home/newagcom/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#100 {main}

**Comment by gonzaloebiz** [comment]
Hi @panthar1 

are you updating from a previous version?

**Comment by panthar1** [comment]
No, but we did do a migration from M1 to M2, during that process, we encountered this error https://community.magento.com/t5/Magento-2-x-Technical-Issues/The-requested-component-quot-datetime-quot-is-not-found-Before/td-p/66297 which I guess is some leftover artifacts the migration-tool created on the M2 site, that were wrong.

If you think that is related to this problem, do you know how we can completely delete artifacts from the M1 to M2 migration?

**Comment by gonzaloebiz** [comment]
If you are migrating from m1 to m2, remove all the entries in the core_config_data for path like 'mailchimp%'

Best

**Comment by panthar1** [comment]
Ahh! You are awesome, looks like deleting those old values in core_config fixed the exception. Thanks a ton!

**Comment by gonzaloebiz** [comment]
you are welcome
