### ISSUE TITLE
Exception #1 (ReflectionException): Class Mailchimp does not exist

### ISSUE THREAD

**Issue by palvinder03** [mailchimp/mc-magento2#83]
I have installed the extension , but it's showing 
Exception #1 (ReflectionException): Class Mailchimp does not exist
can you plz quick help to sort out this
![image](https://user-images.githubusercontent.com/17448065/30115268-dc013084-9337-11e7-861b-fa56b0a0b63c.png)

**Comment by gonzaloebiz** [comment]
see at this https://github.com/mailchimp/mc-magento2/issues/60

**Comment by palvinder03** [comment]
Thanks @gonzaloebiz
