### ISSUE TITLE
PayPal Express orders sync fails - Last name is NULL

### ISSUE THREAD

**Issue by ihor-sviziev** [mailchimp/mc-magento2#840]
### Preconditions

    1. Magento OS 2.3.2
    2. mc-magento2 102.3.36.

### Steps to reproduce

    1. Add to cart any product
    2. Place order using PayPal Express

### Actual and Expected result

**Actual result**
Some orders fails with error
![image](https://user-images.githubusercontent.com/1873745/63433903-b3767200-c42c-11e9-885d-0126030a2ce3.png)

```
customer.last_name : Schema describes string, NULL found instead
```

**Expected result**
All orders should be synced

### Additional information
Sometimes PayPal Express returns empty last name, as result - such order can't be synced with Mailchimp.

Related magento issue: https://github.com/magento/magento2/issues/23061

In case of empty last name - would be great to split first name to 2 parts and 2nd part send to mailchimp as a last name field.

**Comment by gonzaloebiz** [comment]
Hi @ihor-sviziev 

thanks for your feedback.
I think this happens only for guest customers, right?

**Comment by ihor-sviziev** [comment]
Yes

**Comment by gonzaloebiz** [comment]
thanks @ihor-sviziev just fixed and released in the new version
