### ISSUE TITLE
Mailchimp configuration not working in magento 2 Error when istalled?

### ISSUE THREAD

**Issue by k94pro** [mailchimp/mc-magento2#848]
1 exception(s):
Exception #0 (Exception): Notice: Undefined index: id in /home/ploma/public_html/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63

Exception #0 (Exception): Notice: Undefined index: id in /home/ploma/public_html/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63
<pre>#1 Magento\Config\Model\Config\Structure\Element\Iterator->setElements(array('zemez' => array('id' => 'zemez', 'class' => 'zemez_tab', 'sortOrder' => 99, 'translate' => 'label', 'label' => 'Zemez', '_elementType' => 'tab', 'children' => array('tm_amp' => array('id' => 'tm_amp', 'translate' => 'label', 'type' => 'text', 'sortOrder' => 99, 'showInDefault' => 1, 'showInWebsite' => 1, 'showInStore' => 1, 'class' => 'separator-top', 'label' => 'Accelerated Mobi...', 'tab' => 'zemez', 'resource' => 'Zemez_Amp::confi...', 'children' => array('general' => array('id' => 'general', 'translate' => 'label', 'type' => 'text', 'sortOrder' => 10, 'showInDefault' => 1, 'showInWebsite' => 1, 'showInStore' => 1, 'label' => 'General', 'children' => array('enabled' => array('id' => 'enabled', 'translate' => 'label', 'type' => 'select', 'sortOrder' => 11, 'showInDefault' => 1, 'showInWebsite' => 1, 'showInStore' => 1, 'label' => 'Enable Extension', 'source_model' => 'Magento\Config\M...', '_elementType' => 'field', 'path' => 'tm_amp/general'), 'pages' => array('id' => 'pages', 'translate' => 'label comment', 'type' => 'multiselect', 'sortOrder' => 80, 'showInDefault' => 1, 'showInWebsite' => 1, 'showInStore' => 1, 'label' => 'AMP Enabled On', 'source_model' => 'Zemez\Amp\Model\...', '_elementType' => 'field', 'path' => 'tm_amp/general')), '_elementType' => 'group', 'path' => 'tm_amp'), 'logo' => array('id' => 'logo', 'translate' => 'label', 'type' => 'text', 'sortOrder' => 20, 'showInDefault' => 1, 'showInWebsite' => 1, 'showInStore' => 1, 'label' => 'Amp Logo Image', 'children' => array('image' => array('id' => 'image', 'translate' => 'label', 'type' => 'image', 'sortOrder' => 21, 'showInDefault' => 1, 'showInWebsite' => 1, 'showInStore' => 1, 'label' => 'Image', 'backend_model' => 'Magento\Config\M...', 'upload_dir' => array('config' => 'system/filesyste...', 'scope_info' => 1, 'value' => 'theme_options/lo...'), 'base_url' => array('type' => 'media', 'scope_info' => 1, 'value' => 'theme_options/lo...'), 'comment' => 'Allowed file typ...', '_elementType' => 'field', 'path' => 'tm_amp/logo'), 'logo_image_width' => array('id' => 'logo_image_width', 'translate' => 'label', 'type' => 'text', 'sortOrder' => 22, 'showInDefault' => 1, 'showInWebsite' => 1, 'showInStore' => 1, 'label' => 'Logo Image Width', 'frontend_class' => 'required-entry v...', '_elementType' => 'field', 'path' => 'tm_amp/logo'), 'logo_image_heigh...' => array('id' => 'logo_image_heigh...', 'translate' => 'label', 'type' => 'text', 'sortOrder' => 23, 'showInDefault' => 1, 'showInWebsite' => 1, 'showInStore' => 1, 'label' => 'Height', 'frontend_class' => 'required-entry v...', '_elementType' => 'field', 'path' => 'tm_amp/logo')), '_elementType' => 'group', 'path' => 'tm_amp')), '_elementType' => 'section'))), 'general' => array('id' => 'general',

**Comment by gonzaloebiz** [comment]
Please follow the [issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)
