### ISSUE TITLE
Order trying to sync again and again when product wasn't found

### ISSUE THREAD

**Issue by ihor-sviziev** [mailchimp/mc-magento2#858]
### Preconditions
    1. Magento 2.3.2 
    2. mc-magento2 102.3.36.

### Steps to reproduce

    1. Disable cron jobs
    2. Place an order
    3. Delete product that you just bought 
    4. Enable cron jobs

### Actual
1. On each cron run in logs we have something like this:
```
...
[2019-08-29 14:58:10] MailChimpLogger.INFO: "Something went wrong when retreiving product information."
...
```
2. In order grid order status is "Syncing"

### Expected result
1. **Only on first run** we should have message in logs
2. Order should be marked as "error" sync status

**Comment by gonzaloebiz** [comment]
Hi @ihor-sviziev 

take a look at https://github.com/mailchimp/mc-magento2/issues/797 think this fix your issue

Best

**Comment by ihor-sviziev** [comment]
Yeah, looks you’re right.

Duplicate of #797
