### ISSUE TITLE
When run setup upgrade, this error appears  "Connection "checkout" is not defined"

### ISSUE THREAD

**Issue by Shero-Inc** [mailchimp/mc-magento2#86]
Magento CE 
Magento ver. 2.1.8

How to replicate:
git clone repo to the Magento. 
then run setup:upgrade

php bin/magento setup:upgrade

The error is like the following in terminal:

Module 'Ebizmarts_MailChimp':
Installing schema...

  [DomainException]
  Connection "checkout" is not defined

**Comment by Shero-Inc** [comment]
Looks like the issue is happening on this connection
app/code/Ebizmarts/MailChimp/Setup/InstallSchema.php

`$connection = $this->_resource->getConnectionByName('checkout');`

What's the reason of using connection by name, instad of `$connection = $this->_resource->getConnection();`

**Comment by gonzaloebiz** [comment]
Why you use a develop version of the extension?
