### ISSUE TITLE
Adminhtml Error, when try to go to Mailchimp Options

### ISSUE THREAD

**Issue by Shero-Inc** [mailchimp/mc-magento2#87]
Magento CE
Magento ver. 2.1.8

How to replicate: 

Go to admin-> mailchimp-> configuration : 

![screen shot 2017-09-11 at 20 20 22](https://user-images.githubusercontent.com/29729984/30290232-ea204c54-972e-11e7-9cee-b96efec819b8.png)

The same issue for Mailchimp stores option as well.

**Comment by gonzaloebiz** [comment]
composer require ebizmarts/mailchimp-lib
