### ISSUE TITLE
ebizmarts_commerce cron jub gets stuck on running

### ISSUE THREAD

**Issue by vDeggial** [mailchimp/mc-magento2#872]
Magento 2.3.2
Plugin version 102..2.36

Ever since sometime last night no orders are getting synced to Mailchimp, no news log entries in Mailchimp.log and cron seems to get stuck in "running" state:

![image](https://user-images.githubusercontent.com/9992759/64369367-13dee500-cfd1-11e9-8230-3600d888a798.png)

Was all fine just before the issue started around 6:15pm PDT it seems ...

**Comment by vDeggial** [comment]
it seems to be fine now ....

**Comment by vDeggial** [comment]
and the same issue is back again :(

**Comment by gonzaloebiz** [comment]
Hi @shinoamakusa 

thanks for your feedback.
Not looking like an issue in the extension, looks more an issue in your installation, please contact to our support and we are pleased to help you.

Best
