### ISSUE TITLE
Upgrading Magento 2.2.9 - Segmentation fault: 11

### ISSUE THREAD

**Issue by Flipmediaco** [mailchimp/mc-magento2#873]
## Title

Upgrading Magento 2.2.9 - Segmentation fault: 11

Segmentation fault: 11 returned when running:  php -d memory_limit=-1 ./bin/magento setup:upgrade

"Module 'Ebizmarts_MailChimp':
Installing data... Upgrading data... Segmentation fault: 11"

## Issue Description

Having upgraded from Magento 2.2.7, when running upgrade "Segmentation fault: 11" is returned.

I have completely removed MailChimp and Mandrill extensions of prior versions and following this was able to achieve and upgrade.

I then went on to install:-

composer require ebizmarts/mailchimp-lib
composer require mailchimp/mc-magento2:101.2.36

### Preconditions

1. Upgrade to Magento 2.2.9
2. Attempt to run upgrade command: Segmentation fault: 11
3. Uninstall mailchimp extensions
4. Run upgrade command: OK
5. Install via composer mailchimp-lib and mc-magento2:101.2.36
6. Attempt to run upgrade command: Segmentation fault: 11

### Additional information

When reviewing the failed site it stated: 

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
Ebizmarts_MailChimp data: current version - none, required version - 101.2.35

I repeated the above upgrade using the stated version: 101.2.35 resulted in same failure.

**Comment by gonzaloebiz** [comment]
Hi @Flipmediaco 

thanks for your feedback.
What method do you use to update from magento 2.2.7 to magento 2.2.9?

Best

**Comment by Flipmediaco** [comment]
Hi

I via CLI, see below...

php -d memory_limit=-1 ./bin/magento maintenance:enable
composer require magento/product-community-edition 2.2.9 --no-update
composer update --no-dev
rm -rf var/page_cache/* var/di/* var/view_process/* var/cache/* var/generation/*
rm -rf pub/static/adminhtml pub/static/deployed_version.txt pub/static/_requirejs pub/static/frontend
php -d memory_limit=-1 ./bin/magento setup:upgrade
php -d memory_limit=-1 ./bin/magento setup:di:compile
php -d memory_limit=-1 ./bin/magento indexer:reindex
php -d memory_limit=-1 ./bin/magento setup:static-content:deploy -f en_GB en_US
php -d memory_limit=-1 ./bin/magento cache:clean
php -d memory_limit=-1 ./bin/magento cache:flush
php -d memory_limit=-1 ./bin/magento maintenance:disable

**Comment by gonzaloebiz** [comment]
Hi @Flipmediaco 

i just try and works like a charm for me.

1. Install magento 2.2.7 with sample data
2. Install mc-magento2 (composer require mailchimp/mc-magento2:101.2.36)
3. Run setup:upgrade to ends the mc-magento2 installation
4. Upgrade magento from 2.2.7 to 2.2.9 per your instructions

Best

**Comment by Flipmediaco** [comment]
Hi 

I suspect the issue relates to our data mc versions.

The 2.2.7 instance has mailchimp/mc-magento2 1.2.33 installed.

I will attempt and upgrade of mailchimp/mc-magento2 before upgrading: 

composer require mailchimp/mc-magento2:101.2.36

Thanks Laurie

**Comment by gonzaloebiz** [comment]
OK, let me know if works.
For now we close the issue

**Comment by Flipmediaco** [comment]
Hi

I have repeated the upgrade without error using your advise and ensuring I removed the old version prior as I couldn't recall when it was originally installed.

Installing the most recent mailchimp/mc-magento2 for M2.2 before upgrading was at the core of the solution.

Thanks
