### ISSUE TITLE
Magento 2 Bug - Subcribed then Unsubscribed During Account Register

### ISSUE THREAD

**Issue by SOScott84** [mailchimp/mc-magento2#875]
I am experiencing a problem with the mailchimp module in Magento 2.  Whenever I register a customer in Magento, on the frontend, and check "Sign up for newsletter" it creates an account in Mailchimp as unsubscribed, and in Magento, I am unsubscribed from the newsletter.

Upon further investigation vendor/magento/module-newsletter/Model/Plugin/CustomerPlugin.php's afterSave is ran 3 times during customer registration.  During the 3rd time, line 92 is ran -- $subscriber->unsubscribeCustomerById($resultId); based on the conditions in this file.  This unsubscribes the customer both in Magento and Mailchimp.  This is because the extension attribute getIsSubscribed() is false the 3rd time.

But, if I don't allow this method to run the first two times, then an account is never created with Mailchimp, even though the customer is and remains subscribed in Magento.

Between the 2nd and 3rd time vendor/magento/module-newsletter/Model/Plugin/CustomerPlugin.php's afterSave is ran, if I pause it in XDebug, the customer is subscribed both in Magento and Mailchimp.

**Comment by gonzaloebiz** [comment]
Please follow the issue format

Best
