### ISSUE TITLE
After install with composer table not found

### ISSUE THREAD

**Issue by Daniel304** [mailchimp/mc-magento2#876]
After running composer require mailchimp/mc-magento2
I ran setup:upgrade during the run it throws an error:
Upgrading schema.. SQLSTATE[42S02]: Base table or view not found: 1146 Table 'brickfever.mailchimp_sync_ecommerce' doesn't exist, query was: DESCRIBE `mailchimp_sync_ecommerce`

It is magento 2.3.2

**Comment by gonzaloebiz** [comment]
Please take a look at https://github.com/mailchimp/mc-magento2/issues/664

Best
