### ISSUE TITLE
Major Admin Order Grid Slowdown

### ISSUE THREAD

**Issue by timothydmahon** [mailchimp/mc-magento2#88]
**Preconditions:**
Magento EE 2.1.7
Mailchimp for Magento v1.0.21
>30,000 Orders
Filter at 200 Orders per page for full effect

**Steps to reproduce:**
1. Open the Magento 2 admin panel 
2. Navigate to the Sales->Orders Section
3. Optionally, set filter to 200. 

**Expected results:**
Prior to installing this extension expected load time for 200 results sat at around the 5-10s mark.
Actual results:
After installation load time increased to nearly 20-30s. 

**Additional Information:**
Huge performance hit appears to be due to reoccurring order load per order in the grid from here:
https://github.com/mailchimp/mc-magento2/blob/develop/Ui/Component/Listing/Column/Monkey.php#L74

**Comment by gonzaloebiz** [comment]
Hi @timothydmahon 

thanks for your feedback.
I will take a look, looks like you are right

Best
