### ISSUE TITLE
mailchimp_webhook_request table is increasing real fast

### ISSUE THREAD

**Issue by luuksuijkerbuijk** [mailchimp/mc-magento2#880]
## mailchimp_webhook_request table is increasing real fast.

On our live environment the mailchimp_webhook_request table is increasing really fast. Currently this table contains over 40 million records. We already dropped the whole table, but after the sync with MailChimp all the records are back again.

### Preconditions
    1. Magento CE 2.2.5
    2. mc-magento2 101.2.36

I don't know how this happend, so it's hard to provide any more information to reproduce this issue. Hopefully this is enough information, otherwise please let me know!

**Comment by gonzaloebiz** [comment]
Hi @luuksuijkerbuijk 

thanks for your feedback.
Please take a look at https://github.com/mailchimp/mc-magento2/issues/598 as you can view there https://github.com/mailchimp/mc-magento2/commit/14a6259d8a2ef1488b81e783e881efab7e50334f we remove the processed registers with one month age.
Check if the cron job ebizmarts_clean_batches is running

Best

**Comment by luuksuijkerbuijk** [comment]
Hi @gonzaloebiz,

This cron is running with no problems.
Also, I'm talking about the mailchimp_webhook_request table, but also the ebizmarts_clean_webhooks is running successfully.
