### ISSUE TITLE
having confirmation both on account registration and newsletter subscription not working

### ISSUE THREAD

**Issue by springerin** [mailchimp/mc-magento2#89]
So currently there is a bug on magento 2 ( my current installation is 2.1.8) https://github.com/magento/magento2/issues/9787 
Newsletter Subscription is cancelled automatically on Account Confirmation.

Once I solved this bug, the user receives the following mails: 
1 for account confirmation request
1 for newsletter confirmation request

If the user confirms the account, he gets a second newsletter confirmation request because mailchimp sends on every api call with status pending which is the status assigned when the newsletter is not confirmed. 

I try to rewrite the plugin by disabling it and make a new plugin that does the same plus a check on the confirmaton state of the customer but for some reason isn't possible to use in my constructor Ebizmarts\MailChimp\Helper\Data because I get the error :

> PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Bitbull\\Fixes\\Mailchimp\\Model\\Plugin\\Subscriber::__construct() must be an instance of Ebizmarts\\MailChimp\\Helper\\Data, instance of Magento\\Framework\\ObjectManager\\ObjectManager given

This is the code i use:

>  /**
     * Subscriber constructor.
     *
     * @param \Ebizmarts\MailChimp\Helper\Data                         $helper
     * @param \Magento\Customer\Model\ResourceModel\CustomerRepository $customer
     * @param \Magento\Customer\Model\Session                          $customerSession
     * @param \Magento\Store\Model\StoreManagerInterface               $storeManager
     * @param AccountManagementInterface                               $customerAccountManagement
     */
    public function __construct(
        \Ebizmarts\MailChimp\Helper\Data $helper,
        \Magento\Customer\Model\ResourceModel\CustomerRepository $customer,
        \Magento\Customer\Model\Session $customerSession,
        \Magento\Store\Model\StoreManagerInterface $storeManager,
        AccountManagementInterface $customerAccountManagement
    ) {

I already declared in composer.json and module.xml the dependency from your module.
So I am unable to fix this issue myself. Any suggestion on how to fix this?

**Comment by gonzaloebiz** [comment]
Hi @springerin 

sorry but i don't understand.
" try to rewrite the plugin by disabling it and make a new plugin"... you disable what?
How you call this new class Bitbull\Fixes\Mailchimp\Model\Plugin\Subscriber?

**Comment by springerin** [comment]
Following magento directives, my only way to change your plugin is to disable your plugin and write my own plugin to do the same things ( using the same classes you have in your plugin) with the new added code but for some reason I can't use your helper in my own module because of the error I told you up.
While isn't a must to be able to use your helper in my ( or any custom) module, maybe figure a way to not have double request confirmation mail?

Bitbull\Fixes\Mailchimp\Model\Plugin\Subscriber -> is my new plugin so i declare it in the di.xml

**Comment by gonzaloebiz** [comment]
Sure, you (or any) can use our helper
You already run 

bin/magento setup:upgrade
bin/magento setup:static-content:deploy
bin/magento cache:clean

?

**Comment by gonzaloebiz** [comment]
With no news, i close the issue

**Comment by springerin** [comment]
Sorry I didn't see this comment, yes I did all of the commands you've suggested.
If you wish I can make a repo where you can get the code yourself and test it. @gonzaloebiz
