### ISSUE TITLE
Exception: Unable to unserialize value. Error: Syntax error

### ISSUE THREAD

**Issue by amiddio** [mailchimp/mc-magento2#892]
In customer account menu on frontend, when clicking on 'Newsletter Subscriptions' menu, I'm getting error: 

> 
> 1 exception(s):
> Exception #0 (InvalidArgumentException): Unable to unserialize value. Error: Syntax error
> 
> Exception #0 (InvalidArgumentException): Unable to unserialize value. Error: Syntax error
> <pre>#1 Ebizmarts\MailChimp\Helper\Data->getSubscriberInterest(NULL, NULL) called at [vendor/mailchimp-source/Block/Newsletter.php:58]
> #2 Ebizmarts\MailChimp\Block\Newsletter->getInterest() called at [vendor/mailchimp-source/view/frontend/templates/form/newsletter.phtml:5]
> #3 include('/home/devsite...') called at [vendor/magento/framework/View/TemplateEngine/Php.php:59]
> #4 Magento\Framework\View\TemplateEngine\Php->render(&Ebizmarts\MailChimp\Block\Newsletter#0000000024cbb1180000000062d78af8#, '/home/devsite...', array()) called at [vendor/magento/framework/View/Element/Template.php:271]
> #5 Magento\Framework\View\Element\Template->fetchView('/home/devsite...') called at [vendor/magento/framework/View/Element/Template.php:301]
> #6 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1094]
> #7 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1098]
> #8 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:671]
> #9 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:557]
> #10 Magento\Framework\View\Layout->_renderBlock('customer.form.ne...') called at [vendor/magento/framework/View/Layout.php:533]
> #11 Magento\Framework\View\Layout->renderNonCachedElement('customer.form.ne...') called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
> #12 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('customer.form.ne...') called at [vendor/magento/framework/View/Layout.php:488]
> #13 Magento\Framework\View\Layout->renderElement('customer.form.ne...', true) called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
> #14 Magento\Framework\View\Layout\Interceptor->renderElement('customer.form.ne...', true) called at [vendor/magento/framework/View/Element/AbstractBlock.php:518]
> #15 Magento\Framework\View\Element\AbstractBlock->getChildHtml('customer.form.ne...') called at [vendor/magento/module-customer/view/frontend/templates/form/newsletter.phtml:21]
> #16 include('/home/devsite...') called at [vendor/magento/framework/View/TemplateEngine/Php.php:59]
> #17 Magento\Framework\View\TemplateEngine\Php->render(&Magento\Customer\Block\Newsletter#0000000024cbb1250000000062d78af8#, '/home/devsite...', array()) called at [vendor/magento/framework/View/Element/Template.php:271]
> #18 Magento\Framework\View\Element\Template->fetchView('/home/devsite...') called at [vendor/magento/framework/View/Element/Template.php:301]
> #19 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1094]
> #20 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1098]
> #21 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:671]
> #22 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:557]
> #23 Magento\Framework\View\Layout->_renderBlock('customer_newslet...') called at [vendor/magento/framework/View/Layout.php:533]
> #24 Magento\Framework\View\Layout->renderNonCachedElement('customer_newslet...') called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
> #25 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('customer_newslet...') called at [vendor/magento/framework/View/Layout.php:488]
> #26 Magento\Framework\View\Layout->renderElement('customer_newslet...', false) called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
> #27 Magento\Framework\View\Layout\Interceptor->renderElement('customer_newslet...', false) called at [vendor/magento/framework/View/Layout.php:585]
> #28 Magento\Framework\View\Layout->_renderContainer('content', false) called at [vendor/magento/framework/View/Layout.php:535]
> #29 Magento\Framework\View\Layout->renderNonCachedElement('content') called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
> #30 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content') called at [vendor/magento/framework/View/Layout.php:488]
> #31 Magento\Framework\View\Layout->renderElement('content', false) called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
> #32 Magento\Framework\View\Layout\Interceptor->renderElement('content', false) called at [vendor/magento/framework/View/Layout.php:585]
> #33 Magento\Framework\View\Layout->_renderContainer('main', false) called at [vendor/magento/framework/View/Layout.php:535]
> #34 Magento\Framework\View\Layout->renderNonCachedElement('main') called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
> #35 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main') called at [vendor/magento/framework/View/Layout.php:488]
> #36 Magento\Framework\View\Layout->renderElement('main', false) called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
> #37 Magento\Framework\View\Layout\Interceptor->renderElement('main', false) called at [vendor/magento/framework/View/Layout.php:585]
> #38 Magento\Framework\View\Layout->_renderContainer('columns', false) called at [vendor/magento/framework/View/Layout.php:535]
> #39 Magento\Framework\View\Layout->renderNonCachedElement('columns') called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
> #40 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('columns') called at [vendor/magento/framework/View/Layout.php:488]
> #41 Magento\Framework\View\Layout->renderElement('columns', false) called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
> #42 Magento\Framework\View\Layout\Interceptor->renderElement('columns', false) called at [vendor/magento/framework/View/Layout.php:585]
> #43 Magento\Framework\View\Layout->_renderContainer('main.content', false) called at [vendor/magento/framework/View/Layout.php:535]
> #44 Magento\Framework\View\Layout->renderNonCachedElement('main.content') called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
> #45 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content') called at [vendor/magento/framework/View/Layout.php:488]
> #46 Magento\Framework\View\Layout->renderElement('main.content', false) called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
> #47 Magento\Framework\View\Layout\Interceptor->renderElement('main.content', false) called at [vendor/magento/framework/View/Layout.php:585]
> #48 Magento\Framework\View\Layout->_renderContainer('page.wrapper', false) called at [vendor/magento/framework/View/Layout.php:535]
> #49 Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper') called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
> #50 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper') called at [vendor/magento/framework/View/Layout.php:488]
> #51 Magento\Framework\View\Layout->renderElement('page.wrapper', false) called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
> #52 Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper', false) called at [vendor/magento/framework/View/Layout.php:585]
> #53 Magento\Framework\View\Layout->_renderContainer('root', false) called at [vendor/magento/framework/View/Layout.php:535]
> #54 Magento\Framework\View\Layout->renderNonCachedElement('root') called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
> #55 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root') called at [vendor/magento/framework/View/Layout.php:488]
> #56 Magento\Framework\View\Layout->renderElement('root', true) called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
> #57 Magento\Framework\View\Layout\Interceptor->renderElement('root') called at [vendor/magento/framework/View/Layout.php:954]
> #58 Magento\Framework\View\Layout->getOutput() called at [vendor/magento/framework/Interception/Interceptor.php:58]
> #59 Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', array()) called at [vendor/magento/framework/Interception/Interceptor.php:138]
> #60 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
> #61 Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', array(), array(array('layout-model-cac...'))) called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:494]
> #62 Magento\Framework\View\Layout\Interceptor->getOutput() called at [vendor/magento/framework/View/Result/Page.php:258]
> #63 Magento\Framework\View\Result\Page->render(&Magento\Framework\App\Response\Http\Interceptor#0000000024cbb4060000000062d78af8#) called at [vendor/magento/framework/View/Result/Layout.php:171]
> #64 Magento\Framework\View\Result\Layout->renderResult(&Magento\Framework\App\Response\Http\Interceptor#0000000024cbb4060000000062d78af8#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
> #65 Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', array(&Magento\Framework\App\Response\Http\Interceptor#0000000024cbb4060000000062d78af8#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
> #66 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Response\Http\Interceptor#0000000024cbb4060000000062d78af8#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
> #67 Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', array(&Magento\Framework\App\Response\Http\Interceptor#0000000024cbb4060000000062d78af8#), array(array('result-messages', 'result-builtin-c...', 'result-varnish-c...'))) called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:130]
> #68 Magento\Framework\View\Result\Page\Interceptor->renderResult(&Magento\Framework\App\Response\Http\Interceptor#0000000024cbb4060000000062d78af8#) called at [vendor/magento/framework/App/View.php:221]
> #69 Magento\Framework\App\View->renderLayout() called at [vendor/magento/module-newsletter/Controller/Manage/Index.php:24]
> #70 Magento\Newsletter\Controller\Manage\Index->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
> #71 Magento\Newsletter\Controller\Manage\Index\Interceptor->___callParent('execute', array()) called at [vendor/magento/framework/Interception/Interceptor.php:138]
> #72 Magento\Newsletter\Controller\Manage\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/dotmailer/dotmailer-magento2-extension/Plugin/NewsletterManageIndexPlugin.php:70]
> #73 Dotdigitalgroup\Email\Plugin\NewsletterManageIndexPlugin->aroundExecute(&Magento\Newsletter\Controller\Manage\Index\Interceptor#0000000024cbb6500000000062d78af8#, &Closure#0000000024cbb0a80000000062d78af8#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
> #74 Magento\Newsletter\Controller\Manage\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
> #75 Magento\Newsletter\Controller\Manage\Index\Interceptor->___callPlugins('execute', array(), NULL) called at [generated/code/Magento/Newsletter/Controller/Manage/Index/Interceptor.php:26]
> #76 Magento\Newsletter\Controller\Manage\Index\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
> #77 Magento\Framework\App\Action\Action->dispatch(&Magento\Framework\App\Request\Http#0000000024cbb4730000000062d78af8#) called at [vendor/magento/module-newsletter/Controller/Manage.php:45]
> #78 Magento\Newsletter\Controller\Manage->dispatch(&Magento\Framework\App\Request\Http#0000000024cbb4730000000062d78af8#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
> #79 Magento\Newsletter\Controller\Manage\Index\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#0000000024cbb4730000000062d78af8#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
> #80 Magento\Newsletter\Controller\Manage\Index\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000024cbb4730000000062d78af8#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
> #81 Magento\Newsletter\Controller\Manage\Index\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#0000000024cbb4730000000062d78af8#), array(array('designLoader', 'customerNotifica...', 'catalog_app_acti...', 'tax-app-action-d...', 'weee-app-action-...', 'storeCheck', 'contextPlugin', 'customer-app-act...'))) called at [generated/code/Magento/Newsletter/Controller/Manage/Index/Interceptor.php:39]
> #82 Magento\Newsletter\Controller\Manage\Index\Interceptor->dispatch(&Magento\Framework\App\Request\Http#0000000024cbb4730000000062d78af8#) called at [vendor/magento/framework/App/FrontController.php:159]
> #83 Magento\Framework\App\FrontController->processRequest(&Magento\Framework\App\Request\Http#0000000024cbb4730000000062d78af8#, &Magento\Newsletter\Controller\Manage\Index\Interceptor#0000000024cbb6500000000062d78af8#) called at [vendor/magento/framework/App/FrontController.php:99]
> #84 Magento\Framework\App\FrontController->dispatch(&Magento\Framework\App\Request\Http#0000000024cbb4730000000062d78af8#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
> #85 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#0000000024cbb4730000000062d78af8#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
> #86 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000024cbb4730000000062d78af8#) called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:94]
> #87 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#0000000024cbb58d0000000062d78af8#, &Closure#0000000024cbb5b30000000062d78af8#, &Magento\Framework\App\Request\Http#0000000024cbb4730000000062d78af8#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
> #88 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000024cbb4730000000062d78af8#) called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:73]
> #89 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#0000000024cbb58d0000000062d78af8#, &Closure#0000000024cbb5b30000000062d78af8#, &Magento\Framework\App\Request\Http#0000000024cbb4730000000062d78af8#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
> #90 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000024cbb4730000000062d78af8#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
> #91 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#0000000024cbb4730000000062d78af8#), NULL) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
> #92 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#0000000024cbb4730000000062d78af8#) called at [vendor/magento/framework/App/Http.php:137]
> #93 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
> #94 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
> #95 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#0000000024cbb40d0000000062d78af8#) called at [index.php:39]
> </pre>

### Preconditions

1. Magento CE 2.3.2
2. mc-magento2 1.0.32.
3. Logged in customer in frontend

### Steps to reproduce

1. Navigate to storefront as a logged in customer.
2. Go to 'My account' page
3. Click "Newsletter Subscriptions" on the customer account sidebar menu.

### Additional information

I've migrated customers from M1 to current M2.3.2

**Comment by gonzaloebiz** [comment]
Hi @amiddio 

thanks for choosing our extension.
Please uptade the extension to the current version (102.3.37)

Best
