### ISSUE TITLE
Mailchimp blank page in admin (duplicate in Magento 2.3.2-p2)

### ISSUE THREAD

**Issue by ambrose40** [mailchimp/mc-magento2#894]
### Preconditions

Describing preconditions is a great start, provide information on system configuration settings you have changed, detailed information on entities created (Products, Customers, etc), Magento and mc-magento versions. Basically, everything that would help developer set up the same environment as you have.

    1. Magento CE 2.3.2-p2 without sample data is installed.
    2. mailchimp/mc-magento2 102.3.34.
    3. customized porto theme.
    4. My composer.json is attached. Magento and Modules were installed via Composer project.

### Steps to reproduce

This part of the bug report is the most important, as developer will use this information to reproduce the issue. Problem is more likely to be fixed if it can be reproduced.

Precisely describe each step you have taken to reproduce the issue. Try to include as much information as possible, sometimes even minor differences can be crucial.

    1. Navigate to backend as a admin.
    2a. Open Stores -> Configuration -> Mailchimp -> Mailchimp.
    2a. Mailchimp -> Configuration. (alternative variant)
    3. Also checked in DB, and there is no data in any of Mailchimp DB tables.
### Actual and Expected result

To make sure that everybody involved in the fix are on the same page, precisely describe the result you expected to get and the result you actually observed after performing the steps.

    Expected result:
    Mailchimp Admin Configuration page is opened and I can add my Mailchimp API key.
    Actual result:
    Admin theme is displayed and I can press save config, but there is empty page instead of 
    Mailchimp configuration

### Additional information

Attaching var/log folder zip and my composer.json
[composer.json.zip](https://github.com/mailchimp/mc-magento2/files/3717649/composer.json.zip)
[log.zip](https://github.com/mailchimp/mc-magento2/files/3717650/log.zip)

<img width="1680" alt="Screenshot 2019-10-11 at 16 03 06" src="https://user-images.githubusercontent.com/2347642/66653489-dbba6a00-ec40-11e9-9073-d7b83cd3ea3a.png">

**Comment by ambrose40** [comment]
Duplicate of #522

**Comment by ambrose40** [comment]
Please help me sort out this issue. Any help is kindly appreciated.

**Comment by gonzaloebiz** [comment]
Hi @bl82 

thanks for choosing our extension.
This looks like not an issue of the extension, looks like an installation issue, please contact our support team.

Best

**Comment by vinoth-selvi** [comment]
@bl82 Did you found the solution. I'm also facing same problem.

**Comment by ambrose40** [comment]
@vinoth-selvi 
Delete all mailchimp settings in core_config_data, flush magento cache and go to Mailchimp settings page:
`delete from core_config_data where path like "mailchimp%";`
