### ISSUE TITLE
Unable to sync with mailchimp

### ISSUE THREAD

**Issue by thedarrenpeters** [mailchimp/mc-magento2#898]
Preconditions
1. Magento 2.3.2 without sample data
2. Mailchimp v102.3.34
3. Follow install procedures at https://mailchimp.com/help/connect-or-disconnect-mailchimp-for-magento-2/

Expected Result
1. Magento syncs with mailchimp

Actual Results
1. No syncing occurs, cron job errors out with following error 

Warning: Invalid argument supplied for foreach() in .../vendor/mailchimp/mc-magento2/Helper/Data.php on line 1028

**Comment by gonzaloebiz** [comment]
Hi @thedarrenpeters 

thanks for choosing our extension.
Please install the current version

Best

**Comment by thedarrenpeters** [comment]
What is current version?

**Comment by gonzaloebiz** [comment]
You can find it at https://github.com/mailchimp/mc-magento2/releases

Best
