### ISSUE TITLE
API Key Invalid for Api Call

### ISSUE THREAD

**Issue by amiddio** [mailchimp/mc-magento2#899]
Lost configuration settings after browser refresh.

I've entered valid API Key and clicked "Save config":
![Screenshot_1](https://user-images.githubusercontent.com/2463233/66814056-03624880-ef47-11e9-9d51-f01e3de3d6ea.png)

Then I've refreshed the page, and API Key lost:
![Screenshot_2](https://user-images.githubusercontent.com/2463233/66814058-03624880-ef47-11e9-8235-457c56fbaa41.png)

In MailChimp.log I see:

> [2019-10-15 08:12:45] MailChimpLogger.INFO: API Key Invalid for Api Call: [https://us1.api.mailchimp.com/3.0/ecommerce/stores?count=200] using method [GET]
> 	Detail: [Your API key may be invalid, or you've attempted to access the wrong datacenter.]
> 	Params:
> 		{"count":200}
>  [] []
> [2019-10-15 08:12:46] MailChimpLogger.INFO: API Key Invalid for Api Call: [https://us1.api.mailchimp.com/3.0/lists/] using method [GET]
> 	Detail: [Your API key may be invalid, or you've attempted to access the wrong datacenter.]
> 
>  [] []
> [2019-10-15 08:12:46] MailChimpLogger.INFO: API Key Invalid for Api Call: [https://us1.api.mailchimp.com/3.0/] using method [GET]
> 	Detail: [Your API key may be invalid, or you've attempted to access the wrong datacenter.]
> 
>  [] []
> [2019-10-15 08:12:46] MailChimpLogger.INFO: API Key Invalid for Api Call: [https://us1.api.mailchimp.com/3.0/lists/0/interest-categories] using method [GET]
> 	Detail: [Your API key may be invalid, or you've attempted to access the wrong datacenter.]
> 
>  [] []
> [2019-10-15 08:12:46] MailChimpLogger.INFO: API Key Invalid for Api Call: [https://us1.api.mailchimp.com/3.0/lists/0/merge-fields?count=100] using method [GET]
> 	Detail: [Your API key may be invalid, or you've attempted to access the wrong datacenter.]
> 	Params:
> 		{"count":100}
>  [] []

### Preconditions

    1. Magento CE 2.3.2.
    2. mc-magento2 102.3.37.

### Steps to reproduce

    1. Go to Admin -> Configuration -> Mailchimp
    2. Enter valid API Key
    3. Click Save
    4. Refresh broweser
    5. Key is lost

### Actual and Expected result

Key should not be lost.

**Comment by gonzaloebiz** [comment]
Are you using chrome?
Try with firefox, of with an incognito window

Best

**Comment by amiddio** [comment]
No, I use Firefox. 
Checked again via an incognito window:
- deleted all cache data from browser
- deleted cookies and cache storage

The same result: lost key after refresh.

**Comment by gonzaloebiz** [comment]
Hi @amiddio 

i check in both, chrome and firefox and works OK
Are you using some kind of password manager like lastpass or something like? Think that tour browser is auto-filling this field for you.
Try in a different pc in a browser without extensions

**Comment by amiddio** [comment]
Thank you @gonzaloebiz,
it was related with config. I found solution for me here https://magento.stackexchange.com/questions/223978/magento2-2-3-admin-store-configuration-is-save-but-not-display-in-admin-panel
