### ISSUE TITLE
Ecommerce Data is not syncying in magento 2 store and mailchimp 

### ISSUE THREAD

**Issue by trushangsuthartri** [mailchimp/mc-magento2#90]
Magento CE 2.1.8
Mailchimp for Magento 1.0.21

Expected results:

I have installed you MailChimp extension for Magento 2 in a store.

And I followed your instructions hho and configure correctly. And everything seems good,

I am not receiving any data in mailchimp from magento, I think customer, orders should be sync. and after new order place detail of new order shouls be in mailchimp but currently there is nothing in my mailchimp, how can I make it sync? is there any manual way or is there any cron we have to set?

I have follow this tutorial to config mailchimp on magento 2 site
https://kb.mailchimp.com/integrations/e-commerce/connect-or-disconnect-mailchimp-for-magento-2

**Comment by gonzaloebiz** [comment]
Hi @trushangsuthartri 

you already configured your magento cron?

**Comment by trushangsuthartri** [comment]
@gonzaloebiz 

no

**Comment by gonzaloebiz** [comment]
This is why.
The extension needs the cron system 

Best

**Comment by trushangsuthartri** [comment]
@gonzaloebiz 

ok thanks
