### ISSUE TITLE
 Abandon Carts automation deletes First Name

### ISSUE THREAD

**Issue by ihor-sviziev** [mailchimp/mc-magento2#904]
### Preconditions

- Have some integration with Mailchimp that could sync First name, for instance [Picreel](https://www.picreel.com/)
- Magento 2.3.2
- MC Magento2 102.3.36

### Steps to reproduce

1. Sign up to a newsletter through Picreel (including First Name)
2. Go to Mailchimp and see that both Email and First Name exist on your user
3. Add a product to Cart
4. Go to checkout page, fill up your email, _do not finish checkout_
5. Wait untill your quote will be synced to Mailchimp
6. Go to Mailchimp and see if Email and First Name exist on your user

### Actual result
First name is empty in Mailchimp

### Expected result
First name should be present, as we didn't filled it up anywhere in Magento

**Comment by gonzaloebiz** [comment]
Hi @ihor-sviziev 

thanks for your feedback.
Looks like an error in the mailchimp API
As i can view, the request for the new quote is

`    {
        "method": "POST",
        "path": "\/ecommerce\/stores\/xxxxxxxxxxxxxxx\/carts",
        "operation_id": "QUO_2019-10-18-14-40-06-93196500_13",
        "body": "{\"id\":\"13\",\"customer\":{\"id\":\"c8336fcb75ea89d78b543d1026bb4316\",\"email_address\":\"gonzalo@xxxxxx.com\",\"opt_in_status\":false},\"checkout_url\":\"http:\\\/\\\/mc-magento23.local.com\\\/mailchimp\\\/cart\\\/loadquote\\\/id\\\/13\\\/token\\\/xxxxxxxxxxxxxxx\\\/\",\"currency_code\":\"USD\",\"order_total\":\"59.0000\",\"tax_total\":0,\"lines\":[{\"id\":\"1\",\"product_id\":\"6\",\"product_variant_id\":\"6\",\"quantity\":1,\"price\":\"59.0000\"}]}"
    }
`

As you can see, we don't send the firstname or lastname, so supposed this data doesn't change, but mailchimp clean up both, i will look this internally with mailchimp.

Best

**Comment by ihor-sviziev** [comment]
@gonzaloebiz thank you!

**Comment by ihor-sviziev** [comment]
Hi @gonzaloebiz,
Could you explain why this issue was closed without any comments?

**Comment by gonzaloebiz** [comment]
Sure, because we can't do anything to fix it since is an error in the MailChimp end
