### ISSUE TITLE
Invalid ForEach Error when displaying MailChimp Stores

### ISSUE THREAD

**Issue by swleighton** [mailchimp/mc-magento2#905]
After creating a MailChimp store the following error is shown on the MailChimp Store List Page /mailchimp/stores/
`Warning: Invalid argument supplied for foreach() in /app/vendor/magento/framework/View/Element/UiComponent/DataProvider/DataProvider.php on line 250`

No errors are shown in the MailChimp error logs. Data sync is working as expected.

### Preconditions
1. Magento Cloud 3.3.2
2. mc-magento2 102.3.37
3. PHP 7.2.22

### Steps to reproduce
1. Add a MailChimp store
2. Navigate to the store list page /mailchimp/stores/ 
3. See error

#### Expected result:
Page lists all created stores
#### Actual result:
Error is shown

**Comment by gonzaloebiz** [comment]
Hi @swleighton 

are you migrating your magento and/or our extension for a previous version?
We test this use case with a magento 2.3.2 and 2.3.3 and works OK (we don't test it in the cloud)
Are you sure that your run a setup:static-content:deploy and setup:di:compile?

Best

**Comment by swleighton** [comment]
Hi @gonzaloebiz,

We're not migrating, it's a new build. I've also found the following issue experiencing the same problem a couple of years ago https://github.com/mailchimp/mc-magento2/issues/127. 

I'll feedback the possible fix to the team to investigate plus check file permissions.  

Appreciate your help.

Simon
