### ISSUE TITLE
Invalid API key error when attempting to update settings.

### ISSUE THREAD

**Issue by brian-ebizmarts** [mailchimp/mc-magento2#906]
### Preconditions
    1. Magento 2 any version
    2. mc-magento2 any version

### Steps to reproduce

- Turn on offer to save passwords in the browser settings and accept to remember some password on the same domain shared with Magento.
- Set up the extension and attempt to save the settings, the error "Invalid API key" is returned by Mailchimp.

**Comment by jproffer** [comment]
I have this issue with the current version of the plugin (102.3.37).  When I add the API key I get a blank error popup,  and going to stores, the dropdown says 'invalid api key'.

**Comment by SantiParagarino** [comment]
Hello @jproffer 

Please make sure your API Key is currently working. As soon as you add it in the API Key field, when you click outside of the field, do you see your account details show in the box below?
You can get the API Key by clicking the **GET API CREDENTIALS** button.
If that API Key does not work you can also create a new one at https://mailchimp.com/help/about-api-keys/

If you still have problems please contact our support at mailchimp@ebizmarts-desk.zendesk.com

Kind Regards.
