### ISSUE TITLE
2 confirmation emails sent with double opt-in

### ISSUE THREAD

**Issue by ebizmarts-keller** [mailchimp/mc-magento2#91]
mc-magento 1.0.21, 1.0.23
Magento version 2.1.5, 2.1.8

When double opt-in is enabled in Magento, both an email from Magento and an email from Mailchimp are sent to confirm the subscription.

If double opt-in is disabled in Magento, no emails are received to confirm the subscription at all, the email is just subscribed right away (as expected)

Mandrill was installed in all cases, though this happened even with the Mandrill module disabled from the backend.

Expected result: Only 1 email sent to confirm the subscription when double opt-in is enabled in Magento.

**Comment by wigman** [comment]
SUPER hacky/temporary fix:
I commented line 449 in file /vendor/magento/module-newsletter/Model/Subscriber.php

```
        try {
            $this->save();
            if ($isConfirmNeed === true
                && $isOwnSubscribes === false
            ) {
                //$this->sendConfirmationRequestEmail(); <- commented out
            } else {
                $this->sendConfirmationSuccessEmail();
            }
            return $this->getStatus();
        } catch (\Exception $e) {
            throw new \Exception($e->getMessage());
        }
```

If I had more time on hand I would create a preference for this file and override 
```
    public function subscribe($email)
```
with this change (wrapped with a if-statement to check if mailchimp is enabled).

**Comment by lgrassini** [comment]
Hi guys, Any estimation of when this is going to be fixed? Thanks.

**Comment by ghost** [comment]
Seeing this same behavior with Magento 2.2.2 CE and M4M 1.0.25.

Is this a recognized bug that is going to be fixed in the next release?

**Comment by razvanmitre** [comment]
When is this planned for release?

**Comment by SantiParagarino** [comment]
Should be available by the end of January.

**Comment by TristanCICT** [comment]
Any updates yet?

**Comment by gonzaloebiz** [comment]
This issue was fixed with the pull request  https://github.com/mailchimp/mc-magento2/commit/4417b7f88a90e9d452be122f33f0561307d66c7b

**Comment by TristanCICT** [comment]
I'm sorry. I noticed after commenting and updated the module.
