### ISSUE TITLE
Cron_sceduler shows errors on cron

### ISSUE THREAD

**Issue by panthar1** [mailchimp/mc-magento2#911]
We are running magento 2.2.10 and having issues getting this module to work since update from 2.2.7. We are running 101.2.37 version of mc-magento2. I can see the cron(s) are not running successfully; please see the bottom for what is in the cron_scheduler table for the cron job(s). Additionally, our synchronization with mailchimp is not completing successfully, and we suspect it's related to these cron jobs. Any assistance would be much appreciated. Thank you!

Edit | Copy | Delete | 2664485 | ebizmarts_ecommerce | error | Error when running a cron job | 2019-10-28 14:42:03 | 2019-10-28 14:45:00 | 2019-10-28 14:45:03 | NULL | NULL | NULL | NULL | NULL | NULL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | Edit | Copy | Delete | 2664486 | ebizmarts_webhooks | error | Error when running a cron job | 2019-10-28 14:42:03 | 2019-10-28 14:45:00 | 2019-10-28 14:45:03 | NULL | NULL | NULL | NULL | NULL | NULL

**Comment by gonzaloebiz** [comment]
Hi @panthar1 

please contact our support team, we will be glad to help you.

Best
