### ISSUE TITLE
JS error on product page with slow internet

### ISSUE THREAD

**Issue by ihor-sviziev** [mailchimp/mc-magento2#912]
### Preconditions
1. Magento 2.3.2
2. Mailchimp module 102.3.36

### Steps to reproduce
1. Open  Google Chrome in incognito mode
2. Enable Developer tools > Network > Select "Slow 3g" connection
3. Navigate to product page
4. See console logs

### Actual result
We have JS error, can't add product to cart
![image](https://user-images.githubusercontent.com/1873745/68023901-4e9f8980-fcb1-11e9-9058-4d9eaef34f59.png)

### Expected result
We shouldn't have any JS errors, we should be able to add product to cart

### Additional information
This caused by missing dependency to jquery/ui library

**Comment by gonzaloebiz** [comment]
Hi @ihor-sviziev 

really thanks for find this.

**Comment by ihor-sviziev** [comment]
@gonzaloebiz I also looked for the same issue in other files and found:

https://github.com/mailchimp/mc-magento2/blob/a057ea114eb65a306b473b0b6dee7c938317ff62/view/adminhtml/web/js/apikey.js#L18

https://github.com/mailchimp/mc-magento2/blob/a057ea114eb65a306b473b0b6dee7c938317ff62/view/adminhtml/web/js/configapikey.js#L18

In these files we also don't have dependency. I think would be great to fix it also, however I never saw any issues in the admin

**Comment by gonzaloebiz** [comment]
> @gonzaloebiz I also looked for the same issue in other files and found:
> 
> https://github.com/mailchimp/mc-magento2/blob/a057ea114eb65a306b473b0b6dee7c938317ff62/view/adminhtml/web/js/apikey.js#L18
> 
> https://github.com/mailchimp/mc-magento2/blob/a057ea114eb65a306b473b0b6dee7c938317ff62/view/adminhtml/web/js/configapikey.js#L18
> 
> In these files we also don't have dependency. I think would be great to fix it also, however I never saw any issues in the admin

I will take a look at all the js.

Tanks

**Comment by gonzaloebiz** [comment]
@ihor-sviziev 

think all the js are fixed, thanks
