### ISSUE TITLE
Magento 2.1.8 - Installation failed error

### ISSUE THREAD

**Issue by gilbertsohal** [mailchimp/mc-magento2#92]
Preconditions:

Magento CE ver. 2.1.8
MailChimp for Magento mc-magento2-1.0.24
PHP 7.0

Steps to reproduce:
1.Download "MailChimp For Magento2" in ebizmarts
2. Install "MailChimp for Magento2" with Semi-manual installation
3. extract the contents in app/code/Ebizmarts/MailChimp
4. run composer command: composer require ebizmarts/mailchimp-lib

ERROR 
![screenshot](https://user-images.githubusercontent.com/29964872/30788357-81952f82-a1de-11e7-9623-cd4d3f4d8f87.jpg)

Expected result:
Install MailChimp for Magento2 without any error

Actual result:
Showing below error.

Screenshot 1
![screenshot](https://user-images.githubusercontent.com/29964872/30788357-81952f82-a1de-11e7-9623-cd4d3f4d8f87.jpg)

**Comment by gonzaloebiz** [comment]
This is not an error of the extension, recommend to run composer with -vvv

Best

**Comment by gilbertsohal** [comment]
@gonzaloebiz 
Thanks very much for your quick reply. Could you please explain i don't understand how to run composer with -vvv

**Comment by gonzaloebiz** [comment]
composer -vvv require ebizmarts/mailchimp-lib

**Comment by gilbertsohal** [comment]
@gonzaloebiz 

Hi @gilbertsohal
This issue does not seem to be related to Magento but to the Mailchimp extension. Please report issues with third-party extensions directly to their vendors.
Thank you

**Comment by gonzaloebiz** [comment]
You try run composer with -vvv?
Please paste the result

**Comment by gilbertsohal** [comment]
@gonzaloebiz Yes i run composer with -vvv. I got below error.

Error Screenshot
![mailchimp-error](https://user-images.githubusercontent.com/29964872/30941921-2cdcf3a4-a42b-11e7-8d5c-d1e607aed4b2.jpg)

**Comment by gonzaloebiz** [comment]
As you can see here https://github.com/ebizmarts/mailchimp-lib/blob/master/composer.json the mailchip-lib has no dependencies.
