### ISSUE TITLE
Performance cron ebizmarts_ecommerce

### ISSUE THREAD

**Issue by jmayoranotandil** [mailchimp/mc-magento2#93]
The cron ebizmarts_ecommerce has a performance problem when the customer/subscriber table is too large. The problem isn`t visible at first, but day by day the performance of the crons degrades.

The query with problems is

`SELECT e.*, m4m.* FROM customer_entity AS e LEFT JOIN mailchimp_sync_ecommerce AS m4m ON m4m.related_id = e.entity_id and m4m.type = 'CUS' and m4m.mailchimp_store_id = 'XXXXXX' WHERE (e.store_id = 1) AND (m4m.mailchimp_sync_delta IS null OR (m4m.mailchimp_sync_delta > '' and m4m.mailchimp_sync_modified = 1)) LIMIT 100`

To resolve this problem, we applied a simple INDEX on mailchimp_sync_ecommerce table like that:

`CREATE INDEX Related_Index_Sync_Ecommerce ON mailchimp_sync_ecommerce (related_id);`

**Comment by gonzaloebiz** [comment]
Thanks @jmayoranotandil for your contribution

**Comment by jugalpatelkrish** [comment]
Hi @jmayoranotandil  @gonzaloebiz

We have been facing a similar issue:  The query is 


`SELECT `e`.*, `m4m`.* FROM `catalog_product_entity` AS `e` LEFT JOIN `mailchimp_sync_ecommerce` AS `m4m` ON m4m.related_id = e.entity_id and m4m.type = 'PRO' and m4m.mailchimp_store_id = '5545f62327622582d93dc198c9f98c9b' WHERE (m4m.mailchimp_sync_delta IS null OR (m4m.mailchimp_sync_delta > '' and m4m.mailchimp_sync_modified = 1)) AND (e.created_in <= '1511331060') AND (e.updated_in > '1511331060') LIMIT 100;`

It takes around 14 seconds on our server to execute this query.  The server is well optimized still it takes so long.  Can we apply the same solution for this?

Thanks.
