### ISSUE TITLE
Mailchimp sync no longer syncing

### ISSUE THREAD

**Issue by Flipmediaco** [mailchimp/mc-magento2#930]
All orders since upgrade to Magento 2.3.3 & mailchimp/mc-magento2 102.3.37 remain with the label "Syncing" in Mailchimp sync column on order grid

### Preconditions

Syncing prior to upgrade was working correctly, order data was confirmed as being sent to Mailchimp via green tick icon in Mailchimp sync column, since upgrading all orders remain with the status "Syncing" with a red cross in a circle icon.

API credentials reset and validate correctly.

Remove Mailchimp Store and found I was no longer able to recreate the store due to the following error:-

Call to undefined method Ebizmarts\\MailChimp\\Helper\\Data::getUrl() in /vendor/magento/module-backend/App/AbstractAction.php:348

### Steps to reproduce

1. upgrade to Magento 2.3.3 & mailchimp/mc-magento2 102.3.37
2. Remove Mailchimp Store
3. Attempt to add Mailchimp Store

### Actual and Expected result

    Expected result:
    Mailchimp store created and order data sync'd to Mailchimp from Magento

    Actual result:
    500 error on saving Mailchimp store

### Additional information

Initially orders placed prior to upgrade showed status "rsyncing", from upgrade data no subscribers have been added to mailchimp.

**Comment by gonzaloebiz** [comment]
Hi @Flipmediaco 

can you please let us know from what version of magento and mc-magento2 you come?


> All orders since upgrade to Magento 2.3.3 & mailchimp/mc-magento2 102.3.37 remain with the label "Syncing" in Mailchimp sync column on order grid
> 
> ## Issue Description
> ### Preconditions
> Syncing prior to upgrade was working correctly, order data was confirmed as being sent to Mailchimp via green tick icon in Mailchimp sync column, since upgrading all orders remain with the status "Syncing" with a red cross in a circle icon.
> 
> API credentials reset and validate correctly.
> 
> Remove Mailchimp Store and found I was no longer able to recreate the store due to the following error:-
> 
> Call to undefined method Ebizmarts\MailChimp\Helper\Data::getUrl() in /vendor/magento/module-backend/App/AbstractAction.php:348
> 
> ### Steps to reproduce
> 1. upgrade to Magento 2.3.3 & mailchimp/mc-magento2 102.3.37

From what version of magento and mc-magento2 you come?

> 2. Remove Mailchimp Store
> 3. Attempt to add Mailchimp Store
> 
> ### Actual and Expected result
> ```
> Expected result:
> Mailchimp store created and order data sync'd to Mailchimp from Magento
> 
> Actual result:
> 500 error on saving Mailchimp store
> ```
> 
> ### Additional information
> Initially orders placed prior to upgrade showed status "rsyncing", from upgrade data no subscribers have been added to mailchimp.

**Comment by Flipmediaco** [comment]
Prior Version Combinations:-
magento/magento2-base 2.2.7 - mailchimp/mc-magento2 1.0.32
magento/magento2-base 2.2.9 - mailchimp/mc-magento2 101.2.36
magento/magento2-base 2.3.3 - mailchimp/mc-magento2 102.3.37

**Comment by Flipmediaco** [comment]
The error returned on attempting to "Save" via create new mailchimp store:- 

```
Fatal error: Uncaught Error: Call to undefined method Ebizmarts\MailChimp\Helper\Data::getUrl() in /vendor/magento/module-backend/App/AbstractAction.php:348
Stack trace:
#0 /generated/code/Ebizmarts/MailChimp/Controller/Adminhtml/Stores/Save/Interceptor.php(63): Magento\Backend\App\AbstractAction->getUrl('adminhtml/dashb...', Array)
#1 /vendor/magento/module-backend/App/AbstractAction.php(319): Ebizmarts\MailChimp\Controller\Adminhtml\Stores\Save\Interceptor->getUrl('adminhtml/dashb...', Array)
#2 /vendor/magento/module-backend/App/AbstractAction.php(281): Magento\Backend\App\AbstractAction->_redirect('adminhtml/dashb...')
#3 /generated/code/Ebizmarts/MailChimp/Controller/Adminhtml/Stores/Save/Interceptor.php(50): Magento\Backend\App\AbstractAction->_processUrlKeys()
#4 / in /vendor/magento/module-backend/App/AbstractAction.php on line 348
```

Thanks

**Comment by gonzaloebiz** [comment]
Hi @Flipmediaco 

i just try installing magento 2.2.9 and mailchimp 101.2.36 and then upgrade to magento 2.3.3 and mailchimp 102.3.37 and works OK for me
Also search all the code, and we never use helper->getUrl function

What method did you use to install the extension?
Check the file permission

Best

**Comment by Flipmediaco** [comment]
Installed via module composer:

`composer require mailchimp/mc-magento2 --no-update`

_I was able to get past 500 error creating mailchimp store by reseting permissions - sorry I should have checked._

**At this point our instance is still not syncing with mailchimp, having reset the API and deleted / recreated the mailchimp store. All orders in range of "Ecommerce Configuration" "First Date" are showing "Mailchimp Sync" of "Syncing".**

I have reset errors and cron is running correctly...

Any advice on how to debug why this is not working will be taken and actioned.

Thanks

**Comment by gonzaloebiz** [comment]
Check the mailchimp_sync_ecommerce table for theses orders.
For this, select type = 'ORD' and related_id = theidofyourorder
Look for the batch_id column and then search this batch in the mailchimp_sync_batches table and look at the status of the batch.
What status has the batch?

**Comment by Flipmediaco** [comment]
I have traced the batch for a couple of orders, these all shows as complete in mailchimp_sync_batches. In fact everything looks in order... But I would appreciate your feedback. In the following example the icon and feedback in the mailchimp sync column remains the red cross in the circle labeled as "Syncing", the data is as follows.

Example:

Order: 000009102 (order_id/**7285**)
--
mailchimp_sync_ecommerce
--
Id: 23722
mailchimp_store_id: e522ca09ef6c69bfda2e49ad84d98e22
type: ORD
related_id: **7285**
mailchimp_sync_modified: 1
mailchimp_sync_delta: 2019-11-11 18:25:05
mailchimp_sync_error: NULL
mailchimp_sync_deleted: NULL
mailchimp_token: NULL
batch_id: **_66289e95af_**
deleted_related_id: NULL
mailchimp_sent: 2

mailchimp_sync_batches
--
id: 947
store_id: 1
mailchimp_store_id: e522ca09ef6c69bfda2e49ad84d98e22
batch_id: **_66289e95af_**
status: completed
modified_date: 2019-11-11 18:35:03

<img width="323" alt="Screenshot 2019-11-20 at 18 30 49" src="https://user-images.githubusercontent.com/1518211/69266893-f67ae980-0bc3-11ea-8daf-37f99dd0f135.png">

**Comment by gonzaloebiz** [comment]
Take a look at https://github.com/mailchimp/mc-magento2/issues/140
As you can see, the + symbol means that your order was never synced, but... you have registers in the mailchimp_sync_ecommerce table for this order (as your order is modified, should have 
![image](https://user-images.githubusercontent.com/6222792/69346212-32a85b80-0c51-11ea-8f5d-51d962f5279c.png) icon)
... so are you sure that the mailchimp_store_id is the one that you have configured in the configuration page? (go to the configuration page, and in the mailchimp store combo right click and select inspect element, then search for the selected attribute)

Best

**Comment by Flipmediaco** [comment]
Thanks for taking the time. I removed all configuration and rebuilt. I can see that orders are now being cued for syncing and have the "waiting" icon as per your prior message. I suspect an issue between our staging instance and production instance was at fault it. Hopefully I will be able to report normal operation once orders advance to "Syncd".

**Comment by gonzaloebiz** [comment]
OK, i close the issue now, if you need further help, contact our support.

Best
