### ISSUE TITLE
[Performance Issue] HTTP calls to mailchimp on every page request and config cache flush

### ISSUE THREAD

**Issue by IvanChepurnyi** [mailchimp/mc-magento2#939]
The module does HTTP calls on every page when the extension is just installed and not yet all JS URLs are fetched. The code behind a problem is this helper [method](https://github.com/mailchimp/mc-magento2/blob/develop/Helper/Data.php#L840). 

This URL retrieval for JS should have been done via cronjob and storing URL should be done in an own database table. Updating store configuration triggers a complete configuration rebuild that results in a disaster under high load.

### Preconditions
1. Clean Magento 2.3.3
2. Recent Mailchimp extension version installed but not configured
3. Blackfire code profiler installed and configured

### Steps to reproduce
1. Profile any page with Blackfire
2. Open generated profile and check the call stack of the mentioned method

### Expected result

- No HTTP calls 
- No updates to core_config_data

### Actual results
- HTTP call to Mailchimp API 
- Complete wipe-out of configuration cache on the frontend

**Comment by gonzaloebiz** [comment]
Hi @IvanChepurnyi 

thanks for your feedback.
Please take a look at https://github.com/mailchimp/mc-magento2/pull/891 this is already fixed and will be available on next release

Best

**Comment by IvanChepurnyi** [comment]
The mentioned pull request does not address main issue with configuration cache wipe out on frontend and update of `core_config_data` table.
