### ISSUE TITLE
Can't save API Key

### ISSUE THREAD

**Issue by swimmer-zone** [mailchimp/mc-magento2#944]
## Issue Description

If I try to save the API Key in Mailchimp > Configuration, I get the following error in the console: `data.stores is undefined`, because the corresponding AJAX call just returns `{"valid":1}`, which seems right, because I haven't created any Mailchimp Stores yet.

However, if I try to create a Mailchimp Store, I can't save that, because I haven't saved the API-key.

### Preconditions

It happens on Magento CE 2.3.3 with version 102.3.37 of mailchimp/mc-magento2

## Steps to reproduce

1. Login in Magento admin and go to Mailchimp > Configuration
2. Obtain an API Key from Mailchimp
3. Paste it in the API Key field
4. Save

## Expected result

The API Key is saved.

## Actual result

Now the loader keeps spinning, because of the error in the console.

## Possible solution

In the following code, add a check if data.stores is not undefined:

```javascript
$.ajax({
    url: storeUrl,
    data: {'form_key':  window.FORM_KEY, 'apikey': apiKey, 'encrypt': 0},
    type: 'GET',
    dataType: 'json',
    showLoader: true
}).done(function (data) {
    if (data.valid==1) {
        var unique = data.stores.length;
        $.each(data.stores, function (i, item) {
            if (unique == 1) {
                $('#mailchimp_general_monkeystore').append($('<option>', {
                    value: item.id,
                    text: item.name,
                    selected: "selected"
                }));
            } else {
                $('#mailchimp_general_monkeystore').append($('<option>', {
                    value: item.id,
                    text: item.name
                }));
            }
        });
        if ($('#mailchimp_general_monkeystore option').length > 1) {
            $('#row_mailchimp_general_monkeystore').find('.note').hide();
        } else {
            $('#row_mailchimp_general_monkeystore').find('.note').show();
        }
        self._loadDetails();
    } else {
        alert({content:data.errormsg});
    }
});
```

**Comment by gonzaloebiz** [comment]
Hi @Yupsie 

please take a look at https://github.com/mailchimp/mc-magento2/issues/940

Best
