### ISSUE TITLE
Subscriber "Not activated" in Magento even after email confirmation

### ISSUE THREAD

**Issue by viniciusfabri** [mailchimp/mc-magento2#945]
### Preconditions

    1. Magento EE 2.3.3 is installed
    2. mc-magento2 102.3.37
    3. Double opt-in is enabled in MAilchimp (and * Magento always manage emails* is *No*)
    4. *Enable Two Way Sync: Yes*

### Steps to reproduce

    1. Navigate to homepage as a guest.
    2. Try to subscribe
    3. You get the confirmation email, click on the confirmation link

### Actual and Expected result

    Expected result: Customer appears as Subscribed on both Magento and Mailchimp
    Actual result: User appears as "Not Activated" on Magento and Subscribed in Mailchimp

### Additional information

Because of this, when the user tries to subscribe again in the Guest form, the "duplicated" error is not shown

**Comment by gonzaloebiz** [comment]
Hi @viniciusfabri 

sorry but i don't understand. The expected and actual results are the same?
The confirmation of the subscription when you click in the email is made via webhook, look at https://github.com/mailchimp/mc-magento2/blob/develop-2.3/Controller/WebHook/Index.php
Once the webhook is received is saved in a table and processed via cron on this https://github.com/mailchimp/mc-magento2/blob/develop-2.3/Cron/Webhook.php

So, please confirm 
  1. that your site is accessible from any location (if your installation is local or protected, the webhooks don't work)
  2. you already configured the cron for your installation (take a look at https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-cron.html)

Best

**Comment by viniciusfabri** [comment]
Hi @viniciusfabri ,
My bad, updated the description

As for webhooks, if the site has HTTP basic auth (as it has in our case), is there a way to work around it? The site is not yet ready to be live but we want to test this functionality before going live

**Comment by gonzaloebiz** [comment]
No, the site must be open to make the webhooks works, sorry
