### ISSUE TITLE
New release for 2.3.x?

### ISSUE THREAD

**Issue by viniciusfabri** [mailchimp/mc-magento2#949]
Hi,

We were facing #920 on our site and since this ticket is not on a new release yet, I tried to apply a patch for that PR, but it seems the code is behind by some commits and I'd have to apply quite a few patches for it to work. I was wondering if there were any plans of generating a new release from develop-2.3 with these new fixes, since the last one is from September?

We are using Magento EE 2.3.3 and Mailchimp 102.3.37

Or maybe we could use develop-2.3 as our version, but I'm not sure how stable that is and what your recommendation is

**Comment by gonzaloebiz** [comment]
Hi @viniciusfabri 

we are trying to release a new version this month

Best

**Comment by bizlift** [comment]
Is develop-2.3 branch safe to use temporarily until next release?

**Comment by viniciusfabri** [comment]
@bizlift I noticed a bug when creating a webhook and showing the success message, but it created the webhook successfully. The subscription flow seems to be working fine (testing is still in progress), and we are only using this feature, so I can't say for sure about the other functionalities, you might want to do a full regression on your end too

For reference we are on commit b68ad51eea6045a89552b5a01be39d6c4e539362

**Comment by bizlift** [comment]
> Hi @viniciusfabri
> 
> we are trying to release a new version this month
> 
> Best

Just checking in on estimated release.  It's been 2 months now.
