### ISSUE TITLE
getting credential key

### ISSUE THREAD

**Issue by arvin-narvaez** [mailchimp/mc-magento2#951]
Hi,

i have issue when i get credential key after i paste the key is only loading and i see the console have issue. see the image below.

![image](https://user-images.githubusercontent.com/58678342/72048695-548c9900-32f8-11ea-9181-6b29283e3c4e.png)

**Comment by gonzaloebiz** [comment]
Hi @arvin-narvaez 

please follow the [issue reporting guidelines](https://github.com/mailchimp/mc-magento2/wiki/Issue-reporting-guidelines)

Best
