### ISSUE TITLE
Magento2 and Mailchimp: This MailChimp account is not connected to Magento.

### ISSUE THREAD

**Issue by onepack** [mailchimp/mc-magento2#955]
A customer is using:
Magento2.3 
Mailchimp v1.3.33 by ebizmarts.

Magento is one website and multistore.

I enabled the list etc. for one storeview.
All info is visible but the status remains:
This MailChimp account is not connected to Magento.

Please advice why this happens.

**Comment by gonzaloebiz** [comment]
Hi @onepack 

you must enable the ecommerce option

Best

**Comment by onepack** [comment]
Ok, thank you for your fast reply. It seems to do the trick! I don't know why this e-commerce option is needed for the subscribers to sync buy hey, it works so I'm happy.

**Comment by lfolco** [comment]
What if we don't want to use the e-commerce functionality?

**Comment by gonzaloebiz** [comment]
Hi @lfolco,

the subscribers are synced if you enable the integration in your store, you don't need to enable the e-commerce, but the message refers to the connection between your magento and your MailChimp store

Best

**Comment by lfolco** [comment]
Okay, thank you!
