### ISSUE TITLE
Update required dependency for those using magento/product-community-edition

### ISSUE THREAD

**Issue by olivercastro** [mailchimp/mc-magento2#956]
###  Issue Description
Module installation using composer would throw an error due to required dependency for **magento/framework 102.0.*** 

### Preconditions
Installed Magento 2.2.10 using composer. Added the Mailchimp module by executing
`composer require mailchimp/mc-magento2 `

### Actual Result

` - Installation request for magento/product-community-edition 2.2.10 -> satisfiable by magento/product-community-edition[2.2.10].
    - mailchimp/mc-magento2 102.3.34 requires magento/framework 102.0.* -> satisfiable by magento/framework[102.0.0, 102.0.1, 102.0.2, 102.0.3, 102.0.2-p2, 102.0.4, 102.0.3-p1].
    - mailchimp/mc-magento2 102.3.35 requires magento/framework 102.0.* -> satisfiable by magento/framework[102.0.0, 102.0.1, 102.0.2, 102.0.3, 102.0.2-p2, 102.0.4, 102.0.3-p1].
    - mailchimp/mc-magento2 102.3.36 requires magento/framework 102.0.* -> satisfiable by magento/framework[102.0.0, 102.0.1, 102.0.2, 102.0.3, 102.0.2-p2, 102.0.4, 102.0.3-p1].
    - mailchimp/mc-magento2 102.3.37 requires magento/framework 102.0.* -> satisfiable by magento/framework[102.0.0, 102.0.1, 102.0.2, 102.0.3, 102.0.2-p2, 102.0.4, 102.0.3-p1].
`

### Expected Result

Should be able to install Mailchimp on Magento 2.2.10

**Comment by SantiParagarino** [comment]
Hello @olivercastro 
Thanks for reaching us.
You are installing the wrong version, we have one per each Magento (2.1.x, 2.2.x, 2.3.x)
Please note we have an explanation on which version of Mailchimp for Magento can be installed in which Magento version as well as the commands required for it to be installed at https://github.com/mailchimp/mc-magento2/releases
