### ISSUE TITLE
it seems couldn't compatible with magento 2.3.3

### ISSUE THREAD

**Issue by chenghuili** [mailchimp/mc-magento2#957]
I installed the latest mailchimp and I didn't install any the third party of extension. 
the is not API Key list field, only API Key field. and when I type api key, it always notice API Key Invalid. 
and I also couldn't create mailchimp store.

**Comment by SantiParagarino** [comment]
Hello @chenghuili 
Please read our doc on how to install the extension.
Each github release includes an explanation on how to install each version.

Kind Regards,
Santiago Paragarino
