### ISSUE TITLE
Problems when installing Magento extensions with "composer install -o"

### ISSUE THREAD

**Issue by SantiParagarino** [mailchimp/mc-magento2#959]
## Issue Description
Ref.: https://ebizmarts-desk.zendesk.com/agent/tickets/29987

### Preconditions
Tested with Magento 2.3.3 installed manualy and Mailchimp for Magento 102.3.37 installed via composer.

### Steps to reproduce
1. Install Mailchimp for Magento version 102.3.37
2. run composer install -o on Magento root folder.

### Expected result
Magento works without issues.

### Actual result
When trying to run **php bin/magento** commands an error is thrown:
![Screen Shot 2020-02-07 at 12 07 39](https://user-images.githubusercontent.com/8330778/74040419-74b88200-49a2-11ea-8715-902911877781.png)

**Comment by SantiParagarino** [comment]
Should be tested with Magento 2.1 and 2.2

**Comment by gonzaloebiz** [comment]
This is not an issue with the extension, it is a bad use of composer.
For use the -o parameter you need to do this:

- composer -o require mailchimp/mc-magento2:xxx.x.xx
- composer dump-autoload -o
- bin/magento setup:upgrade

Best
