### ISSUE TITLE
Customer DOB doesn't include the year.

### ISSUE THREAD

**Issue by olivercastro** [mailchimp/mc-magento2#961]
###  Issue Description
Customer DOB only gets the first 3 characters of the date format

### Additional information

The offending code can be found on line line 632 of class vendor/mailchimp/mc-magento2/Helper/Data.php

https://imgur.com/a/KPq1zmI

**Comment by gonzaloebiz** [comment]
Hi @olivercastro 

the DOB in mailchimp doesn't include the year, this is why.
Look the mailchimp form
![image](https://user-images.githubusercontent.com/6222792/74155868-0834c180-4bf4-11ea-8b64-e54f8eace1f8.png)
