### ISSUE TITLE
Sales Mailchimp Column Not Filterable Or Exportable

### ISSUE THREAD

**Issue by BreezeMaxWeb-NS** [mailchimp/mc-magento2#962]
When you go to Sales -> Orders in Magento 2 you can see 2 columns, Mailchimp and Mailchimp Sync, but they have the following issues:

- If you click on them you can't sort the orders,
- If you go to filters you are unable to show only Mailchimp orders.
- If you click export CSV there is a Mailchimp column in the export file, but there is never any data populated.

These issues make it very hard to do analytics on Mailchimp orders.

**Comment by barryvdh** [comment]
Did you find an issue for this?

**Comment by gonzaloebiz** [comment]
Look at #1981
