### ISSUE TITLE
Cannot load All Customers in Admin panel if module disabled

### ISSUE THREAD

**Issue by tarasyyyk** [mailchimp/mc-magento2#967]
## Issue Description
An error occurred when trying to load Customer grid in Admin panel with disabled module.
Error is: `Error occurred when creating object: Magento\\Eav\\Model\\Entity\\Attribute\\Source\\Config`.

## Preconditions
Tested with Magento Community Edition 2.3.2, module installed via composer (v.102.3.37).

## Steps to reproduce
Install and enable module _Ebizmarts_MailChimp_.
Run `setup:upgrade`.
Go to Admin panel > Customers > All customers. Grid is loading correct.
Disable module _Ebizmarts_MailChimp_.
Run `setup:upgrade`, `setup:di:compile`.
Clean all caches.
Go to Admin panel > Customers > All customers. Error occurred.

**Expected result:**
Grid is loading with all Customers in system.
**Actual result:**
Showing error page. In reports logs error with stack trace.

## Additional information
This is caused by customer attribute mailchimp_store (?) created by this module. This attribute caused problem when system tries to load this attribute.
It would be good to change module logic so when it disabled it isn't crashed system.

**Comment by gonzaloebiz** [comment]
Hi @tarasyyyk 

can you please specify version of magento and mc-magento2?

**Comment by tarasyyyk** [comment]
Hi @gonzaloebiz . Updated issue description according to guidelines.

**Comment by gonzaloebiz** [comment]
Hi @tarasyyyk 

i can't replicate your issue.
Please try to give more info to replicate

Best
