### ISSUE TITLE
Wrong product image path

### ISSUE THREAD

**Issue by killday** [mailchimp/mc-magento2#968]
### Preconditions

    1. Magento CE 2.2.0
    2. mc-magento2 1.2.33.
   

### Steps to reproduce
Magento root directory is set to /pub as per recommendations by https://devdocs.magento.com/guides/v2.3/install-gde/tutorials/change-docroot-to-pub.html

Sync products to mailchimp.
### Actual 
Images not showing in mailchimp as their URL includes /pub directory in URL like https://www.dev.zenithsecurityco.co.uk/pub/media/catalog/product/cache/0d5164699863645cb07eac70d269722a/n/v/nvr8_7580_8_left_3_1_.png

###Expected result
Correct URL address https://www.dev.zenithsecurityco.co.uk/media/catalog/product/cache/0d5164699863645cb07eac70d269722a/n/v/nvr8_7580_8_left_3_1_.png

**Comment by gonzaloebiz** [comment]
Please look at https://github.com/mailchimp/mc-magento2/issues/169

**Comment by killday** [comment]
I can confirm that this solved the problem:
Many users on that thread report that following works for accessing the images.
{{unsecure_base_url}}media/
{{secure_base_url}}media/

Just need to delete the store, create new one and resync data.
Thanks.
