### ISSUE TITLE
Chrome wrongly autofills Magento admin passwords in API field

### ISSUE THREAD

**Issue by loekvangool** [mailchimp/mc-magento2#970]
### Preconditions

1. Magento CE 2.3.4 without sample data is installed.
2. mc-magento2 102.3.37 configured with a valid API key

### Steps to reproduce

1. Configure the extension as usual
2. Open the extension admin in Chrome
3. Chrome will prefill the admin password in the API field, causing an error every time and sending the password to Mailchimp's API endpoint.

### Actual and Expected result

Probably best to add `autocomplete="off"` to the API key field to prevent annoying errors and credential leaks.

### Additional information

![image](https://user-images.githubusercontent.com/7300472/75338526-21459f80-588f-11ea-8e13-5ae6fda942da.png)

**Comment by gonzaloebiz** [comment]
Hi @loekvangool 

this is a known issue with chrome.
Chrome auto-fill the field, we already try various fixes and chrome ignore the autocomplete, take a look at https://stackoverflow.com/questions/15738259/disabling-chrome-autofill

Best
