### ISSUE TITLE
Multiple emails for order confirmation

### ISSUE THREAD

**Issue by killday** [mailchimp/mc-magento2#971]
### Preconditions

Example:

    1. Magento CE 2.2.0 without sample data is installed.
    2. mc-magento2 1.2.33
    3. Magento always manage emails

### Steps to reproduce

    1. User or Admin create order
 
### Actual and Expected result

   Expected result:
   Send One confirmation email.
    Actual result:
    Sends 3 confirmation emails.

### Additional information

Starts as soon as we install the extension.

**Comment by gonzaloebiz** [comment]
Hi @killday 

please update the extension to the current version (101.2.37)

Best

**Comment by killday** [comment]
Hi @gonzaloebiz 

That doesn't help. Now there been 4 emails.

**Comment by gonzaloebiz** [comment]
Hi @killday 

we test your case, and work ok, we need more info to try to replicate

**Comment by killday** [comment]
What info you need ?

**Comment by gonzaloebiz** [comment]
I don't know, with the replication steps that you provide we can't replicate it.
I don't know your email configuration, or if you have some extension to manage the emails

**Comment by killday** [comment]
Hi @gonzaloebiz 
The only extension for emails we use is mageplaza smtp. 
I've made a test and disabled mc-magento2, make an order and receive only one confirmation email as normal.
