### ISSUE TITLE
Add Phone Number to Customer Fields Mapping

### ISSUE THREAD

**Issue by tanolalano** [mailchimp/mc-magento2#974]
Hi all,
this is a feature request about Customer Fields Mapping.
Magento stores Account information in 'customer_entity' table that is shown on dropdown Magento in Customer Fields Mapping of Mailchimp general configuration. (see attached img)
![Schermata 2020-03-07 alle 07 36 08](https://user-images.githubusercontent.com/4384863/76138248-5ba8fc80-6046-11ea-8a40-919989442f7d.png)
Because Phone number is stored in another table (customer_address_entity) it isn't show on Magento dropdown.
As Dropdown show 'shipping address or 'billing address' there is a way to split or to get phone number to sync to my mailchimp Audience?
I know that programmatically I have to add custom attribute (phone) to Account information to show on Customer Fields Mapping in Magento dropdown, but this get duplicated information. 

Kindy regards
David

**Comment by gonzaloebiz** [comment]
Hi @tanolalano 

please take a look at https://github.com/mailchimp/mc-magento2/issues/1025

Best
