### ISSUE TITLE
API Key list field missed

### ISSUE THREAD

**Issue by chenghuili** [mailchimp/mc-magento2#975]
I have tried many times to installed mailchimp via composer on magento 2.3, but it always missed API Key list field, I don't know where is mistake.
![1583560332206](https://user-images.githubusercontent.com/14212956/76140738-72783f00-6098-11ea-89ae-4b30a3d76d21.jpg)
![apiKeyList](https://user-images.githubusercontent.com/14212956/76140752-7dcb6a80-6098-11ea-824b-15b660c78afd.png)

**Comment by gonzaloebiz** [comment]
The API Key list changes a couple of versions before (you can search in the changelog) and is not there anymore.
