### ISSUE TITLE
Customer Fields Mapping boxes have a tiny height/font-size?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [mailchimp/mc-magento2#978]
### Preconditions

1. Magento CE 2.3.2 is installed without sample data.
2. Installed mc-magento 102.3.37
3. I am using a Mailchimp login that was invited to the project on Mailchimp as an Admin.
4. Configured API Key and Store, subscriber shows up but name not set/mapped.

### Steps to reproduce
1. Login to Magento admin area and goto Mailchimp general config.
2. Attempt to configure Customer Fields Mapping.

### Actual and Expected result

Expected result:
To be able to select fields from drop down selects.

Actual result:
Select boxes are unreadable/unusable due to their height?
![image](https://user-images.githubusercontent.com/1968109/76489612-c5356a80-648d-11ea-82ef-0af69d98fa99.png)

Additional Info:

Dom does appear to have data.

![image](https://user-images.githubusercontent.com/1968109/76489634-d41c1d00-648d-11ea-81d0-d6b8c9a54c3a.png)

If I delete styles.css they show up fine.

Caused by font: inherit on select, textarea, block-footer etc

```css
button,
input,
optgroup,
select,
textarea,
.block-footer .action-add {
  /* color: inherit; */
  /* font: inherit; */
  /* margin: 0; */
}
```
If I comment out font: inherit its good. (This site i'm working on should be mostly default admin css to my knowldge it's a pretty fresh install + weltpixel/pearl theme.)

![image](https://user-images.githubusercontent.com/1968109/76489807-54428280-648e-11ea-9135-9589789210a9.png)

**Comment by gonzaloebiz** [comment]
Hi @LiamKarlMitchell 

what browser are you using?
