### ISSUE TITLE
Abandoned cart e-mail - wrong product name language store id

### ISSUE THREAD

**Issue by samuelmafra** [mailchimp/mc-magento2#979]
We have multi-website stores in different domains, languages and currencies. The emails sent from the abandoned cart show the currency and image correctly, but the language of the product name is incorrect (show default product name). Someone experiencing the same problem?

**Comment by gonzaloebiz** [comment]
Are you using a mailchimp store for each magento store?

**Comment by samuelmafra** [comment]
Yes, each magento store use different mailchimp store.

**Comment by gonzaloebiz** [comment]
What version of the extension are you using?

**Comment by samuelmafra** [comment]
1.0.29

**Comment by gonzaloebiz** [comment]
This is a really old version of the extension, please update it

**Comment by samuelmafra** [comment]
Thank you
