### ISSUE TITLE
Requested country is not available.

### ISSUE THREAD

**Issue by killday** [mailchimp/mc-magento2#981]
### Preconditions
Magento 2.2.0
Mailchimp v101.2.37

### Steps to reproduce
Disable the extension for 30 days - in that period there been new orders and customers all from the same country.
Enable the extension and add new products.

Expected result:
All new products, customers and orders sync in.

 Actual result:
No sync. 
Error:
Requested country is not available error message in the cronjob table for the ecommerce data.

**Comment by killday** [comment]
Update:
1. Delete and recreate store. Same result.
2. Enable all countries. ecommerce cronjob success. No data in Mailchimp

**Comment by gonzaloebiz** [comment]
Typically this happens when you import orders, look at the country id for these orders(keep in mind, the country id is the ISO 3166 ALPHA-2)

best

**Comment by killday** [comment]
So what is the solution here ? I need the products not the orders.

**Comment by gonzaloebiz** [comment]
Fix the country id in the orders

**Comment by killday** [comment]
I haven't import any orders.
