### ISSUE TITLE
Completed orders sometimes receiving abandoned cart emails - associated quotes failing to sync with "Resource Not Found : The requested resource could not be found"

### ISSUE THREAD

**Issue by samsteele** [mailchimp/mc-magento2#982]
We're seeing abandoned cart emails being sent out to customers that have completed their orders. For these orders, the `ebizmarts_ecommerce` cron containing the quote completes succesfully but there are entries in the `mailchimp_errors` table stating that the associated quote failed to sync with a 404 "The requested resource could not be found" error.

### Preconditions

- magento/product-community-edition @ 2.3.4
- mailchimp/mc-magento2 @ 102.3.37
- ebizmarts/mailchimp-lib @ 3.0.31

### Steps to reproduce

Not known, seems random, hoping you can advise.

### Actual and Expected result

Expected Result -
When an order is placed, the associated quote is deleted from Mailchimp which prevents an abandoned cart email being sent out.

Actual Result -
When an order is placed, the associated quote is sometimes not deleted from Mailchimp and the customer receives an abandoned cart email for an order that they completed.

### Additional information

Example of some errors from the `mailchimp_sync_ecommerce` table attached. All associated quotes are intact and marked inactive.
[mailchimp_sync_ecommerce_errors.zip](https://github.com/mailchimp/mc-magento2/files/4416111/mailchimp_sync_ecommerce_errors.zip)

**Comment by gonzaloebiz** [comment]
can't reproduce
