### ISSUE TITLE
Issue syncing DOB merge field

### ISSUE THREAD

**Issue by vDeggial** [mailchimp/mc-magento2#987]
### Preconditions

Magento CE 2.3.2-p2
Mailchimp Plugin version 102.3.38

### Steps to reproduce

- Add Date of Birth as merge field in the config
- Wait for sync

### Expected result

Customers and Subscribers sync fine

### Actual Result
Mailchimp error:
"status_code": 400,
        "operation_id": "CUS_1587148268_2021_SUB",
        "response": {
            "type": "http:\/\/developer.mailchimp.com\/documentation\/mailchimp\/guides\/error-glossary\/",
            "title": "Invalid Resource",
            "status": 400,
            "detail": "Your merge fields were invalid.",
            "instance": "",
            "errors": [
                {
                    "field": "DOB",
                    "message": "Please enter a month (01-12) and a day (01-31)"
                }
            ]
        }

### Additional information

Did not have this issue in previous Mailchimp plugin versions

**Comment by vDeggial** [comment]
It appears that the Date of Birth is not being formatted to MM/DD but the actual value of YYYY-MM-DD is being sent and thus rejected by API

**Comment by vDeggial** [comment]
Upon looking further it seems that Date of Birth is not being designated as IsDate and change in getCustomerAtts() method in last version

from
```
$isDate = ($item->getBackendModel()=='Magento\Eav\Model\Entity\Attribute\Backend\Datetime') ? 1:0;
                $isAddress = ($item->getBackendModel()=='Magento\Customer\Model\Customer\Attribute\Backend\Billing' ||
                    $item->getBackendModel()=='Magento\Customer\Model\Customer\Attribute\Backend\Shipping') ? 1:0;

```
to

```
$isDate = ($item->getBackendModel()==Magento\Eav\Model\Entity\Attribute\Backend\Datetime::class) ? 1:0;
                $isAddress = (
                    $item->getBackendModel()==Magento\Customer\Model\Customer\Attribute\Backend\Billing::class ||
                    $item->getBackendModel()==Magento\Customer\Model\Customer\Attribute\Backend\Shipping::class) ? 1:0;
```

seems to be the issue

**Comment by gonzaloebiz** [comment]
Hi @vDeggial 

thanks for your feedback.
Please take a look at the associated PR

Best

**Comment by vDeggial** [comment]
> Hi @vDeggial
> 
> thanks for your feedback.
> Please take a look at the associated PR
> 
> Best

@gonzaloebiz anytime :) glad to help :)
