### ISSUE TITLE
Version Related Issue

### ISSUE THREAD

**Issue by jerryvasoya338** [mailchimp/mc-magento2#99]
I was latest mail chimp 1.0.24 download and install and then my web is error genrate is some choking..
my web is error genrating is "

> Ebizmarts_MailChimp schema: current version - 1.0.23, required version - 1.0.24

" so you can check and new latest version uploads again plz..

**Comment by EthicalErik** [comment]
Have you ran:
composer update
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy
php bin/magento setup:di:compile
php bin/magento indexer:reindex
php bin/magento cache:flush
php bin/magento cache:clean

**Comment by gonzaloebiz** [comment]
that is not an issue
