### ISSUE TITLE
Eternal Spinning gif after invalid API key has been entered in the configuration

### ISSUE THREAD

**Issue by roberto-ebizmarts** [mailchimp/mc-magento2#990]
## Eternal Spinning gif after invalid API key has been entered in the configuration

> Eternal Spinning gif after invalid API key has been entered in the configuration

### Preconditions
    1. Magento CE 2.3
    2. mc-magento2 102.3.38

### Steps to reproduce

    1. Navigate to Mailchimp for Magento configuration.
    2. Enable the extension. 
    3. Type an invalid API key in the **API Key** field
    4. Click outside the  **API Key** field

### Actual and Expected result

    Expected result:
    Some message indicating the API key is invalid after some seconds of spinning.

    Actual result:
    Eternal spinning

### Additional information

Reference: https://ebizmarts-desk.zendesk.com/agent/tickets/31388

See image below of unexpected result:
![image](https://user-images.githubusercontent.com/51710909/80113514-cc559b00-8558-11ea-94b2-f9c3bf8ced17.png)

**Comment by gitbjorn** [comment]
This also seems to happen with a valid key after clicking 'Resync Subscribers'. The javascript console shows:

configapikey.js:66 Uncaught TypeError: alert is not a function
    at Object.<anonymous> (configapikey.js:66)
    at fire (jquery.js:3238)
    at Object.fireWith [as resolveWith] (jquery.js:3368)
    at done (jquery.js:9846)
    at XMLHttpRequest.callback (jquery.js:10317)

**Comment by pauldonnelly** [comment]
I am having the same issue on 2.3.4. When will this fix be released? it's not in Version 102.3.38

**Comment by gonzaloebiz** [comment]
look at https://github.com/mailchimp/mc-magento2/pull/991
