### ISSUE TITLE
Can't create webhook in admin with Magento Cloud Staging Environment

### ISSUE THREAD

**Issue by jonaschen623** [mailchimp/mc-magento2#994]
Try create webhook in admin, receive error message as below.
![image](https://user-images.githubusercontent.com/1915539/80766048-99cf2200-8b98-11ea-92ca-8b2120d348e8.png)
![image](https://user-images.githubusercontent.com/1915539/80766086-aeabb580-8b98-11ea-95dd-0282db6b5b2d.png)

And on MailChimp, no webhook is generated.
![image](https://user-images.githubusercontent.com/1915539/80766215-fcc0b900-8b98-11ea-8fb2-2d7b53fbaef4.png)

Notice:
**This issue only occurs on staging environment, integration/vendor environment is working.**
![image (2)](https://user-images.githubusercontent.com/1915539/80766444-8cfefe00-8b99-11ea-8d68-62aef6680c6d.png)

From staging server log
MailChimpLogger.INFO: An empty request comes from ip: ****

Manually create webhook in MailChimp account. Sent 5 requests, hit 3 on MailChimp log.

**Source code**
Magento EE 2.3.3
Mailchimp Version 102.3.37

**Steps to reproduce**
1. Navigate to Mailchimp admin configuration (staging environment)
2. Set "Enable Two Way Sync" to yes 
3. Click "Create Webhook" 
4. See alert message.

**Comment by jonaschen623** [comment]
Magento Cloud Team has fixed this issue, so close now.

**Comment by Jackcar** [comment]
I am having this same issue, but I am not in the Magento Cloud. How can I fix it? Thanks.
